import DifferentialGeometry.Geometry.Metric.Convergence.Scaling

set_option autoImplicit false

namespace DifferentialGeometry.PDE.RicciFlow.Perelman.KappaSolutions

alias metricCovDeriv_scale_all := CheegerGromovCompactness.metricCovDeriv_scale_all

alias metricDiffCovDerivAt_scale_all := CheegerGromovCompactness.metricDiffCovDerivAt_scale_all

alias metricDerivNorm_scale_all := CheegerGromovCompactness.metricDerivNorm_scale_all

noncomputable abbrev metricJetScaleLoss := CheegerGromovCompactness.metricJetScaleLoss

alias metricJetScaleLoss_pos := CheegerGromovCompactness.metricJetScaleLoss_pos

alias metricDerivNormSupOn_scale_all_le := CheegerGromovCompactness.metricDerivNormSupOn_scale_all_le

alias metricCPConvOn_scale_all := CheegerGromovCompactness.metricCPConvOn_scale_all

alias metricCInfConvOnCompacts_scale_all := CheegerGromovCompactness.metricCInfConvOnCompacts_scale_all

end DifferentialGeometry.PDE.RicciFlow.Perelman.KappaSolutions
