import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Metric.HalfPlanePacking
import DifferentialGeometry.Geometry.Metric.Approximation.ProductFactorComposition
import DifferentialGeometry.Geometry.Metric.Approximation.IntervalTargetExtension

#check WithLp.not_approximate_orthogonal_cross_in_half_plane
#print axioms WithLp.not_approximate_orthogonal_cross_in_half_plane

#check GC.MetricGeometry.KleinerLottApprox.product_factor_composition_estimates
#print axioms GC.MetricGeometry.KleinerLottApprox.product_factor_composition_estimates

#check GC.MetricGeometry.KleinerLottApprox.enlargeIntervalTarget
#print axioms GC.MetricGeometry.KleinerLottApprox.enlargeIntervalTarget

#check GC.MetricGeometry.KleinerLottApprox.enlargeIntervalTarget_apply
#print axioms GC.MetricGeometry.KleinerLottApprox.enlargeIntervalTarget_apply
