import DifferentialGeometry.Geometry.Flow.RicciFlow.Perelman.KappaSolutions.TensorNormChartConvergence
import DifferentialGeometry.Geometry.Metric.Convergence.CovariantDerivative.Norm.ChartConvergence

namespace DifferentialGeometry.PDE.RicciFlow.Perelman.CanonicalNeighborhood.FiniteHorn

export DifferentialGeometry.CheegerGromovCompactness
  (tensor_norm_tendsto_of_smooth_chart_convergence
    tensor02_covariant_norm_tendsto_of_smooth_chart_convergence)

end DifferentialGeometry.PDE.RicciFlow.Perelman.CanonicalNeighborhood.FiniteHorn
