import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Comparison.AlmostOppositeAngle
import DifferentialGeometry.Topology.MetricSpace.CompactBaseIsometry
import DifferentialGeometry.Topology.MetricSpace.GeodesicLine
import DifferentialGeometry.Topology.MetricSpace.ProductEnds
import DifferentialGeometry.Topology.MetricSpace.LpProductEnds
import DifferentialGeometry.Geometry.Comparison.MultipleEndsSplitting
import DifferentialGeometry.Geometry.Metric.Scaling.RescaleIsometry
import DifferentialGeometry.Geometry.Metric.Approximation.ConvergenceIsometry
import DifferentialGeometry.Geometry.Metric.Approximation.NormedProductBlowdown
import DifferentialGeometry.Geometry.Metric.Approximation.ProductBlowdownRecognition
import DifferentialGeometry.Geometry.Metric.Approximation.KleinerLottCriterion
import DifferentialGeometry.Geometry.Metric.Approximation.MultipleEndsBlowdown

#check DifferentialGeometry.Geometry.Comparison.Toponogov.one_add_cos_comparisonAngle_double_le
#print axioms DifferentialGeometry.Geometry.Comparison.Toponogov.one_add_cos_comparisonAngle_double_le

#check DifferentialGeometry.Geometry.Comparison.Toponogov.pi_sub_lt_comparisonAngle_double
#print axioms DifferentialGeometry.Geometry.Comparison.Toponogov.pi_sub_lt_comparisonAngle_double

#check Metric.exists_isometry_of_local_distortion
#print axioms Metric.exists_isometry_of_local_distortion

#check Metric.exists_isometric_line_of_compact_centers
#print axioms Metric.exists_isometric_line_of_compact_centers

#check Metric.exists_isometric_line_of_unbounded_components
#print axioms Metric.exists_isometric_line_of_unbounded_components

#check Metric.connectedComponentIn_compl_prod_eq_of_unbounded
#print axioms Metric.connectedComponentIn_compl_prod_eq_of_unbounded

#check IsometryEquiv.isBounded_factor_of_unbounded_components
#print axioms IsometryEquiv.isBounded_factor_of_unbounded_components

#check DifferentialGeometry.Geometry.Comparison.Toponogov.exists_isometryEquiv_real_prod_compact_of_unbounded_components
#print axioms DifferentialGeometry.Geometry.Comparison.Toponogov.exists_isometryEquiv_real_prod_compact_of_unbounded_components

#check IsometryEquiv.rescale
#print axioms IsometryEquiv.rescale

#check GC.MetricGeometry.PointedGHConverges.comap_source_isometry
#print axioms GC.MetricGeometry.PointedGHConverges.comap_source_isometry

#check GC.MetricGeometry.rescaledProductFstApprox
#print axioms GC.MetricGeometry.rescaledProductFstApprox

#check GC.MetricGeometry.pointedGHConverges_rescaled_normed_product
#print axioms GC.MetricGeometry.pointedGHConverges_rescaled_normed_product

#check GC.MetricGeometry.pointedGHConverges_rescaled_of_normed_product
#print axioms GC.MetricGeometry.pointedGHConverges_rescaled_of_normed_product

#check GC.MetricGeometry.PointedGHConverges.exists_isometryEquiv_of_rescaled_normed_product
#print axioms GC.MetricGeometry.PointedGHConverges.exists_isometryEquiv_of_rescaled_normed_product

#check GC.MetricGeometry.PointedGHConverges.of_eventually_kleinerLott_approx
#print axioms GC.MetricGeometry.PointedGHConverges.of_eventually_kleinerLott_approx

#check GC.MetricGeometry.PointedGHConverges.exists_isometryEquiv_real_of_unbounded_components
#print axioms GC.MetricGeometry.PointedGHConverges.exists_isometryEquiv_real_of_unbounded_components

#check GC.MetricGeometry.exists_isometryEquiv_real_of_rescaled_approximations
#print axioms GC.MetricGeometry.exists_isometryEquiv_real_of_rescaled_approximations
