import DifferentialGeometry.Tensor.LinearAlgebra.Dimension.FiniteSup
import DifferentialGeometry.Analysis.InnerProductSpace.NormalProjectionSpan
import DifferentialGeometry.Analysis.InnerProductSpace.NormalSpectralSection
import DifferentialGeometry.Analysis.InnerProductSpace.FiniteNormalReduction

#print axioms Submodule.finrank_finset_sup_le_sum
#print axioms Submodule.finrank_finset_sup_span_singleton_sup_le
#print axioms ContinuousLinearMap.range_id_sub_sum_smul_starProjection_orthogonal_le
#print axioms ContinuousLinearMap.finrank_range_id_sub_sum_smul_starProjection_orthogonal_le
#print axioms Submodule.sum_smul_starProjection_orthogonal_mapsTo
#print axioms Submodule.sum_smul_starProjection_orthogonal_apply_of_mem_orthogonal
#print axioms Submodule.starProjection_eigenspace_iSup_of_fixed
#print axioms Submodule.starProjection_weighted_normal_section
#print axioms Submodule.finite_affine_family_normal_reduction
