import DifferentialGeometry.Geometry.Metric.Approximation.ProductResidualBound
import DifferentialGeometry.Geometry.Metric.Approximation.VanishingProductResidual
import DifferentialGeometry.Geometry.Metric.Approximation.TestedResidualParameter
import DifferentialGeometry.Geometry.Metric.LipschitzScaleMultiplicity
import DifferentialGeometry.Geometry.Metric.Approximation.VanishingVolumeDimension

#print axioms WithLp.snd_dist_sq_le_of_fst_dist_gap
#print axioms GC.MetricGeometry.KleinerLottApprox.snd_dist_sq_le_of_coordinate_control
#print axioms GC.MetricGeometry.eventually_residual_lt_of_coordinate_control
#print axioms GC.MetricGeometry.PointedGHConverges.exists_subsequence_with_vanishing_tested_residual
#print axioms GC.MetricGeometry.exists_tested_residual_parameter_of_nonnegative_models
#print axioms GC.MetricGeometry.card_le_of_lipschitz_scale_ball_overlap
#print axioms GC.MetricGeometry.exists_finite_scale_cover_with_multiplicity
#print axioms GC.MetricGeometry.PointedGHConverges.dimH_le_two_of_vanishing_normalizedHausdorffMeasure
