import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryPortEdgeQ2
import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryPortEdgeZeroComparison
import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryPortSupportRows
import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryPortZeroMeeting
import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryPortQuantitativeApplications
import DifferentialGeometry.Geometry.Collapse.LocalExport.BoundaryWholeSupportCount
import DifferentialGeometry.Geometry.Fibration.ActualEdgeGraphModelApplications
import DifferentialGeometry.Geometry.Fibration.ActualModelMarkerPlanes
import DifferentialGeometry.Geometry.Fibration.ActualStageSmallMarkers

/-!
# EGP06's model graph on the boundary family (lane B-PORT-EDGEb, G2)

GENERATED by `build-logs/scratch/B-PORT-EDGEb/gen_model.py` (tables of `egplib.py` /
`B-PORT-EDGE/portedge.py`) from `Geometry/Fibration/ActualEdgeGraphModel.lean` (§Model, §Family),
`…/ActualEdgeGraphModelApplications.lean` (`egpModelGraph_lower_bound`),
`…/ActualStageSmallMarkers.lean` (`egpEdgeList_ratio_GAF4`, `egpSlimList_ratio_GAF4`) and
`…/ActualModelMarkerPlanes.lean` (`egpModelGraph_marker_fderiv_GAFS`); do not edit by hand, re-run
the script.

On B-PORT-A's `CGPTag_BAUGP L Z` (`L : LocalPacketsOnB … U₁ U₂ Ue₁ Ue₂` with the ACTIVE edge family
`L.edgeB`, `Z : ZeroModelFamilyOn … U₁ U₂`) and the boundary family `P : LocalPacketsOnBF …`:
* `egpModelComponent_BAUGP`, `egpModelGraph_BAUGP` (own edge block `(a, 1)`, listed edge / slim
  blocks, the meeting zero block), `egpModelListed_BAUGP`, smoothness, `egpModelGraph_own_BAUGP`,
  `blockRestrict_egpModelGraph_BAUGP` (values in `Q₂`, lane-own `cgpQ2Tags_BPE`);
* `egp06_model_kernel_BAUGP`, `egpModelListed_card_le_BAUGP`, `egp06_model_BAUGP` (global `C²` bound
  `egpGraphConst`), `egpModelGraph_lower_bound_BAUGP`;
* `egpEdgeList_ratio_GAF4_BAUGP`, `egpSlimList_ratio_GAF4_BAUGP`,
`egpModelGraph_marker_fderiv_GAFS_BAUGP`.
Reused unchanged (generic): `blockGraph_KC3`, `blockLift_KC3`, `egpProfileConst`, `egpGraphConst`,
`own_block_bounds_KC3`, `fderiv_clm_comp_apply_KC3`, `support_meeting_sharp_bounds`,
`edge_comparison_list_edge_bounds`, `scaledCutoffBlock_snd_eventually_GAFS`.
Boundary twins: `zeroMeetingList_BPE` (copy of the undelivered `BoundaryPortActiveSupportPacket`),
`LocalPacketsOnB.tsupport_edgeB_cutoff_subset_BAUGA` (closed `fc18_edge_rowE`, same arguments),
`tsupport_edgeB_cutoff_subset_closedBall_BCNT` (closed `EdgeFamily.tsupport_cutoff_subset`).
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric Bundle Manifold Filter
open scoped ContDiff Manifold Topology
open DifferentialGeometry.Topology.Ehresmann DifferentialGeometry.Topology.Manifold
open DifferentialGeometry.Geometry.Riemannian GC.MetricGeometry
open DifferentialGeometry.Geometry.Riemannian.VolumeComparison
open DifferentialGeometry.Analysis DifferentialGeometry.Analysis.Calculus

namespace DifferentialGeometry.Geometry.Collapse

local notation "E3" => EuclideanSpace ℝ (Fin 3)

attribute [-instance] Tensor0SBundle.tangentSpaceNormedAddCommGroup
  Tensor0SBundle.tangentSpaceNormedSpace

attribute [local instance] nezero_finrank_euclideanThree_LC87

local notation "ℝ²" => EuclideanSpace ℝ (Fin 2)

/-- The model metrics of `LocalPacketsOnBF`, as a named local instance. -/
local instance instMetricN_BPEm {X : Type} [MetricSpace X] [ChartedSpace E3 X]
    [IsManifold 𝓘(ℝ, E3) ∞ X] [CompleteSpace X] [SigmaCompactSpace X]
    {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
    {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
    {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
    {σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λz : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
    (P : LocalPacketsOnBF X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        ζ Λz U₁ U₂ Ue₁ Ue₂) (a : X) : MetricSpace (P.N a) :=
  P.instMetricN a

/-- The model charts of `LocalPacketsOnBF`, as a named local instance. -/
local instance instChartedN_BPEm {X : Type} [MetricSpace X] [ChartedSpace E3 X]
    [IsManifold 𝓘(ℝ, E3) ∞ X] [CompleteSpace X] [SigmaCompactSpace X]
    {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
    {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
    {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
    {σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λz : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
    (P : LocalPacketsOnBF X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        ζ Λz U₁ U₂ Ue₁ Ue₂) (a : X) : ChartedSpace E3 (P.N a) :=
  P.instChartedN a

/-- The cone metrics of `LocalPacketsOnBF`, as a named local instance. -/
local instance instMetricC_BPEm {X : Type} [MetricSpace X] [ChartedSpace E3 X]
    [IsManifold 𝓘(ℝ, E3) ∞ X] [CompleteSpace X] [SigmaCompactSpace X]
    {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
    {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
    {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
    {σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λz : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
    (P : LocalPacketsOnBF X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        ζ Λz U₁ U₂ Ue₁ Ue₂) (a : X) : MetricSpace (P.C a) :=
  P.instMetricC a

section Part0



section Model

variable {X : Type} [mX : MetricSpace X] [ChartedSpace E3 X] [IsManifold 𝓘(ℝ, E3) ∞ X]
  [CompleteSpace X] [SigmaCompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
  {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
  {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
  {σc μ b s b' s' ε γc βc Lmax τ γ vs : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
  {N C : X → Type} [∀ a, MetricSpace (N a)] [∀ a, ChartedSpace E3 (N a)]
  [∀ a, MetricSpace (C a)] {o : ∀ a, C a} {δ εr e T V : ℝ}

open Classical in
/-- **The blocks of EGP06's model graph** at the edge reference `i`, with signs `sgn` and
translations `c` per tag (`λ_t(a) = sgn_t a + c_t`): own edge tag `i` ↦ `(a, 1)`; listed edge
`j ≠ i` ↦ `graphPacketModelBlock Δ s_j (λ_t(a))`; listed slim `j` ↦ `sgpModelBlock (10⁵Δ) s_j
(λ_t(a))`; zero `k` meeting `D_i` ↦ `zeroModelBlock (R₀/ρ(i)) (λ_t(a))` (`s_j = ρ(j)/ρ(i)`, scalar
blocks on `planeAxis`); every other tag (circle, unlisted, scale, `E'`) ↦ `0`. -/
def egpModelComponent_BAUGP (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc
    Lmax τ γ δ εr e T V vs U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) : (t : CGPTag_BAUGP L Z) → ℝ → WithLp 2 (ℝ² × ℝ)
  | .inl _ => 0
  | .inr (.inl j) =>
      if j.1 ∈ egpSlimList_BAUGP L i then
        fun a => blockLift_KC3 (sgpModelBlock (10 ^ 5 * Δ) (ρ j.1 / ρ i)
          (sgn (.inr (.inl j)) * a + c (.inr (.inl j))))
      else 0
  | .inr (.inr (.inl j)) =>
      if j.1 = i then fun a => blockLift_KC3 (WithLp.toLp 2 (a, 1))
      else if j.1 ∈ egpEdgeList_BAUGP L i then
        fun a => blockLift_KC3 (graphPacketModelBlock Δ (ρ j.1 / ρ i)
          (sgn (.inr (.inr (.inl j))) * a + c (.inr (.inr (.inl j)))))
      else 0
  | .inr (.inr (.inr (.inl k))) =>
      if k.1 ∈ zeroMeetingList_BPE Z i (20 * Δ) then
        fun a => blockLift_KC3 (zeroModelBlock
          ((Z.zero k.1 ((Set.Finite.mem_toFinset _).mp k.2)).radius / ρ i)
          (sgn (.inr (.inr (.inr (.inl k)))) * a + c (.inr (.inr (.inr (.inl k))))))
      else 0
  | .inr (.inr (.inr (.inr _))) => 0

/-- **EGP06's model graph** `Φ_i : ℝ → 𝓔⁰`'s block space (values in `Q₂`). -/
def egpModelGraph_BAUGP (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc
    Lmax τ γ δ εr e T V vs U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) : ℝ → BlockSpace (fun _ : CGPTag_BAUGP L Z => ℝ²) :=
  blockGraph_KC3 (egpModelComponent_BAUGP L Z i sgn c)

/-- The listed tags of EGP06's model at `i` (where its block may be nonzero). -/
def egpModelListed_BAUGP (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc
    Lmax τ γ δ εr e T V vs U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X) : CGPTag_BAUGP L Z →
        Prop
  | .inl _ => False
  | .inr (.inl j) => j.1 ∈ egpSlimList_BAUGP L i
  | .inr (.inr (.inl j)) => j.1 = i ∨ j.1 ∈ egpEdgeList_BAUGP L i
  | .inr (.inr (.inr (.inl k))) => k.1 ∈ zeroMeetingList_BPE Z i (20 * Δ)
  | .inr (.inr (.inr (.inr _))) => False

open Classical in
/-- Every unlisted block of the model is the zero function. -/
theorem egpModelComponent_eq_zero_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (t : CGPTag_BAUGP L Z) (ht : ¬ egpModelListed_BAUGP L Z i t) :
    egpModelComponent_BAUGP L Z i sgn c t = 0 := by
  rcases t with j | j | j | k | q
  · rfl
  · simp only [egpModelListed_BAUGP] at ht
    simp only [egpModelComponent_BAUGP, ht, ite_false]
  · simp only [egpModelListed_BAUGP, not_or] at ht
    simp only [egpModelComponent_BAUGP, ht.1, ht.2, ite_false]
  · simp only [egpModelListed_BAUGP] at ht
    simp only [egpModelComponent_BAUGP, ht, ite_false]
  · rfl

open Classical in
/-- Every block of the model is smooth. -/
theorem contDiff_egpModelComponent_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (t : CGPTag_BAUGP L Z) :
    ContDiff ℝ ∞ (egpModelComponent_BAUGP L Z i sgn c t) := by
  have haff : ∀ (σ c' : ℝ), ContDiff ℝ ∞ (fun a : ℝ => σ * a + c') :=
    fun σ c' => (contDiff_const.mul contDiff_id).add contDiff_const
  rcases t with j | j | j | k | q
  · exact contDiff_const
  · simp only [egpModelComponent_BAUGP]
    split_ifs
    · exact blockLift_KC3.contDiff.comp ((contDiff_sgpModelBlock _ _).comp (haff _ _))
    · exact contDiff_const
  · simp only [egpModelComponent_BAUGP]
    split_ifs
    · exact blockLift_KC3.contDiff.comp own_block_bounds_KC3.1
    · exact blockLift_KC3.contDiff.comp ((contDiff_graphPacketModelBlock _ _).comp (haff _ _))
    · exact contDiff_const
  · simp only [egpModelComponent_BAUGP]
    split_ifs
    · exact blockLift_KC3.contDiff.comp ((contDiff_zeroModelBlock _).comp (haff _ _))
    · exact contDiff_const
  · exact contDiff_const

theorem contDiff_egpModelGraph_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) : ContDiff ℝ ∞ (egpModelGraph_BAUGP L Z i sgn c) :=
  contDiff_blockGraph_KC3 (contDiff_egpModelComponent_BAUGP L Z i sgn c)

/-- The own block of the model is `(a, 1)`. -/
theorem egpModelGraph_own_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (j : L.edgeB.finite_centres.toFinset) (hj : j.1 = i) (a : ℝ) :
    egpModelGraph_BAUGP L Z i sgn c a (.inr (.inr (.inl j))) = WithLp.toLp 2 (planeAxis a, 1) := by
  change egpModelComponent_BAUGP L Z i sgn c (.inr (.inr (.inl j))) a = _
  simp only [egpModelComponent_BAUGP, hj, ite_true]
  rfl

open Classical in
/-- The model takes values in `Q₂` (no circle, scale or `E'` block). -/
theorem blockRestrict_egpModelGraph_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (a : ℝ) :
    blockRestrict (cgpQ2Tags_BPE L Z) (egpModelGraph_BAUGP L Z i sgn c a) = egpModelGraph_BAUGP L Z
        i sgn c a := by
  refine PiLp.ext fun t => ?_
  rw [blockRestrict_apply]
  split_ifs with ht
  · rfl
  · have h0 : egpModelComponent_BAUGP L Z i sgn c t = 0 := by
      apply egpModelComponent_eq_zero_BAUGP
      rcases t with j | j | j | k | q
      · exact fun h => h
      · exact (ht (Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl⟩)).elim
      · exact (ht (Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl⟩)).elim
      · exact (ht (Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl⟩)).elim
      · exact fun h => h
    change 0 = egpModelComponent_BAUGP L Z i sgn c t a
    rw [h0]
    rfl

open Classical in
/-- **EGP06's model bounds (kernel form).** With `Δ ≥ 1`, signs `|sgn_t| ≤ 1`, ratios
`s_j ≥ 99/100` for the listed edge and slim charts, zero ratios `R₀/ρ(i) ≥ 1` for the zero
supports meeting `D_i`, and at most `N† + 2` listed tags, the model graph has first and second
derivatives at most `C† = 1000(N† + 2)(P† + 1)`. -/
theorem egp06_model_kernel_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) {i : X} (hi : i ∈
        L.edgeB.centres)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (hΔ : 1 ≤ Δ) (hsgn : ∀ t, |sgn t| ≤ 1)
    (hS : ∀ j ∈ egpSlimList_BAUGP L i, 99 / 100 ≤ ρ j / ρ i)
    (hE : ∀ j ∈ egpEdgeList_BAUGP L i, 99 / 100 ≤ ρ j / ρ i)
    (hZ : ∀ k (hk : k ∈ Z.centres), k ∈ zeroMeetingList_BPE Z i (20 * Δ) →
      1 ≤ (Z.zero k hk).radius / ρ i)
    (hcount : ((Finset.univ.filter (egpModelListed_BAUGP L Z i)).card : ℝ) ≤ egp02ListBound + 2)
    (a : ℝ) :
    ‖fderiv ℝ (egpModelGraph_BAUGP L Z i sgn c) a‖ ≤ egpGraphConst ∧
      ‖fderiv ℝ (fderiv ℝ (egpModelGraph_BAUGP L Z i sgn c)) a‖ ≤ egpGraphConst := by
  have hP := one_le_egpProfileConst
  have hPe : edgeProfileDerivativeBound ≤ egpProfileConst := le_max_left _ _
  have hPs : sgpProfileBound ≤ egpProfileConst := (le_max_left _ _).trans (le_max_right _ _)
  have hPz : zeroProfileBound ≤ egpProfileConst := (le_max_right _ _).trans (le_max_right _ _)
  obtain ⟨B, hBdef⟩ : ∃ B : ℝ, B = 50 * (egpProfileConst + 1) := ⟨_, rfl⟩
  have hB : 0 ≤ B := by rw [hBdef]; linarith
  have hB1 : 1 ≤ B := by rw [hBdef]; linarith
  set S := Finset.univ.filter (egpModelListed_BAUGP L Z i) with hSdef
  have hblock : ∀ t, t ∈ S → ∀ a, ‖fderiv ℝ (egpModelComponent_BAUGP L Z i sgn c t) a‖ ≤ B ∧
      ‖fderiv ℝ (fderiv ℝ (egpModelComponent_BAUGP L Z i sgn c t)) a‖ ≤ B := by
    intro t ht a
    have hl := (Finset.mem_filter.mp ht).2
    rcases t with j | j | j | k | q
    · exact hl.elim
    · have hl' : j.1 ∈ egpSlimList_BAUGP L i := hl
      have hℓ : 1 ≤ 10 ^ 5 * Δ := by nlinarith
      have hW (y : ℝ) := sgpModelBlock_derivative_bounds hℓ (hS j.1 hl') y
      simp only [egpModelComponent_BAUGP, hl', ite_true]
      exact lifted_affine_bounds_KC3 ((contDiff_sgpModelBlock _ _).of_le (by simp)) (hsgn _) hB
        (fun y => (hW y).1.trans (by rw [hBdef]; linarith))
        (fun y => (hW y).2.trans (by rw [hBdef]; linarith)) a
    · by_cases hji : j.1 = i
      · simp only [egpModelComponent_BAUGP, hji, ite_true]
        have h := clm_comp_bounds_KC3 blockLift_KC3 norm_blockLift_le_KC3
          (own_block_bounds_KC3.1.of_le (by simp)) (fun y => (own_block_bounds_KC3.2 y).1)
          (fun y => (own_block_bounds_KC3.2 y).2) a
        exact ⟨h.1.trans hB1, h.2.trans hB1⟩
      · have hl' : j.1 ∈ egpEdgeList_BAUGP L i := hl.resolve_left hji
        have hW (y : ℝ) := graphPacketModelBlock_derivative_bounds hΔ (hE j.1 hl') y
        simp only [egpModelComponent_BAUGP, hji, hl', ite_true, ite_false]
        exact lifted_affine_bounds_KC3 ((contDiff_graphPacketModelBlock _ _).of_le (by simp))
          (hsgn _) hB (fun y => (hW y).1.trans (by rw [hBdef]; linarith))
          (fun y => (hW y).2.trans (by rw [hBdef]; linarith)) a
    · have hl' : k.1 ∈ zeroMeetingList_BPE Z i (20 * Δ) := hl
      have hW (y : ℝ) := zeroModelBlock_derivative_bounds
        (hZ k.1 ((Set.Finite.mem_toFinset _).mp k.2) hl') y
      simp only [egpModelComponent_BAUGP, hl', ite_true]
      exact lifted_affine_bounds_KC3 ((contDiff_zeroModelBlock _).of_le (by simp)) (hsgn _) hB
        (fun y => (hW y).1.trans (by rw [hBdef]; linarith))
        (fun y => (hW y).2.trans (by rw [hBdef]; linarith)) a
    · exact hl.elim
  have hz : ∀ t, t ∉ S → egpModelComponent_BAUGP L Z i sgn c t = 0 := fun t ht =>
    egpModelComponent_eq_zero_BAUGP L Z i sgn c t fun hl =>
      ht (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hl⟩)
  have hmain := blockGraph_bounds_KC3
    (fun t => (contDiff_egpModelComponent_BAUGP L Z i sgn c t).of_le (by simp)) S hB hz
    (fun t ht a => (hblock t ht a).1) (fun t ht a => (hblock t ht a).2) a
  -- the count
  have hown : (.inr (.inr (.inl ⟨i, (Set.Finite.mem_toFinset _).mpr hi⟩)) : CGPTag_BAUGP L Z) ∈ S :=
    Finset.mem_filter.mpr ⟨Finset.mem_univ _, Or.inl rfl⟩
  have hS1 : (1 : ℝ) ≤ S.card := by
    exact_mod_cast Finset.card_pos.mpr ⟨_, hown⟩
  have hsqrt : Real.sqrt (S.card : ℝ) ≤ S.card := by
    rw [Real.sqrt_le_left (by linarith)]
    nlinarith
  have hfin : Real.sqrt (S.card : ℝ) * B ≤ egpGraphConst := by
    have h1 : Real.sqrt (S.card : ℝ) * B ≤ (egp02ListBound + 2) * B :=
      mul_le_mul_of_nonneg_right (hsqrt.trans hcount) hB
    have h2 : (egp02ListBound + 2) * B ≤ egpGraphConst := by
      rw [hBdef, egpGraphConst]
      have hN : 0 ≤ egp02ListBound + 2 := by linarith
      nlinarith
    linarith
  exact ⟨hmain.1.trans hfin, hmain.2.trans hfin⟩

end Model

section Family

attribute [local instance] nezero_finrank_euclideanThree_LC87

variable {X : Type} [mX : MetricSpace X] [ChartedSpace E3 X] [IsManifold 𝓘(ℝ, E3) ∞ X]
  [CompleteSpace X] [SigmaCompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
  {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
  {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
  {σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λz : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}

open Classical in
/-- EGP06's listed tags at an edge reference: at most `N† + 2` (EGP02's count, the own tag, and at
most one zero support meeting `D_i`). -/
theorem egpModelListed_card_le_BAUGP
    (P : LocalPacketsOnBF X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        ζ Λz U₁ U₂ Ue₁ Ue₂)
    (hΛ : 0 ≤ Λ) (hΔ : 1 ≤ Δ) (hLΛ : 1000000 * Δ * Λ < 1 / 100000) (he : e < 1 / 40)
    (hT : 1600 * (1000000 * Δ) ≤ T) (i : X) :
    ((Finset.univ.filter (egpModelListed_BAUGP P.toLocalPacketsOnB P.zero i)).card : ℝ) ≤
      egp02ListBound + 2 := by
  have hΔ0 : 0 < Δ := by linarith
  let L := P.toLocalPacketsOnB
  -- the three kinds of listed tags
  let SS := Finset.univ.filter fun j : L.slim.finite_centres.toFinset => j.1 ∈ egpSlimList_BAUGP L i
  let SE := Finset.univ.filter fun j : L.edgeB.finite_centres.toFinset =>
    j.1 = i ∨ j.1 ∈ egpEdgeList_BAUGP L i
  let SZ := Finset.univ.filter fun k : P.zero.finite_centres.toFinset =>
    k.1 ∈ zeroMeetingList_BPE P.zero i (20 * Δ)
  let eS : L.slim.finite_centres.toFinset ↪ CGPTag_BAUGP L P.zero :=
    ⟨fun j => .inr (.inl j), fun _ _ h => by simpa using h⟩
  let eE : L.edgeB.finite_centres.toFinset ↪ CGPTag_BAUGP L P.zero :=
    ⟨fun j => .inr (.inr (.inl j)), fun _ _ h => by simpa using h⟩
  let eZ : P.zero.finite_centres.toFinset ↪ CGPTag_BAUGP L P.zero :=
    ⟨fun k => .inr (.inr (.inr (.inl k))), fun _ _ h => by simpa using h⟩
  have hsub : Finset.univ.filter (egpModelListed_BAUGP L P.zero i) ⊆
      (SS.map eS ∪ SE.map eE) ∪ SZ.map eZ := by
    intro t ht
    have hl := (Finset.mem_filter.mp ht).2
    rcases t with j | j | j | k | q
    · exact hl.elim
    · exact Finset.mem_union_left _ (Finset.mem_union_left _
        (Finset.mem_map_of_mem eS (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hl⟩)))
    · exact Finset.mem_union_left _ (Finset.mem_union_right _
        (Finset.mem_map_of_mem eE (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hl⟩)))
    · exact Finset.mem_union_right _
        (Finset.mem_map_of_mem eZ (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hl⟩))
    · exact hl.elim
  have hcard := (Finset.card_le_card hsub).trans ((Finset.card_union_le _ _).trans
    (Nat.add_le_add_right (Finset.card_union_le _ _) _))
  rw [Finset.card_map, Finset.card_map, Finset.card_map] at hcard
  -- slim
  have hSS : SS.card ≤ (egpSlimList_BAUGP L i).ncard := by
    have h : SS.card ≤ {y | y ∈ L.slim.centres ∧ y ∈ egpSlimList_BAUGP L i}.ncard := by
      rw [← Set.ncard_coe_finset, Finset.coe_filter]
      simp only [Finset.mem_univ, true_and]
      exact ncard_subtype_le_KA2 L.slim.finite_centres
        (p := fun y => y ∈ egpSlimList_BAUGP L i) (q := fun y => y ∈ egpSlimList_BAUGP L i) fun _ _
            hy => hy
    refine h.trans (Set.ncard_le_ncard (fun y hy => hy.2) ?_)
    exact L.slim.finite_centres.subset fun y hy => hy.1
  -- edge
  have hfinE : (egpEdgeList_BAUGP L i).Finite := L.edgeB.finite_centres.subset fun y hy => hy.1
  have hSE : SE.card ≤ (egpEdgeList_BAUGP L i).ncard + 1 := by
    have h : SE.card ≤ {y | y ∈ L.edgeB.centres ∧ (y = i ∨ y ∈ egpEdgeList_BAUGP L i)}.ncard := by
      rw [← Set.ncard_coe_finset, Finset.coe_filter]
      simp only [Finset.mem_univ, true_and]
      exact ncard_subtype_le_KA2 L.edgeB.finite_centres
        (p := fun y => y = i ∨ y ∈ egpEdgeList_BAUGP L i) (q := fun y => y = i ∨ y ∈
            egpEdgeList_BAUGP L i)
        fun _ _ hy => hy
    refine h.trans ((Set.ncard_le_ncard (t := insert i (egpEdgeList_BAUGP L i))
      (fun y hy => ?_) (hfinE.insert i)).trans (Set.ncard_insert_le _ _))
    rcases hy.2 with h1 | h1
    · exact Or.inl h1
    · exact Or.inr h1
  -- zero
  have hT0 : 0 < T := by have : (0 : ℝ) < 1600 * (1000000 * Δ) := by positivity
                         linarith
  have hc : ((Real.toNNReal Λ : NNReal) : ℝ) = Λ := Real.coe_toNNReal _ hΛ
  have hsmall : 2 * (20 * Δ / T) + 2 * (20 * Δ * ((Real.toNNReal Λ : NNReal) : ℝ)) ≤ 1 / 40 := by
    rw [hc]
    have h1 : 20 * Δ / T ≤ 1 / 80000 := by
      rw [div_le_iff₀ hT0]
      linarith
    have h2 : 20 * Δ * Λ ≤ 1 / 5000000 := by nlinarith
    linarith
  have hZ1 := ncard_zeroMeetingList_le_one_BPE P.zero P.lipschitz_scale he hT0 i
    (by positivity : (0 : ℝ) < 20 * Δ) hsmall
  have hSZ : SZ.card ≤ (zeroMeetingList_BPE P.zero i (20 * Δ)).ncard := by
    have h : SZ.card ≤ {y | y ∈ P.zero.centres ∧ y ∈ zeroMeetingList_BPE P.zero i (20 *
        Δ)}.ncard := by
      rw [← Set.ncard_coe_finset, Finset.coe_filter]
      simp only [Finset.mem_univ, true_and]
      exact ncard_subtype_le_KA2 P.zero.finite_centres
        (p := fun y => y ∈ zeroMeetingList_BPE P.zero i (20 * Δ))
        (q := fun y => y ∈ zeroMeetingList_BPE P.zero i (20 * Δ)) fun _ _ hy => hy
    refine h.trans (Set.ncard_le_ncard (fun y hy => hy.2) ?_)
    exact P.zero.finite_centres.subset fun y hy => hy.1
  have hlist := egp02_list_count_BAUGP L hΛ hΔ0 hLΛ i
  have hcardR : ((Finset.univ.filter (egpModelListed_BAUGP L P.zero i)).card : ℝ) ≤
      SS.card + SE.card + SZ.card := by exact_mod_cast hcard
  have hSSR : (SS.card : ℝ) ≤ (egpSlimList_BAUGP L i).ncard := by exact_mod_cast hSS
  have hSER : (SE.card : ℝ) ≤ (egpEdgeList_BAUGP L i).ncard + 1 := by exact_mod_cast hSE
  have hSZR : (SZ.card : ℝ) ≤ 1 := by exact_mod_cast hSZ.trans hZ1
  linarith

open Classical in
/-- **EGP06's model on the actual family.** At an edge centre `i`, for signs `|sgn_t| ≤ 1` and any
translations, the model graph `Φ_i` is smooth, has own block `(a, 1)`, takes values in `Q₂`, and has
`‖DΦ_i‖, ‖D²Φ_i‖ ≤ C†` (early: `C†` depends on no parameter). -/
theorem egp06_model_BAUGP
    (P : LocalPacketsOnBF X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        ζ Λz U₁ U₂ Ue₁ Ue₂)
    (hΛ : 0 ≤ Λ) (hΔ : 1 ≤ Δ) (hLΛ : 1000000 * Δ * Λ < 1 / 100000) (hμ : μ ≤ 1 / 100)
    (hτ : τ ≤ 1 / 100) (he : e < 1 / 40) (hT : 1600 * (1000000 * Δ) ≤ T) {i : X}
    (hi : i ∈ P.edgeB.centres) (sgn c : CGPTag_BAUGP P.toLocalPacketsOnB P.zero → ℝ)
    (hsgn : ∀ t, |sgn t| ≤ 1) :
    ContDiff ℝ ∞ (egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c) ∧
      (∀ (j : P.edgeB.finite_centres.toFinset), j.1 = i → ∀ a,
        egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c a (.inr (.inr (.inl j))) =
          WithLp.toLp 2 (planeAxis a, 1)) ∧
      (∀ a, blockRestrict (cgpQ2Tags_BPE P.toLocalPacketsOnB P.zero)
        (egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c a) =
          egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c a) ∧
      ∀ a, ‖fderiv ℝ (egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c) a‖ ≤ egpGraphConst ∧
        ‖fderiv ℝ (fderiv ℝ (egpModelGraph_BAUGP P.toLocalPacketsOnB P.zero i sgn c)) a‖ ≤
          egpGraphConst := by
  have hΔ0 : 0 < Δ := by linarith
  have hri := hρ i
  have hρL : LipschitzWith (Real.toNNReal Λ) ρ := P.lipschitz_scale
  have hc : ((Real.toNNReal Λ : NNReal) : ℝ) = Λ := Real.coe_toNNReal _ hΛ
  have hΔΛ0 : 0 ≤ Δ * Λ := mul_nonneg hΔ0.le hΛ
  have hΔΛ : 100 * Δ * Λ ≤ 1 / 100 := by nlinarith
  have hLΛ' : 1000000 * Δ * ((Real.toNNReal Λ : NNReal) : ℝ) < 1 / 100000 := by rwa [hc]
  -- slim ratios
  have hS : ∀ j ∈ egpSlimList_BAUGP P.toLocalPacketsOnB i, 99 / 100 ≤ ρ j / ρ i := by
    intro j hj
    obtain ⟨hjc, y₀, hy1, hy2⟩ := hj
    have hsl := fc18_slim_row_BAUGP P.toLocalPacketsOnB hΔ0 hjc
    have hm : (closedBall j ((910000 * Δ) * ρ j) ∩ ball i ((20 * Δ) * ρ i)).Nonempty :=
      ⟨y₀, hsl.1 hy1, hy2⟩
    have hΛ1 : 250 * (Λ * (20 * Δ)) ≤ 1 := by
      have e : Λ * (20 * Δ) = 1 / 50000 * (1000000 * Δ * Λ) := by ring
      linarith
    have hΛ2 : 250 * (Λ * (910000 * Δ)) ≤ 1 := by
      have e : Λ * (910000 * Δ) = 91 / 100 * (1000000 * Δ * Λ) := by ring
      linarith
    exact (support_meeting_sharp_bounds hρL hri (hρ j) (a := 20 * Δ) (c := 910000 * Δ)
      (by positivity) (by positivity) (by rw [hc]; exact hΛ1) (by rw [hc]; exact hΛ2) hm).1.le
  -- edge ratios
  have hE : ∀ j ∈ egpEdgeList_BAUGP P.toLocalPacketsOnB i, 99 / 100 ≤ ρ j / ρ i := by
    intro j hj
    obtain ⟨hjc, y₀, hy1, hy2⟩ := hj
    have h14 := (LocalPacketsOnB.tsupport_edgeB_cutoff_subset_BAUGA P.toLocalPacketsOnB hΛ hΔ0 hμ
        hτ hΔΛ hjc).1 hy1
    have hm : (closedBall j (15 * Δ * ρ j) ∩ ball i (20 * Δ * ρ i)).Nonempty := by
      refine ⟨y₀, closedBall_subset_closedBall ?_ h14, hy2⟩
      nlinarith [hρ j]
    exact (edge_comparison_list_edge_bounds hρL hri (hρ j) hΔ hLΛ' hm).1.le
  -- zero ratios
  have hZ : ∀ k (hk : k ∈ P.zero.centres), k ∈ zeroMeetingList_BPE P.zero i (20 * Δ) →
      1 ≤ (P.zero.zero k hk).radius / ρ i := by
    intro k hk hmeet
    obtain ⟨hk', hm⟩ := hmeet
    have hT0 : 0 < T := by have : (0 : ℝ) < 1600 * (1000000 * Δ) := by positivity
                           linarith
    have hsmall : 2 * (20 * Δ / T) + 2 * (20 * Δ * Λ) ≤ 1 / 40 := by
      have h1 : 20 * Δ / T ≤ 1 / 80000 := by
        rw [div_le_iff₀ hT0]
        linarith
      have h2 : 20 * Δ * Λ ≤ 1 / 5000000 := by nlinarith
      linarith
    obtain ⟨-, hcl⟩ := zero_meeting_clauses_ZERO_BAUGP P hΛ he hT0 i (by positivity) hsmall
    have h := ((hcl k hk' hm).1 i (mem_ball_self (by positivity))).2.2.2.2
    have hT20 : 1 ≤ T / 20 := by
      rw [le_div_iff₀ (by norm_num)]
      have : (20 : ℝ) ≤ 1600 * (1000000 * Δ) := by nlinarith
      linarith
    exact hT20.trans h
  refine ⟨contDiff_egpModelGraph_BAUGP _ _ i sgn c, fun j hj a => egpModelGraph_own_BAUGP _ _ i sgn
      c j hj a,
    fun a => blockRestrict_egpModelGraph_BAUGP _ _ i sgn c a, fun a => ?_⟩
  exact egp06_model_kernel_BAUGP P.toLocalPacketsOnB P.zero hi sgn c hΔ hsgn hS hE hZ
    (egpModelListed_card_le_BAUGP P hΛ hΔ hLΛ he hT i) a

end Family


end Part0

section Part1

variable {X : Type} [mX : MetricSpace X] [ChartedSpace E3 X] [IsManifold 𝓘(ℝ, E3) ∞ X]
  [CompleteSpace X] [SigmaCompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
  {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
  {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
  {σc μ b s b' s' ε γc βc Lmax τ γ vs : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
  {N C : X → Type} [∀ a, MetricSpace (N a)] [∀ a, ChartedSpace E3 (N a)]
  [∀ a, MetricSpace (C a)] {o : ∀ a, C a} {δ εr e T V : ℝ}

/-- **The model derivative is bounded below by the own block**: `|x| ≤ ‖DΦ_i(a) x‖` for every
`a, x` (the own edge tag `i` carries `(a, 1)`). -/
theorem egpModelGraph_lower_bound_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) {i : X}
    (hi : i ∈ L.edgeB.centres) (sgn c : CGPTag_BAUGP L Z → ℝ) (a x : ℝ) :
    ‖x‖ ≤ ‖fderiv ℝ (egpModelGraph_BAUGP L Z i sgn c) a x‖ := by
  let j : L.edgeB.finite_centres.toFinset := ⟨i, (Set.Finite.mem_toFinset _).mpr hi⟩
  have hcomp := fderiv_blockGraph_apply_KC3
    (fun t => (contDiff_egpModelComponent_BAUGP L Z i sgn c t).differentiable (by simp)) a x
    (.inr (.inr (.inl j)))
  have hown : egpModelComponent_BAUGP L Z i sgn c (.inr (.inr (.inl j))) =
      fun a => blockLift_KC3 (WithLp.toLp 2 (a, (1 : ℝ))) := by
    simp only [egpModelComponent_BAUGP, j, ite_true]
  obtain ⟨v₁, hv₁def⟩ : ∃ v : WithLp 2 (ℝ × ℝ), v = WithLp.toLp 2 ((1 : ℝ), (0 : ℝ)) := ⟨_, rfl⟩
  obtain ⟨v₀, hv₀def⟩ : ∃ v : WithLp 2 (ℝ × ℝ), v = WithLp.toLp 2 ((0 : ℝ), (1 : ℝ)) := ⟨_, rfl⟩
  have hfun : (fun a : ℝ => (WithLp.toLp 2 (a, (1 : ℝ)) : WithLp 2 (ℝ × ℝ))) =
      fun a => ContinuousLinearMap.toSpanSingleton ℝ v₁ a + v₀ := by
    funext a
    rw [ContinuousLinearMap.toSpanSingleton_apply, hv₁def, hv₀def, ← WithLp.toLp_smul,
      ← WithLp.toLp_add]
    congr 1
    simp
  have hv₁ : ‖v₁‖ = 1 := by
    rw [hv₁def, WithLp.prod_norm_eq_of_L2]
    simp
  have hd : HasFDerivAt (fun a : ℝ => ContinuousLinearMap.toSpanSingleton ℝ v₁ a + v₀)
      (ContinuousLinearMap.toSpanSingleton ℝ v₁) a :=
    (ContinuousLinearMap.toSpanSingleton ℝ v₁).hasFDerivAt.add_const v₀
  have hW0d : Differentiable ℝ (fun a : ℝ => (WithLp.toLp 2 (a, (1 : ℝ)) : WithLp 2 (ℝ × ℝ))) :=
    own_block_bounds_KC3.1.differentiable (by simp)
  have hW0x : fderiv ℝ (fun a : ℝ => (WithLp.toLp 2 (a, (1 : ℝ)) : WithLp 2 (ℝ × ℝ))) a x =
      x • v₁ := by
    rw [hfun, hd.fderiv]
    rfl
  have hval : fderiv ℝ (egpModelComponent_BAUGP L Z i sgn c (.inr (.inr (.inl j)))) a x =
      blockLift_KC3 (x • v₁) := by
    rw [hown]
    change fderiv ℝ (blockLift_KC3 ∘ fun a : ℝ => (WithLp.toLp 2 (a, (1 : ℝ)) :
      WithLp 2 (ℝ × ℝ))) a x = _
    rw [fderiv_clm_comp_apply_KC3 blockLift_KC3 (hW0d a), hW0x]
  have hnorm : ‖blockLift_KC3 (x • v₁)‖ = ‖x‖ := by
    rw [norm_blockLift_apply_KC3, norm_smul, hv₁, mul_one]
  calc ‖x‖ = ‖fderiv ℝ (egpModelGraph_BAUGP L Z i sgn c) a x (.inr (.inr (.inl j)))‖ := by
        rw [← hnorm, ← hval, ← hcomp]
        rfl
    _ ≤ ‖fderiv ℝ (egpModelGraph_BAUGP L Z i sgn c) a x‖ := PiLp.norm_apply_le _ _


end Part1

section Part2


variable {X : Type} [mX : MetricSpace X] [ChartedSpace E3 X] [IsManifold 𝓘(ℝ, E3) ∞ X]
  [CompleteSpace X] [SigmaCompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
  {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
  {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
  {σc μ b s b' s' ε γc βc Lmax τ γ vs : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
  {N C : X → Type} [∀ a, MetricSpace (N a)] [∀ a, ChartedSpace E3 (N a)]
  [∀ a, MetricSpace (C a)] {o : ∀ a, C a} {δ εr e T V : ℝ}

variable (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T
    V vs U₁ U₂ Ue₁ Ue₂)
  (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂)

/-- EGP02's listed edge centres have `ρ(j) > (99/100)ρ(i)`. -/
theorem egpEdgeList_ratio_GAF4_BAUGP (hΔ : 0 < Δ) (hΛ : 0 ≤ Λ) (hLΛ : 1000000 * Δ * Λ < 1 / 100000)
    {i j : X} (hj : j ∈ egpEdgeList_BAUGP L i) : 99 / 100 * ρ i < ρ j := by
  have hc : ((Real.toNNReal Λ : NNReal) : ℝ) = Λ := Real.coe_toNNReal _ hΛ
  obtain ⟨-, y, hy1, hy2⟩ := hj
  have hy1' : y ∈ closedBall j ((100 * Δ) * ρ j) := L.tsupport_edgeB_cutoff_subset_closedBall_BCNT
      hΔ j hy1
  have hy2' : y ∈ ball i ((20 * Δ) * ρ i) := by
    rw [mul_assoc] at hy2 ⊢
    exact hy2
  obtain ⟨h1, -, -, -⟩ := support_meeting_sharp_bounds L.lipschitz_scale (hρ i) (hρ j)
    (a := 20 * Δ) (c := 100 * Δ) (by positivity) (by positivity) (by rw [hc]; nlinarith)
    (by rw [hc]; nlinarith) ⟨y, hy1', hy2'⟩
  have h := (lt_div_iff₀ (hρ i)).mp h1
  linarith

/-- EGP02's listed slim centres have `ρ(j) > (99/100)ρ(i)`. -/
theorem egpSlimList_ratio_GAF4_BAUGP (hΔ : 0 < Δ) (hΛ : 0 ≤ Λ) (hLΛ : 1000000 * Δ * Λ < 1 / 100000)
    {i j : X} (hj : j ∈ egpSlimList_BAUGP L i) : 99 / 100 * ρ i < ρ j := by
  have hc : ((Real.toNNReal Λ : NNReal) : ℝ) = Λ := Real.coe_toNNReal _ hΛ
  obtain ⟨hjc, y, hy1, hy2⟩ := hj
  have hy1' : y ∈ closedBall j ((910000 * Δ) * ρ j) := (fc18_slim_row_BAUGP L hΔ hjc).1 hy1
  have hy2' : y ∈ ball i ((20 * Δ) * ρ i) := by
    rw [mul_assoc] at hy2 ⊢
    exact hy2
  obtain ⟨h1, -, -, -⟩ := support_meeting_sharp_bounds L.lipschitz_scale (hρ i) (hρ j)
    (a := 20 * Δ) (c := 910000 * Δ) (by positivity) (by positivity) (by rw [hc]; nlinarith)
    (by rw [hc]; nlinarith) ⟨y, hy1', hy2'⟩
  have h := (lt_div_iff₀ (hρ i)).mp h1
  linarith


end Part2

section Part3


section Models

attribute [local instance] nezero_finrank_euclideanThree_LC87

variable {X : Type} [mX : MetricSpace X] [ChartedSpace E3 X] [IsManifold 𝓘(ℝ, E3) ∞ X]
  [CompleteSpace X] [SigmaCompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
  {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
  {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {Λ : ℝ} {β : ℕ → ℝ} {Δ σs : ℝ} {K : ℕ}
  {σc μ b s b' s' ε γc βc Lmax τ γ vs : ℝ} {U₁ U₂ Ue₁ Ue₂ : Set X}
  {N C : X → Type} [∀ a, MetricSpace (N a)] [∀ a, ChartedSpace E3 (N a)]
  [∀ a, MetricSpace (C a)] {o : ∀ a, C a} {δ εr e T V : ℝ}

/-- **GAF04's plane half for EGP06's model** (edge tags): at `a`, the marker of the edge block `j`
of `Φ_i = egpModelGraph_BAUGP` annihilates `DΦ_i(a)` when `j` is the own tag, unlisted, or listed
with
`|s_j⁻¹(sgn_j a + c_j)| < 8Δ` (`s_j = ρ(j)/ρ(i)`). -/
theorem egpModelGraph_marker_fderiv_GAFS_BAUGP
    (L : LocalPacketsOnB X g hmetric ρ hρ Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs
        U₁ U₂ Ue₁ Ue₂)
    (Z : ZeroModelFamilyOn 𝓘(ℝ, E3) X g ρ hρ β N C o δ εr e T V U₁ U₂) (hΔ : 0 < Δ) (i : X)
    (sgn c : CGPTag_BAUGP L Z → ℝ) (j : L.edgeB.finite_centres.toFinset) (a : ℝ)
    (hplat : j.1 ≠ i → j.1 ∈ egpEdgeList_BAUGP L i →
      |(ρ j.1 / ρ i)⁻¹ * (sgn (.inr (.inr (.inl j))) * a + c (.inr (.inr (.inl j))))| < 8 * Δ)
    (h : ℝ) :
    blockMarkerCLM (.inr (.inr (.inl j)) : CGPTag_BAUGP L Z) (fderiv ℝ (egpModelGraph_BAUGP L Z i
        sgn c) a h)
      = 0 := by
  classical
  have hΦ : DifferentiableAt ℝ (egpModelGraph_BAUGP L Z i sgn c) a :=
    ((contDiff_egpModelGraph_BAUGP L Z i sgn c).differentiable (by simp)) a
  have hval : ∀ y, egpModelGraph_BAUGP L Z i sgn c y (.inr (.inr (.inl j))) =
      egpModelComponent_BAUGP L Z i sgn c (.inr (.inr (.inl j))) y := fun _ => rfl
  by_cases hji : j.1 = i
  · refine blockMarkerCLM_fderiv_eq_zero_GAFS (c := 1) _ hΦ (Eventually.of_forall fun y => ?_) h
    dsimp only
    rw [hval]
    simp only [egpModelComponent_BAUGP, hji, ite_true]
    rfl
  · by_cases hS : j.1 ∈ egpEdgeList_BAUGP L i
    · refine blockMarkerCLM_fderiv_eq_zero_GAFS (c := ρ j.1 / ρ i) _ hΦ ?_ h
      have hev := scaledCutoffBlock_snd_eventually_GAFS (s := ρ j.1 / ρ i) (r := 8 * Δ)
        (φ := scaledEdgeCoordinateProfile Δ)
        (fun z hz => by
          rw [Real.norm_eq_abs] at hz
          have hz' : |z / Δ| ≤ 8 := by
            rw [abs_div, abs_of_pos hΔ, div_le_iff₀ hΔ]
            exact hz
          exact intervalPlateauProfile_one (by norm_num) (by norm_num)
            ⟨by linarith [neg_abs_le (z / Δ)], by linarith [le_abs_self (z / Δ)]⟩)
        (u := fun y => sgn (.inr (.inr (.inl j))) * y + c (.inr (.inr (.inl j))))
        ((continuous_const.mul continuous_id).add continuous_const).continuousAt
        (by rw [smul_eq_mul, Real.norm_eq_abs]; exact hplat hji hS)
      filter_upwards [hev] with y hy
      rw [hval]
      simp only [egpModelComponent_BAUGP, hji, hS, ite_true, ite_false]
      exact hy
    · refine blockMarkerCLM_fderiv_eq_zero_GAFS (c := 0) _ hΦ (Eventually.of_forall fun y => ?_) h
      dsimp only
      rw [hval]
      simp only [egpModelComponent_BAUGP, hji, hS, ite_false]
      rfl

end Models


end Part3

end DifferentialGeometry.Geometry.Collapse
