name = "DifferentialGeometry"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DifferentialGeometry"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "DifferentialGeometry"
