import DifferentialGeometry.Geometry.Comparison.Volume.ScaledBallComparison
import DifferentialGeometry.Geometry.Comparison.Volume.RicciScaleMultiplicity
import DifferentialGeometry.Analysis.InnerProductSpace.PrunedGraphRank
import DifferentialGeometry.Analysis.Calculus.PrunedGraph
import DifferentialGeometry.Geometry.Metric.RetainedMarkerLocality
import DifferentialGeometry.Analysis.NormedSpace.ScaleVanishing

#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.ballVolume_mul_scale_le_model_ratio
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.exists_finite_scale_cover_of_ricci_bound
#print axioms ContinuousLinearMap.pruned_graph_range_surjective_of_approximation
#print axioms DifferentialGeometry.Analysis.pruned_graph_derivative_surjective_of_approximation
#print axioms GC.MetricGeometry.nearby_scale_comparison_of_retained_markers
#print axioms GC.MetricGeometry.small_radius_lt_half_reference_of_contributing_support
#print axioms ContinuousLinearMap.norm_on_segment_le_of_vanishing_at_small_scale
