import DifferentialGeometry.Analysis.Integration.Integral.Circle
import DifferentialGeometry.Analysis.Calculus.CircleResolvent
import DifferentialGeometry.Analysis.InnerProductSpace.SpectralProjection
import DifferentialGeometry.Analysis.InnerProductSpace.ProjectionRankStability
import DifferentialGeometry.Analysis.Integration.Integral.Resolvent
import DifferentialGeometry.Analysis.InnerProductSpace.SpectralProjectionBounds
import DifferentialGeometry.Analysis.InnerProductSpace.SpectralProjectionRegularity

#print axioms ContinuousMap.circleIntegralCLM
#print axioms ContinuousMap.circleIntegralCLM_apply
#print axioms ContinuousMap.norm_circleIntegralCLM_le
#print axioms contDiffOn_circleIntegral_resolvent
#print axioms ContDiffOn.circleIntegral_resolvent
#print axioms ContinuousLinearMap.circleIntegral_resolvent_eq_starProjection
#print axioms Submodule.iSup_eigenspace_starProjection_eq
#print axioms Submodule.injective_orthogonalProjectionOnto_restrict_of_norm_sub_lt_one
#print axioms Submodule.finrank_eq_of_norm_starProjection_sub_lt_one
#print axioms spectrum.norm_normalized_circleIntegral_resolvent_sub_le
#print axioms ContinuousLinearMap.norm_starProjection_eigenspace_ball_sub_le
#print axioms ContinuousLinearMap.finrank_eigenspace_ball_eq_of_norm_sub_starProjection_lt
#print axioms ContDiffOn.starProjection_eigenspace_ball
