import Mathlib.Tactic.Linter
import DifferentialGeometry.Analysis.Calculus.BilinearBounds
import DifferentialGeometry.Analysis.Calculus.SecondDerivativeComposition
import DifferentialGeometry.Analysis.Calculus.WeightedAffineCutoff
import DifferentialGeometry.Analysis.Calculus.ScaledCutoffBlock

#check ContinuousLinearMap.norm_fderiv_bilinear_le
#print axioms ContinuousLinearMap.norm_fderiv_bilinear_le

#check ContinuousLinearMap.norm_second_fderiv_bilinear_le
#print axioms ContinuousLinearMap.norm_second_fderiv_bilinear_le

#check DifferentialGeometry.Analysis.norm_second_fderiv_comp_le
#print axioms DifferentialGeometry.Analysis.norm_second_fderiv_comp_le

#check DifferentialGeometry.Analysis.linear_precomp_derivative_bounds
#print axioms DifferentialGeometry.Analysis.linear_precomp_derivative_bounds

#check DifferentialGeometry.Analysis.weighted_affine_cutoff_derivative_bounds
#print axioms DifferentialGeometry.Analysis.weighted_affine_cutoff_derivative_bounds

#check DifferentialGeometry.Analysis.scaledCutoffBlock
#print axioms DifferentialGeometry.Analysis.scaledCutoffBlock

#check DifferentialGeometry.Analysis.contDiff_scaledCutoffBlock
#print axioms DifferentialGeometry.Analysis.contDiff_scaledCutoffBlock

#check DifferentialGeometry.Analysis.scaledCutoffBlock_derivative_bounds
#print axioms DifferentialGeometry.Analysis.scaledCutoffBlock_derivative_bounds

#check DifferentialGeometry.Analysis.scaledCutoffBlock_c1_comp_sub_le
#print axioms DifferentialGeometry.Analysis.scaledCutoffBlock_c1_comp_sub_le
