import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.A13WiringK_S46
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.MicroPointwiseAssemblyK_S113
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.CapWindowZCMain_S64
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.CapKcapMain_S73
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.MicroZeroOrderDoubled_O23
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.MicroLowPoint_S33
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.KcapPt_O29
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.KcoreAssembly_O31
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.SeedsKL84GlueKappa_O22
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.SeedsKL84Pinch_O16
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.L862KappaCert_O28
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HtraceU_O56
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HScaleExact_S119
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.SeedsKL82ClaimMain_O36
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.L862HG2cV3_O63
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.L862HSeed_S139
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HFrontSlice_S148
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HTraceBall_S138
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.BallBound_S141
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HKL70DirectV2_O72
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HFEVol_S127
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HFEGlue_S133
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HTSAssembly_S113
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HBirthReduce_S134
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HShiftReduce_S131
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HShiftReduceV4_S137
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.ZTAssembly_S113
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.L862KL82R_O79
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HZTWire_S150

set_option autoImplicit false

/-!
# CH12-S153 (generated by scratch/S153gen/gen_s153.py from A13Final_S149; O79 swap: `hU` deleted, `hG2c := hG2c_R_closed_O79 Hp hdec hP2 hprof`; S150 swap: `hsurv` deleted, `hZT := hZT_S150 Hp hdec Ctime hP2 hFront hCapWin`). Previously: CH12-S149 (regenerated from A13Final_S124 by scratch/S149gen/regen_s149.py, hKL70 mode O72, hG2c mode U): A13 terminal wiring with ALL existing producers plugged in (as A13Final_S144, with hKL70 := hKL70_direct_v2_O72 (no hloc), hFront := hFront_S148 Hp hRFCa (new binder hRFCa replaces hFront), hKL82 := kl82_1_O36, hG2c := hG2c_v3_O63 (hscale from hprof) .. hU, hKL70 := hKL70_direct_v2_O72, hZT := hZT_of_kl82_S113 .. hFE hTS with hFE/hTS from hFE_of_core_S127/hFEcore_of_trace_S133/hTS_S113/hshift reductions from hsurv); the remaining binders are exactly the producers' own inputs (text cut mechanically from the producer sources), see the delivery block.  Previously: S144, S124 (copy of CH12-S78 via the S113 pipeline), A13 terminal wiring (conditional theorem) with the `hZT` binder at `[FROZEN v2] CH12-S113`, `hptK_of_Z0_ZT_ZC_S113`, and the `hKL70` binder in the U-form of `[FROZEN] CH12-O56 G1/G2` (no `∃ Dcap hD`; cap premise `¬ capPtU_O56`; proof side `hcore_O31 Hp (capPtU_O56 ..)`, `hcap_U_O56`); everything else verbatim

`A13_of_supplies_S149` has the conclusion of `late_derivative_tests_of_flow`
(`LateCutGeometry.lean:158`, binders `F K hK δ hadm hdec slices htimes hnonempty L` and conclusion
`L.hasEventualDerivativeBounds`, verbatim), plus a profile `Hp` (as in S32 / S46) and explicit
hypotheses.  Every proved piece is imported and substituted:

* K-indexed A13 wiring `late_derivative_tests_of_flow_of_supplies_K_S46` (S46 / S32 / CX9 / CX2);
* `hMicroK` := `microWholeBallK_of_pointwise_S44` applied to `hptK_of_Z0_ZT_ZC_S113` (S44 / S64);
* `hZ0` := `micro_zero_order_doubled_v2_O23` with `hZ1` := `micro_low_scalar_point_S33` and
  `hKcan` := `hKcan_v2_of_branchesA_O23` (O23) at the union cap predicate `capPtU_O56` (O56),
  `hcap` := `hcap_U_O56` fed with `hKcap_S73` (S73), `hcore` := `hcore_O31` (O31 G2);
* `hZC` := `hZC_S64` (S64);
* `hG2` := `hG2_of_kl82_kappa_O22` (O22) with `hpinchS_O16` (O16) and `hG2c_kappa_of_cert_O28` (O28).

Remaining explicit ch12 inputs: `hKL82`, `hG2c` (κ-cert), `hKL70` (the KL70.2 core consumed by
`hcore_O31`, at the union cap predicate `capPtU_O56`, no `Dcap`), `hZT`.  ch11 supplies:
`hP1`, `hP2`, `hP3`, `hP4`, `hP6`, `hP5`, `hStrong`, `hcompat`.

S124 changes vs S113: only the `hKL70` binder / its three proof lines (see the title); the free cap radius `Dcap` is gone (the cap predicate is the union over cap radii `capPtU_O56`, lead ruling O56-1 (a)).  No `hscale` binder exists in this terminal (`hscale` enters through the `hG2c` producer only).
-/

noncomputable section

open Set Filter TopologicalSpace Manifold
open DifferentialGeometry DifferentialGeometry.Topology
open DifferentialGeometry.Geometry.Curvature
open DifferentialGeometry.Geometry.Collapse DifferentialGeometry.Geometry.Riemannian
open DifferentialGeometry.Geometry.Riemannian.VolumeComparison
open DifferentialGeometry.PDE.RicciFlow DifferentialGeometry.PDE.RicciFlow.Surgery.Topology
open DifferentialGeometry.PDE.RicciFlow.Perelman
open DifferentialGeometry.PDE.RicciFlow.Perelman.CanonicalNeighborhood.FiniteHorn
open DifferentialGeometry.Integral.Measure
open GC.LongTime
open DifferentialGeometry.Tensor0SBundle DifferentialGeometry.Geometry.Hyperbolic
open scoped Manifold ContDiff Topology ENNReal NNReal

namespace GC.LongTime.Ch12
universe u

/-- **A13 from the supplies (terminal conditional theorem).**  Conclusion = that of
`late_derivative_tests_of_flow`; see the file header for the substituted pieces and the remaining
explicit inputs. -/
theorem A13_of_supplies_S153 {P : OrientedThreeStage.{u}} {g : P.Metric}
    (F : GC.Interface.RawSurgery P g) (K : ℕ) (hK : lateDerivativeOrder ≤ K) (δ : ℝ → ℝ)
    (hadm : hasAnalyticAdmissibility F δ)
    (hdec : ∀ ε : ℝ, 0 < ε → ∃ B : ℝ, ∀ t : ℝ, B < t → δ t < ε)
    (slices : ℕ → RegularSlice F.observation)
    (htimes : ∀ j : ℕ, (j : ℝ) < (slices j).time)
    (hnonempty : ∀ j : ℕ, Nonempty (slices j).stage.Carrier)
    (L : GC.LongTime.LateCutFamily F K slices)
    (Hp : AnalyticSurgeryProfile F δ)
    (hP1 : P1_O2 Hp) (Ctime : ℝ≥0) (hP2 : P2_O2 Hp Ctime) (hP3 : P3_O2 Hp) (hP4 : P4_O2 Hp)
    (hP6 : P6_S23 Hp) (hP5 : P5Linked_O13 Hp)
    (hcompat : CompatibleUpgradedCapRecords_S58 Hp)
    (hStrong : ∃ T : ℝ, ∀ s : RegularSlice F.observation, T ≤ s.time →
      ∀ x : s.stage.Carrier,
      ∀ hR : (Hp.parameters.neckRadius s.time ^ 2)⁻¹ < metricScalarAt s.metric x,
      ∃ W : SpatialCanonicalWitness s.metric Hp.epsilon Hp.C1 Hp.C2 x,
        W.capTubeHasNeckChart Hp.epsilon ∧
        ∀ nk, W.alternative = SpatialCanonicalAlternative.neck nk →
          ∃ (U : TopologicalSpace.Opens s.stage.Carrier) (hxU : x ∈ U)
            (S : SolutionOn (I := ThreeModel) (M := U)
              (RealTimeInterval.closed (s.time - (metricScalarAt s.metric x)⁻¹) s.time
                (sub_le_self _ (inv_nonneg.mpr
                  (lt_of_le_of_lt (inv_nonneg.mpr (sq_nonneg _)) hR).le)))),
            IsSolutionOn S ∧ S.base.metric s.time = s.metric.restrictOpen U ∧
            Nonempty (StrongNeck S Hp.epsilon ⟨x, hxU⟩ s.time))
    (hprof : Hp.parameters.modelAccuracy ≤ (hscale_of_prof_S119.{u}).choose ∧
      2 ≤ Hp.parameters.modelOrder ∧ StandardCap.transitionEnd + 1 ≤ Hp.parameters.modelRadius)
    (heps : 13000 * (13000 * Hp.epsilon) ≤
      min (neckModelTolerance ((1 / 4000000 : ℝ) / 26000)) (((1 / 4000000 : ℝ) / 26000) / 64))
    (hRFCa : ∀ (s : RegularSlice F.observation) (pp : CutoffParameters),
      pp.delta = Hp.parameters.delta → pp.neckRadius = Hp.parameters.neckRadius →
      pp.fixed = Hp.parameters.fixed → pp.recenterConstant = Hp.parameters.recenterConstant →
      StandardCap.transitionEnd + 3 < pp.modelRadius → pp.modelAccuracy ≤ 3 / 4 →
      4 ≤ pp.modelOrder →
      ∀ (i : Fin (sliceHistoryR_O3 F s).eventCount)
        (R : GeometricCutoffRecord (sliceHistoryR_O3 F s).toHistory i pp),
        (∀ b, linkedCanonicalWindow_O2 (R.static b)) →
        ∀ y ∈ frontier (range ((sliceHistoryR_O3 F s).toHistory.event i).oldOutput),
          ∃ (b : ((sliceHistoryR_O3 F s).toHistory.event i).RetainedBoundaryIndex)
            (c : neckRetainedCollar (R.static b).delta), c.1.2 ≤ 1 ∧
              (R.static b).inclusion ((R.static b).witness.retained c) = y)
    (hCapWin : ∀ (θ Dcap : ℝ), StandardCap.transitionEnd + 3 < Dcap → ∃ (Tc εc : ℝ), 0 < εc ∧
      ∀ s : RegularSlice F.observation, Tc ≤ s.time → ∀ T₀ : ℝ, Tc ≤ T₀ → T₀ ≤ s.time →
      ∀ (pp : CutoffParameters)
        (records : ∀ i : Fin (sliceHistoryR_O3 F s).eventCount,
          T₀ - θ ≤ (sliceHistoryR_O3 F s).time i.succ →
          GeometricCutoffRecord (sliceHistoryR_O3 F s).toHistory i pp),
        pp.delta = Hp.parameters.delta → pp.neckRadius = Hp.parameters.neckRadius →
        pp.fixed = Hp.parameters.fixed → pp.recenterConstant = Hp.parameters.recenterConstant →
        32 * (Dcap + 1) + 2 ≤ pp.modelRadius →
        pp.modelAccuracy ≤ εc → 4 ≤ pp.modelOrder →
        (∀ i hi b, linkedCanonicalWindow_O2 ((records i hi).static b)) →
      ∀ (j : Fin (sliceHistoryR_O3 F s).eventCount)
        (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
        (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex) (z : ThreeBall),
        ∃ x : standardCapWindow pp.modelRadius, ‖x.val‖ < Dcap - 1 + 1 ∧
          ((records j hj).static b).window x =
            ((records j hj).static b).inclusion (((records j hj).static b).witness.cap z))
    : L.hasEventualDerivativeBounds := by
  classical
  -- KL84.2: `hG2` from KL82.1, the slice pinching and the κ-certified KL Lemma 86.2
  -- S149 producer wiring (hFront := hFront_S148 Hp hRFCa; hKL70 := O72) (all `have`s are the frozen producer applications; remaining inputs are binders)
  have hKL82 := kl82_1_O36.{u}
  -- S153 (O79 G4/G5): hG2c leaf closed on the region contract (V3-R+), no `hU` binder
  have hG2c := hG2c_R_closed_O79 Hp hdec hP2 hprof
  have hFront := hFront_S148 Hp hRFCa
  -- S150 (via S153): hbirth / hFE / hTS / hZT from `hsurv_core_S146` (60-tube + c₀-clause chain, HZTWire_S150); no `hsurv` / `hBall` binder
  have hZT := hZT_S150 Hp hdec Ctime hP2 hFront hCapWin
  have hG2 := hG2_of_kl82_kappa_O22 Hp hdec hKL82 (hpinchS_O16 Hp) (hG2c_kappa_of_cert_O28 Hp hG2c)
  -- K-cap (S73) and the cap predicate (O29)
  have hKcap := hKcap_S73 Hp hdec hP3 hcompat Ctime hP2
  have hKL70 := hKL70_direct_v2_O72 Hp hKcap Ctime hP2 hP5 heps
  have hcore := hcore_O31 Hp (capPtU_O56 Hp hKcap) hStrong hKL70
  have hcap := hcap_U_O56 Hp hKcap
  -- Z0 on the doubled ball (O23), then the K-indexed pointwise glue (S64) and the micro glue (S44)
  have hKcan := hKcan_v2_of_branchesA_O23 Hp (capPtU_O56 Hp hKcap) hcore hcap
  have hZ0 := micro_zero_order_doubled_v2_O23 Hp (micro_low_scalar_point_S33 Hp) hKcan
  -- S64's `hZC_S64` states the records data as one conjunction; `hptK_of_Z0_ZT_ZC_S113` takes it curried
  -- (adapter as in `scratch/AxS64G1.lean`)
  have hpt := hptK_of_Z0_ZT_ZC_S113 Hp hP5 Ctime hP2 hZ0
    (fun Ctime' hP2' => by
      obtain ⟨θ, hθ, h⟩ := hZC_S64 Hp hdec hP3 hcompat Ctime' hP2'
      refine ⟨θ, hθ, fun Dcap C0 hD hC0 K' => ?_⟩
      obtain ⟨B, T, hBT⟩ := h Dcap C0 hD hC0 K'
      exact ⟨B, T, fun s hs T₀ h1 h2 pp rec h3 h4 h5 h6 h7 h8 y ρ hρ hZ0' hcap k hk =>
        hBT s hs T₀ h1 h2 pp rec ⟨h3, h4, h5, h6, h7, h8⟩ y ρ hρ hZ0' hcap k hk⟩) hZT
  exact late_derivative_tests_of_flow_of_supplies_K_S46 F K hK δ hadm hdec slices htimes hnonempty L
    Hp hP1 Ctime hP2 hP3 hP4 hP6 hG2
    (fun _ _ _ => microWholeBallK_of_pointwise_S44 Hp hpt K)

end GC.LongTime.Ch12
