import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.BallGrad_S141
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HFEGlue_S133

/-!
# CH12-S150 G1: `hBall_S150` -- `hBall_S141` with the `60 (θ'ρ/40)`-ball (the tube radius of F-S146-1)

GENERATED by `build-logs/ch12/scratch/S150gen/gen_g1.py` from `BallBound_S141.lean`; only constants change: the ball radius is `60 (θ'ρ/40) = 3θ'ρ/2`
so the gradient-estimate hypothesis `C₂ · r · √N ≤ 1/4` (`N = 4 max(C0,1)/ρ²`) reads `3 C₂ θ' √c0 ≤ 1/4`, and `θ₁ := 1/(12 C₂ √c0 + 1)`
(was `1/(4 C₂ √c0 + 1)`).  Statement = `[FROZEN] CH12-S138 hBall` with `20 *` → `60 *` in the ball radius.
-/

set_option autoImplicit false

noncomputable section

open Set Manifold DifferentialGeometry DifferentialGeometry.Topology
  DifferentialGeometry.PDE.RicciFlow DifferentialGeometry.PDE.RicciFlow.Surgery.Topology
  DifferentialGeometry.PDE.RicciFlow.Perelman.CanonicalNeighborhood.FiniteHorn
  DifferentialGeometry.Geometry.Collapse DifferentialGeometry.Geometry.Curvature
  DifferentialGeometry.Geometry.Riemannian DifferentialGeometry.Tensor0SBundle
open scoped Manifold ContDiff ENNReal NNReal

namespace GC.LongTime.Ch12

universe u

variable {P : OrientedThreeStage.{u}} {g : P.Metric} {F : GC.Interface.RawSurgery P g} {δ : ℝ → ℝ}

theorem hBall_S150 (Hp : GC.LongTime.AnalyticSurgeryProfile F δ) :
    ∀ w : ℝ, 0 < w → ∀ Λ : ℝ, 1 ≤ Λ → ∀ (θ Dcap C0 : ℝ), 0 < θ → 0 < C0 → StandardCap.transitionEnd + 3 < Dcap →
          ∃ (K' τ₀ : ℝ), 0 < K' ∧ 0 < τ₀ ∧ ∀ τ₁ τ₂ : ℝ, 0 < τ₁ → τ₁ ≤ τ₀ → 0 < τ₂ → τ₂ ≤ τ₀ →
          ∃ (bF TF θ₁ εF : ℝ), 0 < bF ∧ 0 < TF ∧ 0 < θ₁ ∧ 0 < εF ∧
          ∀ s : RegularSlice F.observation, TF ≤ s.time → ∀ T₀ : ℝ, TF ≤ T₀ → T₀ ≤ s.time →
          ∀ (pp : CutoffParameters)
            (records : ∀ i : Fin (sliceHistoryR_O3 F s).eventCount,
              T₀ - θ ≤ (sliceHistoryR_O3 F s).time i.succ →
              GeometricCutoffRecord (sliceHistoryR_O3 F s).toHistory i pp),
            pp.delta = Hp.parameters.delta → pp.neckRadius = Hp.parameters.neckRadius →
            pp.fixed = Hp.parameters.fixed → pp.recenterConstant = Hp.parameters.recenterConstant →
            32 * (Dcap + 1) + 2 ≤ pp.modelRadius →
            pp.modelAccuracy ≤ εF → 4 ≤ pp.modelOrder →
            (∀ i hi b, linkedCanonicalWindow_O2 ((records i hi).static b)) →
          ∀ (p : s.stage.Carrier) (ρ : ℝ), 0 < ρ → ρ ≤ bF * Real.sqrt s.time →
            (∃ n, ∃ i : Fin (F.tower.history n).eventCount, ∃ h,
              (F.tower.history n).time i.succ ∈ Icc (s.time / 2) s.time ∧
              ρ < Λ * (Hp.records n i).nominalRadius h) →
            (∃ z ∈ connectedComponent p, ¬ SectionalBoundedBelowAt s.metric z 0) →
            (∀ q ∈ riemannianBallOf s.metric p ρ,
              SectionalBoundedBelowAt s.metric q (-(ρ ^ 2)⁻¹)) →
            ENNReal.ofReal (w * ρ ^ 3) ≤ ballVolume s.metric p ρ →
            (∀ x ∈ riemannianBallOf s.metric p (2 * ρ), metricScalarAt s.metric x ≤ C0 / ρ ^ 2) →
            ∀ q ∈ riemannianBallOf s.metric p ρ,
              ¬ (∃ (j : Fin (sliceHistoryR_O3 F s).eventCount)
                (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
                (hl : j.succ ≤ Fin.last (sliceHistoryR_O3 F s).eventCount)
                (B : BackwardPointTrace (sliceHistoryR_O3 F s).toHistory j.succ
                  (Fin.last (sliceHistoryR_O3 F s).eventCount) hl q)
                (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex)
                (x : standardCapWindow pp.modelRadius),
                B.point j.succ le_rfl hl = ((records j hj).static b).window x ∧
                  ‖x.val‖ < Dcap + 1 ∧
                  s.time - (sliceHistoryR_O3 F s).time j.succ ≤
                    θ * (((records j hj).static b).neck.scale)⁻¹) →
            ∀ θ' : ℝ, 0 < θ' → θ' ≤ θ₁ → ∀ q' : (s.history.stageAt (sliceTop_S8 s)).Carrier, HEq q' q →
              ∀ (a₀ : Icc (0 : ℝ) s.history.horizon) (hat : a₀ ≤ sliceTop_S8 s)
                (X : BackwardPointTrace s.history (s.history.activeStage a₀)
                  (s.history.activeStage (sliceTop_S8 s)) (s.history.activeStage_mono hat) q'),
                (a₀ : ℝ) = s.time - (τ₁ + τ₂) * (θ' * ρ) ^ 2 →
                (∀ (v : Icc (0 : ℝ) s.history.horizon) (hav : a₀ ≤ v) (hvt : v ≤ sliceTop_S8 s),
                  metricScalarAt (s.history.stageMetric (s.history.activeStage v) v)
                    (X.point (s.history.activeStage v) (s.history.activeStage_mono hav)
                      (s.history.activeStage_mono hvt)) ≤ 4 * max C0 1 / ρ ^ 2) →
                ∀ (v : Icc (0 : ℝ) s.history.horizon) (hav : a₀ ≤ v) (hvt : v ≤ sliceTop_S8 s),
                  ∀ z ∈ riemannianBallOf (s.history.stageMetric (s.history.activeStage v) v)
                    (X.point (s.history.activeStage v) (s.history.activeStage_mono hav)
                      (s.history.activeStage_mono hvt)) (60 * (θ' * ρ / 40)),
                    Real.sqrt (normSq0S (s.history.stageMetric (s.history.activeStage v) v) z 4
                      (metricRm04At (s.history.stageMetric (s.history.activeStage v) v) z)) ≤
                      K' / (θ' * ρ / 40) ^ 2 := by
  intro w hw Λ hΛ θ Dcap C0 hθ hC0 hDcap
  obtain ⟨T₁, hT₁, hmic⟩ := micro_scale_le_neckRadius_O13 Hp Λ 1 (by linarith) one_pos
  obtain ⟨C, hC, hCrm⟩ := slice_rm_bound_of_scalar_O22 Hp
  obtain ⟨c0, hc0def⟩ : ∃ c0 : ℝ, c0 = max C0 1 := ⟨_, rfl⟩
  have hc0 : 1 ≤ c0 := hc0def ▸ le_max_right _ _
  obtain ⟨R, hRdef⟩ : ∃ R : ℝ, R = max (Hp.parameters.neckRadius 0) 1 := ⟨_, rfl⟩
  have hR1 : 1 ≤ R := hRdef ▸ le_max_right _ _
  obtain ⟨m, hmdef⟩ : ∃ m : ℝ, m = max 1 (R ^ 2) := ⟨_, rfl⟩
  have hm1 : 1 ≤ m := hmdef ▸ le_max_left _ _
  have hmR : R ^ 2 ≤ m := hmdef ▸ le_max_right _ _
  have hC2 : 0 ≤ Hp.C2 := by linarith [Hp.C2_ge_one]
  have hsc0 : 0 < Real.sqrt c0 := Real.sqrt_pos.mpr (by linarith)
  obtain ⟨K', hK'def⟩ : ∃ K' : ℝ, K' = C * (16 * c0 * m) / 1600 := ⟨_, rfl⟩
  have hK' : 0 < K' := by rw [hK'def]; positivity
  obtain ⟨θ₁, hθ₁def⟩ : ∃ θ₁ : ℝ, θ₁ = 1 / (12 * Hp.C2 * Real.sqrt c0 + 1) := ⟨_, rfl⟩
  have hθ₁pos : 0 < θ₁ := by rw [hθ₁def]; positivity
  refine ⟨K', 1, hK', one_pos, ?_⟩
  intro τ₁ τ₂ hτ₁ hτ₁₀ hτ₂ hτ₂₀
  refine ⟨1, max T₁ 1, θ₁, 1, one_pos, lt_max_of_lt_right one_pos, hθ₁pos, one_pos, ?_⟩
  intro s hs T₀ hT₀a hT₀b pp records h1 h2 h3 h4 hmr hacc hord hlink p ρ hρ hρb hev hnn hsec hvol
    hRb q hq hnc θ' hθ' hθ'₁ q' hq' a₀ hat X ha₀ hX v hav hvt z hz
  have hsT₁ : T₁ ≤ s.time := (le_max_left _ _).trans hs
  have h0 := hmic s hsT₁ ρ hev
  have h0' : ρ ≤ Hp.parameters.neckRadius s.time := by linarith only [h0]
  have hvs : (v : ℝ) ≤ s.time := v.2.2
  have hanti0 : Hp.parameters.neckRadius s.time ≤ Hp.parameters.neckRadius 0 :=
    Hp.radius_antitone (Set.mem_Ici.mpr le_rfl) (Set.mem_Ici.mpr s.positive.le) s.positive.le
  have hρR : ρ ≤ R := by
    have : Hp.parameters.neckRadius 0 ≤ R := hRdef ▸ le_max_left _ _
    linarith only [h0', hanti0, this]
  have hantiv : Hp.parameters.neckRadius s.time ≤ Hp.parameters.neckRadius v :=
    Hp.radius_antitone (Set.mem_Ici.mpr v.2.1) (Set.mem_Ici.mpr s.positive.le) hvs
  have hρv : ρ ≤ Hp.parameters.neckRadius v := h0'.trans hantiv
  have hρ2 : 0 < ρ ^ 2 := by positivity
  have hN : 0 < 4 * c0 / ρ ^ 2 := by positivity
  have hq1 : (Hp.parameters.neckRadius v ^ 2)⁻¹ ≤ 4 * c0 / ρ ^ 2 := by
    have h1' : (Hp.parameters.neckRadius v ^ 2)⁻¹ ≤ (ρ ^ 2)⁻¹ :=
      inv_anti₀ hρ2 (pow_le_pow_left₀ hρ.le hρv 2)
    have h2' : (ρ ^ 2)⁻¹ ≤ 4 * c0 / ρ ^ 2 := by
      rw [← one_div, div_le_div_iff_of_pos_right hρ2]
      linarith
    exact h1'.trans h2'
  have hsN : Real.sqrt (4 * c0 / ρ ^ 2) = 2 * Real.sqrt c0 / ρ := by
    have : 4 * c0 / ρ ^ 2 = (2 * Real.sqrt c0 / ρ) ^ 2 := by
      rw [div_pow, mul_pow, Real.sq_sqrt (by linarith)]
      ring
    rw [this]
    exact Real.sqrt_sq (by positivity)
  have hθ'1 : θ' * (12 * Hp.C2 * Real.sqrt c0 + 1) ≤ 1 := by
    have := (le_div_iff₀ (by positivity : 0 < 12 * Hp.C2 * Real.sqrt c0 + 1)).mp
      (hθ₁def ▸ hθ'₁ : θ' ≤ 1 / (12 * Hp.C2 * Real.sqrt c0 + 1))
    simpa using this
  have hθ'le1 : θ' ≤ 1 := by
    have : 0 ≤ 12 * Hp.C2 * Real.sqrt c0 := by positivity
    nlinarith only [hθ'1, hθ', this]
  have hr : Hp.C2 * (60 * (θ' * ρ / 40)) * Real.sqrt (4 * c0 / ρ ^ 2) ≤ 1 / 4 := by
    rw [hsN]
    have e : Hp.C2 * (60 * (θ' * ρ / 40)) * (2 * Real.sqrt c0 / ρ) = 3 * (Hp.C2 * θ' * Real.sqrt c0) := by
      field_simp
      ring
    rw [e]
    nlinarith only [hθ'1, hθ', hC2, hsc0]
  have hball := ball_scalar_le_four_S141 Hp s v hN hq1 hr
    (X.point (s.history.activeStage v) (s.history.activeStage_mono hav)
      (s.history.activeStage_mono hvt)) (by rw [hc0def]; exact hX v hav hvt) z hz
  have hMb : 1 ≤ 16 * c0 * m / ρ ^ 2 := by
    rw [le_div_iff₀ hρ2]
    have : ρ ^ 2 ≤ R ^ 2 := pow_le_pow_left₀ hρ.le hρR 2
    nlinarith only [this, hmR, hc0, hm1]
  have hsc : metricScalarAt (s.history.stageMetric (s.history.activeStage v) v) z ≤
      16 * c0 * m / ρ ^ 2 := by
    refine hball.trans ?_
    have e : 4 * (4 * c0 / ρ ^ 2) = 16 * c0 / ρ ^ 2 := by ring
    rw [e]
    apply div_le_div_of_nonneg_right _ hρ2.le
    nlinarith only [hm1, hc0]
  have hrm := hCrm s v hvt z _ hMb hsc
  refine hrm.trans ?_
  have hθρ : 0 < θ' * ρ / 40 := by positivity
  have hρ2' : (θ' * ρ) ^ 2 ≤ ρ ^ 2 := by
    rw [mul_pow]
    exact mul_le_of_le_one_left hρ2.le (pow_le_one₀ hθ'.le hθ'le1)
  rw [hK'def]
  have e : C * (16 * c0 * m) / 1600 / (θ' * ρ / 40) ^ 2 = C * (16 * c0 * m) / (θ' * ρ) ^ 2 := by
    field_simp
    ring
  rw [e, mul_div_assoc']
  apply div_le_div_of_nonneg_left (by positivity) (by positivity) hρ2'

end GC.LongTime.Ch12
