import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HoneS83_S129

set_option autoImplicit false

/-! # CH12-O80 G1: slack thickness premise (`[FROZEN] CH12-O80 slack`, lead ruling (I) of FINDING O74-F2').

`hone_v2_O80` = `hone_S129` (text generated by `scratch/o80/gen_g1.py`) with `(Kth : ℝ) (hKth : 1 ≤ Kth)` and the
premise on the current sequence `IsWThickSequence_S13 S wstar` ↦ `IsWThickSequence_S13 S (Kth * wstar)` (in the
`hEndSfam` binder and in the conclusion; the minimality premise on `S'` stays at `wstar`).  Proof = S129's, with
`escape_persistence_v4_S101` fed by `isWThick_mono_O80` (`wstar ≤ Kth * wstar`). -/

noncomputable section
open Set Filter Topology DifferentialGeometry DifferentialGeometry.Geometry.Hyperbolic
open DifferentialGeometry.PDE.RicciFlow.Surgery.Topology DifferentialGeometry.Geometry.Curvature
open DifferentialGeometry.Geometry.Collapse DifferentialGeometry.Geometry.Connection DifferentialGeometry.Tensor0SBundle
open DifferentialGeometry.Tensor.RSTensor
open Manifold GC.LongTime DifferentialGeometry.CheegerGromovCompactness
open scoped Manifold ContDiff ENNReal
namespace GC.LongTime.Ch12
universe u

/-- Monotonicity of `IsWThickSequence_S13` in the constant. -/
theorem isWThick_mono_O80 {P : OrientedThreeStage.{u}} {g : P.Metric} {F : GC.Interface.RawSurgery P g}
    {S : LatePointSequence_S13 F} {w w' : ℝ} (h : w' ≤ w) (hS : IsWThickSequence_S13 S w) :
    IsWThickSequence_S13 S w' := fun j => by
  obtain ⟨r, hr, hcr, hv⟩ := hS j
  exact ⟨r, hr, hcr, (ENNReal.ofReal_le_ofReal (mul_le_mul_of_nonneg_right h (by positivity))).trans hv⟩

/-- `hone_v2_O80` = `hone_S129` with the slack premise `IsWThickSequence_S13 S (Kth * wstar)` ([FROZEN] CH12-O80 slack). -/
theorem hone_v2_O80 {P : OrientedThreeStage.{u}} {g : P.Metric} (F : GC.Interface.RawSurgery P g)
    (K : ℕ) (Kth : ℝ) (hKth : 1 ≤ Kth)
    (hLTF04 : ∀ (H' : FiniteVolumeHyperbolicModel.{u}) (R' ε' : ℝ) (k' : ℕ), 0 < R' → 0 < ε' →
      ∃ δ' T : ℝ, 0 < δ' ∧ 0 < T ∧ ∀ (t : ℝ) (_ht0 : 0 < t) (_htT : T ≤ t)
        (U : TopologicalSpace.Opens H'.Carrier)
        (f : H'.Carrier → (postStage F.observation t).Carrier),
        riemannianBallOf H'.metric H'.basepoint (2 * R') ⊆ U →
        ContMDiffOn (𝓡 3) (𝓡 3) ∞ f U →
        IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : U => f x) →
        (∀ j : ℕ, j ≤ k' + 3 → ∀ p ∈ riemannianBallOf H'.metric H'.basepoint (2 * R'),
          ckErr_S45 H' (postMetric F.observation t) t⁻¹ f j p < δ') →
        ∃ fs : (s : ℝ) → s ∈ Icc t (2 * t) → H'.Carrier → (postStage F.observation s).Carrier,
          (∀ p ∈ riemannianBallOf H'.metric H'.basepoint (R'), fs t ⟨le_rfl, by linarith⟩ p = f p) ∧
          ∀ (s : ℝ) (hs : s ∈ Icc t (2 * t)),
            ContMDiffOn (𝓡 3) (𝓡 3) ∞ (fs s hs) (riemannianBallOf H'.metric H'.basepoint (R')) ∧
            Set.InjOn (fs s hs) (riemannianBallOf H'.metric H'.basepoint (R')) ∧
            (∀ j : ℕ, j ≤ k' → ∀ p ∈ riemannianBallOf H'.metric H'.basepoint (R'),
              ckErr_S45 H' (postMetric F.observation s) s⁻¹ (fs s hs) j p < ε') ∧
            ∃ (n : ℕ) (first last : Fin ((F.tower.history n).eventCount + 1))
              (ordered : first ≤ last) (a b : ℝ) (_ : a ≤ t) (_ : a ≤ s) (_ : s < b)
              (_ : b ≤ (F.tower.history n).horizon)
              (stages : ∀ r : Icc (0 : ℝ) (F.tower.history n).horizon, (r : ℝ) ∈ Ico a b →
                first ≤ (F.tower.history n).toHistory.activeStage r ∧
                  (F.tower.history n).toHistory.activeStage r ≤ last)
              (φ : H'.Carrier →
                (F.tower.history n).toHistory.backwardSurvivorDomain first last ordered),
              ContMDiffOn (𝓡 3) (𝓡 3) ∞ φ (riemannianBallOf H'.metric H'.basepoint (R')) ∧
              ∀ (r : Icc (0 : ℝ) (F.tower.history n).horizon) (hr : (r : ℝ) ∈ Ico a b)
                (hrs : (r : ℝ) ∈ Icc t (2 * t)),
                ∀ p ∈ riemannianBallOf H'.metric H'.basepoint (R'),
                  HEq ((F.tower.history n).toHistory.backwardSurvivorMap first last ordered
                    ((F.tower.history n).toHistory.activeStage r) (stages r hr).1 (stages r hr).2
                    (φ p)) (fs r hrs p))
    {δ : ℝ → ℝ} (Hp : AnalyticSurgeryProfile F δ)
    (hscale : ∀ n (i : Fin (F.tower.history n).eventCount)
      (b : ((F.tower.history n).toHistory.event i).RetainedBoundaryIndex) (z : ThreeBall),
        ((Hp.records n i).static b).neck.scale / 2 ≤
          metricScalarAt ((Hp.records n i).static b).witness.metric
            (((Hp.records n i).static b).witness.cap z))
    (hdec : ∀ ε : ℝ, 0 < ε → ∃ B : ℝ, ∀ t : ℝ, B < t → δ t < ε)
    (hneg : ∃ ε₁ : ℝ, 0 < ε₁ ∧ ∀ (H : FiniteVolumeHyperbolicModel.{u}) (T : ℝ) (ρ : ℕ → ℝ) (η : ℕ → ℝ)
      (ν : ℕ → ℕ)
      (f : (j : ℕ) → (t : ℝ) → t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
        H.Carrier → (postStage F.observation t).Carrier),
      (∀ j, η j ≤ ε₁) → (∀ j, 2 ≤ ν j) →
      (∀ j t (ht : t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
        ContMDiffOn (𝓡 3) (𝓡 3) ∞ (f j t ht) (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
        Set.InjOn (f j t ht) (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
        ∀ k : ℕ, k ≤ ν j → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
          ckErr_S45 H (postMetric F.observation t) t⁻¹ (f j t ht) k p < η j) →
      ∀ j (t : ℝ) (ht : t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
        ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
          metricScalarAt (postMetric F.observation t) (f j t ht p) ≤ 0)
    (hEndSfam : ∀ wstar : ℝ, 0 < wstar → ∀ (old : ℕ) (Hold : Fin old → FiniteVolumeHyperbolicModel.{u}) (sold : Fin old → ℝ)
      (mold : ∀ i (t : ℝ), sold i ≤ t → (Hold i).Carrier → (postStage F.observation t).Carrier)
      (Rold : Fin old → ℝ) (H : FiniteVolumeHyperbolicModel.{u}) (S : LatePointSequence_S13 F)
      (Φ : PointedRiemannianConvergenceMaps S.pointedSeq (modelPointed_S13 H) id)
      (C : MetricConvergenceData Φ)
      (hcan : ∀ k, C.domain k = CanonicalMetricCompactness.canonicalSourceData Φ k),
      IsWThickSequence_S13 S (Kth * wstar) → (∀ (i : Fin old) (R : ℝ), ∃ J : ℕ, ∀ j, J ≤ j → ∀ hj : sold i ≤ (S.slices j).time,
        S.point j ∉ sliceCast_CX4 (S.slices j) ''
          (mold i _ hj '' riemannianBallOf (Hold i).metric (Hold i).basepoint R)) → (∀ (H' : FiniteVolumeHyperbolicModel.{u}) (S' : LatePointSequence_S13 F),
        IsWThickSequence_S13 S' wstar → PointedSmoothConverges_S13 S' H' →
        (∀ (i : Fin old) (R : ℝ), ∃ J : ℕ, ∀ j, J ≤ j → ∀ hj : sold i ≤ (S'.slices j).time,
        S'.point j ∉ sliceCast_CX4 (S'.slices j) ''
          (mold i _ hj '' riemannianBallOf (Hold i).metric (Hold i).basepoint R)) →
        ∀ Tr' : HyperbolicTruncation H', ∃ Tr : HyperbolicTruncation H, Tr.count ≤ Tr'.count) →
      ∃ β : ℝ → ℝ, (∀ t, 0 < β t) ∧ Filter.Tendsto β Filter.atTop (nhds 0) ∧
      (∃ I : ℕ, ∀ i : ℕ, I ≤ i →
        ∃ U : TopologicalSpace.Opens H.Carrier,
          riemannianBallOf H.metric H.basepoint (2 * (β (S.slices i).time)⁻¹) ⊆ U ∧
          ContMDiffOn (𝓡 3) (𝓡 3) ∞ (sliceApprox_O32 S H Φ i) U ∧
          IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : U => sliceApprox_O32 S H Φ i x) ∧
          ∀ k : ℕ, k ≤ ⌈(β (S.slices i).time)⁻¹⌉₊ →
            ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * (β (S.slices i).time)⁻¹),
            ckErr_S45 H (postMetric F.observation (S.slices i).time) (S.slices i).time⁻¹
              (sliceApprox_O32 S H Φ i) k p < β (S.slices i).time) ∧
      ∀ (ε R : ℝ) (k : ℕ), 0 < ε → 0 < R → ∃ (ε' R' : ℝ) (k' : ℕ), 0 < ε' ∧ 0 < R' ∧
        ε' ≤ ε ∧ R ≤ R' ∧ k ≤ k' ∧ ∃ Te : ℝ,
        ∀ (t t₂ : ℝ) (ht : 0 < t), Te ≤ t → t₂ = 2 * t →
        ∀ g₁ : H.Carrier → (postStage F.observation t).Carrier,
        (∃ U : TopologicalSpace.Opens H.Carrier,
          riemannianBallOf H.metric H.basepoint (2 * (β t)⁻¹) ⊆ U ∧
          ContMDiffOn (𝓡 3) (𝓡 3) ∞ g₁ U ∧
          IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : U => g₁ x) ∧
          ∀ k : ℕ, k ≤ ⌈(β t)⁻¹⌉₊ → ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * (β t)⁻¹),
            ckErr_S45 H (postMetric F.observation t) t⁻¹ g₁ k p < β t) →
        ∀ f : (s : ℝ) → s ∈ Icc t t₂ → H.Carrier → (postStage F.observation s).Carrier,
          (∀ (h0 : t ∈ Icc t t₂), ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * R'), f t h0 p = g₁ p) →
          (∀ s (hs : s ∈ Icc t t₂),
            ContMDiffOn (𝓡 3) (𝓡 3) ∞ (f s hs) (riemannianBallOf H.metric H.basepoint (4 * R')) ∧
            Set.InjOn (f s hs) (riemannianBallOf H.metric H.basepoint (4 * R')) ∧
            ∀ k'' : ℕ, k'' ≤ k' → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * R'),
              ckErr_S45 H (postMetric F.observation s) s⁻¹ (f s hs) k'' p < ε') →
        ∃ (E : ℝ × H.Carrier → H.Carrier)
          (g₂ : H.Carrier → (postStage F.observation t₂).Carrier),
          (∃ U : TopologicalSpace.Opens H.Carrier,
            riemannianBallOf H.metric H.basepoint (2 * (β t₂)⁻¹) ⊆ U ∧
            ContMDiffOn (𝓡 3) (𝓡 3) ∞ g₂ U ∧
            IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : U => g₂ x) ∧
            ∀ k : ℕ, k ≤ ⌈(β t₂)⁻¹⌉₊ → ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * (β t₂)⁻¹),
              ckErr_S45 H (postMetric F.observation t₂) t₂⁻¹ g₂ k p < β t₂) ∧
          ContMDiff (𝓘(ℝ, ℝ).prod (𝓡 3)) (𝓡 3) ∞ E ∧
          (∀ μ, ContMDiff (𝓡 3) (𝓡 3) ∞ (fun p => E (μ, p)) ∧
            Function.Bijective (fun p => E (μ, p))) ∧
          (∀ p, E (0, p) = p) ∧
          (∀ μ p, p ∉ riemannianBallOf H.metric H.basepoint (4 * R) → E (μ, p) = p) ∧
          (∀ μ ∈ Icc (0 : ℝ) 1, ∀ p : H.Carrier,
            let v := mfderiv 𝓘(ℝ, ℝ) (𝓡 3) (fun r => E (r, p)) μ
              ((NormedSpace.fromTangentSpace (𝕜 := ℝ) μ).symm (1 : ℝ));
            H.metric.inner (E (μ, p)) v v ≤ ε ^ 2) ∧
          (∀ μ ∈ Icc (0 : ℝ) 1, ∀ i : ℕ, i ≤ k → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * R),
            ckErr_S45 H H.metric 1 (fun x => E (μ, x)) i p ≤ ε) ∧
          (∀ (h1 : t₂ ∈ Icc t t₂), ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * R), f t₂ h1 (E (1, p)) = g₂ p) ∧
          (∀ s (hs : s ∈ Icc t t₂) (μ : ℝ), ∀ y ∈ riemannianBallOf H.metric H.basepoint 1, ∃ r : ℝ, 0 < r ∧
            curvatureRadius (scaleMetric s⁻¹ (inv_pos.mpr (lt_of_lt_of_le ht hs.1))
              (postMetric F.observation s)) (f s hs (E (μ, y))) = ENNReal.ofReal r ∧
            ENNReal.ofReal (wstar * r ^ 3) ≤ ballVolume (scaleMetric s⁻¹
              (inv_pos.mpr (lt_of_lt_of_le ht hs.1)) (postMetric F.observation s))
              (f s hs (E (μ, y))) r))
    :
    ∀ wstar : ℝ, 0 < wstar →
    ∀ (old : ℕ) (Hold : Fin old → FiniteVolumeHyperbolicModel.{u}) (sold : Fin old → ℝ)
      (mold : ∀ i (t : ℝ), sold i ≤ t → (Hold i).Carrier → (postStage F.observation t).Carrier)
      (Rold : Fin old → ℝ) (H : FiniteVolumeHyperbolicModel.{u}) (S : LatePointSequence_S13 F),
      IsWThickSequence_S13 S (Kth * wstar) → PointedSmoothConverges_S13 S H → (∀ (i : Fin old) (R : ℝ), ∃ J : ℕ, ∀ j, J ≤ j → ∀ hj : sold i ≤ (S.slices j).time,
        S.point j ∉ sliceCast_CX4 (S.slices j) ''
          (mold i _ hj '' riemannianBallOf (Hold i).metric (Hold i).basepoint R)) → (∀ (H' : FiniteVolumeHyperbolicModel.{u}) (S' : LatePointSequence_S13 F),
        IsWThickSequence_S13 S' wstar → PointedSmoothConverges_S13 S' H' →
        (∀ (i : Fin old) (R : ℝ), ∃ J : ℕ, ∀ j, J ≤ j → ∀ hj : sold i ≤ (S'.slices j).time,
        S'.point j ∉ sliceCast_CX4 (S'.slices j) ''
          (mold i _ hj '' riemannianBallOf (Hold i).metric (Hold i).basepoint R)) →
        ∀ Tr' : HyperbolicTruncation H', ∃ Tr : HyperbolicTruncation H, Tr.count ≤ Tr'.count) →
    (∃ L : Fin old → ℝ, (∀ i', 0 < L i') ∧ ∃ Tb : ℝ,
      ∀ (i' : Fin old) (t : ℝ) (ht0 : 0 < t) (hi : sold i' ≤ t), Tb ≤ t →
        ∀ q ∈ riemannianBallOf (Hold i').metric (Hold i').basepoint (Rold i') \
            riemannianBallOf (Hold i').metric (Hold i').basepoint (Rold i' - L i'),
          ∀ r : ℝ, 0 < r →
            curvatureRadius (scaleMetric t⁻¹ (inv_pos.mpr ht0) (postMetric F.observation t)) (mold i' t hi q) =
              ENNReal.ofReal r →
            ballVolume (scaleMetric t⁻¹ (inv_pos.mpr ht0) (postMetric F.observation t)) (mold i' t hi q) r <
              ENNReal.ofReal (wstar * r ^ 3)) →
    (∀ (Φ : PointedRiemannianConvergenceMaps S.pointedSeq (modelPointed_S13 H) id),
      ∀ (L : Fin old → ℝ), (∀ i', 0 < L i') → ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∃ J0 : ℕ, ∀ i : ℕ, J0 ≤ i → ∀ T : ℝ, T = (S.slices i).time → ∀ hT : 0 < T,
        ∀ θ : ℝ → ℝ, (∀ s, θ s ∈ Icc (0 : ℝ) 1) → (∀ s, s ≤ 7 / 4 → θ s = 0) →
        (∀ s, 15 / 8 ≤ s → θ s = 1) →
        ∀ (f : (j : ℕ) → (t : ℝ) → t ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T) →
          H.Carrier → (postStage F.observation t).Carrier)
        (E : ℕ → ℝ × H.Carrier → H.Carrier) (η ρ : ℕ → ℝ) (ν : ℕ → ℕ),
                  ((∀ j, η j ≤ ε₀) ∧ (∀ j, 0 ≤ η j) ∧ Filter.Tendsto η Filter.atTop (nhds 0) ∧ Monotone ρ ∧
        Filter.Tendsto ρ Filter.atTop Filter.atTop ∧ (∀ j, 0 < ρ j) ∧
        Monotone ν ∧ Filter.Tendsto ν Filter.atTop Filter.atTop ∧
        (∀ j, ContMDiff (𝓘(ℝ, ℝ).prod (𝓡 3)) (𝓡 3) ∞ (E j)) ∧
        (∀ j μ, ContMDiff (𝓡 3) (𝓡 3) ∞ (fun p => E j (μ, p)) ∧
          Function.Bijective (fun p => E j (μ, p))) ∧
        (∀ j p, E j (0, p) = p) ∧
        (∀ j μ p, p ∉ riemannianBallOf H.metric H.basepoint (4 * ρ j) → E j (μ, p) = p) ∧
        (∀ j, ∀ μ ∈ Icc (0 : ℝ) 1, ∀ p : H.Carrier,
          let v := mfderiv 𝓘(ℝ, ℝ) (𝓡 3) (fun r => E j (r, p)) μ
            ((NormedSpace.fromTangentSpace (𝕜 := ℝ) μ).symm (1 : ℝ));
          H.metric.inner (E j (μ, p)) v v ≤ η j ^ 2) ∧
        (∀ j, ∀ μ ∈ Icc (0 : ℝ) 1, ∀ k : ℕ, k ≤ ν j → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
          ckErr_S45 H H.metric 1 (fun x => E j (μ, x)) k p ≤ η j) ∧
        (∀ j (h1 : 2 ^ (j + 1) * T ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T))
            (h2 : 2 ^ (j + 1) * T ∈ Icc (2 ^ (j + 1) * T) (2 ^ (j + 1 + 1) * T)),
          ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * ρ j),
            f j _ h1 (E j (1, p)) = f (j + 1) _ h2 p) ∧
        (∀ j t (ht : t ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T)),
          ContMDiffOn (𝓡 3) (𝓡 3) ∞ (f j t ht) (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
          Set.InjOn (f j t ht) (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
          ∀ k : ℕ, k ≤ ν j → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
            ckErr_S45 H (postMetric F.observation t) t⁻¹ (f j t ht) k p < η j) ∧
        (∀ j (s : ℝ), s ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T) →
        ∃ (n : ℕ) (first last : Fin ((F.tower.history n).eventCount + 1))
          (ordered : first ≤ last) (a b : ℝ) (_ : a < s) (_ : s < b)
          (_ : b ≤ (F.tower.history n).horizon)
          (stages : ∀ r : Icc (0 : ℝ) (F.tower.history n).horizon, (r : ℝ) ∈ Ioo a b →
            first ≤ (F.tower.history n).toHistory.activeStage r ∧
              (F.tower.history n).toHistory.activeStage r ≤ last)
          (φ : H.Carrier →
            (F.tower.history n).toHistory.backwardSurvivorDomain first last ordered),
          ContMDiffOn (𝓡 3) (𝓡 3) ∞ φ (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
          ∀ (r : Icc (0 : ℝ) (F.tower.history n).horizon) (hr : (r : ℝ) ∈ Ioo a b)
            (hrs : (r : ℝ) ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T)),
            ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
              HEq ((F.tower.history n).toHistory.backwardSurvivorMap first last ordered
                ((F.tower.history n).toHistory.activeStage r) (stages r hr).1 (stages r hr).2
                (φ p)) (f j r hrs p)) ∧
        (∀ j t (ht : t ∈ Icc (2 ^ j * T) (2 ^ (j + 1) * T)) (μ : ℝ),
          ∀ y ∈ riemannianBallOf H.metric H.basepoint 1, ∃ r : ℝ, 0 < r ∧
          curvatureRadius (scaleMetric t⁻¹ (inv_pos.mpr (lt_of_lt_of_le (by positivity) ht.1))
            (postMetric F.observation t)) (f j t ht (E j (μ, y))) = ENNReal.ofReal r ∧
          ENNReal.ofReal (wstar * r ^ 3) ≤ ballVolume (scaleMetric t⁻¹
            (inv_pos.mpr (lt_of_lt_of_le (by positivity) ht.1)) (postMetric F.observation t))
            (f j t ht (E j (μ, y))) r)) →
          (∀ (h0 : 2 ^ 0 * T ∈ Icc (2 ^ 0 * T) (2 ^ (0 + 1) * T)),
          ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ 0), HEq (f 0 _ h0 p) (sliceApprox_O32 S H Φ i p)) →
          ∀ (i' : Fin old) (r t : ℝ) (hr : T ≤ r) (ht : T ≤ t) (hri : sold i' ≤ r) (hti : sold i' ≤ t), r ≤ t → t ≤ 2 * r →
              smoothedPhysicalMap_CX5 H T hT θ f E t ht H.basepoint ∈
                mold i' t hti '' riemannianBallOf (Hold i').metric (Hold i').basepoint (Rold i' - L i') →
              smoothedPhysicalMap_CX5 H T hT θ f E r hr H.basepoint ∈
                mold i' r hri '' riemannianBallOf (Hold i').metric (Hold i').basepoint (Rold i')) →
    ∃ (start : ℝ) (hstart : 0 < start) (α : ℝ → ℝ) (Ω : TopologicalSpace.Opens (ℝ × H.Carrier))
      (map : (t : ℝ) → start ≤ t → H.Carrier → (postStage F.observation t).Carrier),
      (∀ t, start ≤ t → 0 < α t) ∧ AntitoneOn α (Ici start) ∧
      (∀ ε : ℝ, 0 < ε → ∃ T : ℝ, ∀ t, T ≤ t → α t < ε) ∧
      (∀ t (ht : start ≤ t), ContMDiffOn (𝓡 3) (𝓡 3) ∞ (map t ht) (sourceSlice_CX5 Ω t)) ∧
      (∀ t (ht : start ≤ t),
        IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : sourceSlice_CX5 Ω t => map t ht x)) ∧
      (∀ t, start ≤ t →
        riemannianBallOf H.metric H.basepoint (2 * (α t)⁻¹) ⊆ sourceSlice_CX5 Ω t) ∧
      (∀ t (ht : start ≤ t), ∀ k : ℕ, k ≤ max K ⌈(α t)⁻¹⌉₊ →
        ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * (α t)⁻¹),
          ckErr_S45 H (postMetric F.observation t) t⁻¹ (map t ht) k p < α t) ∧
      (∀ Ω' : TopologicalSpace.Opens (ℝ × H.Carrier), Ω' ≤ Ω →
        ∀ t (_ht : start ≤ t), ∀ x ∈ sourceSlice_CX5 Ω' t,
          Nonempty (PersistentModelPatch F H start α (sourceSlice_CX5 Ω') map t x)) ∧
      (∀ t (ht : start ≤ t), ∀ y ∈ riemannianBallOf H.metric H.basepoint 1, ∃ r : ℝ, 0 < r ∧
        curvatureRadius (scaleMetric t⁻¹ (inv_pos.mpr (hstart.trans_le ht))
          (postMetric F.observation t)) (map t ht y) = ENNReal.ofReal r ∧
        ENNReal.ofReal (wstar * r ^ 3) ≤ ballVolume (scaleMetric t⁻¹
          (inv_pos.mpr (hstart.trans_le ht)) (postMetric F.observation t)) (map t ht y) r) ∧
      (∀ i : Fin old, ∃ T : ℝ, ∀ t (hn : start ≤ t) (hi : sold i ≤ t), T ≤ t →
        map t hn H.basepoint ∉
          mold i t hi '' riemannianBallOf (Hold i).metric (Hold i).basepoint (Rold i)) := by
  classical
  obtain ⟨Trc, hTrc⟩ := hrc_of_hdec_S118 Hp hdec
  obtain ⟨ε₁, hε₁, hnegε⟩ := hneg
  intro wstar hw old Hold sold mold Rold H S hW hPSC hESC hMIN hthin hD
  obtain ⟨Φ, C, hcan⟩ := hPSC
  obtain ⟨β, hβ, hβ0, ⟨I, hI⟩, hstep⟩ :=
    hEndSfam wstar hw old Hold sold mold Rold H S Φ C hcan hW hESC hMIN
  obtain ⟨βη, hβη, hβη0, Tth, hbeta⟩ := hpi03_discrete_from_beta_S129 F H wstar 1 β
    (hstep_of_window_beta_O32 F H wstar 1 hLTF04 β hβ hβ0 hstep)
  obtain ⟨ε₀, hε₀, J0, hJ0⟩ :=
    escape_persistence_v4_S101 F wstar 1 one_pos old Hold sold mold Rold H S Φ
    (isWThick_mono_O80 (le_mul_of_one_le_left hw.le hKth) hW) hESC hthin (hD Φ)
  have hεm : 0 < min ε₀ (min ε₁ (1 / 3)) := lt_min hε₀ (lt_min hε₁ (by norm_num))
  obtain ⟨Tβ, hTβ⟩ := eventually_atTop.1 (hβη0.eventually (gt_mem_nhds hεm))
  obtain ⟨i, hiI, hiT⟩ : ∃ i : ℕ, max I J0 ≤ i ∧
      max (max (max Tth 1) Trc) Tβ < (S.slices i).time := by
    obtain ⟨N, hN⟩ := eventually_atTop.1
      (S.times_tendsto.eventually_gt_atTop (max (max (max Tth 1) Trc) Tβ))
    exact ⟨max (max I J0) N, le_max_left _ _, hN _ (le_max_right _ _)⟩
  have hTpos : 0 < (S.slices i).time :=
    lt_of_lt_of_le one_pos ((le_max_right _ _).trans ((le_max_left _ _).trans ((le_max_left _ _).trans hiT.le)))
  have hTth : Tth ≤ (S.slices i).time :=
    (le_max_left _ _).trans ((le_max_left _ _).trans ((le_max_left _ _).trans hiT.le))
  have hTrcle : Trc ≤ (S.slices i).time := (le_max_right _ _).trans ((le_max_left _ _).trans hiT.le)
  have hTβle : Tβ ≤ (S.slices i).time := (le_max_right _ _).trans hiT.le
  have hbase : ∃ g₁ : H.Carrier → (postStage F.observation (2 ^ 0 * (S.slices i).time)).Carrier,
      (∃ U : TopologicalSpace.Opens H.Carrier,
        riemannianBallOf H.metric H.basepoint (2 * (β (2 ^ 0 * (S.slices i).time))⁻¹) ⊆ U ∧
        ContMDiffOn (𝓡 3) (𝓡 3) ∞ g₁ U ∧
        IsSmoothEmbedding (𝓡 3) (𝓡 3) ∞ (fun x : U => g₁ x) ∧
        ∀ k : ℕ, k ≤ ⌈(β (2 ^ 0 * (S.slices i).time))⁻¹⌉₊ →
          ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * (β (2 ^ 0 * (S.slices i).time))⁻¹),
          ckErr_S45 H (postMetric F.observation (2 ^ 0 * (S.slices i).time))
            (2 ^ 0 * (S.slices i).time)⁻¹ g₁ k p < β (2 ^ 0 * (S.slices i).time)) ∧
      ∀ p, HEq (g₁ p) (sliceApprox_O32 S H Φ i p) := by
    rw [pow_zero, one_mul]
    exact ⟨_, hI i ((le_max_left _ _).trans hiI), fun p => HEq.rfl⟩
  obtain ⟨g₁, hg₁, hheq⟩ := hbase
  obtain ⟨f, E, η, ρ, ν, hsup, hνb, hconj, hstart⟩ :=
    hbeta (S.slices i).time hTpos hTth g₁ hg₁
  have hanchor : ∀ (h0 : 2 ^ 0 * (S.slices i).time ∈ Icc (2 ^ 0 * (S.slices i).time) (2 ^ (0 + 1) * (S.slices i).time)),
      ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ 0), HEq (f 0 _ h0 p) (sliceApprox_O32 S H Φ i p) :=
    fun h0 p hp => (heq_of_eq (hstart h0 p hp)).trans (hheq p)
  have hsmall : βη (S.slices i).time < min ε₀ (min ε₁ (1 / 3)) := hTβ _ hTβle
  have hηε₀ : ∀ j, η j ≤ ε₀ := fun j => (hsup j).trans (hsmall.le.trans (min_le_left _ _))
  have hηε₁ : ∀ j, η j ≤ ε₁ := fun j =>
    (hsup j).trans (hsmall.le.trans ((min_le_right _ _).trans (min_le_left _ _)))
  have hν2 : ∀ j, 2 ≤ ν j := by
    intro j
    have hlt : βη (S.slices i).time < 1 / 3 :=
      hsmall.trans_le ((min_le_right _ _).trans (min_le_right _ _))
    have h3 : (3 : ℝ) ≤ (βη (S.slices i).time)⁻¹ := by
      rw [le_inv_comm₀ (by norm_num) (hβη _)]
      simpa using hlt.le
    have h4 : (2 : ℝ) ≤ ν j := by linarith [h3.trans (hνb j)]
    exact_mod_cast h4
  obtain ⟨hη, hηt, hρm, hρ, hρpos, hνm, hν, hE, hEb, hE0, hsupp, hispeed, hEclose, hend, hacc, hlift0,
    hthick⟩ := hconj
  have hnegAll := hnegε H (S.slices i).time ρ η ν f hηε₁ hν2 hacc
  have hlift0I := hlift0_of_Ico_v2_S97 Hp H hTpos ρ hρpos f hscale
    (fun n i' hle => hTrc n i' (hTrcle.trans hle)) hnegAll hlift0
  obtain ⟨θ, start, hTs, α, Ω, map, hmap, hθr, hθ0, hθ1, h1, h2, h3, h4, h5, h6, h7, h8, h9⟩ :=
    singleModelExplicit_S72 F K H wstar 1 hTpos f E η ρ ν hη hηt hρm hρ hρpos hν hE hEb hE0 hsupp hispeed
      hEclose hend hacc 0 (fun j _ => hlift0I j) hthick
  have hEPc := hJ0 i ((le_max_right _ _).trans hiI) _ rfl hTpos θ hθr hθ0 hθ1 f E η ρ ν
    ⟨hηε₀, hη, hηt, hρm, hρ, hρpos, hνm, hν, hE, hEb, hE0, hsupp, hispeed, hEclose, hend, hacc, hlift0I,
      hthick⟩ hanchor
  refine ⟨start, hTpos.trans_le hTs, α, Ω, map, h1, h2, h3, h4, h5, h6, h7, h8, h9, fun i' => ?_⟩
  obtain ⟨T', hT'⟩ := hEPc i'
  exact ⟨T', fun t hn hi ht => by rw [hmap t hn]; exact hT' t (hTs.trans hn) hi ht⟩

end GC.LongTime.Ch12
