import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HBirthReduce_S134
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HTSAssemblyT_S150

/-!
# CH12-S150 G1 (HShiftOldT_S150): the S150 reduction chain `hbirth_of_hsurvT_S150` / `hshift_of_hbirthT_v4_S150` / `hshift_of_hbirthT_S150` -- the 60-tube / c₀-clause reduction chain

GENERATED by `build-logs/ch12/scratch/S150gen/gen_g1.py` from `HBirthReduceT_S137.lean` (`[FROZEN] CH12-S150 G1/G2`): tube radius
`60 * (θ' * ρ)` (v4: `60 * (θ' * ρ / 40)`), the τ-clause `9 K τ ≤ c₀ θ`, and every hypothesis / conclusion binder gets the outer arguments
`{ε₀' c₀ : ℝ} (hε₀' : 0 < ε₀') (hc₀ : 0 < c₀) (hscaleR : body of hscale_of_record_S105 at (ε₀', c₀))` (the `hsurv_core_S146` shape);
the proofs are those of S137 with `(ε₀', c₀, hscaleR)` taken from the outer binders instead of `obtain ... := hscale_of_record_S105`
and the new clause `hτθ` passed through.
-/

set_option autoImplicit false

noncomputable section

open Set Manifold DifferentialGeometry DifferentialGeometry.Topology
  DifferentialGeometry.PDE.RicciFlow DifferentialGeometry.PDE.RicciFlow.Surgery.Topology
  DifferentialGeometry.PDE.RicciFlow.Perelman.CanonicalNeighborhood.FiniteHorn
  DifferentialGeometry.Geometry.Collapse DifferentialGeometry.Geometry.Curvature
  DifferentialGeometry.Geometry.Riemannian DifferentialGeometry.Tensor0SBundle
open scoped Manifold ContDiff ENNReal NNReal

namespace GC.LongTime.Ch12

universe u

variable {δ : ℝ → ℝ}

theorem hshift_of_hbirthT_S150 {P : OrientedThreeStage.{u}} {g : P.Metric} {F : GC.Interface.RawSurgery P g}
    (Hp : GC.LongTime.AnalyticSurgeryProfile F δ)
    (hbirth : ∀ {ε₀' c₀ : ℝ}, 0 < ε₀' → 0 < c₀ →
      (∀ {H : ObservedHistory.{u}} {pp : CutoffParameters} {i : Fin H.eventCount},
      pp.modelAccuracy ≤ ε₀' → 4 ≤ pp.modelOrder → ∀ (R : GeometricCutoffRecord H i pp)
      (b : (H.event i).RetainedBoundaryIndex) (x : standardCapWindow pp.modelRadius),
      ‖x.val‖ < pp.modelRadius → c₀ * (R.static b).neck.scale ≤
        metricScalarAt (H.event i).outputMetric ((R.static b).window x)) →
      ∀ w : ℝ, 0 < w → ∀ Λ : ℝ, 1 ≤ Λ → ∀ (θ Dcap C0 : ℝ), 0 < θ → 0 < C0 →
      StandardCap.transitionEnd + 3 < Dcap → ∀ K : ℝ, 0 < K →
      ∃ (Cb bH TH θH εH : ℝ), 0 < Cb ∧ 0 < bH ∧ 0 < θH ∧ 0 < εH ∧
      ∀ s : RegularSlice F.observation, TH ≤ s.time → ∀ T₀ : ℝ, TH ≤ T₀ → T₀ ≤ s.time →
      ∀ (pp : CutoffParameters)
        (records : ∀ i : Fin (sliceHistoryR_O3 F s).eventCount,
          T₀ - θ ≤ (sliceHistoryR_O3 F s).time i.succ →
          GeometricCutoffRecord (sliceHistoryR_O3 F s).toHistory i pp),
        pp.delta = Hp.parameters.delta → pp.neckRadius = Hp.parameters.neckRadius →
        pp.fixed = Hp.parameters.fixed → pp.recenterConstant = Hp.parameters.recenterConstant →
        32 * (Dcap + 1) + 2 ≤ pp.modelRadius →
        pp.modelAccuracy ≤ εH → 4 ≤ pp.modelOrder →
        (∀ i hi b, linkedCanonicalWindow_O2 ((records i hi).static b)) →
      ∀ (p : s.stage.Carrier) (ρ : ℝ), 0 < ρ → ρ ≤ bH * Real.sqrt s.time →
        (∃ n, ∃ i : Fin (F.tower.history n).eventCount, ∃ h,
          (F.tower.history n).time i.succ ∈ Icc (s.time / 2) s.time ∧
          ρ < Λ * (Hp.records n i).nominalRadius h) →
        (∃ z ∈ connectedComponent p, ¬ SectionalBoundedBelowAt s.metric z 0) →
        (∀ q ∈ riemannianBallOf s.metric p ρ,
          SectionalBoundedBelowAt s.metric q (-(ρ ^ 2)⁻¹)) →
        ENNReal.ofReal (w * ρ ^ 3) ≤ ballVolume s.metric p ρ →
        (∀ x ∈ riemannianBallOf s.metric p (2 * ρ), metricScalarAt s.metric x ≤ C0 / ρ ^ 2) →
        ∀ q ∈ riemannianBallOf s.metric p ρ,
          ¬ (∃ (j : Fin (sliceHistoryR_O3 F s).eventCount)
            (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
            (hl : j.succ ≤ Fin.last (sliceHistoryR_O3 F s).eventCount)
            (B : BackwardPointTrace (sliceHistoryR_O3 F s).toHistory j.succ
              (Fin.last (sliceHistoryR_O3 F s).eventCount) hl q)
            (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex)
            (x : standardCapWindow pp.modelRadius),
            B.point j.succ le_rfl hl = ((records j hj).static b).window x ∧
              ‖x.val‖ < Dcap + 1 ∧
              s.time - (sliceHistoryR_O3 F s).time j.succ ≤
                θ * (((records j hj).static b).neck.scale)⁻¹) →
          ∀ θ' : ℝ, 0 < θ' → θ' ≤ θH → ∀ τ : ℝ, 0 < τ → 9 * K * τ ≤ 1 → 9 * K * τ ≤ c₀ * θ →
          ∀ (j : Fin (sliceHistoryR_O3 F s).eventCount)
            (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
            (B : BackwardPointTrace (sliceHistoryR_O3 F s).toHistory j.succ
              (Fin.last (sliceHistoryR_O3 F s).eventCount) (Fin.le_last _) q)
            (_ : ∀ (v : Icc (0 : ℝ) (sliceTowerHistory_CX2 s).horizon)
              (hav : towerIdx_S137 s j.succ ≤ (sliceTowerHistory_CX2 s).activeStage v)
              (hvt : (sliceTowerHistory_CX2 s).activeStage v ≤
                towerIdx_S137 s (Fin.last (sliceHistoryR_O3 F s).eventCount)),
              v.val ≤ s.time →
              ∀ q ∈ riemannianBallOf
                ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v)
                ((towerTrace_S137 s B).point ((sliceTowerHistory_CX2 s).activeStage v) hav hvt) (60 * (θ' * ρ)),
              Real.sqrt (normSq0S
                ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v) q 4
                (metricRm04At
                  ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v) q)) ≤ K / (θ' * ρ) ^ 2)
            (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex)
            (x : standardCapWindow pp.modelRadius), ‖x.val‖ < Dcap - 1 + 1 →
            ((records j hj).static b).window x ∈
              riemannianBallOf ((sliceHistoryR_O3 F s).toHistory.event j).outputMetric
                (B.point j.succ le_rfl (Fin.le_last _)) (20 * (θ' * ρ)) →
            metricScalarAt ((sliceHistoryR_O3 F s).toHistory.event j).outputMetric
              (((records j hj).static b).window x) ≤ 9 * K / (θ' * ρ) ^ 2 →
            s.time - (sliceHistoryR_O3 F s).time j.succ < τ * (θ' * ρ) ^ 2 →
            ((records j hj).static b).neck.scale ≤ Cb / ρ ^ 2)
    :
    ∀ {ε₀' c₀ : ℝ}, 0 < ε₀' → 0 < c₀ →
      (∀ {H : ObservedHistory.{u}} {pp : CutoffParameters} {i : Fin H.eventCount},
      pp.modelAccuracy ≤ ε₀' → 4 ≤ pp.modelOrder → ∀ (R : GeometricCutoffRecord H i pp)
      (b : (H.event i).RetainedBoundaryIndex) (x : standardCapWindow pp.modelRadius),
      ‖x.val‖ < pp.modelRadius → c₀ * (R.static b).neck.scale ≤
        metricScalarAt (H.event i).outputMetric ((R.static b).window x)) →
      ∀ w : ℝ, 0 < w → ∀ Λ : ℝ, 1 ≤ Λ → ∀ (θ Dcap C0 : ℝ), 0 < θ → 0 < C0 →
      StandardCap.transitionEnd + 3 < Dcap → ∀ K : ℝ, 0 < K →
      ∃ (bH TH θH εH : ℝ), 0 < bH ∧ 0 < θH ∧ 0 < εH ∧
      ∀ s : RegularSlice F.observation, TH ≤ s.time → ∀ T₀ : ℝ, TH ≤ T₀ → T₀ ≤ s.time →
      ∀ (pp : CutoffParameters)
        (records : ∀ i : Fin (sliceHistoryR_O3 F s).eventCount,
          T₀ - θ ≤ (sliceHistoryR_O3 F s).time i.succ →
          GeometricCutoffRecord (sliceHistoryR_O3 F s).toHistory i pp),
        pp.delta = Hp.parameters.delta → pp.neckRadius = Hp.parameters.neckRadius →
        pp.fixed = Hp.parameters.fixed → pp.recenterConstant = Hp.parameters.recenterConstant →
        32 * (Dcap + 1) + 2 ≤ pp.modelRadius →
        pp.modelAccuracy ≤ εH → 4 ≤ pp.modelOrder →
        (∀ i hi b, linkedCanonicalWindow_O2 ((records i hi).static b)) →
      ∀ (p : s.stage.Carrier) (ρ : ℝ), 0 < ρ → ρ ≤ bH * Real.sqrt s.time →
        (∃ n, ∃ i : Fin (F.tower.history n).eventCount, ∃ h,
          (F.tower.history n).time i.succ ∈ Icc (s.time / 2) s.time ∧
          ρ < Λ * (Hp.records n i).nominalRadius h) →
        (∃ z ∈ connectedComponent p, ¬ SectionalBoundedBelowAt s.metric z 0) →
        (∀ q ∈ riemannianBallOf s.metric p ρ,
          SectionalBoundedBelowAt s.metric q (-(ρ ^ 2)⁻¹)) →
        ENNReal.ofReal (w * ρ ^ 3) ≤ ballVolume s.metric p ρ →
        (∀ x ∈ riemannianBallOf s.metric p (2 * ρ), metricScalarAt s.metric x ≤ C0 / ρ ^ 2) →
        ∀ q ∈ riemannianBallOf s.metric p ρ,
          ¬ (∃ (j : Fin (sliceHistoryR_O3 F s).eventCount)
            (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
            (hl : j.succ ≤ Fin.last (sliceHistoryR_O3 F s).eventCount)
            (B : BackwardPointTrace (sliceHistoryR_O3 F s).toHistory j.succ
              (Fin.last (sliceHistoryR_O3 F s).eventCount) hl q)
            (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex)
            (x : standardCapWindow pp.modelRadius),
            B.point j.succ le_rfl hl = ((records j hj).static b).window x ∧
              ‖x.val‖ < Dcap + 1 ∧
              s.time - (sliceHistoryR_O3 F s).time j.succ ≤
                θ * (((records j hj).static b).neck.scale)⁻¹) →
          ∀ θ' : ℝ, 0 < θ' → θ' ≤ θH → ∀ τ : ℝ, 0 < τ → 9 * K * τ ≤ 1 → 9 * K * τ ≤ c₀ * θ →
          ∀ (j : Fin (sliceHistoryR_O3 F s).eventCount)
            (hj : T₀ - θ ≤ (sliceHistoryR_O3 F s).time j.succ)
            (B : BackwardPointTrace (sliceHistoryR_O3 F s).toHistory j.succ
              (Fin.last (sliceHistoryR_O3 F s).eventCount) (Fin.le_last _) q)
            (_ : ∀ (v : Icc (0 : ℝ) (sliceTowerHistory_CX2 s).horizon)
              (hav : towerIdx_S137 s j.succ ≤ (sliceTowerHistory_CX2 s).activeStage v)
              (hvt : (sliceTowerHistory_CX2 s).activeStage v ≤
                towerIdx_S137 s (Fin.last (sliceHistoryR_O3 F s).eventCount)),
              v.val ≤ s.time →
              ∀ q ∈ riemannianBallOf
                ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v)
                ((towerTrace_S137 s B).point ((sliceTowerHistory_CX2 s).activeStage v) hav hvt) (60 * (θ' * ρ)),
              Real.sqrt (normSq0S
                ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v) q 4
                (metricRm04At
                  ((sliceTowerHistory_CX2 s).stageMetric ((sliceTowerHistory_CX2 s).activeStage v) v) q)) ≤ K / (θ' * ρ) ^ 2)
            (b : ((sliceHistoryR_O3 F s).toHistory.event j).RetainedBoundaryIndex)
            (x : standardCapWindow pp.modelRadius), ‖x.val‖ < Dcap - 1 + 1 →
            ((records j hj).static b).window x ∈
              riemannianBallOf ((sliceHistoryR_O3 F s).toHistory.event j).outputMetric
                (B.point j.succ le_rfl (Fin.le_last _)) (20 * (θ' * ρ)) →
            metricScalarAt ((sliceHistoryR_O3 F s).toHistory.event j).outputMetric
              (((records j hj).static b).window x) ≤ 9 * K / (θ' * ρ) ^ 2 →
            s.time - (sliceHistoryR_O3 F s).time j.succ < τ * (θ' * ρ) ^ 2 →
            40 * (θ' * ρ) * Real.sqrt ((records j hj).static b).neck.scale ≤ 1 := by
  intro ε₀' c₀ hε₀' hc₀ hscaleR w hw Λ hΛ θ Dcap C0 hθ hC0 hD K hK
  obtain ⟨Cb, bH, TH, θH, εH, hCb, hb, hθH, hεH, h⟩ := hbirth hε₀' hc₀ hscaleR w hw Λ hΛ θ Dcap C0 hθ hC0 hD K hK
  have hpos : 0 < 40 * Real.sqrt Cb + 1 := by positivity
  refine ⟨bH, TH, min θH (1 / (40 * Real.sqrt Cb + 1)), εH, hb, lt_min hθH (by positivity), hεH, ?_⟩
  intro s hs T₀ hT₀ hT₀s pp records e1 e2 e3 e4 hmr hacc hord hlink p ρ hρ hρb h2 h3 h4 h5 h6 q hq hno
    θ' hθ' hθ'H τ hτ hτK hτθ j hj B htube b x hx hmem hsc hage
  have hle : θ' ≤ 1 / (40 * Real.sqrt Cb + 1) := hθ'H.trans (min_le_right _ _)
  have hsc' := h s hs T₀ hT₀ hT₀s pp records e1 e2 e3 e4 hmr hacc hord hlink p ρ hρ hρb h2 h3 h4 h5 h6 q hq hno
    θ' hθ' (hθ'H.trans (min_le_left _ _)) τ hτ hτK hτθ j hj B htube b x hx hmem hsc hage
  refine shift_le_of_Cb_S131 hρ hCb.le hsc' rfl hθ'.le ?_
  calc θ' * (40 * Real.sqrt Cb) ≤ 1 / (40 * Real.sqrt Cb + 1) * (40 * Real.sqrt Cb) :=
        mul_le_mul_of_nonneg_right hle (by positivity)
    _ ≤ 1 := by
        rw [div_mul_eq_mul_div, one_mul, div_le_one hpos]
        linarith

end GC.LongTime.Ch12
