import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.PatchWiring_S61
import DifferentialGeometry.Geometry.Flow.RicciFlow.LongTime.Ch12.HliftBridgeV2_S97

set_option autoImplicit false

/-! # CH12-S118 G1a: tail (j ≥ J₀) versions of the S61 patch wiring and the S97 Ico→Ioo adapter; `hrc` from `δ → 0`

* `persistentModelPatch_of_windows_tail_S118` = `persistentModelPatch_of_windows_S61` with `hlift0` only for `j ≥ J₀`
  (text of the S61 proof, generated by `scratch/s118/gen_tail.py`; the S61 proof only uses `hlift0` at the window index
  `j ≥ max (N₀ m) J` of a point beyond `t_{max (N₀ m) J}`, `J ≥ J₀` is added to `J`).
* `hlift0_of_Ico_tail_S118` = `hlift0_of_Ico_v2_S97` with `hneg` and the output for `j ≥ J₁` only (`hlift0Ico` for all `j`).
* `hrc_of_hdec_S118` : `hrc` (late-time recentering smallness) from `δ → 0` (`Hp.accuracy_eq : parameters.delta = δ`). -/
noncomputable section
open Set Filter Topology DifferentialGeometry DifferentialGeometry.Geometry.Hyperbolic
open DifferentialGeometry.Geometry.Collapse DifferentialGeometry.Geometry.Curvature
open DifferentialGeometry.PDE.RicciFlow.Surgery.Topology
open DifferentialGeometry.Topology DifferentialGeometry.Geometry.Riemannian
open Manifold GC.LongTime
open scoped Manifold ContDiff ENNReal

namespace GC.LongTime.Ch12
universe u

theorem persistentModelPatch_of_windows_tail_S118 {P : OrientedThreeStage.{u}} {g : P.Metric} (F : GC.Interface.RawSurgery P g)
    (H : FiniteVolumeHyperbolicModel.{u}) {T start : ℝ} (hT : 0 < T) (hTs : T ≤ start)
    (α θ : ℝ → ℝ) (B : ℝ) (hB : 0 ≤ B) (hθ : ContDiff ℝ ∞ θ)
    (hθrange : ∀ s, θ s ∈ Icc (0 : ℝ) 1) (hθ0 : ∀ s, s ≤ 7 / 4 → θ s = 0)
    (hθ1 : ∀ s, 15 / 8 ≤ s → θ s = 1) (hθderiv : ∀ s, |deriv θ s| ≤ B)
    (f : (j : ℕ) → (t : ℝ) → t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
      H.Carrier → (postStage F.observation t).Carrier)
    (E : ℕ → ℝ × H.Carrier → H.Carrier) (η ρ : ℕ → ℝ) (ν : ℕ → ℕ)
    (hη : ∀ j, 0 ≤ η j) (hηt : Tendsto η atTop (𝓝 0)) (hρ : Tendsto ρ atTop atTop)
    (hE : ∀ j, ContMDiff (𝓘(ℝ, ℝ).prod (𝓡 3)) (𝓡 3) ∞ (E j))
    (hbij : ∀ j μ, Function.Bijective (fun p => E j (μ, p)))
    (hE0 : ∀ j p, E j (0, p) = p)
    (hsupp : ∀ j μ p, p ∉ riemannianBallOf H.metric H.basepoint (4 * ρ j) → E j (μ, p) = p)
    (hispeed : ∀ j, ∀ μ ∈ Icc (0 : ℝ) 1, ∀ p : H.Carrier,
      let v := mfderiv 𝓘(ℝ, ℝ) (𝓡 3) (fun r => E j (r, p)) μ (timeVector_CX5 μ);
      H.metric.inner (E j (μ, p)) v v ≤ η j ^ 2)
    (hend : ∀ j (h1 : dyadicTime_CX5 T (j + 1) ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)))
      (h2 : dyadicTime_CX5 T (j + 1) ∈ Icc (dyadicTime_CX5 T (j + 1)) (dyadicTime_CX5 T (j + 1 + 1))),
      ∀ p ∈ riemannianBallOf H.metric H.basepoint (2 * ρ j), f j _ h1 (E j (1, p)) = f (j + 1) _ h2 p)
    (hacc : ∀ j t (ht : t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
      ContMDiffOn (𝓡 3) (𝓡 3) ∞ (f j t ht) (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
      ∀ k : ℕ, k ≤ ν j → ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
        ckErr_S45 H (postMetric F.observation t) t⁻¹ (f j t ht) k p < η j)
    (hbudget : ∀ t, start ≤ t → 4 * B * η (dyadicIndex_CX5 T t) < α t)
    (J₀ : ℕ)
    (hlift0 : ∀ j, J₀ ≤ j → ∀ (s : ℝ), s ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
      ∃ (n : ℕ) (first last : Fin ((F.tower.history n).eventCount + 1))
        (ordered : first ≤ last) (a b : ℝ) (_ : a < s) (_ : s < b)
        (_ : b ≤ (F.tower.history n).horizon)
        (stages : ∀ r : Icc (0 : ℝ) (F.tower.history n).horizon, (r : ℝ) ∈ Ioo a b →
          first ≤ (F.tower.history n).toHistory.activeStage r ∧
            (F.tower.history n).toHistory.activeStage r ≤ last)
        (φ : H.Carrier → (F.tower.history n).toHistory.backwardSurvivorDomain first last ordered),
        ContMDiffOn (𝓡 3) (𝓡 3) ∞ φ (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
        ∀ (r : Icc (0 : ℝ) (F.tower.history n).horizon) (hr : (r : ℝ) ∈ Ioo a b)
          (hrs : (r : ℝ) ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
          ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
          HEq ((F.tower.history n).toHistory.backwardSurvivorMap first last ordered
            ((F.tower.history n).toHistory.activeStage r) (stages r hr).1 (stages r hr).2 (φ p))
            (f j r hrs p)) :
    ∃ Ω : TopologicalSpace.Opens (ℝ × H.Carrier),
      (∀ m : ℕ, ∃ τ : ℝ, ∀ t, τ < t → riemannianBallOf H.metric H.basepoint m ⊆ sourceSlice_CX5 Ω t) ∧
      ∀ Ω' : TopologicalSpace.Opens (ℝ × H.Carrier), Ω' ≤ Ω →
        ∀ t (_ht : start ≤ t), ∀ x ∈ sourceSlice_CX5 Ω' t,
          Nonempty (PersistentModelPatch F H start α (sourceSlice_CX5 Ω')
            (fun t ht => smoothedPhysicalMap_CX5 H T hT θ f E t (hTs.trans ht)) t x) := by
  classical
  choose N₀ hN₀ using fun m : ℕ => exists_exhaustionIndex_S49 hρ m
  obtain ⟨J, hJJ₀, hJ⟩ : ∃ J : ℕ, J₀ ≤ J ∧ ∀ j, J ≤ j → η j ≤ 1 := by
    obtain ⟨J, hJ⟩ := eventually_atTop.1
      (hηt.eventually (eventually_le_nhds (by norm_num : (0 : ℝ) < 1)))
    exact ⟨max J J₀, le_max_right _ _, fun j hj => hJ j ((le_max_left _ _).trans hj)⟩
  let Ub : ℕ → TopologicalSpace.Opens H.Carrier := fun m =>
    ⟨riemannianBallOf H.metric H.basepoint m, isOpen_riemannianBallOf_S61 H _⟩
  have hmono := dyadicTime_strictMono_CX5 hT
  refine ⟨exhaustionSpaceTime_CX5 Ub (fun m => dyadicTime_CX5 T (max (N₀ m) J)),
    fun m => ⟨dyadicTime_CX5 T (max (N₀ m) J), fun t ht p hp =>
      exhaustionSpaceTime_contains_CX5 Ub _ m ht hp⟩, ?_⟩
  intro Ω' hle t _ x hx
  have hΩ : (t, x) ∈ ⋃ n, Ioi (dyadicTime_CX5 T (max (N₀ n) J)) ×ˢ (Ub n : Set H.Carrier) :=
    hle (show (t, x) ∈ Ω' from hx)
  obtain ⟨m, hm⟩ := Set.mem_iUnion.1 hΩ
  have htN : dyadicTime_CX5 T (max (N₀ m) J) < t := hm.1
  have hNm : ∀ k, max (N₀ m) J ≤ k → (m : ℝ) ≤ ρ k ∧ η k ≤ 1 := fun k hk =>
    ⟨hN₀ m k ((le_max_left _ _).trans hk), hJ k ((le_max_right _ _).trans hk)⟩
  have hT0 : T < t := lt_of_le_of_lt (by simpa using hmono.monotone (Nat.zero_le (max (N₀ m) J))) htN
  obtain ⟨j, -, -, -, -, -, -, -, hj1, hj2, -⟩ := exists_windows_S49 hT hT0
    (a₀ := t - 1) (b₀ := t + 1) (by linarith) (by linarith)
  let Um : Set H.Carrier := riemannianBallOf H.metric H.basepoint m
  have hjN : max (N₀ m) J ≤ j := Nat.lt_succ_iff.1 (hmono.lt_iff_lt.1 (htN.trans_le hj2))
  have hjJ₀ : J₀ ≤ j := hJJ₀.trans ((le_max_right _ _).trans hjN)
  rcases hj2.lt_or_eq with hlt | heq
  · obtain ⟨n, first, last, ordered, aL, bL, hsL, hsL', hbL, stagesL, φ, hφ, hheq⟩ :=
      hlift0 j hjJ₀ t ⟨hj1.le, hj2⟩
    obtain ⟨a₁, b₁, U, ha₁, ha₁t, htb₁, hb₁, hxU, hbox⟩ :=
      exists_sourceBox_CX5 Ω' (hT.trans hT0) hsL' (show (t, x) ∈ Ω' from hx)
    obtain ⟨a, b, hTa, ha0, hNa, hat, htb, hbb, hwin, hge⟩ := window_data_S61 hT
      (max (N₀ m) J) htN j hj1 hj2 (a₀ := max a₁ aL) (b₀ := b₁) (max_lt ha₁t hsL) htb₁
    have hbl : aL ≤ a := (le_max_right _ _).trans ha0
    have ha₁a : a₁ ≤ a := (le_max_left _ _).trans ha0
    have hbL' : b ≤ bL := hbb.trans hb₁
    have hwid : ∀ r : ℝ, r ∈ Ioo a b → r ∈ Ioo aL bL := fun r hr =>
      ⟨hbl.trans_lt hr.1, hr.2.trans_le hbL'⟩
    have hnojoin : ∀ k : ℕ, a < dyadicTime_CX5 T (k + 1) → dyadicTime_CX5 T (k + 1) < b → False := by
      rcases hwin with ⟨_, _, h⟩ | ⟨h, _, _⟩
      · exact h
      · exact absurd h hlt.ne
    exact patch_core_S61 F H hT hTs α θ B hB hθ hθrange hθ0 hθ1 hθderiv f E η ρ ν hη hE hbij hE0
      hsupp hispeed hend hacc hbudget Ω' t x j m n first last ordered a b hTa hat htb
      (hbb.trans (hb₁.trans hbL))
      ⟨(U : Set H.Carrier) ∩ Um, U.isOpen.inter (isOpen_riemannianBallOf_S61 H _)⟩ ⟨hxU, hm.2⟩
      (fun s hs => Set.inter_subset_left.trans
        (hbox s ⟨ha₁a.trans_lt hs.1, hs.2.trans_le (hbb)⟩))
      Set.inter_subset_right
      (fun k _ h2 => (hNm k (hge k h2)).1) (fun k _ h2 => (hNm k (hge k h2)).2)
      (fun r hr => stagesL r (hwid r hr)) hwin φ φ hφ
      (fun r hr hrs p hp => hheq r (hwid r hr) hrs p hp)
      (fun h2b _ => (hnojoin j (hat.trans_le hj2) h2b).elim)
  · have hjt1 : dyadicTime_CX5 T j ≤ dyadicTime_CX5 T (j + 1) := (hmono (Nat.lt_succ_self j)).le
    have hjt2 : dyadicTime_CX5 T (j + 1) ≤ dyadicTime_CX5 T (j + 1 + 1) :=
      (hmono (Nat.lt_succ_self (j + 1))).le
    obtain ⟨a₁, b₁, hs₁, hs₁', n₁, hb₁, hu₁⟩ := lift_uniform_S55 F
      (riemannianBallOf H.metric H.basepoint (4 * ρ j))
      (Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)))
      (fun r => (postStage F.observation r).Carrier) (fun r hr => f j r hr) t
      (hlift0 j hjJ₀ t ⟨hj1.le, hj2⟩)
    obtain ⟨a₂, b₂, hs₂, hs₂', n₂, hb₂, hu₂⟩ := lift_uniform_S55 F
      (riemannianBallOf H.metric H.basepoint (4 * ρ (j + 1)))
      (Icc (dyadicTime_CX5 T (j + 1)) (dyadicTime_CX5 T (j + 1 + 1)))
      (fun r => (postStage F.observation r).Carrier) (fun r hr => f (j + 1) r hr) t
      (hlift0 (j + 1) (hjJ₀.trans (Nat.le_succ j)) t ⟨heq.ge, heq ▸ hjt2⟩)
    obtain ⟨first₁, last₁, ordered₁, stages₁, φ₁, hφ₁, hheq₁⟩ := hu₁ (max n₁ n₂) (le_max_left _ _)
    obtain ⟨first₂, last₂, ordered₂, stages₂, φ₂, hφ₂, hheq₂⟩ := hu₂ (max n₁ n₂) (le_max_right _ _)
    obtain ⟨a₃, b₃, U, ha₃, ha₃t, htb₃, hb₃, hxU, hbox⟩ :=
      exists_sourceBox_CX5 Ω' (hT.trans hT0) (lt_min hs₁' hs₂') (show (t, x) ∈ Ω' from hx)
    obtain ⟨a, b, hTa, ha0, hNa, hat, htb, hbb, hwin, hge⟩ := window_data_S61 hT
      (max (N₀ m) J) htN j hj1 hj2 (a₀ := max (max a₃ a₁) a₂) (b₀ := b₃)
      (max_lt (max_lt ha₃t hs₁) hs₂) htb₃
    have ha₃a : a₃ ≤ a := ((le_max_left _ _).trans (le_max_left _ _)).trans ha0
    have ha₁a : a₁ ≤ a := ((le_max_right _ _).trans (le_max_left _ _)).trans ha0
    have ha₂a : a₂ ≤ a := (le_max_right _ _).trans ha0
    have hb1 : b ≤ b₁ := hbb.trans (hb₃.trans (min_le_left _ _))
    have hb2 : b ≤ b₂ := hbb.trans (hb₃.trans (min_le_right _ _))
    have hw1 : ∀ r : ℝ, r ∈ Ioo a b → r ∈ Ioo a₁ b₁ := fun r hr =>
      ⟨ha₁a.trans_lt hr.1, hr.2.trans_le hb1⟩
    have hw2 : ∀ r : ℝ, r ∈ Ioo a b → r ∈ Ioo a₂ b₂ := fun r hr =>
      ⟨ha₂a.trans_lt hr.1, hr.2.trans_le hb2⟩
    have hbN : b ≤ (F.tower.history (max n₁ n₂)).horizon := by
      rw [F.tower.horizon_eq]
      have : (max n₁ n₂ : ℕ) ≥ n₁ := le_max_left _ _
      have h1 : (n₁ : ℝ) ≤ ((max n₁ n₂ : ℕ) : ℝ) := by exact_mod_cast this
      have h2 : b₁ ≤ (n₁ : ℝ) := by simpa [F.tower.horizon_eq n₁] using hb₁
      exact hb1.trans (h2.trans h1)
    let r₀ : Icc (0 : ℝ) (F.tower.history (max n₁ n₂)).horizon :=
      ⟨t, (hT.trans hT0).le, htb.le.trans hbN⟩
    have hc₁ := stages₁ r₀ ⟨hs₁, hs₁'⟩
    have hc₂ := stages₂ r₀ ⟨hs₂, hs₂'⟩
    have o : max first₁ first₂ ≤ min last₁ last₂ :=
      le_trans (max_le hc₁.1 hc₂.1) (le_min hc₁.2 hc₂.2)
    let K := (F.tower.history (max n₁ n₂)).toHistory
    exact patch_core_S61 F H hT hTs α θ B hB hθ hθrange hθ0 hθ1 hθderiv f E η ρ ν hη hE hbij hE0
      hsupp hispeed hend hacc hbudget Ω' t x j m (max n₁ n₂) (max first₁ first₂)
      (min last₁ last₂) o a b hTa hat htb hbN
      ⟨(U : Set H.Carrier) ∩ Um, U.isOpen.inter (isOpen_riemannianBallOf_S61 H _)⟩ ⟨hxU, hm.2⟩
      (fun s hs => Set.inter_subset_left.trans
        (hbox s ⟨ha₃a.trans_lt hs.1, hs.2.trans_le hbb⟩))
      Set.inter_subset_right
      (fun k _ h2 => (hNm k (hge k h2)).1) (fun k _ h2 => (hNm k (hge k h2)).2)
      (fun r hr => ⟨max_le (stages₁ r (hw1 r.1 hr)).1 (stages₂ r (hw2 r.1 hr)).1,
        le_min (stages₁ r (hw1 r.1 hr)).2 (stages₂ r (hw2 r.1 hr)).2⟩) hwin
      (fun x => survivorRestrict_S49 K ordered₁ o (le_max_left _ _) (min_le_left _ _) (φ₁ x))
      (fun x => survivorRestrict_S49 K ordered₂ o (le_max_right _ _) (min_le_right _ _) (φ₂ x))
      ((contMDiff_survivorRestrict_S49 K ordered₁ o (le_max_left _ _)
        (min_le_left _ _)).comp_contMDiffOn hφ₁)
      (fun r hr hrs p hp => (heq_of_eq (backwardSurvivorMap_survivorRestrict_S49 K ordered₁ o
        (le_max_left _ _) (min_le_left _ _) _ _ _ (φ₁ p))).trans (hheq₁ r (hw1 r.1 hr) hrs p hp))
      (fun _ _ => ⟨(contMDiff_survivorRestrict_S49 K ordered₂ o (le_max_right _ _)
        (min_le_right _ _)).comp_contMDiffOn hφ₂,
        fun r hr hrs p hp => (heq_of_eq (backwardSurvivorMap_survivorRestrict_S49 K ordered₂ o
          (le_max_right _ _) (min_le_right _ _) _ _ _ (φ₂ p))).trans
          (hheq₂ r (hw2 r.1 hr) hrs p hp)⟩)

theorem hlift0_of_Ico_tail_S118 {P : OrientedThreeStage.{u}} {g : P.Metric}
    {F : GC.Interface.RawSurgery P g} {δ : ℝ → ℝ} (Hp : AnalyticSurgeryProfile F δ)
    (H : FiniteVolumeHyperbolicModel.{u}) {T : ℝ} (hT : 0 < T) (ρ : ℕ → ℝ) (hρpos : ∀ j, 0 < ρ j)
    (f : (j : ℕ) → (t : ℝ) → t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
      H.Carrier → (postStage F.observation t).Carrier)
    (hscale : ∀ n (i : Fin (F.tower.history n).eventCount),
      ∀ (b : ((F.tower.history n).toHistory.event i).RetainedBoundaryIndex) (z : ThreeBall),
        ((Hp.records n i).static b).neck.scale / 2 ≤
          metricScalarAt ((Hp.records n i).static b).witness.metric
            (((Hp.records n i).static b).witness.cap z))
    (hrc : ∀ n (i : Fin (F.tower.history n).eventCount),
      T ≤ (F.tower.history n).toHistory.time i.succ →
      Hp.parameters.recenterConstant *
        Hp.parameters.delta ((F.tower.history n).toHistory.time i.succ) ≤ 1 / 2)
    (J₁ : ℕ)
    (hneg : ∀ j, J₁ ≤ j → ∀ (t : ℝ) (ht : t ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
      ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
        metricScalarAt (postMetric F.observation t) (f j t ht p) ≤ 0)
    (hlift0Ico : ∀ j (s : ℝ), s ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
      ∃ (n : ℕ) (first last : Fin ((F.tower.history n).eventCount + 1))
      (ordered : first ≤ last) (a b : ℝ) (_ : a ≤ dyadicTime_CX5 T j) (_ : a ≤ s) (_ : s < b)
      (_ : b ≤ (F.tower.history n).horizon)
      (stages : ∀ r : Icc (0 : ℝ) (F.tower.history n).horizon, (r : ℝ) ∈ Ico a b →
        first ≤ (F.tower.history n).toHistory.activeStage r ∧
          (F.tower.history n).toHistory.activeStage r ≤ last)
      (φ : H.Carrier → (F.tower.history n).toHistory.backwardSurvivorDomain first last ordered),
      ContMDiffOn (𝓡 3) (𝓡 3) ∞ φ (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
      ∀ (r : Icc (0 : ℝ) (F.tower.history n).horizon) (hr : (r : ℝ) ∈ Ico a b)
        (hrW : (r : ℝ) ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
        ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
        HEq ((F.tower.history n).toHistory.backwardSurvivorMap first last ordered
          ((F.tower.history n).toHistory.activeStage r) (stages r hr).1 (stages r hr).2 (φ p))
          (f j r hrW p)) :
    ∀ j, J₁ ≤ j → ∀ (s : ℝ), s ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1)) →
      ∃ (n : ℕ) (first last : Fin ((F.tower.history n).eventCount + 1))
      (ordered : first ≤ last) (a b : ℝ) (_ : a < s) (_ : s < b)
      (_ : b ≤ (F.tower.history n).horizon)
      (stages : ∀ r : Icc (0 : ℝ) (F.tower.history n).horizon, (r : ℝ) ∈ Ioo a b →
        first ≤ (F.tower.history n).toHistory.activeStage r ∧
          (F.tower.history n).toHistory.activeStage r ≤ last)
      (φ : H.Carrier → (F.tower.history n).toHistory.backwardSurvivorDomain first last ordered),
      ContMDiffOn (𝓡 3) (𝓡 3) ∞ φ (riemannianBallOf H.metric H.basepoint (4 * ρ j)) ∧
      ∀ (r : Icc (0 : ℝ) (F.tower.history n).horizon) (hr : (r : ℝ) ∈ Ioo a b)
        (hrW : (r : ℝ) ∈ Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))),
        ∀ p ∈ riemannianBallOf H.metric H.basepoint (4 * ρ j),
        HEq ((F.tower.history n).toHistory.backwardSurvivorMap first last ordered
          ((F.tower.history n).toHistory.activeStage r) (stages r hr).1 (stages r hr).2 (φ p))
          (f j r hrW p) := by
  intro j hj s hs
  have hTj : T ≤ dyadicTime_CX5 T j := by
    have h1 : (1 : ℝ) ≤ 2 ^ j := one_le_pow₀ (by norm_num)
    change T ≤ 2 ^ j * T
    nlinarith
  have hTs : T ≤ s := hTj.trans hs.1
  obtain ⟨n, first, last, ordered, a, b, hat0, hat, htb, hb, stages, φ, hφ, hheq⟩ := hlift0Ico j s hs
  exact hlift_Ioo_of_Ico_S89 Hp (riemannianBallOf H.metric H.basepoint (4 * ρ j))
    ⟨H.basepoint, mem_riemannianBallOf_self_O13 H.metric H.basepoint (by linarith [hρpos j])⟩
    (Icc (dyadicTime_CX5 T j) (dyadicTime_CX5 T (j + 1))) (fun r hr => f j r hr) s hs
    (hT.le.trans hTs) (fun n i _ => hscale n i)
    (fun n i htime => hrc n i (htime ▸ hTs)) (hneg j hj s hs)
    ⟨n, first, last, ordered, a, b, hat, fun r hr _ => hat0.trans hr.1, htb, hb, stages, φ, hφ, hheq⟩

/-- `hrc` (late-time recentering smallness at event times `≥ Trc`) from `δ → 0`: `Hp.parameters.delta = δ`
(`Hp.accuracy_eq`) and `recenterConstant ≥ 4 > 0`. -/
theorem hrc_of_hdec_S118 {P : OrientedThreeStage.{u}} {g : P.Metric}
    {F : GC.Interface.RawSurgery P g} {δ : ℝ → ℝ} (Hp : AnalyticSurgeryProfile F δ)
    (hdec : ∀ ε : ℝ, 0 < ε → ∃ B : ℝ, ∀ t : ℝ, B < t → δ t < ε) :
    ∃ Trc : ℝ, ∀ n (i : Fin (F.tower.history n).eventCount),
      Trc ≤ (F.tower.history n).toHistory.time i.succ →
      Hp.parameters.recenterConstant *
        Hp.parameters.delta ((F.tower.history n).toHistory.time i.succ) ≤ 1 / 2 := by
  have hc : 0 < Hp.parameters.recenterConstant := by
    have := Hp.parameters.recenterConstant_ge_four
    linarith
  obtain ⟨B, hB⟩ := hdec (1 / (2 * Hp.parameters.recenterConstant)) (by positivity)
  refine ⟨B + 1, fun n i h => ?_⟩
  have h1 : δ ((F.tower.history n).toHistory.time i.succ) <
      1 / (2 * Hp.parameters.recenterConstant) := hB _ (by linarith)
  rw [Hp.accuracy_eq]
  have h2 := mul_le_mul_of_nonneg_left h1.le hc.le
  have e : Hp.parameters.recenterConstant * (1 / (2 * Hp.parameters.recenterConstant)) = 1 / 2 := by
    field_simp
  linarith

end GC.LongTime.Ch12
