import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Metric.RadialSupportBuffer
import DifferentialGeometry.Geometry.Metric.SlowScaleQuotient
import DifferentialGeometry.Geometry.Metric.WeakEdgeLocalization

#check GC.MetricGeometry.radial_support_test_ball_buffer
#print axioms GC.MetricGeometry.radial_support_test_ball_buffer

#check GC.MetricGeometry.lipschitz_quotient_difference_le
#print axioms GC.MetricGeometry.lipschitz_quotient_difference_le

#check GC.MetricGeometry.slow_scale_quotient_variation
#print axioms GC.MetricGeometry.slow_scale_quotient_variation

#check GC.MetricGeometry.strong_set_proximity_of_support_meeting
#print axioms GC.MetricGeometry.strong_set_proximity_of_support_meeting

#check GC.MetricGeometry.weak_edge_quotient_alternative
#print axioms GC.MetricGeometry.weak_edge_quotient_alternative
