import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Metric.Approximation.PaddedStripBoundary
import DifferentialGeometry.Geometry.Metric.Approximation.SlimChartCutoffSupport
import DifferentialGeometry.Geometry.Metric.Approximation.EdgeChartCutoffSupport

#check GC.MetricGeometry.strip_height_lt_of_local_half_plane_model
#print axioms GC.MetricGeometry.strip_height_lt_of_local_half_plane_model

#check GC.MetricGeometry.padded_strip_height_lt_of_half_plane_model
#print axioms GC.MetricGeometry.padded_strip_height_lt_of_half_plane_model

#check GC.MetricGeometry.tsupport_slim_chart_cutoff_subset
#print axioms GC.MetricGeometry.tsupport_slim_chart_cutoff_subset

#check GC.MetricGeometry.tsupport_edge_chart_cutoff_subset
#print axioms GC.MetricGeometry.tsupport_edge_chart_cutoff_subset
