import Mathlib.Tactic.Linter
import DifferentialGeometry.Analysis.Calculus.PerturbedProjection
import DifferentialGeometry.Analysis.Calculus.CutoffAdjustment
import DifferentialGeometry.Analysis.Calculus.AdjustmentProjections
import DifferentialGeometry.Analysis.InnerProductSpace.SubspaceRankTransfer

#check DifferentialGeometry.Analysis.norm_displacement_le_of_derivative_comparison
#print axioms DifferentialGeometry.Analysis.norm_displacement_le_of_derivative_comparison

#check DifferentialGeometry.Analysis.perturbed_projection_on_original_ball
#print axioms DifferentialGeometry.Analysis.perturbed_projection_on_original_ball

#check DifferentialGeometry.Analysis.cutoff_adjustment_value_derivative_le
#print axioms DifferentialGeometry.Analysis.cutoff_adjustment_value_derivative_le

#check DifferentialGeometry.Analysis.projected_cutoff_adjustment_value_derivative_le
#print axioms DifferentialGeometry.Analysis.projected_cutoff_adjustment_value_derivative_le

#check DifferentialGeometry.Analysis.projected_cutoff_adjustment_cumulative_le
#print axioms DifferentialGeometry.Analysis.projected_cutoff_adjustment_cumulative_le

#check DifferentialGeometry.Analysis.retained_projection_cutoff_adjustment
#print axioms DifferentialGeometry.Analysis.retained_projection_cutoff_adjustment

#check DifferentialGeometry.Analysis.factor_projection_cutoff_adjustment
#print axioms DifferentialGeometry.Analysis.factor_projection_cutoff_adjustment

#check DifferentialGeometry.Analysis.ker_fderiv_le_ker_postcomp
#print axioms DifferentialGeometry.Analysis.ker_fderiv_le_ker_postcomp

#check DifferentialGeometry.Analysis.ker_fderiv_postcomp_eq_of_injOn_range
#print axioms DifferentialGeometry.Analysis.ker_fderiv_postcomp_eq_of_injOn_range

#check ContinuousLinearMap.surjective_codRestrict_of_rank_margin
#print axioms ContinuousLinearMap.surjective_codRestrict_of_rank_margin
