import DifferentialGeometry.Topology.ThreeManifold.GraphManifold.Seifert.ConeFoldBijective

/-!
# The side-pairing quotient of the doubled triangle

Lane A4Q (design `docs/geometrization/handoffs/20261004-design-a4-cone-fold.md`, §0 (ii) and
erratum item 3). On the doubled domain `domain = T ∪ σ₀T` the side pairings are
`sidePair i = σ₀ ∘ σᵢ` (`i = 1, 2`): `sidePair 1 z = z - 2W` is the parabolic translation and
`sidePair 2 = σ₀σ₂` is the rotation about `v₂` (elliptic when `v₂` is a cone). `PairRel` is the
relation generated by them: a point of the wall `i ≠ 0` of `T` is paired with its image in
`σ₀T`. The map `foldExt f` is `f` on `T` and `conj ∘ f ∘ σ₀` on `σ₀T` (the two agree on the
common wall `0`, where `f` is real). From `Set.BijOn f σ.triangle σ.basePlus`, the reality of
`f` exactly on the walls and nothing else — in particular without assuming that `T` is a
fundamental domain of the reflection group — the induced map on the quotient
`Quot PairRel → base` is a bijection onto the full base `base = {‖u‖ < 3}`, with the hole
`‖u + 3/2‖ > 1/2` removed for the cusp (`quotient_bijOn`, and the concrete form
`foldExt_eq_iff`, `foldExt_surjOn`, `foldExt_mapsTo`). The regression section instantiates the
sets for the shapes `(π/2, 0)` (`rightAngleCusp`, the `(2, ⊤, ⊤)` block) and `(π/3, π/3)`
(`equilateralCones`, the `(3, 3, ⊤)` block): the targets, the real segments and the endpoint
values of the profile.
-/

set_option autoImplicit false

noncomputable section

open Complex
open scoped ComplexConjugate ContDiff Topology

namespace GC.Seifert

namespace ConeShape

variable (σ : ConeShape)

def base : Set ℂ := {u | ‖u‖ < 3 ∧ (σ.θ₂ = 0 → 1 / 2 < ‖u + 3 / 2‖)}

theorem mem_basePlus_iff {u : ℂ} : u ∈ σ.basePlus ↔ u ∈ σ.base ∧ 0 ≤ u.im := by
  simp only [basePlus, base, Set.mem_ofPred_eq]
  tauto

theorem conj_mem_base {u : ℂ} (hu : u ∈ σ.base) : conj u ∈ σ.base := by
  refine ⟨by rw [Complex.norm_conj]; exact hu.1, fun h => ?_⟩
  have e : conj u + 3 / 2 = conj (u + 3 / 2) := by
    rw [map_add, map_div₀, map_ofNat, map_ofNat]
  rw [e, Complex.norm_conj]
  exact hu.2 h

def domain : Set ℂ := σ.triangle ∪ σ.refl 0 '' σ.triangle

def sidePair (i : Fin 3) (z : ℂ) : ℂ := σ.refl 0 (σ.refl i z)

def PairRel (z w : ℂ) : Prop :=
  z = w ∨ (∃ i : Fin 3, i ≠ 0 ∧ z ∈ σ.foldWall i ∧ w = σ.sidePair i z) ∨
    (∃ i : Fin 3, i ≠ 0 ∧ w ∈ σ.foldWall i ∧ z = σ.sidePair i w)

def foldExt (f : ℂ → ℂ) (z : ℂ) : ℂ := if 0 ≤ z.re then f z else conj (f (σ.refl 0 z))

theorem refl_zero_refl_zero (z : ℂ) : σ.refl 0 (σ.refl 0 z) = z := by
  simp [refl]

theorem refl_zero_re (z : ℂ) : (σ.refl 0 z).re = -z.re := by
  simp [refl]

theorem refl_zero_im (z : ℂ) : (σ.refl 0 z).im = z.im := by
  simp [refl]

theorem sidePair_one (z : ℂ) : σ.sidePair 1 z = z - 2 * σ.width := by
  apply Complex.ext <;> simp [sidePair, refl]

theorem sidePair_eq_refl_zero {i : Fin 3} {z : ℂ} (hz : z ∈ σ.foldWall i) :
    σ.sidePair i z = σ.refl 0 z := by
  rw [sidePair, σ.refl_eq_self_of_mem_foldWall hz]

theorem mem_domain_iff {z : ℂ} :
    z ∈ σ.domain ↔ z ∈ σ.triangle ∨ σ.refl 0 z ∈ σ.triangle := by
  constructor
  · rintro (h | ⟨w, hw, rfl⟩)
    · exact Or.inl h
    · right
      rwa [refl_zero_refl_zero]
  · rintro (h | h)
    · exact Or.inl h
    · exact Or.inr ⟨_, h, σ.refl_zero_refl_zero z⟩

theorem re_nonneg_of_mem_triangle {z : ℂ} (hz : z ∈ σ.triangle) : 0 ≤ z.re := hz.2 0

theorem foldExt_of_mem_triangle (f : ℂ → ℂ) {z : ℂ} (hz : z ∈ σ.triangle) :
    σ.foldExt f z = f z := by
  simp only [foldExt, σ.re_nonneg_of_mem_triangle hz, ↓reduceIte]

theorem pairRel_refl (z : ℂ) : σ.PairRel z z := Or.inl rfl

theorem pairRel_symm {z w : ℂ} (h : σ.PairRel z w) : σ.PairRel w z := by
  rcases h with h | h | h
  · exact Or.inl h.symm
  · exact Or.inr (Or.inr h)
  · exact Or.inr (Or.inl h)

section Fold

variable {σ}
variable {f : ℂ → ℂ}

theorem foldExt_of_refl_mem
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    {z : ℂ} (hz : σ.refl 0 z ∈ σ.triangle) : σ.foldExt f z = conj (f (σ.refl 0 z)) := by
  by_cases h : 0 ≤ z.re
  · simp only [foldExt, h, ↓reduceIte]
    have h2 := σ.re_nonneg_of_mem_triangle hz
    rw [refl_zero_re] at h2
    have hre : z.re = 0 := le_antisymm (by linarith) h
    have hz0 : 0 < z.im := by
      have := hz.1
      rwa [refl_zero_im] at this
    have hfix : σ.refl 0 z = z := σ.refl_of_wallSide_eq_zero hz0 (i := 0) hre
    rw [hfix] at hz ⊢
    exact (Complex.conj_eq_iff_im.2 (hreal 0 z hz hre)).symm
  · simp only [foldExt, h, ↓reduceIte]

theorem foldExt_respects
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (z w : σ.domain) (h : σ.PairRel z w) : σ.foldExt f z = σ.foldExt f w := by
  have key : ∀ i : Fin 3, ∀ a ∈ σ.foldWall i, σ.foldExt f a = σ.foldExt f (σ.sidePair i a) := by
    intro i a ha
    rw [σ.sidePair_eq_refl_zero ha, σ.foldExt_of_mem_triangle f ha.1,
      foldExt_of_refl_mem hreal (by rw [refl_zero_refl_zero]; exact ha.1), refl_zero_refl_zero]
    exact (Complex.conj_eq_iff_im.2 (hreal i a ha.1 ha.2)).symm
  rcases h with h | ⟨i, -, hz, hw⟩ | ⟨i, -, hw, hz⟩
  · rw [h]
  · rw [hw]
    exact key i z hz
  · rw [hz]
    exact (key i w hw).symm

theorem foldExt_mapsTo
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) :
    Set.MapsTo (σ.foldExt f) σ.domain σ.base := by
  intro z hz
  rcases σ.mem_domain_iff.1 hz with h | h
  · rw [σ.foldExt_of_mem_triangle f h]
    exact (σ.mem_basePlus_iff.1 (hbij.mapsTo h)).1
  · rw [foldExt_of_refl_mem hreal h]
    exact σ.conj_mem_base (σ.mem_basePlus_iff.1 (hbij.mapsTo h)).1

theorem foldExt_surjOn
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) :
    Set.SurjOn (σ.foldExt f) σ.domain σ.base := by
  intro u hu
  rcases le_or_gt 0 u.im with him | him
  · obtain ⟨z, hz, rfl⟩ := hbij.surjOn (σ.mem_basePlus_iff.2 ⟨hu, him⟩)
    exact ⟨z, Or.inl hz, σ.foldExt_of_mem_triangle f hz⟩
  · have hc : conj u ∈ σ.basePlus :=
      σ.mem_basePlus_iff.2 ⟨σ.conj_mem_base hu, by rw [Complex.conj_im]; linarith⟩
    obtain ⟨z, hz, hzu⟩ := hbij.surjOn hc
    refine ⟨σ.refl 0 z, Or.inr ⟨z, hz, rfl⟩, ?_⟩
    rw [foldExt_of_refl_mem hreal (by rw [refl_zero_refl_zero]; exact hz), refl_zero_refl_zero,
      hzu, Complex.conj_conj]

theorem pairRel_of_foldExt_eq
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hint : ∀ z ∈ σ.triangle, (f z).im = 0 → ∃ i, σ.wallSide i z = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) {z w : ℂ} (hz : z ∈ σ.domain)
    (hw : w ∈ σ.domain) (h : σ.foldExt f z = σ.foldExt f w) : σ.PairRel z w := by
  have mixed : ∀ a b : ℂ, a ∈ σ.triangle → b ∉ σ.triangle → σ.refl 0 b ∈ σ.triangle →
      σ.foldExt f a = σ.foldExt f b → σ.PairRel a b := by
    intro a b ha hb hb' hab
    rw [σ.foldExt_of_mem_triangle f ha, foldExt_of_refl_mem hreal hb'] at hab
    have h1 := (hbij.mapsTo ha).2.1
    have h2 := (hbij.mapsTo hb').2.1
    have him2 : (f (σ.refl 0 b)).im = 0 := by
      have := congrArg Complex.im hab
      rw [Complex.conj_im] at this
      linarith
    have him : (f a).im = 0 := by
      rw [hab, Complex.conj_im, him2, neg_zero]
    have heq : f a = f (σ.refl 0 b) := by
      rw [hab]
      exact Complex.conj_eq_iff_im.2 him2
    have hab' : a = σ.refl 0 b := hbij.injOn ha hb' heq
    obtain ⟨i, hi⟩ := hint a ha him
    have hi0 : i ≠ 0 := by
      rintro rfl
      apply hb
      have hfix : σ.refl 0 a = a := σ.refl_of_wallSide_eq_zero ha.1 hi
      rw [hab', refl_zero_refl_zero] at hfix
      rw [hfix]
      exact hb'
    refine Or.inr (Or.inl ⟨i, hi0, ⟨ha, hi⟩, ?_⟩)
    rw [σ.sidePair_eq_refl_zero ⟨ha, hi⟩, hab', refl_zero_refl_zero]
  by_cases hzT : z ∈ σ.triangle
  · by_cases hwT : w ∈ σ.triangle
    · rw [σ.foldExt_of_mem_triangle f hzT, σ.foldExt_of_mem_triangle f hwT] at h
      exact Or.inl (hbij.injOn hzT hwT h)
    · exact mixed z w hzT hwT ((σ.mem_domain_iff.1 hw).resolve_left hwT) h
  · have hz' := (σ.mem_domain_iff.1 hz).resolve_left hzT
    by_cases hwT : w ∈ σ.triangle
    · exact σ.pairRel_symm (mixed w z hwT hzT hz' h.symm)
    · have hw' := (σ.mem_domain_iff.1 hw).resolve_left hwT
      rw [foldExt_of_refl_mem hreal hz', foldExt_of_refl_mem hreal hw'] at h
      have h' : f (σ.refl 0 z) = f (σ.refl 0 w) := by
        have := congrArg conj h
        rwa [Complex.conj_conj, Complex.conj_conj] at this
      have := hbij.injOn hz' hw' h'
      have e := congrArg (σ.refl 0) this
      rw [refl_zero_refl_zero, refl_zero_refl_zero] at e
      exact Or.inl e

theorem foldExt_eq_iff
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hint : ∀ z ∈ σ.triangle, (f z).im = 0 → ∃ i, σ.wallSide i z = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) {z w : ℂ} (hz : z ∈ σ.domain)
    (hw : w ∈ σ.domain) : σ.foldExt f z = σ.foldExt f w ↔ σ.PairRel z w :=
  ⟨pairRel_of_foldExt_eq hreal hint hbij hz hw,
    fun h => foldExt_respects hreal ⟨z, hz⟩ ⟨w, hw⟩ h⟩

theorem quotient_bijOn
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hint : ∀ z ∈ σ.triangle, (f z).im = 0 → ∃ i, σ.wallSide i z = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) :
    Set.BijOn (Quot.lift (fun z : σ.domain => σ.foldExt f z) (foldExt_respects hreal))
      Set.univ σ.base := by
  refine ⟨?_, ?_, ?_⟩
  · rintro q -
    induction q using Quot.ind with
    | mk z => exact foldExt_mapsTo hreal hbij z.2
  · rintro q - q' - h
    induction q using Quot.ind with
    | mk z =>
      induction q' using Quot.ind with
      | mk w => exact Quot.sound (pairRel_of_foldExt_eq hreal hint hbij z.2 w.2 h)
  · intro u hu
    obtain ⟨z, hz, hzu⟩ := foldExt_surjOn hreal hbij hu
    exact ⟨Quot.mk _ ⟨z, hz⟩, trivial, hzu⟩

theorem quotient_bijOn_of_local {U : Set ℂ} (hU : IsOpen U) (hTU : σ.triangle ⊆ U)
    (hf : ContDiffOn ℝ ∞ f U)
    (hdet : ∀ z ∈ U, z ≠ σ.vertexOne → z ≠ σ.vertexTwo → (fderiv ℝ f z).det ≠ 0)
    (hreal : ∀ i : Fin 3, ∀ z ∈ σ.triangle, σ.wallSide i z = 0 → (f z).im = 0)
    (hbij : Set.BijOn f σ.triangle σ.basePlus) :
    Set.BijOn (Quot.lift (fun z : σ.domain => σ.foldExt f z) (foldExt_respects hreal))
      Set.univ σ.base :=
  quotient_bijOn hreal (fun _ hz him => σ.exists_wall_of_im_eq_zero hU hTU hf hdet hbij.mapsTo
    hz him) hbij

end Fold

section Regression

def rightAngleCusp : ConeShape where
  θ₁ := Real.pi / 2
  θ₂ := 0
  θ₁_pos := by positivity
  θ₁_le := le_rfl
  θ₂_nonneg := le_rfl
  θ₂_le := by positivity
  sum_lt := by linarith [Real.pi_pos]

def equilateralCones : ConeShape where
  θ₁ := Real.pi / 3
  θ₂ := Real.pi / 3
  θ₁_pos := by positivity
  θ₁_le := by linarith [Real.pi_pos]
  θ₂_nonneg := by positivity
  θ₂_le := by linarith [Real.pi_pos]
  sum_lt := by linarith [Real.pi_pos]

theorem rightAngleCusp_basePlus :
    rightAngleCusp.basePlus = {u | ‖u‖ < 3 ∧ 0 ≤ u.im ∧ 1 / 2 < ‖u + 3 / 2‖} := by
  ext u
  simp [basePlus, rightAngleCusp]

theorem rightAngleCusp_base : rightAngleCusp.base = {u | ‖u‖ < 3 ∧ 1 / 2 < ‖u + 3 / 2‖} := by
  ext u
  simp [base, rightAngleCusp]

theorem equilateralCones_basePlus : equilateralCones.basePlus = {u | ‖u‖ < 3 ∧ 0 ≤ u.im} := by
  ext u
  simp [basePlus, equilateralCones, Real.pi_ne_zero]

theorem equilateralCones_base : equilateralCones.base = {u | ‖u‖ < 3} := by
  ext u
  simp [base, equilateralCones, Real.pi_ne_zero]

theorem ofReal_mem_rightAngleCusp_basePlus (a : ℝ) :
    (a : ℂ) ∈ rightAngleCusp.basePlus ↔ (-3 < a ∧ a < -2) ∨ (-1 < a ∧ a < 3) := by
  rw [rightAngleCusp_basePlus]
  have e : (a : ℂ) + 3 / 2 = ((a + 3 / 2 : ℝ) : ℂ) := by push_cast; ring
  simp only [Set.mem_ofPred_eq, e, Complex.norm_real, Real.norm_eq_abs, Complex.ofReal_im,
    le_refl, true_and]
  constructor
  · rintro ⟨h1, h2⟩
    obtain ⟨a1, a2⟩ := abs_lt.1 h1
    rcases le_or_gt 0 (a + 3 / 2) with h | h
    · rw [abs_of_nonneg h] at h2
      right
      constructor <;> linarith
    · rw [abs_of_neg h] at h2
      left
      constructor <;> linarith
  · rintro (⟨h1, h2⟩ | ⟨h1, h2⟩)
    · refine ⟨abs_lt.2 ⟨by linarith, by linarith⟩, ?_⟩
      rw [abs_of_neg (by linarith)]
      linarith
    · refine ⟨abs_lt.2 ⟨by linarith, by linarith⟩, ?_⟩
      rw [abs_of_pos (by linarith)]
      linarith

theorem ofReal_mem_equilateralCones_basePlus (a : ℝ) :
    (a : ℂ) ∈ equilateralCones.basePlus ↔ -3 < a ∧ a < 3 := by
  rw [equilateralCones_basePlus]
  simp only [Set.mem_ofPred_eq, Complex.norm_real, Real.norm_eq_abs, Complex.ofReal_im, le_refl,
    and_true]
  exact abs_lt

theorem rightAngleCusp_width : rightAngleCusp.width = 1 / 4 := by
  simp [width, rightAngleCusp]

theorem rightAngleCusp_vertexOne : rightAngleCusp.vertexOne = ⟨1 / 4, 1 / 4⟩ := by
  apply Complex.ext <;> simp [vertexOne, width, rightAngleCusp]

theorem rightAngleCusp_constK : rightAngleCusp.constK = 1 / 8 := by
  simp [constK, rightAngleCusp]
  norm_num

theorem equilateralCones_width : equilateralCones.width = 1 / 4 := by
  simp [width, equilateralCones, Real.cos_pi_div_three]
  norm_num

theorem equilateralCones_centre : equilateralCones.centre = 1 / 8 := by
  simp [centre, equilateralCones, Real.cos_pi_div_three]
  norm_num

theorem equilateralCones_constK : equilateralCones.constK = 9 / 64 := by
  simp [constK, equilateralCones, Real.cos_pi_div_three]
  norm_num

theorem sqrt_equilateralCones_constK : Real.sqrt equilateralCones.constK = 3 / 8 := by
  rw [equilateralCones_constK, show (9 / 64 : ℝ) = (3 / 8) ^ 2 by norm_num]
  exact Real.sqrt_sq (by norm_num)

theorem coneProfile_equilateral_canonical : coneProfile (9 / 64) (3 / 8) = 3 / 2 := by
  norm_num [coneProfile]

theorem coneProfile_rightAngle_zero : coneProfile (1 / 8) 0 = 1 / 2 := by
  norm_num [coneProfile]

theorem outerProfile_rightAngle_canonical (Y₁ Y₂ : ℝ) (hY : Y₁ < Y₂) {y : ℝ} (hy : y ≤ Y₁)
    (hy' : y = Real.sqrt (1 / 8)) : outerProfile (1 / 8) Y₁ Y₂ y = 3 := by
  rw [outerProfile_of_le hY hy, hy', coneProfile_sqrt (by norm_num)]
  norm_num

end Regression

end ConeShape

end GC.Seifert
