import Mathlib.Analysis.Complex.UpperHalfPlane.Metric
import Mathlib.NumberTheory.Modular

/-!
# The ideal triangle `(0, 1/2, ∞)` and its reflection group

Packet K16b of `docs/geometrization/handoffs/20261003-survey-k16-pants-geometry.md` (route B).
`idealTriangle ⊆ ℍ` is the closed ideal triangle with vertices `0`, `1/2`, `∞`, given by
`0 ≤ Re z ≤ 1/2` and `1/4 ≤ |z - 1/4|`; `idealTriangleInterior` is its interior
(`interior_idealTriangle`). The walls `wall 0`, `wall 1`, `wall 2` are the whole geodesics
`Re z = 0`, `Re z = 1/2` and `|z - 1/4| = 1/4`, cut out by the signed functions `wallSide i`,
positive on the side of the triangle. No point of `ℍ` lies on two walls (`wall_disjoint`).

The reflections `z ↦ -z̄`, `z ↦ 1 - z̄` and `z ↦ z̄ / (4 z̄ - 1)` in the walls are the integer
matrices `wallMatrix i` of determinant `-1` (`wallReflectionInt i : GL (Fin 2) ℤ`), acting on `ℍ`
through Mathlib's action of `GL (Fin 2) ℝ`, which composes with complex conjugation when the
determinant is negative. Every element of `GL (Fin 2) ℝ` acts isometrically (`isometry_glSMul`);
`wallReflection i` is an involution fixing `wall i` pointwise and swapping its two sides.
`triangleGroup` is the subgroup generated by the three reflections.

Tiling. Every orbit meets the triangle (`exists_smul_mem_idealTriangle`): as in
`ModularGroup.exists_smul_mem_fd`, maximise `Im` over the orbit (the elements are integral of
determinant `±1`), move into the strip `0 ≤ Re z ≤ 1/2` by the translations
`(σ₁ σ₀) ^ n = (z ↦ z + n)` and `σ₁`, and use that the inversion `σ₂` raises `Im` strictly
inside the half disc. Two points of the triangle in one orbit coincide, and the element is `1` or
the reflection in a wall through the point (`smul_mem_idealTriangle`): every element is a reduced
word in the reflections, and reduced words play ping-pong on the open half planes beyond the
walls (`wallSide_wallWord_smul_neg`). The orientation-preserving part `evenTriangleGroup` has
index two and is generated by `σ₁ σ₀` and `σ₂ σ₀`, acting as `T` and `U₄ = !![1, 0; 4, 1]`.
-/

set_option autoImplicit false

noncomputable section

open UpperHalfPlane Matrix
open scoped MatrixGroups ComplexConjugate

namespace GC.Seifert

def idealTriangle : Set ℍ :=
  {z | 0 ≤ z.re ∧ z.re ≤ 1 / 2 ∧ 1 / 4 ≤ ‖(z : ℂ) - 1 / 4‖}

def idealTriangleInterior : Set ℍ :=
  {z | 0 < z.re ∧ z.re < 1 / 2 ∧ 1 / 4 < ‖(z : ℂ) - 1 / 4‖}

def wall : Fin 3 → Set ℍ
  | 0 => {z | z.re = 0}
  | 1 => {z | z.re = 1 / 2}
  | 2 => {z | ‖(z : ℂ) - 1 / 4‖ = 1 / 4}

def wallSide : Fin 3 → ℍ → ℝ
  | 0, z => z.re
  | 1, z => 1 / 2 - z.re
  | 2, z => ‖(z : ℂ) - 1 / 4‖ ^ 2 - 1 / 16

theorem norm_sub_quarter_sq (z : ℍ) :
    ‖(z : ℂ) - 1 / 4‖ ^ 2 = z.re ^ 2 + z.im ^ 2 - z.re / 2 + 1 / 16 := by
  rw [Complex.sq_norm, Complex.normSq_apply]
  simp
  ring

theorem wallSide_zero (z : ℍ) : wallSide 0 z = z.re := rfl

theorem wallSide_one (z : ℍ) : wallSide 1 z = 1 / 2 - z.re := rfl

theorem wallSide_two (z : ℍ) : wallSide 2 z = z.re ^ 2 + z.im ^ 2 - z.re / 2 := by
  change ‖(z : ℂ) - 1 / 4‖ ^ 2 - 1 / 16 = _
  rw [norm_sub_quarter_sq]
  ring

theorem quarter_le_norm_iff (z : ℍ) : 1 / 4 ≤ ‖(z : ℂ) - 1 / 4‖ ↔ 0 ≤ wallSide 2 z := by
  rw [← sq_le_sq₀ (by norm_num) (norm_nonneg _)]
  change _ ↔ 0 ≤ ‖(z : ℂ) - 1 / 4‖ ^ 2 - 1 / 16
  constructor <;> intro h <;> linarith

theorem quarter_lt_norm_iff (z : ℍ) : 1 / 4 < ‖(z : ℂ) - 1 / 4‖ ↔ 0 < wallSide 2 z := by
  rw [← sq_lt_sq₀ (by norm_num) (norm_nonneg _)]
  change _ ↔ 0 < ‖(z : ℂ) - 1 / 4‖ ^ 2 - 1 / 16
  constructor <;> intro h <;> linarith

theorem norm_eq_quarter_iff (z : ℍ) : ‖(z : ℂ) - 1 / 4‖ = 1 / 4 ↔ wallSide 2 z = 0 := by
  rw [← sq_eq_sq₀ (norm_nonneg _) (by norm_num)]
  change _ ↔ ‖(z : ℂ) - 1 / 4‖ ^ 2 - 1 / 16 = 0
  constructor <;> intro h <;> linarith

theorem mem_idealTriangle_iff (z : ℍ) : z ∈ idealTriangle ↔ ∀ i, 0 ≤ wallSide i z := by
  constructor
  · rintro ⟨h0, h1, h2⟩ i
    fin_cases i
    exacts [h0, sub_nonneg.2 h1, (quarter_le_norm_iff z).1 h2]
  · intro h
    exact ⟨h 0, sub_nonneg.1 (h 1), (quarter_le_norm_iff z).2 (h 2)⟩

theorem mem_idealTriangleInterior_iff (z : ℍ) :
    z ∈ idealTriangleInterior ↔ ∀ i, 0 < wallSide i z := by
  constructor
  · rintro ⟨h0, h1, h2⟩ i
    fin_cases i
    exacts [h0, sub_pos.2 h1, (quarter_lt_norm_iff z).1 h2]
  · intro h
    exact ⟨h 0, sub_pos.1 (h 1), (quarter_lt_norm_iff z).2 (h 2)⟩

theorem mem_wall_iff (i : Fin 3) (z : ℍ) : z ∈ wall i ↔ wallSide i z = 0 := by
  fin_cases i
  exacts [Iff.rfl, by change z.re = 1 / 2 ↔ 1 / 2 - z.re = 0; rw [sub_eq_zero, eq_comm],
    norm_eq_quarter_iff z]

theorem idealTriangleInterior_subset : idealTriangleInterior ⊆ idealTriangle := fun z hz ↦
  (mem_idealTriangle_iff z).2 fun i ↦ ((mem_idealTriangleInterior_iff z).1 hz i).le

theorem interior_idealTriangle : interior idealTriangle = idealTriangleInterior := by
  have hT : idealTriangle = ((↑) : ℍ → ℂ) ⁻¹'
      ({w : ℂ | 0 ≤ w.re} ∩ {w | w.re ≤ 1 / 2} ∩ (Metric.ball (1 / 4) (1 / 4))ᶜ) := by
    ext z
    simp [idealTriangle, Complex.dist_eq, and_assoc]
  have hI : idealTriangleInterior = ((↑) : ℍ → ℂ) ⁻¹'
      ({w : ℂ | 0 < w.re} ∩ {w | w.re < 1 / 2} ∩ (Metric.closedBall (1 / 4) (1 / 4))ᶜ) := by
    ext z
    simp [idealTriangleInterior, Complex.dist_eq, and_assoc]
  rw [hT, hI, ← isOpenEmbedding_coe.isOpenMap.preimage_interior_eq_interior_preimage
      continuous_coe, interior_inter, interior_inter, Complex.interior_setOfPred_le_re,
    Complex.interior_setOfPred_re_le, interior_compl, closure_ball _ (by norm_num)]

theorem pos_wallSide_of_wallSide_neg {i j : Fin 3} (hij : i ≠ j) {z : ℍ}
    (hz : wallSide j z < 0) : 0 < wallSide i z := by
  have hy := z.im_pos
  fin_cases i <;> fin_cases j <;>
    simp only [Fin.zero_eta, Fin.mk_one, Fin.reduceFinMk, wallSide_zero, wallSide_one,
      wallSide_two, ne_eq, not_true_eq_false] at hz hij ⊢ <;> nlinarith

theorem wall_disjoint {i j : Fin 3} (hij : i ≠ j) : Disjoint (wall i) (wall j) := by
  rw [Set.disjoint_left]
  intro z hi hj
  rw [mem_wall_iff] at hi hj
  have hy := z.im_pos
  fin_cases i <;> fin_cases j <;>
    simp only [Fin.zero_eta, Fin.mk_one, Fin.reduceFinMk, wallSide_zero, wallSide_one,
      wallSide_two, ne_eq, not_true_eq_false] at hi hj hij <;> nlinarith

def wallMatrix : Fin 3 → Matrix (Fin 2) (Fin 2) ℤ
  | 0 => !![-1, 0; 0, 1]
  | 1 => !![-1, 1; 0, 1]
  | 2 => !![1, 0; 4, -1]

theorem wallMatrix_mul_self (i : Fin 3) : wallMatrix i * wallMatrix i = 1 := by
  fin_cases i <;> simp [wallMatrix, Matrix.one_fin_two]

def wallReflectionInt (i : Fin 3) : GL (Fin 2) ℤ :=
  ⟨wallMatrix i, wallMatrix i, wallMatrix_mul_self i, wallMatrix_mul_self i⟩

def wallReflection (i : Fin 3) : GL (Fin 2) ℝ :=
  GeneralLinearGroup.map (Int.castRingHom ℝ) (wallReflectionInt i)

def triangleGroup : Subgroup (GL (Fin 2) ℝ) :=
  Subgroup.closure (Set.range wallReflection)

theorem wallReflection_apply (i : Fin 3) (a b : Fin 2) :
    wallReflection i a b = wallMatrix i a b := rfl

theorem val_wallReflection_apply (i : Fin 3) (a b : Fin 2) :
    (wallReflection i : Matrix (Fin 2) (Fin 2) ℝ) a b = wallMatrix i a b := rfl

theorem wallReflection_mul_self (i : Fin 3) : wallReflection i * wallReflection i = 1 := by
  rw [wallReflection, ← map_mul]
  convert map_one (GeneralLinearGroup.map (n := Fin 2) (Int.castRingHom ℝ))
  exact Units.ext (wallMatrix_mul_self i)

theorem wallReflection_inv (i : Fin 3) : (wallReflection i)⁻¹ = wallReflection i :=
  inv_eq_of_mul_eq_one_right (wallReflection_mul_self i)

theorem wallReflection_smul_smul (i : Fin 3) (z : ℍ) :
    wallReflection i • wallReflection i • z = z := by
  rw [← mul_smul, wallReflection_mul_self, one_smul]

theorem wallReflection_mem_triangleGroup (i : Fin 3) : wallReflection i ∈ triangleGroup :=
  Subgroup.subset_closure ⟨i, rfl⟩

theorem val_det_wallReflection (i : Fin 3) : (wallReflection i).det.val = -1 := by
  rw [GeneralLinearGroup.val_det_apply, det_fin_two]
  simp only [val_wallReflection_apply]
  fin_cases i <;> simp [wallMatrix]

theorem coe_smul_of_det_neg {g : GL (Fin 2) ℝ} (hg : g.det.val < 0) (z : ℍ) :
    ((g • z : ℍ) : ℂ) = conj (num g z / denom g z) := by
  rw [coe_smul, σ, ite_eq_right_iff.2 fun h ↦ absurd h hg.not_gt]
  rfl

theorem coe_wallReflection_zero_smul (z : ℍ) :
    ((wallReflection 0 • z : ℍ) : ℂ) = -conj (z : ℂ) := by
  rw [coe_smul_of_det_neg (by rw [val_det_wallReflection]; norm_num)]
  simp [num, denom, wallReflection_apply, wallMatrix]

theorem coe_wallReflection_one_smul (z : ℍ) :
    ((wallReflection 1 • z : ℍ) : ℂ) = 1 - conj (z : ℂ) := by
  rw [coe_smul_of_det_neg (by rw [val_det_wallReflection]; norm_num)]
  simp [num, denom, wallReflection_apply, wallMatrix]
  ring

theorem coe_wallReflection_two_smul (z : ℍ) :
    ((wallReflection 2 • z : ℍ) : ℂ) = conj (z : ℂ) / (4 * conj (z : ℂ) - 1) := by
  rw [coe_smul_of_det_neg (by rw [val_det_wallReflection]; norm_num)]
  simp [num, denom, wallReflection_apply, wallMatrix, map_ofNat, sub_eq_add_neg]

theorem re_wallReflection_zero_smul (z : ℍ) : (wallReflection 0 • z).re = -z.re := by
  rw [← coe_re, coe_wallReflection_zero_smul]
  simp

theorem im_wallReflection_zero_smul (z : ℍ) : (wallReflection 0 • z).im = z.im := by
  rw [← coe_im, coe_wallReflection_zero_smul]
  simp

theorem re_wallReflection_one_smul (z : ℍ) : (wallReflection 1 • z).re = 1 - z.re := by
  rw [← coe_re, coe_wallReflection_one_smul]
  simp

theorem im_wallReflection_one_smul (z : ℍ) : (wallReflection 1 • z).im = z.im := by
  rw [← coe_im, coe_wallReflection_one_smul]
  simp

theorem wallReflection_two_denom_eq (z : ℍ) :
    (4 * z.re - 1) ^ 2 + (4 * z.im) ^ 2 = 1 + 16 * wallSide 2 z := by
  rw [wallSide_two]
  ring

theorem wallReflection_two_denom_pos (z : ℍ) : 0 < 1 + 16 * wallSide 2 z := by
  rw [← wallReflection_two_denom_eq]
  have := z.im_pos
  positivity

theorem re_wallReflection_two_smul (z : ℍ) :
    (wallReflection 2 • z).re = (4 * (z.re ^ 2 + z.im ^ 2) - z.re) / (1 + 16 * wallSide 2 z) := by
  rw [← coe_re, coe_wallReflection_two_smul, ← wallReflection_two_denom_eq, Complex.div_re]
  simp [Complex.normSq_apply]
  field_simp
  ring

theorem im_wallReflection_two_smul (z : ℍ) :
    (wallReflection 2 • z).im = z.im / (1 + 16 * wallSide 2 z) := by
  rw [← coe_im, coe_wallReflection_two_smul, ← wallReflection_two_denom_eq, Complex.div_im]
  simp [Complex.normSq_apply]
  field_simp
  ring

theorem wallSide_wallReflection_smul (i : Fin 3) (z : ℍ) :
    ∃ c : ℝ, 0 < c ∧ wallSide i (wallReflection i • z) = -(c * wallSide i z) := by
  fin_cases i
  · refine ⟨1, one_pos, ?_⟩
    simp only [Fin.zero_eta, wallSide_zero, re_wallReflection_zero_smul, one_mul]
  · refine ⟨1, one_pos, ?_⟩
    simp only [Fin.mk_one, wallSide_one, re_wallReflection_one_smul]
    ring
  · have hD := wallReflection_two_denom_pos z
    refine ⟨(1 + 16 * wallSide 2 z)⁻¹, inv_pos.2 hD, ?_⟩
    simp only [Fin.reduceFinMk]
    rw [wallSide_two (wallReflection 2 • z), re_wallReflection_two_smul,
      im_wallReflection_two_smul]
    have key : ∀ x y s D : ℝ, D ≠ 0 → D = 1 + 16 * s → s = x ^ 2 + y ^ 2 - x / 2 →
        ((4 * (x ^ 2 + y ^ 2) - x) / D) ^ 2 + (y / D) ^ 2 - (4 * (x ^ 2 + y ^ 2) - x) / D / 2 =
          -(D⁻¹ * s) := by
      intro x y s D hD hDs hs
      field_simp
      subst hDs hs
      ring
    exact key _ _ _ _ hD.ne' rfl (wallSide_two z)

theorem wallSide_wallReflection_smul_neg_iff (i : Fin 3) (z : ℍ) :
    wallSide i (wallReflection i • z) < 0 ↔ 0 < wallSide i z := by
  obtain ⟨c, hc, h⟩ := wallSide_wallReflection_smul i z
  rw [h, neg_lt_zero]
  exact ⟨fun h ↦ pos_of_mul_pos_right h hc.le, fun h ↦ mul_pos hc h⟩

theorem wallSide_wallReflection_smul_pos_iff (i : Fin 3) (z : ℍ) :
    0 < wallSide i (wallReflection i • z) ↔ wallSide i z < 0 := by
  obtain ⟨c, hc, h⟩ := wallSide_wallReflection_smul i z
  rw [h, neg_pos]
  exact ⟨fun h ↦ neg_of_mul_neg_right h hc.le, fun h ↦ mul_neg_of_pos_of_neg hc h⟩

private theorem ext_of_re_im {z w : ℍ} (hre : z.re = w.re) (him : z.im = w.im) : z = w :=
  UpperHalfPlane.ext (Complex.ext hre him)

theorem wallReflection_smul_of_mem_wall {i : Fin 3} {z : ℍ} (hz : z ∈ wall i) :
    wallReflection i • z = z := by
  rw [mem_wall_iff] at hz
  fin_cases i
  · refine ext_of_re_im ?_ (im_wallReflection_zero_smul z)
    simp only [Fin.zero_eta] at hz ⊢
    rw [re_wallReflection_zero_smul, ← wallSide_zero, hz, neg_zero]
  · refine ext_of_re_im ?_ (im_wallReflection_one_smul z)
    simp only [Fin.mk_one, wallSide_one] at hz ⊢
    rw [re_wallReflection_one_smul]
    linarith
  · simp only [Fin.reduceFinMk] at hz ⊢
    refine ext_of_re_im ?_ ?_
    · rw [re_wallReflection_two_smul, hz]
      rw [wallSide_two] at hz
      simp only [mul_zero, add_zero, div_one]
      linarith
    · rw [im_wallReflection_two_smul, hz]
      simp

theorem isometry_J_smul : Isometry (fun z : ℍ ↦ J • z) := by
  refine Isometry.of_dist_eq fun z w ↦ ?_
  have him : ∀ u : ℍ, (J • u).im = u.im := fun u ↦ by
    rw [← coe_im, coe_J_smul]
    simp
  rw [dist_eq, dist_eq, him, him, coe_J_smul, coe_J_smul, dist_neg_neg, Complex.dist_conj_conj]

theorem isometry_smul_of_det_pos {g : GL (Fin 2) ℝ} (hg : 0 < g.det.val) :
    Isometry (fun z : ℍ ↦ g • z) := by
  set c : ℝ := √(g.det.val) with hc
  have hc0 : 0 < c := Real.sqrt_pos.2 hg
  let h : SL(2, ℝ) := ⟨c⁻¹ • (g : Matrix (Fin 2) (Fin 2) ℝ), by
    rw [det_smul, Fintype.card_fin, ← GeneralLinearGroup.val_det_apply, inv_pow, hc,
      Real.sq_sqrt hg.le, inv_mul_cancel₀ hg.ne']⟩
  have key : (fun z : ℍ ↦ g • z) = fun z ↦ h • z := by
    funext z
    ext1
    have hc' : (c⁻¹ : ℂ) ≠ 0 := by exact_mod_cast (inv_pos.2 hc0).ne'
    rw [coe_smul_of_det_pos hg, coe_specialLinearGroup_apply,
      ← mul_div_mul_left _ _ hc']
    simp [h, num, denom]
    ring
  rw [key]
  exact isometry_smul ℍ h

theorem isometry_glSMul (g : GL (Fin 2) ℝ) : Isometry (fun z : ℍ ↦ g • z) := by
  rcases g.det_ne_zero.lt_or_gt with hg | hg
  · have hJg : 0 < (J * g).det.val := by
      rw [map_mul, Units.val_mul, det_J]
      simp [hg]
    have key : (fun z : ℍ ↦ g • z) = (fun z ↦ J • z) ∘ fun z ↦ (J * g) • z := by
      funext z
      rw [Function.comp_apply, ← mul_smul, ← mul_assoc, ← sq, J_sq, one_mul]
    rw [key]
    exact isometry_J_smul.comp (isometry_smul_of_det_pos hJg)
  · exact isometry_smul_of_det_pos hg

instance glIsIsometricSMul : IsIsometricSMul (GL (Fin 2) ℝ) ℍ :=
  ⟨isometry_glSMul⟩

theorem isometry_wallReflection_smul (i : Fin 3) :
    Isometry (fun z : ℍ ↦ wallReflection i • z) :=
  isometry_glSMul _

theorem triangleGroup_le_range :
    triangleGroup ≤ (GeneralLinearGroup.map (n := Fin 2) (Int.castRingHom ℝ)).range := by
  rw [triangleGroup, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  exact ⟨wallReflectionInt i, rfl⟩

private theorem abs_val_det_map (g : GL (Fin 2) ℤ) :
    |(GeneralLinearGroup.map (Int.castRingHom ℝ) g).det.val| = 1 := by
  rw [GeneralLinearGroup.map_det, Units.coe_map]
  rcases Int.units_eq_one_or (GeneralLinearGroup.det g) with h | h <;> simp [h]

private theorem denom_map (g : GL (Fin 2) ℤ) (z : ℍ) :
    denom (GeneralLinearGroup.map (Int.castRingHom ℝ) g) z =
      ((g 1 0 : ℤ) : ℂ) * z + (g 1 1 : ℤ) := by
  simp [denom]

theorem exists_triangleGroup_max_im (z : ℍ) :
    ∃ w ∈ triangleGroup, ∀ w' ∈ triangleGroup, (w' • z).im ≤ (w • z).im := by
  let s : Set (Fin 2 → ℤ) := {p | ∃ g : GL (Fin 2) ℤ,
    GeneralLinearGroup.map (Int.castRingHom ℝ) g ∈ triangleGroup ∧
      (g : Matrix (Fin 2) (Fin 2) ℤ) 1 = p}
  have hs : s.Nonempty := ⟨_, 1, by simp, rfl⟩
  obtain ⟨p, ⟨g, hg, rfl⟩, hp⟩ :=
    Filter.Tendsto.exists_within_forall_le hs (ModularGroup.tendsto_normSq_coprime_pair z)
  refine ⟨_, hg, fun w' hw' ↦ ?_⟩
  obtain ⟨g', rfl⟩ := triangleGroup_le_range hw'
  have h := hp _ ⟨g', hw', rfl⟩
  rw [im_smul_eq_div_normSq, im_smul_eq_div_normSq, abs_val_det_map, abs_val_det_map, one_mul]
  refine div_le_div_of_nonneg_left z.im_pos.le (normSq_denom_pos _ z.im_ne_zero) ?_
  rw [denom_map, denom_map]
  exact h

theorem wallReflection_one_mul_zero_smul (z : ℍ) :
    (wallReflection 1 * wallReflection 0) • z = (1 : ℝ) +ᵥ z := by
  rw [mul_smul]
  refine ext_of_re_im ?_ ?_
  · rw [re_wallReflection_one_smul, re_wallReflection_zero_smul, vadd_re]
    ring
  · rw [im_wallReflection_one_smul, im_wallReflection_zero_smul, vadd_im]

theorem wallReflection_one_mul_zero_zpow_smul (n : ℤ) (z : ℍ) :
    (wallReflection 1 * wallReflection 0) ^ n • z = (n : ℝ) +ᵥ z := by
  induction n generalizing z with
  | zero => simp
  | succ k ih =>
    rw [zpow_add_one, mul_smul, wallReflection_one_mul_zero_smul, ih, vadd_vadd]
    push_cast
    ring_nf
  | pred k ih =>
    have hinv : (wallReflection 1 * wallReflection 0)⁻¹ • z = (-1 : ℝ) +ᵥ z := by
      rw [inv_smul_eq_iff, wallReflection_one_mul_zero_smul, vadd_vadd]
      norm_num
    rw [zpow_sub_one, mul_smul, hinv, ih, vadd_vadd]
    push_cast
    ring_nf

theorem exists_smul_re_mem (z : ℍ) : ∃ w ∈ triangleGroup,
    0 ≤ (w • z).re ∧ (w • z).re ≤ 1 / 2 ∧ (w • z).im = z.im := by
  have ht : wallReflection 1 * wallReflection 0 ∈ triangleGroup :=
    mul_mem (wallReflection_mem_triangleGroup 1) (wallReflection_mem_triangleGroup 0)
  have hu := wallReflection_one_mul_zero_zpow_smul (-⌊z.re⌋) z
  have hure : ((wallReflection 1 * wallReflection 0) ^ (-⌊z.re⌋) • z).re = Int.fract z.re := by
    rw [hu, vadd_re, Int.fract]
    push_cast
    ring
  have huim : ((wallReflection 1 * wallReflection 0) ^ (-⌊z.re⌋) • z).im = z.im := by
    rw [hu, vadd_im]
  by_cases h : Int.fract z.re ≤ 1 / 2
  · exact ⟨_, zpow_mem ht _, hure ▸ Int.fract_nonneg _, hure ▸ h, huim⟩
  · refine ⟨wallReflection 1 * (wallReflection 1 * wallReflection 0) ^ (-⌊z.re⌋),
      mul_mem (wallReflection_mem_triangleGroup 1) (zpow_mem ht _), ?_, ?_, ?_⟩ <;>
      rw [mul_smul]
    · rw [re_wallReflection_one_smul, hure]
      linarith [Int.fract_lt_one z.re]
    · rw [re_wallReflection_one_smul, hure]
      linarith
    · rw [im_wallReflection_one_smul, huim]

theorem exists_smul_mem_idealTriangle (z : ℍ) : ∃ w ∈ triangleGroup, w • z ∈ idealTriangle := by
  obtain ⟨w₀, hw₀, hmax⟩ := exists_triangleGroup_max_im z
  obtain ⟨w₁, hw₁, h0, h1, him⟩ := exists_smul_re_mem (w₀ • z)
  refine ⟨w₁ * w₀, mul_mem hw₁ hw₀, ?_⟩
  rw [mul_smul]
  refine ⟨h0, h1, (quarter_le_norm_iff _).2 ?_⟩
  by_contra hneg
  push Not at hneg
  have h := hmax (wallReflection 2 * w₁ * w₀)
    (mul_mem (mul_mem (wallReflection_mem_triangleGroup 2) hw₁) hw₀)
  rw [mul_smul, mul_smul, im_wallReflection_two_smul, him,
    div_le_iff₀ (wallReflection_two_denom_pos _)] at h
  nlinarith [(w₀ • z).im_pos]

def wallWord (l : List (Fin 3)) : GL (Fin 2) ℝ :=
  (l.map wallReflection).prod

theorem wallWord_nil : wallWord [] = 1 := rfl

theorem wallWord_cons (i : Fin 3) (l : List (Fin 3)) :
    wallWord (i :: l) = wallReflection i * wallWord l := by
  simp [wallWord]

theorem wallWord_mem_triangleGroup (l : List (Fin 3)) : wallWord l ∈ triangleGroup := by
  induction l with
  | nil => exact triangleGroup.one_mem
  | cons i l ih =>
    rw [wallWord_cons]
    exact mul_mem (wallReflection_mem_triangleGroup i) ih

theorem exists_isChain_wallWord_eq_mul (i : Fin 3) {l : List (Fin 3)}
    (hl : l.IsChain (· ≠ ·)) :
    ∃ l' : List (Fin 3), l'.IsChain (· ≠ ·) ∧ wallWord l' = wallReflection i * wallWord l := by
  cases l with
  | nil => exact ⟨[i], .singleton i, by simp [wallWord]⟩
  | cons j l =>
    by_cases hij : i = j
    · subst hij
      refine ⟨l, hl.of_cons, ?_⟩
      rw [wallWord_cons, ← mul_assoc, wallReflection_mul_self, one_mul]
    · exact ⟨i :: j :: l, List.isChain_cons_cons.2 ⟨hij, hl⟩, wallWord_cons _ _⟩

theorem exists_isChain_wallWord_eq {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup) :
    ∃ l : List (Fin 3), l.IsChain (· ≠ ·) ∧ wallWord l = w := by
  induction hw using Subgroup.closure_induction_left with
  | one => exact ⟨[], .nil, rfl⟩
  | mul_left x hx y _ ih =>
    obtain ⟨i, rfl⟩ := hx
    obtain ⟨l, hl, rfl⟩ := ih
    exact exists_isChain_wallWord_eq_mul i hl
  | inv_mul_cancel x hx y _ ih =>
    obtain ⟨i, rfl⟩ := hx
    obtain ⟨l, hl, rfl⟩ := ih
    rw [wallReflection_inv]
    exact exists_isChain_wallWord_eq_mul i hl

theorem pos_wallSide_of_mem_idealTriangle {i : Fin 3} {z : ℍ} (hz : z ∈ idealTriangle)
    (hzi : z ∉ wall i) : 0 < wallSide i z := by
  rw [mem_wall_iff] at hzi
  exact lt_of_le_of_ne ((mem_idealTriangle_iff z).1 hz i) (Ne.symm hzi)

theorem wallSide_wallWord_smul_neg {z : ℍ} (hz : z ∈ idealTriangle) :
    ∀ (l : List (Fin 3)) (i : Fin 3), (i :: l).IsChain (· ≠ ·) →
      wallSide i (wallWord (i :: l) • z) < 0 ∨ (l = [] ∧ z ∈ wall i)
  | [], i, _ => by
    by_cases h : z ∈ wall i
    · exact Or.inr ⟨rfl, h⟩
    · left
      rw [wallWord_cons, wallWord_nil, mul_one, wallSide_wallReflection_smul_neg_iff]
      exact pos_wallSide_of_mem_idealTriangle hz h
  | j :: l, i, h => by
    rw [List.isChain_cons_cons] at h
    left
    rw [wallWord_cons, mul_smul, wallSide_wallReflection_smul_neg_iff]
    rcases wallSide_wallWord_smul_neg hz l j h.2 with h' | ⟨rfl, hj⟩
    · exact pos_wallSide_of_wallSide_neg h.1 h'
    · rw [wallWord_cons, wallWord_nil, mul_one, wallReflection_smul_of_mem_wall hj]
      exact pos_wallSide_of_mem_idealTriangle hz
        fun hi ↦ Set.disjoint_left.1 (wall_disjoint h.1) hi hj

theorem smul_mem_idealTriangle {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup) {z : ℍ}
    (hz : z ∈ idealTriangle) (hwz : w • z ∈ idealTriangle) :
    w • z = z ∧ (w = 1 ∨ ∃ i, z ∈ wall i ∧ w = wallReflection i) := by
  obtain ⟨l, hl, rfl⟩ := exists_isChain_wallWord_eq hw
  cases l with
  | nil => simp [wallWord_nil]
  | cons i l =>
    rcases wallSide_wallWord_smul_neg hz l i hl with h | ⟨rfl, hi⟩
    · exact absurd ((mem_idealTriangle_iff _).1 hwz i) (not_le.2 h)
    · rw [wallWord_cons, wallWord_nil, mul_one]
      exact ⟨wallReflection_smul_of_mem_wall hi, Or.inr ⟨i, hi, rfl⟩⟩

theorem eq_one_of_smul_mem_idealTriangle {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup) {z : ℍ}
    (hz : z ∈ idealTriangleInterior) (hwz : w • z ∈ idealTriangle) : w = 1 := by
  rcases (smul_mem_idealTriangle hw (idealTriangleInterior_subset hz) hwz).2 with h | ⟨i, hi, -⟩
  · exact h
  · exact absurd ((mem_wall_iff i z).1 hi) ((mem_idealTriangleInterior_iff z).1 hz i).ne'

theorem eq_of_smul_eq_of_mem_idealTriangle {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup)
    {z z' : ℍ} (hz : z ∈ idealTriangle) (hz' : z' ∈ idealTriangle) (h : w • z = z') :
    z = z' := by
  subst h
  exact (smul_mem_idealTriangle hw hz hz').1.symm

theorem neg_one_notMem_triangleGroup : (-1 : GL (Fin 2) ℝ) ∉ triangleGroup := by
  intro h
  have hz : UpperHalfPlane.mk (1 / 4 + Complex.I) (by simp) ∈ idealTriangleInterior := by
    refine ⟨by simp, by norm_num, ?_⟩
    norm_num
  have h1 := eq_one_of_smul_mem_idealTriangle h hz
    (by rw [UpperHalfPlane.neg_smul, one_smul]; exact idealTriangleInterior_subset hz)
  have h00 := congrArg (fun g : GL (Fin 2) ℝ ↦ g 0 0) h1
  norm_num at h00

theorem val_det_wallWord (l : List (Fin 3)) : (wallWord l).det.val = (-1) ^ l.length := by
  induction l with
  | nil => simp [wallWord_nil]
  | cons i l ih =>
    rw [wallWord_cons, map_mul, Units.val_mul, val_det_wallReflection, ih, List.length_cons,
      pow_succ]
    ring

theorem val_det_eq_one_or_of_mem_triangleGroup {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup) :
    w.det.val = 1 ∨ w.det.val = -1 := by
  obtain ⟨l, -, rfl⟩ := exists_isChain_wallWord_eq hw
  rw [val_det_wallWord]
  exact neg_one_pow_eq_or ℝ l.length

def evenTriangleGroup : Subgroup (GL (Fin 2) ℝ) :=
  triangleGroup ⊓ (GeneralLinearGroup.det : GL (Fin 2) ℝ →* ℝˣ).ker

theorem mem_evenTriangleGroup_iff {w : GL (Fin 2) ℝ} :
    w ∈ evenTriangleGroup ↔ w ∈ triangleGroup ∧ w.det.val = 1 := by
  rw [evenTriangleGroup, Subgroup.mem_inf, MonoidHom.mem_ker, Units.ext_iff, Units.val_one]

theorem relIndex_evenTriangleGroup : evenTriangleGroup.relIndex triangleGroup = 2 := by
  rw [Subgroup.relIndex, Subgroup.index_eq_two_iff_exists_notMem_and]
  refine ⟨⟨wallReflection 0, wallReflection_mem_triangleGroup 0⟩, ?_, fun b ↦ ?_⟩
  · rw [Subgroup.mem_subgroupOf, mem_evenTriangleGroup_iff]
    intro h
    have := h.2
    rw [val_det_wallReflection] at this
    norm_num at this
  · simp only [Subgroup.mem_subgroupOf, mem_evenTriangleGroup_iff, Subgroup.coe_mul, map_mul,
      Units.val_mul, val_det_wallReflection]
    rcases val_det_eq_one_or_of_mem_triangleGroup b.2 with h | h
    · exact Or.inr ⟨b.2, h⟩
    · exact Or.inl ⟨mul_mem b.2 (wallReflection_mem_triangleGroup 0), by rw [h]; norm_num⟩

theorem wallReflection_mul_zero_mem_closure (a : Fin 3) :
    wallReflection a * wallReflection 0 ∈ Subgroup.closure
      {wallReflection 1 * wallReflection 0, wallReflection 2 * wallReflection 0} := by
  fin_cases a
  · simp only [Fin.zero_eta, wallReflection_mul_self]
    exact Subgroup.one_mem _
  · exact Subgroup.subset_closure (Set.mem_insert _ _)
  · exact Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)

theorem wallWord_mem_closure : ∀ l : List (Fin 3), Even l.length →
    wallWord l ∈ Subgroup.closure
      {wallReflection 1 * wallReflection 0, wallReflection 2 * wallReflection 0}
  | [], _ => Subgroup.one_mem _
  | [_], h => absurd h (by simp)
  | a :: b :: l, h => by
    have hl : Even l.length := by
      simpa [List.length_cons, Nat.even_add_one] using h
    have hab : wallReflection a * wallReflection b =
        (wallReflection a * wallReflection 0) * (wallReflection b * wallReflection 0)⁻¹ := by
      rw [_root_.mul_inv_rev, wallReflection_inv, wallReflection_inv, mul_assoc,
        ← mul_assoc (wallReflection 0), wallReflection_mul_self, one_mul]
    rw [wallWord_cons, wallWord_cons, ← mul_assoc, hab]
    exact mul_mem (mul_mem (wallReflection_mul_zero_mem_closure a)
      (inv_mem (wallReflection_mul_zero_mem_closure b))) (wallWord_mem_closure l hl)

theorem evenTriangleGroup_eq_closure : evenTriangleGroup = Subgroup.closure
    {wallReflection 1 * wallReflection 0, wallReflection 2 * wallReflection 0} := by
  refine le_antisymm (fun w hw ↦ ?_) ?_
  · rw [mem_evenTriangleGroup_iff] at hw
    obtain ⟨l, -, rfl⟩ := exists_isChain_wallWord_eq hw.1
    refine wallWord_mem_closure l ?_
    rw [val_det_wallWord, neg_one_pow_eq_one_iff_even (by norm_num)] at hw
    exact hw.2
  · rw [Subgroup.closure_le]
    rintro _ (rfl | rfl) <;> rw [SetLike.mem_coe, mem_evenTriangleGroup_iff] <;>
      refine ⟨mul_mem (wallReflection_mem_triangleGroup _)
        (wallReflection_mem_triangleGroup 0), ?_⟩ <;>
      rw [map_mul, Units.val_mul, val_det_wallReflection, val_det_wallReflection] <;> norm_num

def triangleU₄ : SL(2, ℤ) :=
  ⟨!![1, 0; 4, 1], by simp [det_fin_two]⟩

theorem wallReflection_one_mul_zero_smul_eq (z : ℍ) :
    (wallReflection 1 * wallReflection 0) • z = ModularGroup.T • z := by
  rw [wallReflection_one_mul_zero_smul, modular_T_smul]

theorem wallReflection_two_mul_zero_smul_eq (z : ℍ) :
    (wallReflection 2 * wallReflection 0) • z =
      triangleU₄ • z := by
  ext1
  rw [mul_smul, coe_wallReflection_two_smul, coe_wallReflection_zero_smul,
    coe_specialLinearGroup_apply]
  simp only [map_neg, Complex.conj_conj, triangleU₄]
  rw [show (4 : ℂ) * -(z : ℂ) - 1 = -(4 * z + 1) by ring, neg_div_neg_eq]
  simp

theorem exists_mem_closure_smul_eq_of_det_eq_one {w : GL (Fin 2) ℝ}
    (hw : w ∈ triangleGroup) (hdet : w.det = 1) :
    ∃ γ ∈ Subgroup.closure
      {ModularGroup.T, triangleU₄},
      ∀ z : ℍ, w • z = γ • z := by
  have hw' : w ∈ evenTriangleGroup :=
    mem_evenTriangleGroup_iff.2 ⟨hw, by rw [hdet, Units.val_one]⟩
  rw [evenTriangleGroup_eq_closure] at hw'
  clear hw hdet
  induction hw' using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨_, Subgroup.subset_closure (Set.mem_insert _ _),
        wallReflection_one_mul_zero_smul_eq⟩
    · exact ⟨_, Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl),
        wallReflection_two_mul_zero_smul_eq⟩
  | one => exact ⟨1, Subgroup.one_mem _, fun z ↦ by rw [one_smul, one_smul]⟩
  | mul x y _ _ hx hy =>
    obtain ⟨γ, hγ, hxγ⟩ := hx
    obtain ⟨δ, hδ, hyδ⟩ := hy
    exact ⟨γ * δ, mul_mem hγ hδ, fun z ↦ by rw [mul_smul, mul_smul, hyδ, hxγ]⟩
  | inv x _ hx =>
    obtain ⟨γ, hγ, hxγ⟩ := hx
    refine ⟨γ⁻¹, inv_mem hγ, fun z ↦ ?_⟩
    rw [inv_smul_eq_iff, hxγ, smul_inv_smul]

end GC.Seifert
