import DifferentialGeometry.Topology.ThreeManifold.GraphManifold.Seifert.PantsGeometry
import DifferentialGeometry.Topology.ThreeManifold.GraphManifold.Seifert.IdealTriangle

/-!
# A fundamental domain for the pants group

Packet K16d, tier 1. Lane H2's `evenTriangleGroup`, the orientation-preserving half of the
reflection group of the ideal triangle `(0, 1/2, ∞)`, is generated by `σ₁ σ₀` and `σ₂ σ₀`,
acting as `T` and `U₄`; since `triangleU₄` is `pantsU₄`, `pantsGroup` is that closure
(`pantsGroup_eq_closure`) and every element of either group acts as an element of the other
(`exists_pantsGroup_smul_eq`, `exists_triangleGroup_smul_eq`). Hence `pantsDomain`, the ideal
triangle together with its mirror image `σ₀ • idealTriangle` in `Re z = 0`, meets every orbit
(`exists_pantsGroup_smul_mem_pantsDomain`). An element of `pantsGroup` mapping a point of either
triangle into the same triangle is `1` (`eq_one_of_mem_pantsGroup_of_smul_mem_idealTriangle`,
`eq_one_of_mem_pantsGroup_of_smul_mem_reflected`; `Γ₁(4)` acts freely), and a point of the
triangle sent into the mirror triangle lies on a wall and is sent to its mirror image
`σ₀ • z` (`mem_wall_of_smul_mem_reflected`). So `Re z = 0` is interior to the domain, `T⁻¹`
identifies `Re z = 1/2` with `Re z = -1/2` (`modularT_inv_smul_of_mem_wall_one`) and `U₄⁻¹`
identifies `|z - 1/4| = 1/4` with `|z + 1/4| = 1/4` (`pantsU₄_inv_smul_of_mem_wall_two`).
-/

set_option autoImplicit false

noncomputable section

open UpperHalfPlane Matrix
open scoped MatrixGroups

namespace GC.Seifert

theorem pantsU₄_eq_triangleU₄ : pantsU₄ = triangleU₄ :=
  rfl

theorem pantsGroup_eq_closure : pantsGroup = Subgroup.closure {ModularGroup.T, triangleU₄} :=
  rfl

theorem det_wallReflection_mul_zero (i : Fin 3) : (wallReflection i * wallReflection 0).det = 1 :=
  Units.ext (by rw [map_mul, Units.val_mul, val_det_wallReflection, val_det_wallReflection,
    Units.val_one]; norm_num)

theorem exists_pantsGroup_smul_eq {w : GL (Fin 2) ℝ} (hw : w ∈ triangleGroup) (hdet : w.det = 1) :
    ∃ γ ∈ pantsGroup, ∀ z : ℍ, w • z = γ • z :=
  exists_mem_closure_smul_eq_of_det_eq_one hw hdet

theorem exists_triangleGroup_smul_eq {γ : SL(2, ℤ)} (hγ : γ ∈ pantsGroup) :
    ∃ w ∈ triangleGroup, w.det = 1 ∧ ∀ z : ℍ, γ • z = w • z := by
  induction hγ using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨_, mul_mem (wallReflection_mem_triangleGroup 1) (wallReflection_mem_triangleGroup 0),
        det_wallReflection_mul_zero 1, fun z => (wallReflection_one_mul_zero_smul_eq z).symm⟩
    · exact ⟨_, mul_mem (wallReflection_mem_triangleGroup 2) (wallReflection_mem_triangleGroup 0),
        det_wallReflection_mul_zero 2, fun z => (wallReflection_two_mul_zero_smul_eq z).symm⟩
  | one => exact ⟨1, Subgroup.one_mem _, map_one _, fun z => by rw [one_smul, one_smul]⟩
  | mul x y _ _ hx hy =>
    obtain ⟨w, hw, hdw, hxw⟩ := hx
    obtain ⟨v, hv, hdv, hyv⟩ := hy
    exact ⟨w * v, mul_mem hw hv, by rw [map_mul, hdw, hdv, one_mul],
      fun z => by rw [mul_smul, mul_smul, hyv, hxw]⟩
  | inv x _ hx =>
    obtain ⟨w, hw, hdw, hxw⟩ := hx
    exact ⟨w⁻¹, inv_mem hw, by rw [map_inv, hdw, inv_one],
      fun z => by rw [inv_smul_eq_iff, hxw, smul_inv_smul]⟩

def pantsDomain : Set ℍ :=
  idealTriangle ∪ (fun z : ℍ => wallReflection 0 • z) '' idealTriangle

theorem exists_pantsGroup_smul_mem_pantsDomain (z : ℍ) :
    ∃ γ ∈ pantsGroup, γ • z ∈ pantsDomain := by
  obtain ⟨w, hw, hwz⟩ := exists_smul_mem_idealTriangle z
  rcases val_det_eq_one_or_of_mem_triangleGroup hw with h | h
  · obtain ⟨γ, hγ, hγw⟩ := exists_pantsGroup_smul_eq hw (Units.val_eq_one.mp h)
    exact ⟨γ, hγ, Or.inl (by rw [← hγw]; exact hwz)⟩
  · obtain ⟨γ, hγ, hγw⟩ := exists_pantsGroup_smul_eq
      (mul_mem (wallReflection_mem_triangleGroup 0) hw)
      (Units.ext (by
        rw [map_mul, Units.val_mul, val_det_wallReflection, h, Units.val_one]; norm_num))
    exact ⟨γ, hγ, Or.inr ⟨w • z, hwz, by rw [← hγw, mul_smul]⟩⟩

theorem eq_one_of_mem_pantsGroup_of_smul_mem_idealTriangle {γ : SL(2, ℤ)} (hγ : γ ∈ pantsGroup)
    {z : ℍ} (hz : z ∈ idealTriangle) (hγz : γ • z ∈ idealTriangle) : γ = 1 := by
  obtain ⟨w, hw, -, hγw⟩ := exists_triangleGroup_smul_eq hγ
  rw [hγw] at hγz
  exact gamma1_four_free (pantsGroup_le_gamma1 hγ)
    (by rw [hγw]; exact (smul_mem_idealTriangle hw hz hγz).1)

theorem eq_one_of_mem_pantsGroup_of_smul_mem_reflected {γ : SL(2, ℤ)} (hγ : γ ∈ pantsGroup)
    {z : ℍ} (hz : wallReflection 0 • z ∈ idealTriangle)
    (hγz : wallReflection 0 • γ • z ∈ idealTriangle) : γ = 1 := by
  obtain ⟨w, hw, -, hγw⟩ := exists_triangleGroup_smul_eq hγ
  have hw' : wallReflection 0 * w * wallReflection 0 ∈ triangleGroup :=
    mul_mem (mul_mem (wallReflection_mem_triangleGroup 0) hw) (wallReflection_mem_triangleGroup 0)
  have h := (smul_mem_idealTriangle hw' hz (by
    rw [mul_smul, mul_smul, wallReflection_smul_smul, ← hγw]; exact hγz)).1
  rw [mul_smul, mul_smul, wallReflection_smul_smul] at h
  refine gamma1_four_free (pantsGroup_le_gamma1 hγ) (z := z) ?_
  have h' := congrArg (fun u : ℍ => wallReflection 0 • u) h
  simp only [wallReflection_smul_smul] at h'
  rw [hγw]
  exact h'

theorem mem_wall_of_smul_mem_reflected {γ : SL(2, ℤ)} (hγ : γ ∈ pantsGroup) {z : ℍ}
    (hz : z ∈ idealTriangle) (hγz : wallReflection 0 • γ • z ∈ idealTriangle) :
    ∃ i, z ∈ wall i ∧ γ • z = wallReflection 0 • z := by
  obtain ⟨w, hw, hdet, hγw⟩ := exists_triangleGroup_smul_eq hγ
  have hw' : wallReflection 0 * w ∈ triangleGroup :=
    mul_mem (wallReflection_mem_triangleGroup 0) hw
  obtain ⟨h1, h2⟩ := smul_mem_idealTriangle hw' hz (by rw [mul_smul, ← hγw]; exact hγz)
  rcases h2 with h2 | ⟨i, hi, h2⟩
  · exfalso
    have := congrArg (fun g : GL (Fin 2) ℝ => g.det.val) h2
    simp only [map_mul, Units.val_mul, val_det_wallReflection, hdet, Units.val_one] at this
    norm_num at this
  · refine ⟨i, hi, ?_⟩
    rw [mul_smul, ← hγw] at h1
    have h' := congrArg (fun u : ℍ => wallReflection 0 • u) h1
    simpa only [wallReflection_smul_smul] using h'

theorem modularT_inv_smul_of_mem_wall_one {z : ℍ} (hz : z ∈ wall 1) :
    ModularGroup.T⁻¹ • z = wallReflection 0 • z := by
  rw [inv_smul_eq_iff, ← wallReflection_one_mul_zero_smul_eq, mul_smul, wallReflection_smul_smul,
    wallReflection_smul_of_mem_wall hz]

theorem pantsU₄_inv_smul_of_mem_wall_two {z : ℍ} (hz : z ∈ wall 2) :
    pantsU₄⁻¹ • z = wallReflection 0 • z := by
  rw [inv_smul_eq_iff, pantsU₄_eq_triangleU₄, ← wallReflection_two_mul_zero_smul_eq, mul_smul,
    wallReflection_smul_smul, wallReflection_smul_of_mem_wall hz]

end GC.Seifert
