import DifferentialGeometry.Topology.ThreeManifold.GraphManifold.Seifert.SaddleSlabUniqueness
import DifferentialGeometry.Topology.Manifold.Quotient
import DifferentialGeometry.Topology.Morse.Hessian
import DifferentialGeometry.Topology.Manifold.Orientation.SurfaceFrame

/-!
# Model slabs for one-saddle slabs with a connected lower level

Lane MD3 (shared core of the orientable incidence lemma and of T5). The open Möbius band
`MobiusBand` is the quotient of `ℝ × ℝ` by the group generated by `(θ, y) ↦ (θ + π, -y)`
(`mobiusTwistPerm`, `mobiusDeckGroup`), a free properly discontinuous smooth action, so it is a
boundaryless surface modelled on `ℝ × ℝ` and `mobiusProj` is a local diffeomorphism. The model
function `mobiusHeight [θ, y] = y² + cos 2θ` has a nondegenerate saddle of index one at
`mobiusSaddle = [0, 0]` (value `1`) and a minimum at `[π / 2, 0]` (value `-1`); on the slab
`mobiusHeight ⁻¹' [0, 2]` the saddle is the only critical point, the levels `0` and `2` are
regular and connected, and the slab is compact and connected (`mobiusSlabParam` parametrises it
by `[0, 2π] × [0, 1]`). Critical points, nondegeneracy and index pass through local
diffeomorphisms (`isCriticalPointAt_comp_localDiffeomorph_iff`,
`isNondegenerateCriticalPointAt_comp_localDiffeomorph_iff`,
`sigNeg_chartHessianAt_comp_localDiffeomorph`). The band is not orientable along the critical
level: no oriented surface admits a map from `MobiusBand` that is a local diffeomorphism at every
point of `mobiusHeight ⁻¹' {1}` (`SurfaceOrientation.not_mobius_localDiffeomorph`); the loop
`t ↦ [t, √2 sin t]`, `t ∈ [0, π]`, carries the coordinate frame to its reflection.
-/

set_option autoImplicit false

noncomputable section
open Set Function
open scoped Manifold ContDiff Topology

namespace GC.Seifert

def mobiusTwistPerm : Equiv.Perm (ℝ × ℝ) where
  toFun p := (p.1 + Real.pi, -p.2)
  invFun p := (p.1 - Real.pi, -p.2)
  left_inv p := by simp
  right_inv p := by simp

theorem mobiusTwistPerm_inv_apply (p : ℝ × ℝ) :
    mobiusTwistPerm⁻¹ p = (p.1 - Real.pi, -p.2) := rfl

theorem mobiusTwistPerm_apply (p : ℝ × ℝ) : mobiusTwistPerm p = (p.1 + Real.pi, -p.2) := rfl

theorem mobiusTwistPerm_zpow_apply (n : ℤ) (p : ℝ × ℝ) :
    (mobiusTwistPerm ^ n) p = (p.1 + n * Real.pi, (-1) ^ n * p.2) := by
  induction n using Int.induction_on generalizing p with
  | zero => simp
  | succ k ih =>
    rw [zpow_add_one, Equiv.Perm.mul_apply, ih, mobiusTwistPerm_apply]
    ext
    · push_cast
      ring
    · change (-1 : ℝ) ^ (k : ℤ) * -p.2 = (-1) ^ ((k : ℤ) + 1) * p.2
      rw [zpow_add_one₀ (by norm_num)]
      ring
  | pred k ih =>
    rw [zpow_sub_one, Equiv.Perm.mul_apply, ih, mobiusTwistPerm_inv_apply]
    ext
    · push_cast
      ring
    · change (-1 : ℝ) ^ (-(k : ℤ)) * -p.2 = (-1) ^ (-(k : ℤ) - 1) * p.2
      rw [zpow_sub_one₀ (by norm_num)]
      have h : ((-1 : ℝ))⁻¹ = -1 := by norm_num
      rw [h]
      ring

def mobiusDeckGroup : Subgroup (Equiv.Perm (ℝ × ℝ)) := Subgroup.zpowers mobiusTwistPerm

theorem mobiusDeckGroup_smul (g : mobiusDeckGroup) :
    ∃ n : ℤ, ∀ p : ℝ × ℝ, g • p = (p.1 + n * Real.pi, (-1) ^ n * p.2) := by
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp g.2
  refine ⟨n, fun p => ?_⟩
  change g.1 p = _
  rw [← hn, mobiusTwistPerm_zpow_apply]

def mobiusZ (n : ℤ) : mobiusDeckGroup := ⟨mobiusTwistPerm ^ n, Subgroup.zpow_mem_zpowers _ n⟩

theorem mobiusZ_smul (n : ℤ) (p : ℝ × ℝ) :
    mobiusZ n • p = (p.1 + n * Real.pi, (-1) ^ n * p.2) :=
  mobiusTwistPerm_zpow_apply n p

theorem mobiusZ_surjective : Surjective mobiusZ := by
  intro g
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp g.2
  exact ⟨n, Subtype.ext hn⟩

theorem contDiff_mobiusZ_smul (n : ℤ) : ContDiff ℝ ∞ (fun p : ℝ × ℝ => mobiusZ n • p) := by
  simp only [mobiusZ_smul]
  exact (contDiff_fst.add contDiff_const).prodMk (contDiff_const.mul contDiff_snd)

instance : ContinuousConstSMul mobiusDeckGroup (ℝ × ℝ) where
  continuous_const_smul g := by
    obtain ⟨n, rfl⟩ := mobiusZ_surjective g
    exact (contDiff_mobiusZ_smul n).continuous

instance : ContMDiffConstSMul 𝓘(ℝ, ℝ × ℝ) ∞ mobiusDeckGroup (ℝ × ℝ) where
  contMDiff_const_smul g := by
    obtain ⟨n, rfl⟩ := mobiusZ_surjective g
    exact (contDiff_mobiusZ_smul n).contMDiff

instance : IsCancelSMul mobiusDeckGroup (ℝ × ℝ) := by
  rw [isCancelSMul_iff_eq_one_of_smul_eq]
  intro g p hg
  obtain ⟨n, rfl⟩ := mobiusZ_surjective g
  rw [mobiusZ_smul] at hg
  have h1 := congrArg Prod.fst hg
  simp only at h1
  have hn : (n : ℝ) * Real.pi = 0 := by linarith
  have hn0 : n = 0 := by
    rcases mul_eq_zero.mp hn with h | h
    · exact_mod_cast h
    · exact absurd h Real.pi_ne_zero
  subst hn0
  apply Subtype.ext
  change mobiusTwistPerm ^ (0 : ℤ) = 1
  simp

theorem exists_bound_of_isCompact {K : Set (ℝ × ℝ)} (hK : IsCompact K) :
    ∃ R : ℝ, ∀ p ∈ K, |p.1| ≤ R := by
  obtain ⟨R, hR⟩ := (hK.image continuous_fst).isBounded.subset_closedBall 0
  refine ⟨R, fun p hp => ?_⟩
  have h := hR (mem_image_of_mem Prod.fst hp)
  rwa [Metric.mem_closedBall, Real.dist_eq, sub_zero] at h

instance : ProperlyDiscontinuousSMul mobiusDeckGroup (ℝ × ℝ) where
  finite_disjoint_inter_image {K L} hK hL := by
    obtain ⟨R, hR⟩ := exists_bound_of_isCompact (hK.union hL)
    obtain ⟨N, hN⟩ := exists_nat_gt (2 * R / Real.pi)
    refine ((Finset.Icc (-(N : ℤ)) N).finite_toSet.image mobiusZ).subset ?_
    intro g hg
    obtain ⟨n, rfl⟩ := mobiusZ_surjective g
    obtain ⟨z, ⟨k, hk, rfl⟩, hkL⟩ := hg
    have h1 := hR k (Or.inl hk)
    have h2 : |(mobiusZ n • k).1| ≤ R := hR _ (Or.inr hkL)
    rw [mobiusZ_smul] at h2
    have hnπ : |(n : ℝ) * Real.pi| ≤ 2 * R := by
      have : (n : ℝ) * Real.pi = (k.1 + n * Real.pi) - k.1 := by ring
      rw [this]
      exact (abs_sub _ _).trans (by linarith)
    have hn : |(n : ℝ)| < N := by
      rw [abs_mul, abs_of_pos Real.pi_pos] at hnπ
      have h3 : |(n : ℝ)| ≤ 2 * R / Real.pi := by
        rw [le_div_iff₀ Real.pi_pos]
        exact hnπ
      exact h3.trans_lt hN
    refine ⟨n, ?_, rfl⟩
    rw [Finset.coe_Icc, Set.mem_Icc]
    have h4 := abs_lt.mp hn
    constructor <;> [exact_mod_cast h4.1.le; exact_mod_cast h4.2.le]

abbrev MobiusBand : Type := MulAction.orbitRel.Quotient mobiusDeckGroup (ℝ × ℝ)

def mobiusProj : ℝ × ℝ → MobiusBand := Quotient.mk _

theorem isLocalDiffeomorph_mobiusProj :
    IsLocalDiffeomorph 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ × ℝ) ∞ mobiusProj :=
  MulAction.isLocalDiffeomorph_quotientMk_of_properlyDiscontinuousSMul 𝓘(ℝ, ℝ × ℝ)

def mobiusHeightLift (p : ℝ × ℝ) : ℝ := p.2 ^ 2 + Real.cos (2 * p.1)

theorem mobiusHeightLift_smul (g : mobiusDeckGroup) (p : ℝ × ℝ) :
    mobiusHeightLift (g • p) = mobiusHeightLift p := by
  obtain ⟨n, rfl⟩ := mobiusZ_surjective g
  rw [mobiusZ_smul]
  simp only [mobiusHeightLift]
  have h1 : ((-1 : ℝ) ^ n * p.2) ^ 2 = p.2 ^ 2 := by
    have hsq : ((-1 : ℝ) ^ n) ^ 2 = 1 := by
      rw [← zpow_natCast, ← zpow_mul, mul_comm, zpow_mul]
      norm_num
    rw [mul_pow, hsq, one_mul]
  have h2 : Real.cos (2 * (p.1 + n * Real.pi)) = Real.cos (2 * p.1) := by
    have : 2 * (p.1 + n * Real.pi) = 2 * p.1 + ((n : ℤ) : ℝ) * (2 * Real.pi) := by ring
    rw [this, Real.cos_add_int_mul_two_pi]
  rw [h1, h2]

def mobiusHeight : MobiusBand → ℝ :=
  Quotient.lift mobiusHeightLift fun a b hab => by
    obtain ⟨g, hg⟩ := MulAction.mem_orbit_iff.mp (MulAction.orbitRel_apply.mp hab)
    rw [← hg, mobiusHeightLift_smul]

theorem mobiusHeight_mk (p : ℝ × ℝ) : mobiusHeight (mobiusProj p) = mobiusHeightLift p := rfl

theorem mobiusProj_surjective : Surjective mobiusProj := Quotient.mk_surjective

theorem contDiff_mobiusHeightLift : ContDiff ℝ ∞ mobiusHeightLift :=
  (contDiff_snd.pow 2).add (Real.contDiff_cos.comp (contDiff_const.mul contDiff_fst))

theorem contMDiff_mobiusHeight : ContMDiff 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ) ∞ mobiusHeight :=
  isLocalDiffeomorph_mobiusProj.contMDiff_of_comp_of_surjective mobiusProj_surjective
    contDiff_mobiusHeightLift.contMDiff

theorem hasFDerivAt_mobiusHeightLift (p : ℝ × ℝ) :
    HasFDerivAt mobiusHeightLift
      ((-(2 * Real.sin (2 * p.1))) • ContinuousLinearMap.fst ℝ ℝ ℝ +
        (2 * p.2) • ContinuousLinearMap.snd ℝ ℝ ℝ) p := by
  have h1 : HasFDerivAt (fun q : ℝ × ℝ => q.2 ^ 2)
      ((2 * p.2) • ContinuousLinearMap.snd ℝ ℝ ℝ) p := by
    have hs : HasFDerivAt (fun q : ℝ × ℝ => q.2) (ContinuousLinearMap.snd ℝ ℝ ℝ) p :=
      hasFDerivAt_snd
    have := hs.pow 2
    convert this using 1
    simp
  have h2 : HasFDerivAt (fun q : ℝ × ℝ => Real.cos (2 * q.1))
      ((-(2 * Real.sin (2 * p.1))) • ContinuousLinearMap.fst ℝ ℝ ℝ) p := by
    have := ((hasFDerivAt_fst (p := p)).const_mul 2).cos
    convert this using 1
    ext <;> simp; ring
  exact h1.add h2 |>.congr_fderiv (add_comm _ _)

theorem fderiv_mobiusHeightLift :
    fderiv ℝ mobiusHeightLift = fun p =>
      (-(2 * Real.sin (2 * p.1))) • ContinuousLinearMap.fst ℝ ℝ ℝ +
        (2 * p.2) • ContinuousLinearMap.snd ℝ ℝ ℝ :=
  funext fun p => (hasFDerivAt_mobiusHeightLift p).fderiv

theorem fderiv_mobiusHeightLift_eq_zero_iff (p : ℝ × ℝ) :
    fderiv ℝ mobiusHeightLift p = 0 ↔ Real.sin (2 * p.1) = 0 ∧ p.2 = 0 := by
  rw [fderiv_mobiusHeightLift]
  constructor
  · intro h
    have h1 : -(2 * Real.sin (2 * p.1)) = 0 := by
      simpa using congrArg (fun L : ℝ × ℝ →L[ℝ] ℝ => L (1, 0)) h
    have h2 : 2 * p.2 = 0 := by
      simpa using congrArg (fun L : ℝ × ℝ →L[ℝ] ℝ => L (0, 1)) h
    exact ⟨by linarith, by linarith⟩
  · rintro ⟨h1, h2⟩
    ext <;> simp [h1, h2]

section LocalTransfer

open DifferentialGeometry.Topology DifferentialGeometry.Topology.Morse

variable {E F : Type} [NormedAddCommGroup E] [NormedSpace ℝ E] [NormedAddCommGroup F]
  [NormedSpace ℝ F] {H H' : Type} [TopologicalSpace H] [TopologicalSpace H']
  {I : ModelWithCorners ℝ E H} {J : ModelWithCorners ℝ F H'} [I.Boundaryless] [J.Boundaryless]
  {M N : Type} [TopologicalSpace M] [ChartedSpace H M] [TopologicalSpace N] [ChartedSpace H' N]

omit [I.Boundaryless] [J.Boundaryless] in
theorem isCriticalPointAt_comp_localDiffeomorph_iff {φ : M → N} {f : N → ℝ} {x : M}
    (hφ : IsLocalDiffeomorphAt I J ∞ φ x) (hf : MDifferentiableAt J 𝓘(ℝ, ℝ) f (φ x)) :
    IsCriticalPointAt I (f ∘ φ) x ↔ IsCriticalPointAt J f (φ x) := by
  unfold IsCriticalPointAt
  rw [mfderiv_comp x hf (hφ.mdifferentiableAt (by simp))]
  set L := hφ.mfderivToContinuousLinearEquiv (by simp)
  have hL : mfderiv I J φ x = (L : TangentSpace I x →L[ℝ] TangentSpace J (φ x)) := rfl
  rw [hL]
  constructor
  · intro h
    ext v
    have h' := congrArg (fun T : TangentSpace I x →L[ℝ] ℝ => T (L.symm v)) h
    have h'' : mfderiv J 𝓘(ℝ, ℝ) f (φ x) (L (L.symm v)) = 0 := h'
    rwa [L.apply_symm_apply v] at h''
  · intro h
    rw [h]
    rfl

theorem chartHessianAt_comp_localDiffeomorph {φ : M → N} {f : N → ℝ} {x : M}
    (hφ : IsLocalDiffeomorphAt I J ∞ φ x) (hf : ContMDiffAt J 𝓘(ℝ, ℝ) 2 f (φ x))
    (hcrit : IsCriticalPointAt J f (φ x)) :
    chartHessianAt (fun z => f (φ ((extChartAt I x).symm z))) (extChartAt I x x) =
      (chartHessianAt (fun z => f ((extChartAt J (φ x)).symm z))
        (extChartAt J (φ x) (φ x))).comp (mfderiv I J φ x).toLinearMap :=
  chartHessianAt_comp_mfderiv (hφ.contMDiffAt.of_le (by norm_cast)) hf hcrit

theorem isNondegenerateCriticalPointAt_comp_localDiffeomorph_iff {φ : M → N} {f : N → ℝ}
    {x : M} (hφ : IsLocalDiffeomorphAt I J ∞ φ x) (hf : ContMDiffAt J 𝓘(ℝ, ℝ) 2 f (φ x)) :
    IsNondegenerateCriticalPointAt I (f ∘ φ) x ↔ IsNondegenerateCriticalPointAt J f (φ x) := by
  have hc := isCriticalPointAt_comp_localDiffeomorph_iff hφ (hf.mdifferentiableAt (by norm_num))
  by_cases hcrit : IsCriticalPointAt J f (φ x)
  · simp only [IsNondegenerateCriticalPointAt, hc, hcrit, true_and]
    simp only [Function.comp_apply]
    rw [chartHessianAt_comp_localDiffeomorph hφ hf hcrit]
    let L : E ≃ₗ[ℝ] F := (hφ.mfderivToContinuousLinearEquiv (by simp)).toLinearEquiv
    let Q := chartHessianAt (fun y => f ((extChartAt J (φ x)).symm y))
      (extChartAt J (φ x) (φ x))
    change (QuadraticMap.associated (Q.comp L.toLinearMap)).SeparatingLeft ↔
      (QuadraticMap.associated Q).SeparatingLeft
    have hB : QuadraticMap.associated (Q.comp L.toLinearMap) =
        (L.symm.arrowCongr (L.symm.arrowCongr (LinearEquiv.refl ℝ ℝ)))
          (QuadraticMap.associated Q) := by
      ext u v
      simp [QuadraticMap.associated_apply]
    rw [hB]
    exact LinearMap.separatingLeft_congr_iff L.symm L.symm
  · simp only [IsNondegenerateCriticalPointAt, hc, hcrit, false_and]

theorem sigNeg_chartHessianAt_comp_localDiffeomorph {φ : M → N} {f : N → ℝ} {x : M}
    (hφ : IsLocalDiffeomorphAt I J ∞ φ x) (hf : ContMDiffAt J 𝓘(ℝ, ℝ) 2 f (φ x))
    (hcrit : IsCriticalPointAt J f (φ x)) :
    _root_.sigNeg (chartHessianAt (fun z => f (φ ((extChartAt I x).symm z)))
      (extChartAt I x x)) =
      _root_.sigNeg (chartHessianAt (fun z => f ((extChartAt J (φ x)).symm z))
        (extChartAt J (φ x) (φ x))) := by
  apply QuadraticMap.Equivalent.sigNeg_eq
  refine ⟨{ (hφ.mfderivToContinuousLinearEquiv (by simp)).toLinearEquiv with
    map_app' := ?_ }⟩
  intro v
  rw [chartHessianAt_comp_localDiffeomorph hφ hf hcrit]
  rfl

end LocalTransfer

section MobiusMorse

open DifferentialGeometry.Topology DifferentialGeometry.Topology.Morse

def mobiusSaddle : MobiusBand := mobiusProj (0, 0)

theorem isCriticalPointAt_mobiusHeight_mk_iff (m : ℝ × ℝ) :
    IsCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeight (mobiusProj m) ↔
      Real.sin (2 * m.1) = 0 ∧ m.2 = 0 := by
  rw [← isCriticalPointAt_comp_localDiffeomorph_iff (isLocalDiffeomorph_mobiusProj m)
    (contMDiff_mobiusHeight.mdifferentiableAt (by simp))]
  have h : mobiusHeight ∘ mobiusProj = mobiusHeightLift := rfl
  rw [h, IsCriticalPointAt, mfderiv_eq_fderiv]
  exact fderiv_mobiusHeightLift_eq_zero_iff m

theorem mobiusHeight_of_isCriticalPointAt {x : MobiusBand}
    (hx : IsCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeight x) :
    mobiusHeight x = 1 ∨ mobiusHeight x = -1 := by
  obtain ⟨m, rfl⟩ := mobiusProj_surjective x
  obtain ⟨h1, h2⟩ := (isCriticalPointAt_mobiusHeight_mk_iff m).mp hx
  rw [mobiusHeight_mk, mobiusHeightLift, h2]
  have hc := Real.sin_sq_add_cos_sq (2 * m.1)
  rw [h1] at hc
  have hsq : Real.cos (2 * m.1) ^ 2 = 1 := by linarith
  have h0 : (0 : ℝ) ^ 2 + Real.cos (2 * m.1) = Real.cos (2 * m.1) := by ring
  rw [h0]
  exact sq_eq_one_iff.mp hsq

theorem mobiusHeight_regular_endpoints :
    ∀ x : MobiusBand, mobiusHeight x = 0 ∨ mobiusHeight x = 2 →
      mfderiv 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ) mobiusHeight x ≠ 0 := by
  intro x hx hcrit
  rcases mobiusHeight_of_isCriticalPointAt hcrit with h | h <;> rcases hx with h' | h' <;>
    rw [h'] at h <;> norm_num at h

theorem mobiusProj_eq_saddle_of {m : ℝ × ℝ} (h1 : Real.cos (2 * m.1) = 1) (h2 : m.2 = 0) :
    mobiusProj m = mobiusSaddle := by
  obtain ⟨n, hn⟩ := Real.cos_eq_one_iff (2 * m.1) |>.mp h1
  have hm : m = mobiusZ n • ((0 : ℝ), (0 : ℝ)) := by
    rw [mobiusZ_smul]
    ext
    · simp only [zero_add]
      linarith
    · simp [h2]
  rw [hm]
  exact Quotient.sound (MulAction.orbitRel_apply.mpr ⟨mobiusZ n, rfl⟩)

theorem isCriticalPointAt_mobiusHeight_iff {x : MobiusBand} (hx : mobiusHeight x ∈ Icc 0 2) :
    IsCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeight x ↔ x = mobiusSaddle := by
  constructor
  · intro hcrit
    obtain ⟨m, rfl⟩ := mobiusProj_surjective x
    obtain ⟨h1, h2⟩ := (isCriticalPointAt_mobiusHeight_mk_iff m).mp hcrit
    have hv := mobiusHeight_of_isCriticalPointAt hcrit
    rcases hv with hv | hv
    · rw [mobiusHeight_mk, mobiusHeightLift, h2] at hv
      exact mobiusProj_eq_saddle_of (by linarith) h2
    · rw [hv] at hx
      norm_num at hx
  · rintro rfl
    exact (isCriticalPointAt_mobiusHeight_mk_iff (0, 0)).mpr ⟨by simp, rfl⟩

theorem hasFDerivAt_fderiv_mobiusHeightLift_zero :
    HasFDerivAt (fderiv ℝ mobiusHeightLift)
      ((-(4 : ℝ) • ContinuousLinearMap.fst ℝ ℝ ℝ).smulRight (ContinuousLinearMap.fst ℝ ℝ ℝ) +
        ((2 : ℝ) • ContinuousLinearMap.snd ℝ ℝ ℝ).smulRight (ContinuousLinearMap.snd ℝ ℝ ℝ))
      ((0 : ℝ), (0 : ℝ)) := by
  rw [fderiv_mobiusHeightLift]
  have hs : HasFDerivAt (fun q : ℝ × ℝ => -(2 * Real.sin (2 * q.1)))
      (-(4 : ℝ) • ContinuousLinearMap.fst ℝ ℝ ℝ) ((0 : ℝ), (0 : ℝ)) := by
    have := (((hasFDerivAt_fst (p := ((0 : ℝ), (0 : ℝ)))).const_mul 2).sin.const_mul 2).neg
    convert this using 1
    ext <;> simp; ring
  have hy : HasFDerivAt (fun q : ℝ × ℝ => 2 * q.2)
      ((2 : ℝ) • ContinuousLinearMap.snd ℝ ℝ ℝ) ((0 : ℝ), (0 : ℝ)) := by
    have hs' : HasFDerivAt (fun q : ℝ × ℝ => q.2) (ContinuousLinearMap.snd ℝ ℝ ℝ)
        ((0 : ℝ), (0 : ℝ)) := hasFDerivAt_snd
    exact hs'.const_mul 2
  exact (hs.smul_const (ContinuousLinearMap.fst ℝ ℝ ℝ)).add
    (hy.smul_const (ContinuousLinearMap.snd ℝ ℝ ℝ))

theorem fderiv_fderiv_mobiusHeightLift_zero_apply (v w : ℝ × ℝ) :
    fderiv ℝ (fderiv ℝ mobiusHeightLift) ((0 : ℝ), (0 : ℝ)) v w =
      -4 * v.1 * w.1 + 2 * v.2 * w.2 := by
  rw [hasFDerivAt_fderiv_mobiusHeightLift_zero.fderiv]
  simp

theorem isNondegenerateCriticalPointAt_mobiusHeightLift_zero :
    IsNondegenerateCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeightLift ((0 : ℝ), (0 : ℝ)) := by
  rw [isNondegenerateCriticalPointAt_model_iff
    (contDiff_mobiusHeightLift.contDiffAt.of_le (by simp))]
  refine ⟨(fderiv_mobiusHeightLift_eq_zero_iff _).mpr ⟨by simp, rfl⟩, ?_⟩
  intro u v huv
  have h1 := congrArg (fun L : ℝ × ℝ →L[ℝ] ℝ => L (1, 0)) huv
  have h2 := congrArg (fun L : ℝ × ℝ →L[ℝ] ℝ => L (0, 1)) huv
  simp only [fderiv_fderiv_mobiusHeightLift_zero_apply] at h1 h2
  ext <;> linarith

theorem isNondegenerateCriticalPointAt_mobiusHeight_saddle :
    IsNondegenerateCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeight mobiusSaddle :=
  (isNondegenerateCriticalPointAt_comp_localDiffeomorph_iff
    (isLocalDiffeomorph_mobiusProj ((0 : ℝ), (0 : ℝ)))
    (contMDiff_mobiusHeight.contMDiffAt.of_le (by norm_cast))).mp
    isNondegenerateCriticalPointAt_mobiusHeightLift_zero

theorem sigNeg_chartHessianAt_mobiusHeightLift_zero :
    sigNeg (chartHessianAt mobiusHeightLift ((0 : ℝ), (0 : ℝ))) = 1 := by
  classical
  let w : Fin 2 → ℝ := ![-4, 2]
  have he : QuadraticMap.Equivalent (chartHessianAt mobiusHeightLift ((0 : ℝ), (0 : ℝ)))
      (QuadraticMap.weightedSumSquares ℝ w) := by
    refine ⟨{ (LinearEquiv.finTwoArrow ℝ ℝ).symm with map_app' := ?_ }⟩
    intro v
    change _ = fderiv ℝ (fderiv ℝ mobiusHeightLift) ((0 : ℝ), (0 : ℝ)) v v
    rw [fderiv_fderiv_mobiusHeightLift_zero_apply]
    simp [LinearEquiv.finTwoArrow, QuadraticMap.weightedSumSquares_apply, Fin.sum_univ_two, w]
    ring
  rw [QuadraticForm.sigNeg_of_equiv_weightedSumSquares he]
  have hw : {i | w i < 0} = ({0} : Set (Fin 2)) := by
    ext i
    fin_cases i <;> norm_num [w]
  rw [hw, Set.ncard_singleton]

theorem sigNeg_chartHessianAt_mobiusHeight_saddle :
    sigNeg (chartHessianAt
      (fun y => mobiusHeight ((extChartAt 𝓘(ℝ, ℝ × ℝ) mobiusSaddle).symm y))
      (extChartAt 𝓘(ℝ, ℝ × ℝ) mobiusSaddle mobiusSaddle)) = 1 := by
  have hcrit : IsCriticalPointAt 𝓘(ℝ, ℝ × ℝ) mobiusHeight (mobiusProj ((0 : ℝ), (0 : ℝ))) :=
    (isCriticalPointAt_mobiusHeight_mk_iff _).mpr ⟨by simp, rfl⟩
  have h := sigNeg_chartHessianAt_comp_localDiffeomorph
    (isLocalDiffeomorph_mobiusProj ((0 : ℝ), (0 : ℝ)))
    (contMDiff_mobiusHeight.contMDiffAt.of_le (by norm_cast)) hcrit
  rw [← sigNeg_chartHessianAt_mobiusHeightLift_zero]
  refine h.symm.trans ?_
  simp only [extChartAt_model_space_eq_id, PartialEquiv.refl_symm, PartialEquiv.refl_coe, id_eq]
  rfl

end MobiusMorse

section MobiusTopology

theorem mobiusProj_smul (g : mobiusDeckGroup) (m : ℝ × ℝ) :
    mobiusProj (g • m) = mobiusProj m :=
  Quotient.sound (MulAction.orbitRel_apply.mpr ⟨g, rfl⟩)

theorem continuous_mobiusProj : Continuous mobiusProj :=
  isLocalDiffeomorph_mobiusProj.contMDiff.continuous

theorem exists_rep_Ico (m : ℝ × ℝ) : ∃ n : ℤ, (mobiusZ n • m).1 ∈ Ico 0 Real.pi := by
  refine ⟨-⌊m.1 / Real.pi⌋, ?_⟩
  rw [mobiusZ_smul]
  have hπ := Real.pi_pos
  have h1 := Int.floor_le (m.1 / Real.pi)
  have h2 := Int.lt_floor_add_one (m.1 / Real.pi)
  rw [le_div_iff₀ hπ] at h1
  rw [div_lt_iff₀ hπ] at h2
  push_cast
  constructor <;> nlinarith

theorem exists_rep_nonneg (m : ℝ × ℝ) : ∃ m' : ℝ × ℝ, mobiusProj m' = mobiusProj m ∧
    m'.1 ∈ Icc 0 (2 * Real.pi) ∧ 0 ≤ m'.2 := by
  obtain ⟨n, hn⟩ := exists_rep_Ico m
  set m₁ := mobiusZ n • m
  by_cases hy : 0 ≤ m₁.2
  · exact ⟨m₁, mobiusProj_smul _ _, ⟨hn.1, by linarith [hn.2, Real.pi_pos]⟩, hy⟩
  · refine ⟨mobiusZ 1 • m₁, by rw [mobiusProj_smul, mobiusProj_smul], ?_, ?_⟩
    · rw [mobiusZ_smul]
      push_cast
      constructor <;> linarith [hn.1, hn.2, Real.pi_pos]
    · rw [mobiusZ_smul]
      simp only [zpow_one, neg_mul, one_mul]
      linarith

def mobiusLow (θ : ℝ) : ℝ := Real.sqrt (max 0 (-Real.cos (2 * θ)))

def mobiusHigh (θ : ℝ) : ℝ := Real.sqrt (2 - Real.cos (2 * θ))

theorem continuous_mobiusLow : Continuous mobiusLow :=
  Real.continuous_sqrt.comp (continuous_const.max
    (Real.continuous_cos.comp (continuous_const.mul continuous_id)).neg)

theorem continuous_mobiusHigh : Continuous mobiusHigh :=
  Real.continuous_sqrt.comp (continuous_const.sub
    (Real.continuous_cos.comp (continuous_const.mul continuous_id)))

theorem mobiusLow_lt_high (θ : ℝ) : mobiusLow θ < mobiusHigh θ := by
  apply Real.sqrt_lt_sqrt (le_max_left _ _)
  have h := Real.cos_le_one (2 * θ)
  rcases le_total 0 (-Real.cos (2 * θ)) with hc | hc
  · rw [max_eq_right hc]; linarith
  · rw [max_eq_left hc]; linarith

def mobiusSlabParam (q : ℝ × ℝ) : ℝ × ℝ :=
  (q.1, (1 - q.2) * mobiusLow q.1 + q.2 * mobiusHigh q.1)

theorem continuous_mobiusSlabParam : Continuous mobiusSlabParam :=
  continuous_fst.prodMk (((continuous_const.sub continuous_snd).mul
    (continuous_mobiusLow.comp continuous_fst)).add
    (continuous_snd.mul (continuous_mobiusHigh.comp continuous_fst)))

theorem mobiusHeight_preimage_Icc_eq :
    mobiusHeight ⁻¹' Icc 0 2 =
      (mobiusProj ∘ mobiusSlabParam) '' (Icc 0 (2 * Real.pi) ×ˢ Icc 0 1) := by
  ext x
  constructor
  · intro hx
    obtain ⟨m, rfl⟩ := mobiusProj_surjective x
    obtain ⟨m', hm', hθ, hy⟩ := exists_rep_nonneg m
    rw [mem_preimage, ← hm', mobiusHeight_mk, mobiusHeightLift] at hx
    have hl := mobiusLow_lt_high m'.1
    have hlow : mobiusLow m'.1 ≤ m'.2 := by
      apply Real.sqrt_le_iff.mpr ⟨hy, ?_⟩
      exact max_le (sq_nonneg _) (by linarith [hx.1])
    have hhigh : m'.2 ≤ mobiusHigh m'.1 := Real.le_sqrt_of_sq_le (by linarith [hx.2])
    refine ⟨(m'.1, (m'.2 - mobiusLow m'.1) / (mobiusHigh m'.1 - mobiusLow m'.1)),
      ⟨hθ, ?_, ?_⟩, ?_⟩
    · exact div_nonneg (by linarith) (by linarith)
    · rw [div_le_one (by linarith)]
      linarith
    · rw [comp_apply, ← hm']
      congr 1
      simp only [mobiusSlabParam]
      ext
      · rfl
      · have hne : mobiusHigh m'.1 - mobiusLow m'.1 ≠ 0 := by linarith
        change (1 - (m'.2 - mobiusLow m'.1) / (mobiusHigh m'.1 - mobiusLow m'.1)) *
          mobiusLow m'.1 + (m'.2 - mobiusLow m'.1) / (mobiusHigh m'.1 - mobiusLow m'.1) *
          mobiusHigh m'.1 = m'.2
        field_simp
        ring
  · rintro ⟨q, ⟨hθ, ht0, ht1⟩, rfl⟩
    rw [mem_preimage, comp_apply, mobiusHeight_mk, mobiusHeightLift]
    simp only [mobiusSlabParam]
    have hl0 : 0 ≤ mobiusLow q.1 := Real.sqrt_nonneg _
    have hlh := mobiusLow_lt_high q.1
    have hy0 : mobiusLow q.1 ≤ (1 - q.2) * mobiusLow q.1 + q.2 * mobiusHigh q.1 := by nlinarith
    have hy1 : (1 - q.2) * mobiusLow q.1 + q.2 * mobiusHigh q.1 ≤ mobiusHigh q.1 := by nlinarith
    have hlsq : mobiusLow q.1 ^ 2 = max 0 (-Real.cos (2 * q.1)) :=
      Real.sq_sqrt (le_max_left _ _)
    have hhsq : mobiusHigh q.1 ^ 2 = 2 - Real.cos (2 * q.1) :=
      Real.sq_sqrt (by linarith [Real.cos_le_one (2 * q.1)])
    have h1 := pow_le_pow_left₀ hl0 hy0 2
    have h2 := pow_le_pow_left₀ (hl0.trans hy0) hy1 2
    constructor
    · have := le_max_right 0 (-Real.cos (2 * q.1))
      nlinarith
    · nlinarith

theorem isCompact_mobiusHeight_preimage_Icc : IsCompact (mobiusHeight ⁻¹' Icc 0 2) := by
  rw [mobiusHeight_preimage_Icc_eq]
  exact (isCompact_Icc.prod isCompact_Icc).image
    (continuous_mobiusProj.comp continuous_mobiusSlabParam)

theorem isConnected_mobiusHeight_preimage_Icc : IsConnected (mobiusHeight ⁻¹' Icc 0 2) := by
  rw [mobiusHeight_preimage_Icc_eq]
  refine ((isConnected_Icc ?_).prod (isConnected_Icc zero_le_one)).image _
    (continuous_mobiusProj.comp continuous_mobiusSlabParam).continuousOn
  linarith [Real.pi_pos]

theorem mobiusHeight_preimage_two_eq :
    mobiusHeight ⁻¹' {2} =
      mobiusProj '' ((fun θ => (θ, mobiusHigh θ)) '' Icc 0 (2 * Real.pi)) := by
  ext x
  constructor
  · intro hx
    obtain ⟨m, rfl⟩ := mobiusProj_surjective x
    obtain ⟨m', hm', hθ, hy⟩ := exists_rep_nonneg m
    rw [mem_preimage, ← hm', mobiusHeight_mk, mobiusHeightLift, mem_singleton_iff] at hx
    refine ⟨m', ⟨m'.1, hθ, ?_⟩, hm'⟩
    ext
    · rfl
    · change Real.sqrt (2 - Real.cos (2 * m'.1)) = m'.2
      rw [show 2 - Real.cos (2 * m'.1) = m'.2 ^ 2 by linarith]
      exact Real.sqrt_sq hy
  · rintro ⟨w, ⟨θ, -, rfl⟩, rfl⟩
    rw [mem_preimage, mobiusHeight_mk, mobiusHeightLift, mem_singleton_iff]
    change Real.sqrt (2 - Real.cos (2 * θ)) ^ 2 + Real.cos (2 * θ) = 2
    rw [Real.sq_sqrt (by linarith [Real.cos_le_one (2 * θ)])]
    ring

theorem isPreconnected_mobiusHeight_two : IsPreconnected (mobiusHeight ⁻¹' {2}) := by
  rw [mobiusHeight_preimage_two_eq]
  exact (isPreconnected_Icc.image _ (continuous_id.prodMk
    continuous_mobiusHigh).continuousOn).image _ continuous_mobiusProj.continuousOn

theorem cos_two_mul_nonpos_iff {θ : ℝ} (hθ : θ ∈ Icc 0 Real.pi) :
    Real.cos (2 * θ) ≤ 0 ↔ θ ∈ Icc (Real.pi / 4) (3 * Real.pi / 4) := by
  have hπ := Real.pi_pos
  constructor
  · intro hc
    by_contra hn
    rcases not_and_or.mp hn with h | h
    · have hpos : 0 < Real.cos (2 * θ) := Real.cos_pos_of_mem_Ioo
        ⟨by linarith [hθ.1], by linarith [not_le.mp h]⟩
      linarith
    · have hpos : 0 < Real.cos (2 * θ - 2 * Real.pi) := Real.cos_pos_of_mem_Ioo
        ⟨by linarith [not_le.mp h], by linarith [hθ.2]⟩
      rw [Real.cos_sub_two_pi] at hpos
      linarith
  · rintro ⟨h1, h2⟩
    exact Real.cos_nonpos_of_pi_div_two_le_of_le (by linarith) (by linarith)

theorem mobiusHeight_preimage_zero_eq :
    mobiusHeight ⁻¹' {0} = mobiusProj ''
      ((fun θ => (θ, mobiusLow θ)) '' Icc (Real.pi / 4) (3 * Real.pi / 4) ∪
        (fun θ => (θ, -mobiusLow θ)) '' Icc (Real.pi / 4) (3 * Real.pi / 4)) := by
  have hπ := Real.pi_pos
  ext x
  constructor
  · intro hx
    obtain ⟨m, rfl⟩ := mobiusProj_surjective x
    obtain ⟨n, hn⟩ := exists_rep_Ico m
    set m₁ := mobiusZ n • m
    rw [mem_preimage, ← mobiusProj_smul (mobiusZ n), mobiusHeight_mk, mobiusHeightLift,
      mem_singleton_iff] at hx
    have hc : Real.cos (2 * m₁.1) ≤ 0 := by nlinarith [sq_nonneg m₁.2]
    have hθ := (cos_two_mul_nonpos_iff ⟨hn.1, hn.2.le⟩).mp hc
    have hlow : mobiusLow m₁.1 = |m₁.2| := by
      unfold mobiusLow
      rw [max_eq_right (by linarith), show -Real.cos (2 * m₁.1) = m₁.2 ^ 2 by linarith,
        Real.sqrt_sq_eq_abs]
    refine ⟨m₁, ?_, mobiusProj_smul _ _⟩
    rcases le_total 0 m₁.2 with hy | hy
    · refine Or.inl ⟨m₁.1, hθ, ?_⟩
      ext
      · rfl
      · change mobiusLow m₁.1 = m₁.2
        rw [hlow, abs_of_nonneg hy]
    · refine Or.inr ⟨m₁.1, hθ, ?_⟩
      ext
      · rfl
      · change -mobiusLow m₁.1 = m₁.2
        rw [hlow, abs_of_nonpos hy, neg_neg]
  · rintro ⟨w, hA, rfl⟩
    rw [mem_preimage, mobiusHeight_mk, mobiusHeightLift, mem_singleton_iff]
    have key (θ : ℝ) (hθ : θ ∈ Icc (Real.pi / 4) (3 * Real.pi / 4)) :
        mobiusLow θ ^ 2 + Real.cos (2 * θ) = 0 := by
      have hc := (cos_two_mul_nonpos_iff ⟨by linarith [hθ.1], by linarith [hθ.2]⟩).mpr hθ
      unfold mobiusLow
      rw [Real.sq_sqrt (le_max_left _ _), max_eq_right (by linarith)]
      ring
    rcases hA with ⟨θ, hθ, rfl⟩ | ⟨θ, hθ, rfl⟩
    · exact key θ hθ
    · change (-mobiusLow θ) ^ 2 + Real.cos (2 * θ) = 0
      rw [neg_sq]
      exact key θ hθ

theorem isPreconnected_mobiusHeight_zero : IsPreconnected (mobiusHeight ⁻¹' {0}) := by
  have hπ := Real.pi_pos
  rw [mobiusHeight_preimage_zero_eq]
  have hI : IsPreconnected (Icc (Real.pi / 4) (3 * Real.pi / 4)) := isPreconnected_Icc
  have h1 := hI.image _ (continuous_id.prodMk continuous_mobiusLow).continuousOn
  have h2 := hI.image _ (continuous_id.prodMk continuous_mobiusLow.neg).continuousOn
  have hmeet : (Real.pi / 4, mobiusLow (Real.pi / 4)) ∈
      (fun θ => (θ, mobiusLow θ)) '' Icc (Real.pi / 4) (3 * Real.pi / 4) ∩
        (fun θ => (θ, -mobiusLow θ)) '' Icc (Real.pi / 4) (3 * Real.pi / 4) := by
    have h0 : mobiusLow (Real.pi / 4) = 0 := by
      unfold mobiusLow
      rw [show 2 * (Real.pi / 4) = Real.pi / 2 by ring, Real.cos_pi_div_two, neg_zero,
        max_self, Real.sqrt_zero]
    refine ⟨⟨Real.pi / 4, ⟨le_rfl, by linarith⟩, rfl⟩, ⟨Real.pi / 4, ⟨le_rfl, by linarith⟩, ?_⟩⟩
    change (Real.pi / 4, -mobiusLow (Real.pi / 4)) = (Real.pi / 4, mobiusLow (Real.pi / 4))
    rw [h0, neg_zero]
  exact (h1.union _ hmeet.1 hmeet.2 h2).image _ continuous_mobiusProj.continuousOn

end MobiusTopology

section NonOrientable

open Bundle Module
open DifferentialGeometry.PDE.RicciFlow.Perelman.KappaSolutions

def mobiusLoop (t : ℝ) : ℝ × ℝ := (t, Real.sqrt 2 * Real.sin t)

theorem continuous_mobiusLoop : Continuous mobiusLoop :=
  continuous_id.prodMk (continuous_const.mul Real.continuous_sin)

theorem mobiusHeightLift_mobiusLoop (t : ℝ) : mobiusHeightLift (mobiusLoop t) = 1 := by
  simp only [mobiusHeightLift, mobiusLoop]
  rw [mul_pow, Real.sq_sqrt (by norm_num), Real.cos_two_mul]
  have := Real.sin_sq_add_cos_sq t
  linarith

theorem mobiusLoop_pi : mobiusLoop Real.pi = mobiusZ 1 • mobiusLoop 0 := by
  rw [mobiusZ_smul]
  simp [mobiusLoop]

theorem basis_orientation_ne_of_neg {V : Type*} [AddCommGroup V] [Module ℝ V]
    (b₀ b₁ : Basis (Fin 2) ℝ V) (hfirst : b₁ 0 = b₀ 0) (hsecond : b₁ 1 = -(b₀ 1)) :
    b₀.orientation ≠ b₁.orientation := by
  intro horientation
  have hdet : b₀.det b₁ = -1 := by
    rw [Basis.det_apply, Matrix.det_fin_two]
    simp [Basis.toMatrix_apply, hfirst, hsecond]
  have hpos := (b₀.orientation_eq_iff_det_pos b₁).mp horientation
  rw [hdet] at hpos
  norm_num at hpos

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] {H : Type*} [TopologicalSpace H]
  {I : ModelWithCorners ℝ E H} {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  [IsManifold I ∞ M]

theorem continuousAt_tangentMap_of_isLocalDiffeomorphAt {Q : ℝ × ℝ → M} {p : ℝ × ℝ}
    (hQ : IsLocalDiffeomorphAt 𝓘(ℝ, ℝ × ℝ) I ∞ Q p) (v : ℝ × ℝ) :
    ContinuousAt (tangentMap 𝓘(ℝ, ℝ × ℝ) I Q)
      (TotalSpace.mk' (ℝ × ℝ) (E := TangentSpace 𝓘(ℝ, ℝ × ℝ)) p v) := by
  obtain ⟨Φ, hp, heq⟩ := hQ
  have hV : ContMDiffOn 𝓘(ℝ, ℝ × ℝ) I ∞ Q Φ.source :=
    Φ.contMDiffOn.congr fun y hy => heq hy
  have hT := hV.continuousOn_tangentMapWithin (by norm_cast)
    Φ.open_source.uniqueMDiffOn
  have hopen : IsOpen (TotalSpace.proj ⁻¹' Φ.source :
      Set (TangentBundle 𝓘(ℝ, ℝ × ℝ) (ℝ × ℝ))) :=
    Φ.open_source.preimage (FiberBundle.continuous_proj (ℝ × ℝ) _)
  have hmem : TotalSpace.mk' (ℝ × ℝ) (E := TangentSpace 𝓘(ℝ, ℝ × ℝ)) p v ∈
      (TotalSpace.proj ⁻¹' Φ.source : Set (TangentBundle 𝓘(ℝ, ℝ × ℝ) (ℝ × ℝ))) := hp
  refine ((hT.continuousAt (hopen.mem_nhds hmem)).congr ?_)
  filter_upwards [hopen.mem_nhds hmem] with w hw
  exact tangentMapWithin_eq_tangentMap (Φ.open_source.uniqueMDiffOn _ hw)
    ((hV.contMDiffAt (Φ.open_source.mem_nhds hw)).mdifferentiableAt (by simp))

theorem SurfaceOrientation.not_mobius_localDiffeomorph (o : SurfaceOrientation I M)
    (q : MobiusBand → M)
    (hq : ∀ x, mobiusHeight x = 1 → IsLocalDiffeomorphAt 𝓘(ℝ, ℝ × ℝ) I ∞ q x) : False := by
  let Q : ℝ × ℝ → M := q ∘ mobiusProj
  have hQ (t : ℝ) : IsLocalDiffeomorphAt 𝓘(ℝ, ℝ × ℝ) I ∞ Q (mobiusLoop t) :=
    (isLocalDiffeomorph_mobiusProj _).comp I M
      (hq _ (by rw [mobiusHeight_mk]; exact mobiusHeightLift_mobiusLoop t))
  let γ : ℝ → M := fun t => Q (mobiusLoop t)
  let e : Basis (Fin 2) ℝ (ℝ × ℝ) := Basis.finTwoProd ℝ
  let B : (t : ℝ) → Basis (Fin 2) ℝ (TangentSpace I (γ t)) := fun t =>
    e.map ((hQ t).mfderivToContinuousLinearEquiv (by simp)).toLinearEquiv
  have hB (t : ℝ) (i : Fin 2) : B t i = mfderiv 𝓘(ℝ, ℝ × ℝ) I Q (mobiusLoop t) (e i) := rfl
  have hγ : Continuous γ := by
    refine continuous_iff_continuousAt.mpr fun t => ?_
    exact (hQ t).contMDiffAt.continuousAt.comp continuous_mobiusLoop.continuousAt
  have hcont (i : Fin 2) : Continuous fun t =>
      TotalSpace.mk' E (E := TangentSpace I) (γ t) (B t i) := by
    have hlift : Continuous fun t : ℝ =>
        TotalSpace.mk' (ℝ × ℝ) (E := TangentSpace 𝓘(ℝ, ℝ × ℝ)) (mobiusLoop t) (e i) := by
      have h := (tangentBundleModelSpaceHomeomorph 𝓘(ℝ, ℝ × ℝ)).symm.continuous.comp
        (continuous_mobiusLoop.prodMk (continuous_const (y := e i)))
      exact h
    refine continuous_iff_continuousAt.mpr fun t => ?_
    exact ContinuousAt.comp (x := t)
      (f := fun t : ℝ => TotalSpace.mk' (ℝ × ℝ) (E := TangentSpace 𝓘(ℝ, ℝ × ℝ))
        (mobiusLoop t) (e i))
      (continuousAt_tangentMap_of_isLocalDiffeomorphAt (hQ t) (e i)) hlift.continuousAt
  have hloop : γ 0 = γ Real.pi := by
    change q (mobiusProj (mobiusLoop 0)) = q (mobiusProj (mobiusLoop Real.pi))
    rw [mobiusLoop_pi, mobiusProj_smul]
  have horientation : (B 0).orientation = (B Real.pi).orientation :=
    o.frame_orientation_eq_of_loop γ hγ B hcont 0 Real.pi hloop
  let τ : ℝ × ℝ → ℝ × ℝ := fun p => mobiusZ 1 • p
  have hτ : HasFDerivAt τ ((ContinuousLinearMap.fst ℝ ℝ ℝ).prod
      (-(ContinuousLinearMap.snd ℝ ℝ ℝ))) (mobiusLoop 0) := by
    have hfun : τ = fun p => (p.1 + Real.pi, -p.2) := by
      funext p
      simp [τ, mobiusZ_smul]
    rw [hfun]
    exact (hasFDerivAt_fst.add_const _).prodMk hasFDerivAt_snd.neg
  have hcomp : Q ∘ τ = Q := by
    funext p
    exact congrArg q (mobiusProj_smul (mobiusZ 1) p)
  have hd (v : ℝ × ℝ) : mfderiv 𝓘(ℝ, ℝ × ℝ) I Q (mobiusLoop Real.pi)
      (((ContinuousLinearMap.fst ℝ ℝ ℝ).prod (-(ContinuousLinearMap.snd ℝ ℝ ℝ))) v) =
      mfderiv 𝓘(ℝ, ℝ × ℝ) I Q (mobiusLoop 0) v := by
    have hτ0 : τ (mobiusLoop 0) = mobiusLoop Real.pi := (mobiusLoop_pi).symm
    have hQd : MDifferentiableAt 𝓘(ℝ, ℝ × ℝ) I Q (τ (mobiusLoop 0)) := by
      rw [hτ0]
      exact (hQ Real.pi).mdifferentiableAt (by simp)
    have hc := mfderiv_comp_apply (x := mobiusLoop 0) hQd hτ.differentiableAt.mdifferentiableAt v
    rw [hcomp, mfderiv_eq_fderiv, hτ.fderiv, hτ0] at hc
    exact hc.symm
  have he0 : ((ContinuousLinearMap.fst ℝ ℝ ℝ).prod (-(ContinuousLinearMap.snd ℝ ℝ ℝ))) (e 0) =
      e 0 := by
    simp [e, Module.Basis.finTwoProd_zero]
  have he1 : ((ContinuousLinearMap.fst ℝ ℝ ℝ).prod (-(ContinuousLinearMap.snd ℝ ℝ ℝ))) (e 1) =
      -(e 1) := by
    simp [e, Module.Basis.finTwoProd_one]
  have hfirst : B Real.pi 0 = B 0 0 := by
    rw [hB, hB, ← hd, he0]
  have hsecond : B Real.pi 1 = -(B 0 1) := by
    let L : (ℝ × ℝ) →L[ℝ] E := mfderiv 𝓘(ℝ, ℝ × ℝ) I Q (mobiusLoop Real.pi)
    have h1 : B Real.pi 1 = L (e 1) := hB Real.pi 1
    have h2 : B 0 1 = L (((ContinuousLinearMap.fst ℝ ℝ ℝ).prod
        (-(ContinuousLinearMap.snd ℝ ℝ ℝ))) (e 1)) := (hB 0 1).trans (hd (e 1)).symm
    rw [h1, h2, he1, L.map_neg]
    exact (neg_neg (L (e 1))).symm
  exact basis_orientation_ne_of_neg (B 0) (B Real.pi) hfirst hsecond horientation

end NonOrientable

section NegPants

open DifferentialGeometry.Topology DifferentialGeometry.Topology.Morse

def negPantsHeight (z : ℂ) : ℝ := -pantsHeight z

theorem contDiff_negPantsHeight : ContDiff ℝ ∞ negPantsHeight := contDiff_pantsHeight.neg

theorem contMDiff_negPantsHeight : ContMDiff 𝓘(ℝ, ℂ) 𝓘(ℝ, ℝ) ∞ negPantsHeight :=
  contDiff_negPantsHeight.contMDiff

theorem negPantsHeight_regular_endpoints :
    ∀ z : ℂ, negPantsHeight z = -1 ∨ negPantsHeight z = 0 →
      mfderiv 𝓘(ℝ, ℂ) 𝓘(ℝ, ℝ) negPantsHeight z ≠ 0 := by
  intro z hz hcrit
  refine pantsHeight_regular_endpoints z ?_
    ((NegDual.isCriticalPointAt_neg_iff 𝓘(ℝ, ℂ) pantsHeight z).mp hcrit)
  unfold negPantsHeight at hz
  rcases hz with h | h
  · exact Or.inr (by linarith)
  · exact Or.inl (by linarith)

theorem isCriticalPointAt_negPantsHeight_iff {z : ℂ} (hz : negPantsHeight z ∈ Icc (-1) 0) :
    IsCriticalPointAt 𝓘(ℝ, ℂ) negPantsHeight z ↔ z = 0 := by
  have hz' : pantsHeight z ∈ Icc 0 1 := by
    unfold negPantsHeight at hz
    exact ⟨by linarith [hz.2], by linarith [hz.1]⟩
  exact (NegDual.isCriticalPointAt_neg_iff 𝓘(ℝ, ℂ) pantsHeight z).trans
    (isCriticalPointAt_pantsHeight_iff hz')

theorem isNondegenerateCriticalPointAt_negPantsHeight_zero :
    IsNondegenerateCriticalPointAt 𝓘(ℝ, ℂ) negPantsHeight 0 :=
  (NegDual.isNondegenerateCriticalPointAt_neg_iff 𝓘(ℝ, ℂ) pantsHeight 0).mpr
    isNondegenerateCriticalPointAt_pantsHeight_zero

theorem sigNeg_chartHessianAt_negPantsHeight_zero :
    sigNeg (chartHessianAt (fun y => negPantsHeight ((extChartAt 𝓘(ℝ, ℂ) (0 : ℂ)).symm y))
      (extChartAt 𝓘(ℝ, ℂ) (0 : ℂ) 0)) = 1 := by
  have h := sigNeg_chartHessianAt_pantsHeight_zero
  have hs := sigPos_add_sigNeg_eq_finrank _ isNondegenerateCriticalPointAt_pantsHeight_zero.2
  rw [Complex.finrank_real_complex] at hs
  change sigNeg (chartHessianAt (fun y => -pantsHeight ((extChartAt 𝓘(ℝ, ℂ) (0 : ℂ)).symm y))
    (extChartAt 𝓘(ℝ, ℂ) (0 : ℂ) 0)) = 1
  rw [NegDual.chartHessianAt_neg, sigNeg_neg]
  omega

theorem negPantsHeight_preimage_Icc :
    negPantsHeight ⁻¹' Icc (-1) 0 = pantsHeight ⁻¹' Icc 0 1 := by
  have h := NegDual.preimage_neg_Icc (f := pantsHeight) (a := 0) (b := 1)
  rw [neg_zero] at h
  exact h

theorem isCompact_negPantsHeight_preimage_Icc : IsCompact (negPantsHeight ⁻¹' Icc (-1) 0) := by
  rw [negPantsHeight_preimage_Icc]
  exact isCompact_pantsHeight_preimage_Icc

theorem isConnected_negPantsHeight_preimage_Icc :
    IsConnected (negPantsHeight ⁻¹' Icc (-1) 0) := by
  rw [negPantsHeight_preimage_Icc]
  exact isConnected_pantsHeight_preimage_Icc

theorem isPreconnected_negPantsHeight_neg_one : IsPreconnected (negPantsHeight ⁻¹' {-1}) := by
  have h : negPantsHeight ⁻¹' {-1} = Metric.sphere (0 : ℂ) 3 := by
    ext z
    simp only [mem_preimage, mem_singleton_iff, negPantsHeight, mem_sphere_iff_norm, sub_zero]
    rw [neg_eq_iff_eq_neg, neg_neg]
    exact pantsHeight_eq_one_iff z
  rw [h]
  exact isPreconnected_sphere (by rw [Complex.rank_real_complex]; norm_num) 0 3

theorem not_isPreconnected_negPantsHeight_zero :
    ¬ IsPreconnected (negPantsHeight ⁻¹' {0}) := by
  have h : negPantsHeight ⁻¹' {0} = pantsHeight ⁻¹' {0} := by
    ext z
    simp only [mem_preimage, mem_singleton_iff, negPantsHeight, neg_eq_zero]
  rw [h]
  exact not_isPreconnected_pantsHeight_zero

end NegPants

end GC.Seifert
