import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Metric.Approximation.CommonCoordinateCancellation
import DifferentialGeometry.Topology.MetricSpace.CoarseGap
import DifferentialGeometry.Geometry.Metric.Approximation.BoundedFactorRestriction

#check GC.MetricGeometry.exists_factor_approximation_of_common_coordinate
#print axioms GC.MetricGeometry.exists_factor_approximation_of_common_coordinate

#check IsPreconnected.lt_iff_lt_of_coarse_bound
#print axioms IsPreconnected.lt_iff_lt_of_coarse_bound

#check GC.MetricGeometry.exists_restricted_factor_approximation
#print axioms GC.MetricGeometry.exists_restricted_factor_approximation

#check GC.MetricGeometry.exists_factor_approximation_of_bounded_target
#print axioms GC.MetricGeometry.exists_factor_approximation_of_bounded_target
