import DifferentialGeometry.Geometry.Thurston.ProjectiveSumDihedralChart
import DifferentialGeometry.Geometry.Thurston.SphericalProductDihedralQuotient
import DifferentialGeometry.Topology.ThreeManifold.ConnectedSum.ConnectingCylinder
import DifferentialGeometry.Topology.ThreeManifold.ConnectedSum.ChoiceIndependence
import DifferentialGeometry.Topology.ThreeManifold.AntipodalPresentation
import DifferentialGeometry.Topology.Manifold.LocalDiffeomorph.OpenCodRestrict

/-!
# `RP³ # RP³` is the quotient of `S² × ℝ` by the standard infinite dihedral group

Chapter 7, packet P8c. Let `D : DihedralChart X` be a stereographic ball chart on an antipodal
quotient `X` of `S³`, with core map `(y, t) ↦ p (σ⁻¹ (μ t • R y))`. The map
`DihedralChart.projection : S² × ℝ → X # X` sends `(y, t + n)` with `|t| ≤ 1/4` to the left copy
of `X` and `(y, t + 1/2 + n)` with `|t| < 1/4` to the right copy, both through the core map.
Because `μ s + μ (1/2 - s) = 2κ`, near the gluing sphere it is the connecting cylinder of the
connected sum in the affine parameter `5/2 - 2 μ s / κ`, so it is a local diffeomorphism
everywhere. It is surjective and its fibres are exactly the orbits of the group generated by
`(x, s) ↦ (-x, -s)` and `(x, s) ↦ (-x, 1 - s)`.

Since connected sums do not depend on the oriented ball charts, this gives the presentation of
the endpoint model `connectedSum RP³ RP³` (`projectiveSumStandardDihedralPresentation`), which
discharges the named input `ProjectiveSumStandardDihedralPresentation` of packet P8.
-/

set_option autoImplicit false

noncomputable section

open Set Function Manifold Filter
open DifferentialGeometry DifferentialGeometry.Topology
open DifferentialGeometry.PDE.RicciFlow.Perelman.KappaSolutions
open scoped Manifold ContDiff Topology

namespace GC.Geometry.SphericalProduct

local notation "E3" => EuclideanSpace ℝ (Fin 3)
local notation "E4" => EuclideanSpace ℝ (Fin 4)
local notation "S2" => Metric.sphere (0 : E3) 1
local notation "S3" => Metric.sphere (0 : E4) 1
local notation "CM" => SpatialNeckCylinderModel

private local instance dihedralSumFinrankThree : Fact (Module.finrank ℝ E3 = 2 + 1) :=
  ⟨by simp⟩

universe u

section LocalDiffeomorph

variable {E F G : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [NormedAddCommGroup F]
  [NormedSpace ℝ F] [NormedAddCommGroup G] [NormedSpace ℝ G]
  {H H' H'' : Type*} [TopologicalSpace H] [TopologicalSpace H']
  {I : ModelWithCorners ℝ E H} {J : ModelWithCorners ℝ F H'}
  {M N : Type*} [TopologicalSpace M] [ChartedSpace H M] [TopologicalSpace N] [ChartedSpace H' N]

theorem isLocalDiffeomorphAt_of_eventually_factor {tH : TopologicalSpace H''}
    {K : ModelWithCorners ℝ G H''} {P : Type*} {tP : TopologicalSpace P}
    {cP : ChartedSpace H'' P}
    {V : TopologicalSpace.Opens N} {Φ : V → P}
    (hΦ : IsLocalDiffeomorph J K ∞ Φ) {g : M → N} {x : M} (hg : IsLocalDiffeomorphAt I J ∞ g x)
    {f : M → P} (hV : ∀ᶠ y in 𝓝 x, g y ∈ V)
    (hf : ∀ᶠ y in 𝓝 x, ∀ hy : g y ∈ V, f y = Φ ⟨g y, hy⟩) :
    IsLocalDiffeomorphAt I K ∞ f x := by
  classical
  have hx : g x ∈ V := hV.self_of_nhds
  let g' : M → V := fun y => if hy : g y ∈ V then ⟨g y, hy⟩ else ⟨g x, hx⟩
  have hg'eq : (fun y => (g' y : N)) =ᶠ[𝓝 x] g := by
    filter_upwards [hV] with y hy
    simp only [g', dite_eq_left hy]
  have hcod := DifferentialGeometry.isLocalDiffeomorphAt_subtypeCodRestrict (V := V)
    (fun y => (g' y).2) (DifferentialGeometry.IsLocalDiffeomorphAt.of_eventuallyEq hg'eq hg)
  have hcomp := hcod.comp K P (hΦ _)
  refine DifferentialGeometry.IsLocalDiffeomorphAt.of_eventuallyEq ?_ hcomp
  filter_upwards [hV, hf] with y hy hfy
  rw [hfy hy]
  simp only [Function.comp_apply, g', dite_eq_left hy]

theorem isLocalDiffeomorphAt_of_invariant {tH : TopologicalSpace H''}
    {K : ModelWithCorners ℝ G H''} {P : Type*} {tP : TopologicalSpace P}
    {cP : ChartedSpace H'' P}
    {f : M → P} {T : M → M} {x : M}
    (hT : IsLocalDiffeomorphAt I I ∞ T x) (hfT : ∀ y, f (T y) = f y)
    (hf : IsLocalDiffeomorphAt I K ∞ f (T x)) : IsLocalDiffeomorphAt I K ∞ f x := by
  have h := hT.comp K P hf
  rwa [show f ∘ T = f from funext hfT] at h

end LocalDiffeomorph

theorem isLocalDiffeomorphAt_cylinder_reparam (A : E3 ≃ₗᵢ[ℝ] E3) {g : ℝ → ℝ} {y : S2} {s : ℝ}
    (hg : IsLocalDiffeomorphAt 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ) ∞ g s) :
    IsLocalDiffeomorphAt CM CM ∞
      (Prod.map (DifferentialGeometry.Geometry.sphereDiffeo (n := 2) A) g) (y, s) :=
  ((DifferentialGeometry.Geometry.sphereDiffeo (n := 2) A).isLocalDiffeomorph y).prodMap hg

theorem isLocalDiffeomorphAt_prodMap_id {g : ℝ → ℝ} {y : S2} {s : ℝ}
    (hg : IsLocalDiffeomorphAt 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ) ∞ g s) :
    IsLocalDiffeomorphAt CM CM ∞ (Prod.map id g) (y, s) :=
  ((Diffeomorph.refl (𝓡 2) S2 ∞).isLocalDiffeomorph y).prodMap hg

theorem isLocalDiffeomorphAt_affine_line (a b : ℝ) (ha : a ≠ 0) (s : ℝ) :
    IsLocalDiffeomorphAt 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ) ∞ (fun t : ℝ => a * t + b) s := by
  refine isLocalDiffeomorphAt_real isOpen_univ
    ((contDiff_const.mul contDiff_id).add contDiff_const).contDiffOn (mem_univ s) ha ?_
  simpa using ((hasDerivAt_id s).const_mul a).add_const b

def dihedralReflectionZero : CylinderIsometry :=
  (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ (0 : ℝ))

def dihedralReflectionHalf : CylinderIsometry :=
  (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ (1 / 2 : ℝ))

theorem dihedralGroup_eq :
    dihedralGroup 0 (1 / 2) =
      Subgroup.closure {dihedralReflectionZero, dihedralReflectionHalf} := rfl

theorem cylinderAct_dihedralReflectionZero (p : SpatialNeckCylinder) :
    cylinderAct dihedralReflectionZero p = (-p.1, -p.2) := by
  refine Prod.ext (Subtype.ext ?_) ?_
  · rw [cylinderAct_fst, coe_neg_sphere]
    rfl
  · rw [cylinderAct_snd]
    change (0 - p.2) + 0 = -p.2
    ring

theorem cylinderAct_dihedralReflectionHalf (p : SpatialNeckCylinder) :
    cylinderAct dihedralReflectionHalf p = (-p.1, 1 - p.2) := by
  refine Prod.ext (Subtype.ext ?_) ?_
  · rw [cylinderAct_fst, coe_neg_sphere]
    rfl
  · rw [cylinderAct_snd]
    change (1 / 2 - p.2) + 1 / 2 = 1 - p.2
    ring

theorem dihedralReflectionZero_mem : dihedralReflectionZero ∈ dihedralGroup 0 (1 / 2) :=
  Subgroup.subset_closure (Or.inl rfl)

theorem dihedralReflectionHalf_mem : dihedralReflectionHalf ∈ dihedralGroup 0 (1 / 2) :=
  Subgroup.subset_closure (Or.inr rfl)

theorem exists_dihedral_translation (m : ℤ) :
    ∃ γ ∈ dihedralGroup 0 (1 / 2), ∀ p, cylinderAct γ p = (p.1, p.2 + m) := by
  let τ := dihedralReflectionHalf * dihedralReflectionZero
  have hτ : τ ∈ dihedralGroup 0 (1 / 2) :=
    Subgroup.mul_mem _ dihedralReflectionHalf_mem dihedralReflectionZero_mem
  have hτp : ∀ p : SpatialNeckCylinder, cylinderAct τ p = (p.1, p.2 + 1) := by
    intro p
    rw [cylinderAct_mul, cylinderAct_dihedralReflectionZero, cylinderAct_dihedralReflectionHalf,
      neg_neg]
    exact Prod.ext rfl (by ring)
  induction m using Int.induction_on with
  | zero => exact ⟨1, Subgroup.one_mem _, fun p => by rw [cylinderAct_one]; simp⟩
  | succ n ih =>
    obtain ⟨γ, hγ, h⟩ := ih
    refine ⟨τ * γ, Subgroup.mul_mem _ hτ hγ, fun p => ?_⟩
    rw [cylinderAct_mul, h, hτp]
    exact Prod.ext rfl (by push_cast; ring)
  | pred n ih =>
    obtain ⟨γ, hγ, h⟩ := ih
    refine ⟨τ⁻¹ * γ, Subgroup.mul_mem _ (Subgroup.inv_mem _ hτ) hγ, fun p => ?_⟩
    rw [cylinderAct_mul, h]
    have hq := hτp (p.1, p.2 + ((-(n : ℤ) - 1 : ℤ) : ℝ))
    have hq' : ((p.1, p.2 + ((-(n : ℤ) - 1 : ℤ) : ℝ)).1,
        (p.1, p.2 + ((-(n : ℤ) - 1 : ℤ) : ℝ)).2 + 1) = (p.1, p.2 + ((-(n : ℤ) : ℤ) : ℝ)) :=
      Prod.ext rfl (by push_cast; ring)
    rw [hq'] at hq
    rw [← hq, cylinderAct_inv_cylinderAct]

theorem exists_dihedral_reflection (m : ℤ) :
    ∃ γ ∈ dihedralGroup 0 (1 / 2), ∀ p, cylinderAct γ p = (-p.1, m - p.2) := by
  obtain ⟨γ, hγ, h⟩ := exists_dihedral_translation m
  refine ⟨γ * dihedralReflectionZero, Subgroup.mul_mem _ hγ dihedralReflectionZero_mem,
    fun p => ?_⟩
  rw [cylinderAct_mul, cylinderAct_dihedralReflectionZero, h]
  exact Prod.ext rfl (by ring)

def cylinderInvariance {Z : Type*} (f : SpatialNeckCylinder → Z) :
    Subgroup CylinderIsometry where
  carrier := {γ | ∀ p, f (cylinderAct γ p) = f p}
  mul_mem' := by
    intro a b ha hb p
    rw [cylinderAct_mul, ha, hb]
  one_mem' := by
    intro p
    rw [cylinderAct_one]
  inv_mem' := by
    intro γ hγ p
    have h := hγ (cylinderAct γ⁻¹ p)
    rw [← cylinderAct_mul, mul_inv_cancel, cylinderAct_one] at h
    exact h.symm

theorem dihedralGroup_le_cylinderInvariance {Z : Type*} (f : SpatialNeckCylinder → Z)
    (h₀ : ∀ p : SpatialNeckCylinder, f (-p.1, -p.2) = f p)
    (h₁ : ∀ p : SpatialNeckCylinder, f (-p.1, 1 - p.2) = f p) :
    dihedralGroup 0 (1 / 2) ≤ cylinderInvariance f := by
  rw [dihedralGroup_eq, Subgroup.closure_le]
  rintro γ (rfl | hγ)
  · intro p
    rw [cylinderAct_dihedralReflectionZero]
    exact h₀ p
  · rw [Set.mem_singleton_iff] at hγ
    subst hγ
    intro p
    rw [cylinderAct_dihedralReflectionHalf]
    exact h₁ p

namespace DihedralChart

variable {X : ConnectedClosedOrientedManifold.{u} 3} (D : DihedralChart X)

abbrev sum : ConnectedClosedOrientedManifold.{u} 3 :=
  (smoothConnectedSum X X D.chart D.chart boundaryAttachment).toConnectedClosedOrientedManifold

def left (y : S2) (t : ℝ) (ht : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4)) : D.sum.Carrier :=
  ConnectedSumQuotient.inl D.chart.toBallChart D.chart.toBallChart
    boundaryAttachment.1.toHomeomorph ⟨D.core y t, D.core_not_mem_ball ht⟩

def right (y : S2) (t : ℝ) (ht : t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)) : D.sum.Carrier :=
  ConnectedSumQuotient.inr D.chart.toBallChart D.chart.toBallChart
    boundaryAttachment.1.toHomeomorph ⟨D.core y t, fun h =>
      D.core_not_mem_closedBall ht (image_mono Metric.ball_subset_closedBall h)⟩

theorem left_eq_left {y y' : S2} {t t' : ℝ} {ht : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4)}
    {ht' : t' ∈ Icc (-(1 / 4) : ℝ) (1 / 4)} (h : D.core y t = D.core y' t') :
    D.left y t ht = D.left y' t' ht' :=
  congrArg _ (Subtype.ext h)

theorem right_eq_right {y y' : S2} {t t' : ℝ} {ht : t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)}
    {ht' : t' ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)} (h : D.core y t = D.core y' t') :
    D.right y t ht = D.right y' t' ht' :=
  congrArg _ (Subtype.ext h)

theorem core_eq_of_left_eq {y y' : S2} {t t' : ℝ} {ht : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4)}
    {ht' : t' ∈ Icc (-(1 / 4) : ℝ) (1 / 4)} (h : D.left y t ht = D.left y' t' ht') :
    D.core y t = D.core y' t' :=
  congrArg Subtype.val (ConnectedSumQuotient.inl_injective _ _ _ h)

theorem core_eq_of_right_eq {y y' : S2} {t t' : ℝ} {ht : t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)}
    {ht' : t' ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)} (h : D.right y t ht = D.right y' t' ht') :
    D.core y t = D.core y' t' :=
  congrArg Subtype.val (ConnectedSumQuotient.inr_injective _ _ _ h)

theorem left_ne_right {y y' : S2} {t t' : ℝ} (ht : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4))
    (ht' : t' ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)) : D.left y t ht ≠ D.right y' t' ht' := by
  intro h
  obtain ⟨z, -, hz⟩ := (ConnectedSumQuotient.inl_eq_inr_iff _ _ _ _ _).mp h
  apply D.core_not_mem_closedBall (y := y') ht'
  refine ⟨((boundaryAttachment.1.toHomeomorph z : S2) : E3), ?_, ?_⟩
  · rw [Metric.mem_closedBall, dist_zero_right, norm_eq_of_mem_sphere]
  · exact congrArg Subtype.val hz

def projectionAux (y : S2) (w : ℝ) (hw : w ∈ Ico (0 : ℝ) 1) : D.sum.Carrier :=
  if h₁ : w ≤ 1 / 4 then D.left y w ⟨by linarith [hw.1], h₁⟩
  else if h₂ : 3 / 4 ≤ w then D.left y (w - 1) ⟨by linarith, by linarith [hw.2]⟩
  else D.right y (w - 1 / 2) ⟨by linarith [not_le.mp h₁], by linarith [not_le.mp h₂]⟩

def projection (p : SpatialNeckCylinder) : D.sum.Carrier :=
  D.projectionAux p.1 (Int.fract p.2) ⟨Int.fract_nonneg _, Int.fract_lt_one _⟩

theorem projection_eq_aux (p : SpatialNeckCylinder) {w : ℝ} (hw : w ∈ Ico (0 : ℝ) 1)
    (h : Int.fract p.2 = w) : D.projection p = D.projectionAux p.1 w hw := by
  unfold projection
  subst h
  rfl

theorem projection_left (y : S2) {t : ℝ} (ht : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4)) (n : ℤ) :
    D.projection (y, t + n) = D.left y t ht := by
  rcases le_or_gt 0 t with h0 | h0
  · have hw : t ∈ Ico (0 : ℝ) 1 := ⟨h0, by linarith [ht.2]⟩
    rw [D.projection_eq_aux _ hw (Int.fract_eq_iff.mpr ⟨h0, hw.2, n, by simp⟩)]
    unfold projectionAux
    rw [dite_eq_left ht.2]
  · have hw : t + 1 ∈ Ico (0 : ℝ) 1 := ⟨by linarith [ht.1], by linarith⟩
    rw [D.projection_eq_aux _ hw (Int.fract_eq_iff.mpr ⟨hw.1, hw.2, n - 1, by push_cast; ring⟩)]
    unfold projectionAux
    rw [dite_eq_right (by linarith [ht.1]), dite_eq_left (by linarith [ht.1])]
    exact D.left_eq_left (by rw [add_sub_cancel_right])

theorem projection_right (y : S2) {t : ℝ} (ht : t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)) (n : ℤ) :
    D.projection (y, t + 1 / 2 + n) = D.right y t ht := by
  have hw : t + 1 / 2 ∈ Ico (0 : ℝ) 1 := ⟨by linarith [ht.1], by linarith [ht.2]⟩
  rw [D.projection_eq_aux _ hw (Int.fract_eq_iff.mpr ⟨hw.1, hw.2, n, by simp⟩)]
  unfold projectionAux
  rw [dite_eq_right (by linarith [ht.1]), dite_eq_right (by linarith [ht.2])]
  exact D.right_eq_right (by rw [add_sub_cancel_right])

theorem projection_cases (s : ℝ) :
    (∃ (n : ℤ) (t : ℝ), t ∈ Icc (-(1 / 4) : ℝ) (1 / 4) ∧ s = t + n) ∨
      ∃ (n : ℤ) (t : ℝ), t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) ∧ s = t + 1 / 2 + n := by
  have hs := Int.floor_add_fract s
  have h0 := Int.fract_nonneg s
  have h1 := Int.fract_lt_one s
  by_cases ha : Int.fract s ≤ 1 / 4
  · exact Or.inl ⟨⌊s⌋, Int.fract s, ⟨by linarith, ha⟩, by linarith⟩
  by_cases hb : 3 / 4 ≤ Int.fract s
  · exact Or.inl ⟨⌊s⌋ + 1, Int.fract s - 1, ⟨by linarith, by linarith⟩, by push_cast; linarith⟩
  · exact Or.inr ⟨⌊s⌋, Int.fract s - 1 / 2, ⟨by linarith [not_le.mp ha],
      by linarith [not_le.mp hb]⟩, by linarith⟩

theorem projection_add_int (p : SpatialNeckCylinder) (m : ℤ) :
    D.projection (p.1, p.2 + m) = D.projection p := by
  obtain ⟨y, s⟩ := p
  rcases projection_cases s with ⟨n, t, ht, rfl⟩ | ⟨n, t, ht, rfl⟩
  · rw [show t + (n : ℝ) + m = t + ((n + m : ℤ) : ℝ) by push_cast; ring, D.projection_left y ht,
      D.projection_left y ht]
  · rw [show t + 1 / 2 + (n : ℝ) + m = t + 1 / 2 + ((n + m : ℤ) : ℝ) by push_cast; ring,
      D.projection_right y ht, D.projection_right y ht]

theorem projection_neg (p : SpatialNeckCylinder) : D.projection (-p.1, -p.2) = D.projection p := by
  obtain ⟨y, s⟩ := p
  rcases projection_cases s with ⟨n, t, ht, rfl⟩ | ⟨n, t, ht, rfl⟩
  · have ht' : -t ∈ Icc (-(1 / 4) : ℝ) (1 / 4) := ⟨by linarith [ht.2], by linarith [ht.1]⟩
    rw [show -(t + (n : ℝ)) = -t + ((-n : ℤ) : ℝ) by push_cast; ring, D.projection_left _ ht',
      D.projection_left y ht]
    exact D.left_eq_left (D.core_neg y (Icc_subset_dihedralDomain ht))
  · have ht' : -t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) := ⟨by linarith [ht.2], by linarith [ht.1]⟩
    rw [show -(t + 1 / 2 + (n : ℝ)) = -t + 1 / 2 + ((-n - 1 : ℤ) : ℝ) by push_cast; ring,
      D.projection_right _ ht', D.projection_right y ht]
    exact D.right_eq_right (D.core_neg y (Icc_subset_dihedralDomain (Ioo_subset_Icc_self ht)))

theorem projection_cylinderAct {γ : CylinderIsometry} (hγ : γ ∈ dihedralGroup 0 (1 / 2))
    (p : SpatialNeckCylinder) : D.projection (cylinderAct γ p) = D.projection p := by
  refine dihedralGroup_le_cylinderInvariance D.projection D.projection_neg (fun p => ?_) hγ p
  rw [show 1 - p.2 = -p.2 + ((1 : ℤ) : ℝ) by push_cast; ring]
  exact (D.projection_add_int (-p.1, -p.2) 1).trans (D.projection_neg p)

theorem projection_eq_iff (a b : SpatialNeckCylinder) :
    D.projection a = D.projection b ↔ ∃ γ ∈ dihedralGroup 0 (1 / 2), cylinderAct γ a = b := by
  constructor
  · intro h
    obtain ⟨y, s⟩ := a
    obtain ⟨y', s'⟩ := b
    rcases projection_cases s with ⟨n, t, ht, rfl⟩ | ⟨n, t, ht, rfl⟩ <;>
      rcases projection_cases s' with ⟨n', t', ht', rfl⟩ | ⟨n', t', ht', rfl⟩
    · rw [D.projection_left y ht, D.projection_left y' ht'] at h
      rcases D.core_eq_core (Icc_subset_dihedralDomain ht) (Icc_subset_dihedralDomain ht')
        (D.core_eq_of_left_eq h) with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · obtain ⟨γ, hγ, hact⟩ := exists_dihedral_translation (n' - n)
        exact ⟨γ, hγ, by rw [hact]; exact Prod.ext rfl (by push_cast; ring)⟩
      · obtain ⟨γ, hγ, hact⟩ := exists_dihedral_reflection (n + n')
        exact ⟨γ, hγ, by rw [hact]; exact Prod.ext rfl (by push_cast; ring)⟩
    · rw [D.projection_left y ht, D.projection_right y' ht'] at h
      exact absurd h (D.left_ne_right ht ht')
    · rw [D.projection_right y ht, D.projection_left y' ht'] at h
      exact absurd h.symm (D.left_ne_right ht' ht)
    · rw [D.projection_right y ht, D.projection_right y' ht'] at h
      have hd := Icc_subset_dihedralDomain (Ioo_subset_Icc_self ht)
      have hd' := Icc_subset_dihedralDomain (Ioo_subset_Icc_self ht')
      rcases D.core_eq_core hd hd' (D.core_eq_of_right_eq h) with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · obtain ⟨γ, hγ, hact⟩ := exists_dihedral_translation (n' - n)
        exact ⟨γ, hγ, by rw [hact]; exact Prod.ext rfl (by push_cast; ring)⟩
      · obtain ⟨γ, hγ, hact⟩ := exists_dihedral_reflection (n + n' + 1)
        exact ⟨γ, hγ, by rw [hact]; exact Prod.ext rfl (by push_cast; ring)⟩
  · rintro ⟨γ, hγ, rfl⟩
    exact (D.projection_cylinderAct hγ a).symm

theorem exists_projection_eq_inl (q : D.chart.toBallChart.Punctured) :
    ∃ p, D.projection p = ConnectedSumQuotient.inl D.chart.toBallChart D.chart.toBallChart
      boundaryAttachment.1.toHomeomorph q := by
  obtain ⟨y, t, ht, hq⟩ := D.exists_core_eq q.1 q.2
  have ht' : t ∈ Icc (-(1 / 4) : ℝ) (1 / 4) := ⟨by linarith [ht.1], ht.2⟩
  refine ⟨(y, t + ((0 : ℤ) : ℝ)), ?_⟩
  rw [D.projection_left y ht']
  exact congrArg _ (Subtype.ext hq)

theorem projection_surjective : Surjective D.projection := by
  intro z
  rcases ConnectedSumQuotient.jointly_surjective _ _ _ z with ⟨q, rfl⟩ | ⟨q, rfl⟩
  · exact D.exists_projection_eq_inl q
  obtain ⟨y, t, ht, hq⟩ := D.exists_core_eq q.1 q.2
  rcases lt_or_eq_of_le ht.2 with hlt | rfl
  · have ht' : t ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) := ⟨by linarith [ht.1], hlt⟩
    refine ⟨(y, t + 1 / 2 + ((0 : ℤ) : ℝ)), ?_⟩
    rw [D.projection_right y ht']
    exact congrArg _ (Subtype.ext hq)
  · have hb : q = D.chart.toBallChart.boundaryMap
        (boundaryAttachment.1.toHomeomorph (-y)) := by
      apply Subtype.ext
      rw [← hq, D.core_quarter, BallChart.boundaryMap_val]
      congr 1
      change (y : E3) = -((-y : S2) : E3)
      rw [coe_neg_sphere, neg_neg]
    rw [hb, ← ConnectedSumQuotient.boundary_eq]
    exact D.exists_projection_eq_inl _

theorem eventually_snd_mem {y : S2} {s : ℝ} {U : Set ℝ} (hU : IsOpen U) (hs : s ∈ U) :
    ∀ᶠ p : SpatialNeckCylinder in 𝓝 (y, s), p.2 ∈ U :=
  continuous_snd.continuousAt.preimage_mem_nhds (hU.mem_nhds hs)

theorem isLocalDiffeomorphAt_projection_left {y : S2} {s : ℝ}
    (hs : s ∈ Ioo (-(1 / 4) : ℝ) (1 / 4)) :
    IsLocalDiffeomorphAt CM (𝓡 3) ∞ D.projection (y, s) := by
  have hs' := Icc_subset_dihedralDomain (Ioo_subset_Icc_self hs)
  refine isLocalDiffeomorphAt_of_eventually_factor
    (smoothConnectedSum X X D.chart D.chart boundaryAttachment).interiorLeft_localDiffeomorph
    (D.isLocalDiffeomorphAt_core hs') (V := D.chart.toBallChart.interior) ?_ ?_
  · filter_upwards [eventually_snd_mem isOpen_Ioo hs] with p hp
    exact D.core_not_mem_closedBall hp
  · filter_upwards [eventually_snd_mem isOpen_Ioo hs] with p hp hmem
    obtain ⟨y', s'⟩ := p
    have hL := D.projection_left y' (Ioo_subset_Icc_self hp) 0
    rw [Int.cast_zero, add_zero] at hL
    exact hL

theorem isLocalDiffeomorphAt_projection_right {y : S2} {s : ℝ}
    (hs : s ∈ Ioo (1 / 4 : ℝ) (3 / 4)) :
    IsLocalDiffeomorphAt CM (𝓡 3) ∞ D.projection (y, s) := by
  have hs₀ : s - 1 / 2 ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) := ⟨by linarith [hs.1], by linarith [hs.2]⟩
  have hd := Icc_subset_dihedralDomain (Ioo_subset_Icc_self hs₀)
  have hshift : IsLocalDiffeomorphAt CM CM ∞ (Prod.map id (fun t : ℝ => 1 * t + -(1 / 2)))
      (y, s) :=
    isLocalDiffeomorphAt_prodMap_id (isLocalDiffeomorphAt_affine_line 1 _ one_ne_zero s)
  have hcore : IsLocalDiffeomorphAt CM (𝓡 3) ∞ (fun p : SpatialNeckCylinder => D.core p.1 p.2)
      (Prod.map id (fun t : ℝ => 1 * t + -(1 / 2)) (y, s)) := by
    have e : Prod.map id (fun t : ℝ => 1 * t + -(1 / 2)) (y, s) = (y, s - 1 / 2) :=
      Prod.ext rfl (show 1 * s + -(1 / 2) = s - 1 / 2 by ring)
    rw [e]
    exact D.isLocalDiffeomorphAt_core hd
  have hg : IsLocalDiffeomorphAt CM (𝓡 3) ∞
      (fun p : SpatialNeckCylinder => D.core p.1 (p.2 - 1 / 2)) (y, s) := by
    have h := hshift.comp (𝓡 3) X.Carrier hcore
    refine DifferentialGeometry.IsLocalDiffeomorphAt.of_eventuallyEq
      (Eventually.of_forall fun p => ?_) h
    change D.core p.1 (p.2 - 1 / 2) = D.core p.1 (1 * p.2 + -(1 / 2))
    rw [one_mul, sub_eq_add_neg]
  refine isLocalDiffeomorphAt_of_eventually_factor
    (smoothConnectedSum X X D.chart D.chart boundaryAttachment).interiorRight_localDiffeomorph
    hg (V := D.chart.toBallChart.interior) ?_ ?_
  · filter_upwards [eventually_snd_mem isOpen_Ioo hs] with p hp
    exact D.core_not_mem_closedBall ⟨by linarith [hp.1], by linarith [hp.2]⟩
  · filter_upwards [eventually_snd_mem isOpen_Ioo hs] with p hp hmem
    obtain ⟨y', s'⟩ := p
    have hp' : s' - 1 / 2 ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) :=
      ⟨by linarith [hp.1], by linarith [hp.2]⟩
    have hR := D.projection_right y' hp' 0
    rw [Int.cast_zero, add_zero, sub_add_cancel] at hR
    exact hR

def seamParam (s : ℝ) : ℝ := 5 / 2 - 2 * dihedralProfile s / dihedralNeck

theorem seamParam_quarter : seamParam (1 / 4) = 1 / 2 := by
  have hk := dihedralNeck_pos.ne'
  unfold seamParam
  rw [dihedralProfile_quarter]
  field_simp
  norm_num

theorem isLocalDiffeomorphAt_seamParam :
    IsLocalDiffeomorphAt 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ) ∞ seamParam (1 / 4) := by
  have hq : (1 / 4 : ℝ) ∈ dihedralDomain := Icc_subset_dihedralDomain ⟨by norm_num, le_rfl⟩
  obtain ⟨d, hd, hD⟩ := exists_hasDerivAt_dihedralProfile hq
  have hk := dihedralNeck_pos
  refine isLocalDiffeomorphAt_real isOpen_dihedralDomain ?_ hq
    (neg_ne_zero.mpr (div_ne_zero (mul_ne_zero two_ne_zero hd.ne) hk.ne'))
    (((hD.const_mul 2).div_const dihedralNeck).const_sub (5 / 2))
  exact contDiffOn_const.sub ((contDiffOn_const.mul contDiffOn_dihedralProfile).div_const _)

theorem contDiffOn_seamParam : ContDiffOn ℝ ∞ seamParam dihedralDomain :=
  contDiffOn_const.sub ((contDiffOn_const.mul contDiffOn_dihedralProfile).div_const _)

theorem continuousAt_seamParam : ContinuousAt seamParam (1 / 4) :=
  contDiffOn_seamParam.continuousOn.continuousAt (isOpen_dihedralDomain.mem_nhds
    (Icc_subset_dihedralDomain ⟨by norm_num, le_rfl⟩))

theorem isLocalDiffeomorphAt_projection_seam (y : S2) :
    IsLocalDiffeomorphAt CM (𝓡 3) ∞ D.projection (y, 1 / 4) := by
  have hk := dihedralNeck_pos
  have hg : IsLocalDiffeomorphAt CM CM ∞ (Prod.map id seamParam) (y, 1 / 4) :=
    isLocalDiffeomorphAt_prodMap_id isLocalDiffeomorphAt_seamParam
  have hV : ∀ᶠ p : SpatialNeckCylinder in 𝓝 (y, 1 / 4),
      seamParam p.2 ∈ Ioo (-(1 / 2) : ℝ) (3 / 2) := by
    have h := continuousAt_seamParam.preimage_mem_nhds (isOpen_Ioo.mem_nhds
      (show seamParam (1 / 4) ∈ Ioo (-(1 / 2) : ℝ) (3 / 2) by
        rw [seamParam_quarter]; constructor <;> norm_num))
    exact (continuous_snd.continuousAt (x := (y, (1 / 4 : ℝ)))).preimage_mem_nhds h
  refine isLocalDiffeomorphAt_of_eventually_factor
    (ConnectedSumQuotient.isLocalDiffeomorph_connectingCylinderOpen D.chart D.chart
      boundaryAttachment) hg (V := ConnectedSumQuotient.connectingCylinderDomain) ?_ ?_
  · filter_upwards [hV] with p hp
    exact ⟨mem_univ _, hp⟩
  · filter_upwards [eventually_snd_mem isOpen_Ioo
      (show (1 / 4 : ℝ) ∈ Ioo (1 / 12) (5 / 12) by constructor <;> norm_num)] with p hp hmem
    obtain ⟨y', s'⟩ := p
    have hd : s' ∈ dihedralDomain := ⟨by linarith [hp.1], hp.2⟩
    have hrefl := dihedralProfile_add_reflect hd
    have hτ : (1 - 2 * seamParam s') / 4 = dihedralProfile s' / dihedralNeck - 1 := by
      unfold seamParam
      field_simp
      ring
    change D.projection (y', s') = ConnectedSumQuotient.collarMap D.chart.toBallChart
      D.chart.toBallChart boundaryAttachment.val (y', ⟨(1 - 2 * seamParam s') / 4, _⟩)
    rcases le_or_gt s' (1 / 4) with hle | hgt
    · have hL := D.projection_left y' (⟨by linarith [hp.1], hle⟩ :
        s' ∈ Icc (-(1 / 4) : ℝ) (1 / 4)) 0
      rw [Int.cast_zero, add_zero] at hL
      rw [hL]
      have hnn : 0 ≤ (1 - 2 * seamParam s') / 4 := by
        rw [hτ, sub_nonneg, le_div_iff₀ hk, one_mul]
        by_contra hlt
        have := (dihedralProfile_lt_neck_iff hd).mp (not_le.mp hlt)
        linarith
      rw [ConnectedSumQuotient.collarMap_of_nonneg _ _ _ _ hnn]
      unfold left
      refine congrArg (ConnectedSumQuotient.inl _ _ _) (Subtype.ext ?_)
      change D.core y' s' = D.chart.chart ((1 + (1 - 2 * seamParam s') / 4) • (y' : E3))
      apply D.core_eq_chart
      rw [hτ]
      field_simp
      ring
    · have hneg : (1 - 2 * seamParam s') / 4 < 0 := by
        rw [hτ, sub_neg, div_lt_iff₀ hk, one_mul]
        exact (dihedralProfile_lt_neck_iff hd).mpr hgt
      have hr : s' - 1 / 2 ∈ Ioo (-(1 / 4) : ℝ) (1 / 4) :=
        ⟨by linarith, by linarith [hp.2]⟩
      have hR := D.projection_right y' hr 0
      rw [Int.cast_zero, add_zero, sub_add_cancel] at hR
      rw [hR, ConnectedSumQuotient.collarMap_of_neg _ _ _ _ hneg]
      unfold right
      refine congrArg (ConnectedSumQuotient.inr _ _ _) (Subtype.ext ?_)
      change D.core y' (s' - 1 / 2) = D.chart.chart
        ((1 - (1 - 2 * seamParam s') / 4) • ((-y' : S2) : E3))
      rw [← D.core_neg y' (Icc_subset_dihedralDomain (Ioo_subset_Icc_self hr))]
      apply D.core_eq_chart
      have e : dihedralNeck * (1 - (dihedralProfile s' / dihedralNeck - 1)) =
          2 * dihedralNeck - dihedralProfile s' := by
        field_simp
        ring
      rw [hτ, show -(s' - 1 / 2) = 1 / 2 - s' by ring, e]
      linarith

theorem isLocalDiffeomorphAt_projection_fundamental {y : S2} {s : ℝ}
    (hs : s ∈ Icc (-(1 / 4) : ℝ) (3 / 4)) (hs' : s ≠ 3 / 4) :
    IsLocalDiffeomorphAt CM (𝓡 3) ∞ D.projection (y, s) := by
  rcases lt_trichotomy s (1 / 4) with hlt | rfl | hgt
  · rcases eq_or_lt_of_le hs.1 with heq | hlo
    · subst heq
      have hN : IsLocalDiffeomorphAt CM CM ∞
          (Prod.map (DifferentialGeometry.Geometry.sphereDiffeo (n := 2)
            (LinearIsometryEquiv.neg ℝ)) (fun t : ℝ => -1 * t + 0)) (y, -(1 / 4)) :=
        isLocalDiffeomorphAt_cylinder_reparam _
          (isLocalDiffeomorphAt_affine_line (-1) 0 (by norm_num) _)
      refine isLocalDiffeomorphAt_of_invariant hN (fun p => ?_) ?_
      · have hp : Prod.map (DifferentialGeometry.Geometry.sphereDiffeo (n := 2)
            (LinearIsometryEquiv.neg ℝ)) (fun t : ℝ => -1 * t + 0) p = (-p.1, -p.2) :=
          Prod.ext (Subtype.ext (by simp [coe_neg_sphere])) (by simp)
        rw [hp, D.projection_neg]
      · have hp : Prod.map (DifferentialGeometry.Geometry.sphereDiffeo (n := 2)
            (LinearIsometryEquiv.neg ℝ)) (fun t : ℝ => -1 * t + 0) (y, -(1 / 4)) =
            (-y, 1 / 4) :=
          Prod.ext (Subtype.ext (by simp [coe_neg_sphere])) (by norm_num)
        rw [hp]
        exact D.isLocalDiffeomorphAt_projection_seam (-y)
    · exact D.isLocalDiffeomorphAt_projection_left ⟨hlo, hlt⟩
  · exact D.isLocalDiffeomorphAt_projection_seam y
  · exact D.isLocalDiffeomorphAt_projection_right ⟨hgt, lt_of_le_of_ne hs.2 hs'⟩

theorem isLocalDiffeomorph_projection : IsLocalDiffeomorph CM (𝓡 3) ∞ D.projection := by
  rintro ⟨y, s⟩
  set n : ℤ := ⌊s + 1 / 4⌋
  have h1 := Int.floor_le (s + 1 / 4)
  have h2 := Int.lt_floor_add_one (s + 1 / 4)
  have hT : IsLocalDiffeomorphAt CM CM ∞ (Prod.map id (fun t : ℝ => 1 * t + -(n : ℝ))) (y, s) :=
    isLocalDiffeomorphAt_prodMap_id (isLocalDiffeomorphAt_affine_line 1 _ one_ne_zero s)
  have hTp : ∀ p : SpatialNeckCylinder, Prod.map id (fun t : ℝ => 1 * t + -(n : ℝ)) p =
      (p.1, p.2 + ((-n : ℤ) : ℝ)) := by
    intro p
    refine Prod.ext rfl ?_
    change 1 * p.2 + -(n : ℝ) = p.2 + ((-n : ℤ) : ℝ)
    push_cast
    ring
  refine isLocalDiffeomorphAt_of_invariant hT (fun p => by rw [hTp, D.projection_add_int]) ?_
  rw [hTp]
  apply D.isLocalDiffeomorphAt_projection_fundamental
  · constructor <;> push_cast <;> linarith
  · push_cast
    intro h
    linarith

def presentation : CylinderQuotientPresentation (dihedralGroup 0 (1 / 2)) D.sum.Carrier where
  proj := D.projection
  isLocalDiffeomorph := D.isLocalDiffeomorph_projection
  surjective := D.projection_surjective
  fibres := D.projection_eq_iff

end DihedralChart

theorem nonempty_connectedSum_dihedralPresentation (X : ConnectedClosedOrientedManifold.{u} 3)
    (P : AntipodalSpherePresentation X.Carrier) :
    Nonempty (CylinderQuotientPresentation (dihedralGroup 0 (1 / 2))
      (connectedSum X X).Carrier) := by
  obtain ⟨D⟩ := nonempty_dihedralChart X P
  obtain ⟨e⟩ := nonempty_orientedDiffeomorph_smoothConnectedSum_of_charts D.chart
    (orientedBallChart X) D.chart (orientedBallChart X) boundaryAttachment
  exact ⟨{ proj := e.1 ∘ D.projection
           isLocalDiffeomorph := DifferentialGeometry.isLocalDiffeomorph_comp
             e.1.isLocalDiffeomorph D.isLocalDiffeomorph_projection
           surjective := e.1.surjective.comp D.projection_surjective
           fibres := fun a b => e.1.injective.eq_iff.trans (D.projection_eq_iff a b) }⟩

def projectiveThreeSpaceAntipodalPresentation :
    AntipodalSpherePresentation projectiveThreeSpaceLift.{u}.Carrier where
  proj x := ClosedOrientedManifold.uliftDiffeomorph.{0, u}
    SphericalSpaceFormGroup.antipodal.manifold.toClosedOrientedManifold
    (SphericalSpaceFormGroup.antipodal.projection x)
  isLocalDiffeomorph := DifferentialGeometry.isLocalDiffeomorph_comp
    (N := SphericalSpaceFormGroup.antipodal.Orbit)
    (ClosedOrientedManifold.uliftDiffeomorph.{0, u}
      SphericalSpaceFormGroup.antipodal.manifold.toClosedOrientedManifold).isLocalDiffeomorph
    SphericalSpaceFormGroup.antipodal.projection_isLocalDiffeomorph
  surjective := (ClosedOrientedManifold.uliftDiffeomorph.{0, u}
    SphericalSpaceFormGroup.antipodal.manifold.toClosedOrientedManifold).surjective.comp
    SphericalSpaceFormGroup.antipodal.projection_surjective
  fibres x y := (ClosedOrientedManifold.uliftDiffeomorph.{0, u}
    SphericalSpaceFormGroup.antipodal.manifold.toClosedOrientedManifold).injective.eq_iff.trans
    (SphericalSpaceFormGroup.antipodal_projection_eq_iff x y)

theorem projectiveSumStandardDihedralPresentation :
    ProjectiveSumStandardDihedralPresentation.{u} :=
  nonempty_connectedSum_dihedralPresentation projectiveThreeSpaceLift.{u}
    projectiveThreeSpaceAntipodalPresentation

theorem dihedralCylinderQuotientIsProjectiveSum :
    DihedralCylinderQuotientIsProjectiveSum.{u} :=
  dihedralCylinderQuotientIsProjectiveSum_of_standard projectiveSumStandardDihedralPresentation

theorem sphericalProductStandardConnectedSum_of_universalCover_only
    (hU : SphericalProductUniversalCover.{u}) :
    GC.Endpoint.SphericalProductStandardConnectedSum.{u} :=
  sphericalProductStandardConnectedSum_of_universalCover_of_projectiveSum hU
    projectiveSumStandardDihedralPresentation

end GC.Geometry.SphericalProduct
