import DifferentialGeometry.Geometry.Thurston.ScrewLift
import DifferentialGeometry.Geometry.Metric.Sphere.Isometry.OrthogonalAction
import Mathlib.Analysis.Quaternion

/-!
# Spherical screw lifts on the round three-sphere

The global model of the spherical connection model is the round unit sphere `RoundThree` with
its Hopf fibration. A point `u` is read as the quaternion `s3Quat u = ⟨u₀, -u₃, u₂, -u₁⟩`; the
Hopf map is `u ↦ Im (q k q̄)` (`hopfS3`), the fibre translation by `t` is right multiplication by
`e^{-kt}` and base rotations are left multiplications. The real-lift group
`S3Lift = unitary ℍ × Multiplicative ℝ` acts by isometries (`s3Perm`, `s3Diffeo_isometry`) with
kernel generated by `s3Period = (-1, π)`; lifted identities record this integer period and
their images in `Equiv.Perm RoundThree` are the periodic ones. `screwAtS3 v p q ℓ` and
`screwGeneratorS3 v p a ℓ` are the clockwise screw and the screw generator about the Hopf fibre
through `hopfParam v`, with the conventions of `ScrewLift.lean`.
-/

set_option autoImplicit false
noncomputable section
open DifferentialGeometry DifferentialGeometry.Geometry
open scoped Manifold ContDiff

namespace GC.Geometry

local instance factFinrankEuclideanFourS3 :
    Fact (Module.finrank ℝ (EuclideanSpace ℝ (Fin 4)) = 3 + 1) :=
  ⟨by simp⟩

abbrev S3Lift : Type := unitary (Quaternion ℝ) × Multiplicative ℝ

def s3Quat : EuclideanSpace ℝ (Fin 4) ≃ₗᵢ[ℝ] Quaternion ℝ where
  toFun u := ⟨u 0, -u 3, u 2, -u 1⟩
  invFun q := !₂[q.re, -q.imK, q.imJ, -q.imI]
  map_add' u v := by ext <;> simp <;> ring
  map_smul' c u := by ext <;> simp
  left_inv u := by ext i; fin_cases i <;> simp
  right_inv q := by ext <;> simp
  norm_map' u := by
    rw [← Quaternion.linearIsometryEquivTuple.norm_map, EuclideanSpace.norm_eq,
      EuclideanSpace.norm_eq]
    congr 1
    simp [Fin.sum_univ_four]
    ring

@[simp] theorem s3Quat_re (u : EuclideanSpace ℝ (Fin 4)) : (s3Quat u).re = u 0 := rfl
@[simp] theorem s3Quat_imI (u : EuclideanSpace ℝ (Fin 4)) : (s3Quat u).imI = -u 3 := rfl
@[simp] theorem s3Quat_imJ (u : EuclideanSpace ℝ (Fin 4)) : (s3Quat u).imJ = u 2 := rfl
@[simp] theorem s3Quat_imK (u : EuclideanSpace ℝ (Fin 4)) : (s3Quat u).imK = -u 1 := rfl

def s3FibreUnit (t : ℝ) : Quaternion ℝ := ⟨Real.cos t, 0, 0, -Real.sin t⟩

private theorem mem_unitary_of_normSq {a : Quaternion ℝ} (h : Quaternion.normSq a = 1) :
    a ∈ unitary (Quaternion ℝ) :=
  Unitary.mem_iff.mpr ⟨by rw [Quaternion.star_mul_self, h]; rfl,
    by rw [Quaternion.self_mul_star, h]; rfl⟩

private theorem s3FibreUnit_mem (t : ℝ) : s3FibreUnit t ∈ unitary (Quaternion ℝ) :=
  mem_unitary_of_normSq (by
    rw [Quaternion.normSq_def']
    simp only [s3FibreUnit]
    linear_combination Real.cos_sq_add_sin_sq t)

private def s3FibreUnitary (t : ℝ) : unitary (Quaternion ℝ) := ⟨s3FibreUnit t, s3FibreUnit_mem t⟩

theorem s3FibreUnit_add (s t : ℝ) : s3FibreUnit (s + t) = s3FibreUnit s * s3FibreUnit t := by
  ext <;> simp [s3FibreUnit, Real.cos_add, Real.sin_add]

theorem s3FibreUnit_zero : s3FibreUnit 0 = 1 := by
  ext <;> simp [s3FibreUnit]

theorem s3FibreUnit_comm (s t : ℝ) :
    s3FibreUnit s * s3FibreUnit t = s3FibreUnit t * s3FibreUnit s := by
  rw [← s3FibreUnit_add, ← s3FibreUnit_add, add_comm]

private def quatLR (g r : unitary (Quaternion ℝ)) : Quaternion ℝ ≃ₗᵢ[ℝ] Quaternion ℝ where
  toFun q := (g : Quaternion ℝ) * q * r
  invFun q := star (g : Quaternion ℝ) * q * star (r : Quaternion ℝ)
  map_add' a b := by simp [mul_add, add_mul]
  map_smul' c a := by simp
  left_inv q := by
    change star (g : Quaternion ℝ) * ((g : Quaternion ℝ) * q * r) * star (r : Quaternion ℝ) = q
    rw [← mul_assoc, ← mul_assoc, Unitary.star_mul_self_of_mem g.2, one_mul, mul_assoc,
      Unitary.mul_star_self_of_mem r.2, mul_one]
  right_inv q := by
    change (g : Quaternion ℝ) * (star (g : Quaternion ℝ) * q * star (r : Quaternion ℝ)) * r = q
    rw [← mul_assoc, ← mul_assoc, Unitary.mul_star_self_of_mem g.2, one_mul, mul_assoc,
      Unitary.star_mul_self_of_mem r.2, mul_one]
  norm_map' q := by
    change ‖(g : Quaternion ℝ) * q * r‖ = ‖q‖
    rw [norm_mul, norm_mul, CStarRing.norm_coe_unitary, CStarRing.norm_coe_unitary, one_mul,
      mul_one]

def s3QuatAct (x : S3Lift) : Quaternion ℝ ≃ₗᵢ[ℝ] Quaternion ℝ :=
  quatLR x.1 (s3FibreUnitary (Multiplicative.toAdd x.2))

theorem s3QuatAct_apply (x : S3Lift) (q : Quaternion ℝ) :
    s3QuatAct x q = (x.1 : Quaternion ℝ) * q * s3FibreUnit (Multiplicative.toAdd x.2) :=
  rfl

def s3Act (x : S3Lift) : EuclideanSpace ℝ (Fin 4) ≃ₗᵢ[ℝ] EuclideanSpace ℝ (Fin 4) :=
  s3Quat.trans ((s3QuatAct x).trans s3Quat.symm)

theorem s3Act_apply (x : S3Lift) (u : EuclideanSpace ℝ (Fin 4)) :
    s3Quat (s3Act x u) =
      (x.1 : Quaternion ℝ) * s3Quat u * s3FibreUnit (Multiplicative.toAdd x.2) := by
  simp [s3Act, s3QuatAct, quatLR, s3FibreUnitary]

def s3Diffeo (x : S3Lift) : RoundThree ≃ₘ⟮𝓡 3, 𝓡 3⟯ RoundThree :=
  sphereDiffeo (n := 3) (s3Act x)

theorem s3Diffeo_coe (x : S3Lift) (u : RoundThree) :
    ((s3Diffeo x u : RoundThree) : EuclideanSpace ℝ (Fin 4)) = s3Act x u := rfl

private theorem s3Act_one (u : EuclideanSpace ℝ (Fin 4)) : s3Act 1 u = u := by
  apply s3Quat.injective
  rw [s3Act_apply]
  simp [s3FibreUnit_zero]

private theorem s3Act_mul (x y : S3Lift) (u : EuclideanSpace ℝ (Fin 4)) :
    s3Act (x * y) u = s3Act x (s3Act y u) := by
  apply s3Quat.injective
  rw [s3Act_apply, s3Act_apply, s3Act_apply]
  simp only [Prod.fst_mul, Prod.snd_mul, toAdd_mul, Submonoid.coe_mul, s3FibreUnit_add,
    mul_assoc]
  rw [s3FibreUnit_comm]

def s3Perm : S3Lift →* Equiv.Perm RoundThree where
  toFun x := (s3Diffeo x).toEquiv
  map_one' := Equiv.ext fun u => Subtype.ext (s3Act_one u)
  map_mul' x y := Equiv.ext fun u => Subtype.ext (s3Act_mul x y u)

theorem s3Perm_apply (x : S3Lift) : s3Perm x = (s3Diffeo x).toEquiv := rfl

theorem s3Diffeo_isometry (x : S3Lift) :
    Diffeomorph.pullbackMetric sphericalModelMetric (s3Diffeo x) = sphericalModelMetric :=
  pullbackMetric_round_eq (n := 3) (s3Act x)

def s3Period : S3Lift := (-1, Multiplicative.ofAdd Real.pi)

def fibreLiftS3 (t : ℝ) : S3Lift := (1, Multiplicative.ofAdd t)

def fibreTranslationS3 (t : ℝ) : RoundThree ≃ₘ⟮𝓡 3, 𝓡 3⟯ RoundThree := s3Diffeo (fibreLiftS3 t)

theorem s3FibreUnit_pi : s3FibreUnit Real.pi = -1 := by
  ext <;> simp [s3FibreUnit]

theorem s3Perm_s3Period : s3Perm s3Period = 1 := by
  apply Equiv.ext
  intro u
  apply Subtype.ext
  apply s3Quat.injective
  change s3Quat (s3Act s3Period u) = s3Quat u
  rw [s3Act_apply]
  simp [s3Period, s3FibreUnit_pi, Unitary.coe_neg]

private def s3BasePoint : RoundThree :=
  ⟨!₂[1, 0, 0, 0], by simp [EuclideanSpace.norm_eq, Fin.sum_univ_four]⟩

private def s3IPoint : RoundThree :=
  ⟨!₂[0, 0, 0, -1], by simp [EuclideanSpace.norm_eq, Fin.sum_univ_four]⟩

private theorem s3Perm_fix {x : S3Lift} (h : s3Perm x = 1) (u : RoundThree) :
    (x.1 : Quaternion ℝ) * s3Quat u * s3FibreUnit (Multiplicative.toAdd x.2) = s3Quat u := by
  rw [← s3Act_apply]
  exact congrArg (fun y : RoundThree => s3Quat y) (Equiv.ext_iff.mp h u)

theorem s3Perm_eq_one_iff (x : S3Lift) : s3Perm x = 1 ↔ x ∈ Subgroup.zpowers s3Period := by
  constructor
  · intro h
    set t := Multiplicative.toAdd x.2 with ht
    have h1 := s3Perm_fix h s3BasePoint
    have h2 := s3Perm_fix h s3IPoint
    have hg : (x.1 : Quaternion ℝ) = star (s3FibreUnit t) := by
      have hs := Unitary.mul_star_self_of_mem (s3FibreUnit_mem t)
      have hb : s3Quat s3BasePoint = 1 := by ext <;> simp [s3BasePoint]
      rw [hb, mul_one] at h1
      calc (x.1 : Quaternion ℝ) = x.1 * s3FibreUnit t * star (s3FibreUnit t) := by
            rw [mul_assoc, hs, mul_one]
        _ = star (s3FibreUnit t) := by rw [h1, one_mul]
    rw [hg] at h2
    have hi := congrArg (fun q : Quaternion ℝ => q.imI) h2
    simp [s3IPoint, s3FibreUnit] at hi
    have hS : Real.sin t = 0 := by
      have hc := Real.cos_sq_add_sin_sq t
      nlinarith [sq_nonneg (Real.sin t)]
    obtain ⟨m, hm⟩ := Real.sin_eq_zero_iff.mp hS
    refine Subgroup.mem_zpowers_iff.mpr ⟨m, ?_⟩
    have hcos := Real.cos_int_mul_pi m
    rw [hm] at hcos
    apply Prod.ext
    · rw [Prod.pow_fst]
      apply Subtype.ext
      rw [hg]
      change (((-1 : unitary (Quaternion ℝ)) ^ m : unitary (Quaternion ℝ)) : Quaternion ℝ) = _
      rcases Int.even_or_odd m with he | ho
      · rw [he.neg_one_zpow] at hcos ⊢
        ext <;> simp [s3FibreUnit, hcos, hS]
      · rw [ho.neg_one_zpow] at hcos ⊢
        ext <;> simp [s3FibreUnit, hcos, hS, Unitary.coe_neg]
    · rw [Prod.pow_snd]
      apply Multiplicative.toAdd.injective
      rw [toAdd_zpow]
      simp [s3Period, ← ht, ← hm, zsmul_eq_mul]
  · rintro ⟨m, rfl⟩
    rw [map_zpow, s3Perm_s3Period, one_zpow]

theorem fibreLiftS3_two_pi : fibreLiftS3 (2 * Real.pi) = s3Period ^ (2 : ℕ) := by
  apply Prod.ext
  · simp [fibreLiftS3, s3Period]
  · apply Multiplicative.toAdd.injective
    simp [fibreLiftS3, s3Period, toAdd_pow]

theorem fibreTranslationS3_eq_one_iff (t : ℝ) :
    (fibreTranslationS3 t).toEquiv = 1 ↔ ∃ m : ℤ, t = 2 * Real.pi * m := by
  constructor
  · intro h
    have h1 := s3Perm_fix (x := fibreLiftS3 t) h s3BasePoint
    have hb : s3Quat s3BasePoint = 1 := by ext <;> simp [s3BasePoint]
    rw [hb] at h1
    have hr : Real.cos t = 1 := by
      simpa [fibreLiftS3, s3FibreUnit] using congrArg (fun q : Quaternion ℝ => q.re) h1
    obtain ⟨m, hm⟩ := (Real.cos_eq_one_iff t).mp hr
    exact ⟨m, by rw [← hm]; ring⟩
  · rintro ⟨m, rfl⟩
    apply Equiv.ext
    intro u
    apply Subtype.ext
    apply s3Quat.injective
    change s3Quat (s3Act (fibreLiftS3 _) u) = s3Quat u
    rw [s3Act_apply]
    have hc : Real.cos (2 * Real.pi * m) = 1 := by
      rw [show 2 * Real.pi * m = m * (2 * Real.pi) by ring]
      exact Real.cos_int_mul_two_pi m
    have hs : Real.sin (2 * Real.pi * m) = 0 := by
      rw [show 2 * Real.pi * m = ((2 * m : ℤ) : ℝ) * Real.pi by push_cast; ring]
      exact Real.sin_int_mul_pi _
    have he : s3FibreUnit (2 * Real.pi * m) = 1 := by
      ext <;> simp [s3FibreUnit, hc, hs]
    simp [fibreLiftS3, he]

private def quatIm (w : Quaternion ℝ) : EuclideanSpace ℝ (Fin 3) := !₂[w.imI, w.imJ, w.imK]

private def vecQuat (n : EuclideanSpace ℝ (Fin 3)) : Quaternion ℝ := ⟨0, n 0, n 1, n 2⟩

private def quatK : Quaternion ℝ := ⟨0, 0, 0, 1⟩

def hopfS3 (u : EuclideanSpace ℝ (Fin 4)) : EuclideanSpace ℝ (Fin 3) :=
  quatIm (s3Quat u * quatK * star (s3Quat u))

def coneAxis (v : ModelCoordinates) : EuclideanSpace ℝ (Fin 3) :=
  (1 + planeDot v v)⁻¹ • !₂[2 * v 0, 2 * v 1, 1 - planeDot v v]

theorem norm_coneAxis (v : ModelCoordinates) : ‖coneAxis v‖ = 1 := by
  have hD : 0 < 1 + planeDot v v := by have := planeDot_self_nonneg v; linarith
  rw [coneAxis, norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hD, inv_mul_eq_one₀ hD.ne',
    EuclideanSpace.norm_eq, eq_comm, Real.sqrt_eq_iff_mul_self_eq (by positivity) hD.le]
  simp only [Fin.sum_univ_three, Real.norm_eq_abs, sq_abs]
  simp [planeDot]
  ring

private theorem vecQuat_quatIm {w : Quaternion ℝ} (h : w.re = 0) : vecQuat (quatIm w) = w := by
  ext <;> simp [vecQuat, quatIm, h]

private theorem re_conj_quatK (q : Quaternion ℝ) : (q * quatK * star q).re = 0 := by
  simp [quatK]
  ring

private theorem s3FibreUnit_quatK (t : ℝ) :
    s3FibreUnit t * quatK * star (s3FibreUnit t) = quatK := by
  have hs := Unitary.mul_star_self_of_mem (s3FibreUnit_mem t)
  have hc : s3FibreUnit t * quatK = quatK * s3FibreUnit t := by
    ext <;> simp [s3FibreUnit, quatK]
  rw [hc, mul_assoc, hs, mul_one]

def quatRotate (g : unitary (Quaternion ℝ)) (n : EuclideanSpace ℝ (Fin 3)) :
    EuclideanSpace ℝ (Fin 3) :=
  let w := (g : Quaternion ℝ) * ⟨0, n 0, n 1, n 2⟩ * star (g : Quaternion ℝ)
  !₂[w.imI, w.imJ, w.imK]

theorem hopfS3_s3Act (x : S3Lift) (u : EuclideanSpace ℝ (Fin 4)) :
    hopfS3 (s3Act x u) = quatRotate x.1 (hopfS3 u) := by
  have key : s3Quat (s3Act x u) * quatK * star (s3Quat (s3Act x u)) =
      (x.1 : Quaternion ℝ) * (s3Quat u * quatK * star (s3Quat u)) * star (x.1 : Quaternion ℝ) := by
    rw [s3Act_apply, star_mul, star_mul]
    have he := s3FibreUnit_quatK (Multiplicative.toAdd x.2)
    calc (x.1 : Quaternion ℝ) * s3Quat u * s3FibreUnit (Multiplicative.toAdd x.2) * quatK *
          (star (s3FibreUnit (Multiplicative.toAdd x.2)) *
            (star (s3Quat u) * star (x.1 : Quaternion ℝ)))
        = (x.1 : Quaternion ℝ) * s3Quat u * (s3FibreUnit (Multiplicative.toAdd x.2) * quatK *
            star (s3FibreUnit (Multiplicative.toAdd x.2))) *
              (star (s3Quat u) * star (x.1 : Quaternion ℝ)) := by
          simp only [mul_assoc]
      _ = _ := by rw [he]; simp only [mul_assoc]
  change quatIm _ = quatRotate x.1 (quatIm _)
  rw [key]
  unfold quatRotate
  rw [show (⟨0, (quatIm (s3Quat u * quatK * star (s3Quat u))) 0,
      (quatIm (s3Quat u * quatK * star (s3Quat u))) 1,
      (quatIm (s3Quat u * quatK * star (s3Quat u))) 2⟩ : Quaternion ℝ) =
      vecQuat (quatIm (s3Quat u * quatK * star (s3Quat u))) from rfl,
    vecQuat_quatIm (re_conj_quatK _)]
  rfl

private theorem hopfS3_smul (c : ℝ) (u : EuclideanSpace ℝ (Fin 4)) :
    hopfS3 (c • u) = c ^ 2 • hopfS3 u := by
  ext i
  fin_cases i <;> simp [hopfS3, quatIm, quatK] <;> ring

theorem hopfS3_hopfParam (v : ModelCoordinates) : hopfS3 (hopfParam v) = coneAxis v := by
  have hD := stereoDenom_pos v
  change hopfS3 ((Real.sqrt (stereoDenom v))⁻¹ • hopfFrame v) = coneAxis v
  rw [hopfS3_smul, inv_pow, Real.sq_sqrt hD.le]
  have hsc := Real.cos_sq_add_sin_sq (v 2)
  have hden : stereoDenom v = 1 + planeDot v v := by unfold stereoDenom planeDot; ring
  rw [coneAxis, ← hden]
  congr 1
  ext i
  fin_cases i <;> simp [hopfS3, quatIm, quatK, hopfFrame, planeDot]
  · linear_combination 2 * v 0 * hsc
  · linear_combination 2 * v 1 * hsc
  · linear_combination (1 - v 0 ^ 2 - v 1 ^ 2) * hsc

private theorem sum_sq_of_norm {n : EuclideanSpace ℝ (Fin 3)} (hn : ‖n‖ = 1) :
    n 0 ^ 2 + n 1 ^ 2 + n 2 ^ 2 = 1 := by
  have h := EuclideanSpace.norm_sq_eq n
  rw [hn] at h
  simp only [Fin.sum_univ_three, Real.norm_eq_abs, sq_abs, one_pow] at h
  linarith

def axisQuat (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) (θ : ℝ) : unitary (Quaternion ℝ) :=
  ⟨⟨Real.cos (θ / 2), Real.sin (θ / 2) * n 0, Real.sin (θ / 2) * n 1, Real.sin (θ / 2) * n 2⟩,
    mem_unitary_of_normSq (by
      rw [Quaternion.normSq_def']
      linear_combination Real.sin (θ / 2) ^ 2 * sum_sq_of_norm hn +
        Real.cos_sq_add_sin_sq (θ / 2))⟩

private theorem axisQuat_add (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) (a b : ℝ) :
    axisQuat n hn (a + b) = axisQuat n hn a * axisQuat n hn b := by
  have hs := sum_sq_of_norm hn
  apply Subtype.ext
  ext <;> simp [axisQuat, add_div, Real.cos_add, Real.sin_add]
  · linear_combination (Real.sin (a / 2) * Real.sin (b / 2)) * hs
  all_goals ring

private theorem axisQuat_zero (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) :
    axisQuat n hn 0 = 1 := by
  apply Subtype.ext
  ext <;> simp [axisQuat]

private def axisHom (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) :
    Multiplicative ℝ →* unitary (Quaternion ℝ) where
  toFun θ := axisQuat n hn (Multiplicative.toAdd θ)
  map_one' := axisQuat_zero n hn
  map_mul' _ _ := axisQuat_add n hn _ _

private theorem axisQuat_zpow (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) (θ : ℝ) (m : ℤ) :
    axisQuat n hn θ ^ m = axisQuat n hn (θ * m) := by
  have h := map_zpow (axisHom n hn) (Multiplicative.ofAdd θ) m
  rw [← ofAdd_zsmul] at h
  change axisQuat n hn (m • θ) = axisQuat n hn θ ^ m at h
  rw [← h, zsmul_eq_mul, mul_comm]

private theorem axisQuat_two_pi (n : EuclideanSpace ℝ (Fin 3)) (hn : ‖n‖ = 1) :
    axisQuat n hn (2 * Real.pi) = -1 := by
  apply Subtype.ext
  ext <;> simp [axisQuat, Unitary.coe_neg]

def screwLiftS3 (v : ModelCoordinates) (θ s : ℝ) : S3Lift :=
  (axisQuat (coneAxis v) (norm_coneAxis v) θ, Multiplicative.ofAdd (s + θ / 2))

def screwS3 (v : ModelCoordinates) (θ s : ℝ) : RoundThree ≃ₘ⟮𝓡 3, 𝓡 3⟯ RoundThree :=
  s3Diffeo (screwLiftS3 v θ s)

def screwGeneratorLiftS3 (v : ModelCoordinates) (p : ℕ+) (a : ℤ) (ℓ : ℝ) : S3Lift :=
  screwLiftS3 v (2 * Real.pi * (-a) / p) (ℓ / p)

def screwAtLiftS3 (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ : ℝ) : S3Lift :=
  screwLiftS3 v (-2 * Real.pi / p) (-ℓ * q / p)

def screwGeneratorS3 (v : ModelCoordinates) (p : ℕ+) (a : ℤ) (ℓ : ℝ) :
    RoundThree ≃ₘ⟮𝓡 3, 𝓡 3⟯ RoundThree :=
  s3Diffeo (screwGeneratorLiftS3 v p a ℓ)

def screwAtS3 (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ : ℝ) :
    RoundThree ≃ₘ⟮𝓡 3, 𝓡 3⟯ RoundThree :=
  s3Diffeo (screwAtLiftS3 v p q ℓ)

theorem screwLiftS3_zpow (v : ModelCoordinates) (θ s : ℝ) (m : ℤ) :
    screwLiftS3 v θ s ^ m = screwLiftS3 v (θ * m) (s * m) := by
  apply Prod.ext
  · rw [Prod.pow_fst]
    exact axisQuat_zpow (coneAxis v) (norm_coneAxis v) θ m
  · rw [Prod.pow_snd]
    apply Multiplicative.toAdd.injective
    simp only [screwLiftS3, toAdd_zpow, toAdd_ofAdd, zsmul_eq_mul]
    ring

theorem screwLiftS3_add_two_pi (v : ModelCoordinates) (θ s : ℝ) (m : ℤ) :
    screwLiftS3 v (θ + m * (2 * Real.pi)) s = screwLiftS3 v θ s * s3Period ^ m := by
  apply Prod.ext
  · rw [Prod.fst_mul, Prod.pow_fst]
    change axisQuat (coneAxis v) (norm_coneAxis v) (θ + m * (2 * Real.pi)) =
      axisQuat (coneAxis v) (norm_coneAxis v) θ * (-1) ^ m
    rw [axisQuat_add, ← axisQuat_two_pi (coneAxis v) (norm_coneAxis v), axisQuat_zpow,
      mul_comm (2 * Real.pi)]
  · rw [Prod.snd_mul, Prod.pow_snd]
    apply Multiplicative.toAdd.injective
    simp only [screwLiftS3, s3Period, toAdd_mul, toAdd_zpow, toAdd_ofAdd, zsmul_eq_mul]
    ring

theorem screwLiftS3_zero (v : ModelCoordinates) (s : ℝ) : screwLiftS3 v 0 s = fibreLiftS3 s := by
  apply Prod.ext
  · exact axisQuat_zero (coneAxis v) (norm_coneAxis v)
  · simp [screwLiftS3, fibreLiftS3]

private theorem s3Quat_unit (u : RoundThree) : star (s3Quat u) * s3Quat u = 1 := by
  have h : Quaternion.normSq (s3Quat u) = 1 := by
    rw [Quaternion.normSq_eq_norm_mul_self, LinearIsometryEquiv.norm_map,
      mem_sphere_zero_iff_norm.mp u.2, mul_one]
  rw [Quaternion.star_mul_self, h]
  rfl

private theorem s3FibreUnit_two_pi_mul (m : ℤ) : s3FibreUnit (2 * Real.pi * m) = 1 := by
  have hc : Real.cos (2 * Real.pi * m) = 1 := by
    rw [show 2 * Real.pi * m = m * (2 * Real.pi) by ring]
    exact Real.cos_int_mul_two_pi m
  have hs : Real.sin (2 * Real.pi * m) = 0 := by
    rw [show 2 * Real.pi * m = ((2 * m : ℤ) : ℝ) * Real.pi by push_cast; ring]
    exact Real.sin_int_mul_pi _
  ext <;> simp [s3FibreUnit, hc, hs]

private theorem s3Quat_hopfAmbient_add (x : ModelCoordinates) (s : ℝ) :
    s3Quat (hopfAmbient (x + fibreShift s)) = s3Quat (hopfAmbient x) * s3FibreUnit s := by
  have hD : stereoDenom (x + fibreShift s) = stereoDenom x := by simp [stereoDenom]
  unfold hopfAmbient
  rw [hD, map_smul, map_smul, smul_mul_assoc]
  congr 1
  ext <;> simp [hopfFrame, s3FibreUnit, Real.cos_add, Real.sin_add] <;> ring

private theorem s3Quat_hopfAmbient_rotation (x : ModelCoordinates) (θ : ℝ) :
    s3Quat (hopfAmbient (planeRotation θ x)) =
      s3FibreUnit (-(θ / 2)) * s3Quat (hopfAmbient x) * s3FibreUnit (θ / 2) := by
  have hsc := Real.cos_sq_add_sin_sq (θ / 2)
  have hD : stereoDenom (planeRotation θ x) = stereoDenom x := by
    unfold stereoDenom
    simp only [planeRotation_apply_zero, planeRotation_apply_one]
    linear_combination (x 0 ^ 2 + x 1 ^ 2) * Real.cos_sq_add_sin_sq θ
  have hc : Real.cos θ = Real.cos (θ / 2) ^ 2 - Real.sin (θ / 2) ^ 2 := by
    have h := Real.cos_two_mul (θ / 2)
    rw [show 2 * (θ / 2) = θ by ring] at h
    linear_combination h + hsc
  have hs : Real.sin θ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := by
    have h := Real.sin_two_mul (θ / 2)
    rwa [show 2 * (θ / 2) = θ by ring] at h
  unfold hopfAmbient
  rw [hD, map_smul, map_smul, mul_smul_comm, smul_mul_assoc]
  congr 1
  ext <;> simp only [hopfFrame, Fin.isValue, planeRotation_apply_two, planeRotation_apply_zero, hc,
    hs, planeRotation_apply_one, s3Quat_imI, Matrix.cons_val, neg_add_rev, s3FibreUnit,
    Real.cos_neg, Real.sin_neg, neg_neg, Quaternion.imI_mul, Quaternion.re_mul, s3Quat_re,
    Matrix.cons_val_zero, zero_mul, sub_zero, s3Quat_imJ, s3Quat_imK, Matrix.cons_val_one, mul_neg,
    sub_neg_eq_add, mul_zero, add_zero, neg_zero, zero_add, Quaternion.imJ_mul, Quaternion.imK_mul]
  all_goals first
    | ring1
    | linear_combination (-Real.cos (x 2)) * hsc
    | linear_combination Real.cos (x 2) * hsc
    | linear_combination Real.sin (x 2) * hsc

private theorem axis_mul_of_fibre (v : ModelCoordinates) (θ : ℝ) (q : Quaternion ℝ)
    (hq : star q * q = 1) (hk : q * quatK * star q = vecQuat (coneAxis v)) :
    (axisQuat (coneAxis v) (norm_coneAxis v) θ : Quaternion ℝ) * q =
      q * s3FibreUnit (-(θ / 2)) := by
  have hdecomp : (axisQuat (coneAxis v) (norm_coneAxis v) θ : Quaternion ℝ) =
      (Real.cos (θ / 2) : Quaternion ℝ) +
        (Real.sin (θ / 2) : Quaternion ℝ) * vecQuat (coneAxis v) := by
    ext <;> simp [axisQuat, vecQuat]
  have hfib : s3FibreUnit (-(θ / 2)) =
      (Real.cos (θ / 2) : Quaternion ℝ) + (Real.sin (θ / 2) : Quaternion ℝ) * quatK := by
    ext <;> simp [s3FibreUnit, quatK]
  have hn : vecQuat (coneAxis v) * q = q * quatK := by
    rw [← hk, mul_assoc, mul_assoc, hq, mul_one]
  rw [hdecomp, hfib, add_mul, mul_add, mul_assoc, hn, Quaternion.coe_commutes, ← mul_assoc,
    Quaternion.coe_commutes, mul_assoc]

private theorem coneAxis_add_fibreShift (v : ModelCoordinates) (t : ℝ) :
    coneAxis (v + fibreShift t) = coneAxis v := by
  simp [coneAxis, planeDot]

private theorem conj_quatK_hopfParam (v : ModelCoordinates) :
    s3Quat (hopfAmbient v) * quatK * star (s3Quat (hopfAmbient v)) = vecQuat (coneAxis v) := by
  rw [← hopfS3_hopfParam v]
  exact (vecQuat_quatIm (re_conj_quatK _)).symm

theorem screwS3_hopfParam_fibre (v : ModelCoordinates) (θ s t : ℝ) :
    screwS3 v θ s (hopfParam (v + fibreShift t)) = hopfParam (v + fibreShift (t + s)) := by
  apply Subtype.ext
  apply s3Quat.injective
  change s3Quat (s3Act (screwLiftS3 v θ s) (hopfAmbient (v + fibreShift t))) =
    s3Quat (hopfAmbient (v + fibreShift (t + s)))
  rw [s3Act_apply]
  have hq : star (s3Quat (hopfAmbient (v + fibreShift t))) *
      s3Quat (hopfAmbient (v + fibreShift t)) = 1 := s3Quat_unit (hopfParam (v + fibreShift t))
  have hk := conj_quatK_hopfParam (v + fibreShift t)
  rw [coneAxis_add_fibreShift] at hk
  change (axisQuat (coneAxis v) (norm_coneAxis v) θ : Quaternion ℝ) *
      s3Quat (hopfAmbient (v + fibreShift t)) * s3FibreUnit (s + θ / 2) = _
  rw [show v + fibreShift (t + s) = v + fibreShift t + fibreShift s by
      ext i; fin_cases i <;> simp [add_assoc],
    s3Quat_hopfAmbient_add (v + fibreShift t) s, axis_mul_of_fibre v θ _ hq hk, mul_assoc,
    ← s3FibreUnit_add, show -(θ / 2) + (s + θ / 2) = s by ring]

theorem hopfS3_screwS3 (v : ModelCoordinates) (θ s : ℝ) (u : RoundThree) :
    hopfS3 (screwS3 v θ s u) =
      quatRotate (axisQuat (coneAxis v) (norm_coneAxis v) θ) (hopfS3 u) :=
  hopfS3_s3Act (screwLiftS3 v θ s) u

private theorem screwDiffeomorph_eq (θ s : ℝ) (x : ModelCoordinates) :
    screwDiffeomorph θ s x = planeRotation θ x + fibreShift s := by
  change planeRotation (θ * ((1 : ℤ) : ℝ)) x + fibreShift (s * ((1 : ℤ) : ℝ)) = _
  simp only [Int.cast_one, mul_one]

theorem hopfParam_screwDiffeomorph (θ s : ℝ) (x : ModelCoordinates) :
    hopfParam (screwDiffeomorph θ s x) = screwS3 0 θ s (hopfParam x) := by
  apply Subtype.ext
  apply s3Quat.injective
  change s3Quat (hopfAmbient (screwDiffeomorph θ s x)) =
    s3Quat (s3Act (screwLiftS3 0 θ s) (hopfAmbient x))
  have hg : ((screwLiftS3 0 θ s).1 : Quaternion ℝ) = s3FibreUnit (-(θ / 2)) := by
    ext <;> simp [screwLiftS3, axisQuat, coneAxis, planeDot, s3FibreUnit]
  rw [screwDiffeomorph_eq, s3Quat_hopfAmbient_add, s3Quat_hopfAmbient_rotation, s3Act_apply, hg,
    mul_assoc, mul_assoc, ← s3FibreUnit_add]
  simp [screwLiftS3, add_comm, mul_assoc]

theorem hopfParam_fibreTranslation (s : ℝ) (x : ModelCoordinates) :
    hopfParam (fibreTranslation s x) = fibreTranslationS3 s (hopfParam x) := by
  apply Subtype.ext
  apply s3Quat.injective
  change s3Quat (hopfAmbient (screwDiffeomorph 0 s x)) =
    s3Quat (s3Act (fibreLiftS3 s) (hopfAmbient x))
  have hx : planeRotation 0 x = x := by ext i; fin_cases i <;> simp
  rw [screwDiffeomorph_eq, hx, s3Quat_hopfAmbient_add, s3Act_apply]
  simp [fibreLiftS3]

theorem coneProfile_inner_hopfParam (x v w : ModelCoordinates) :
    ConnectionModel.spherical.coneProfile.metric.inner x v w =
      sphericalModelMetric.inner (hopfParam x) (mfderiv (𝓡 3) (𝓡 3) hopfParam x v)
        (mfderiv (𝓡 3) (𝓡 3) hopfParam x w) := by
  rw [RadialProfile.metric_inner, sphericalModelMetric_hopfParam]
  have h := roundProfile_inner (1 / 2) 1 (by norm_num) x v w
  rw [FibreConnection.one_smul'] at h
  exact h

theorem hopfParam_eq_hopfParam_iff (x y : ModelCoordinates) :
    hopfParam x = hopfParam y ↔ x 0 = y 0 ∧ x 1 = y 1 ∧ ∃ m : ℤ, y 2 = x 2 + 2 * Real.pi * m := by
  constructor
  · intro h
    have hc : coneAxis x = coneAxis y := by
      rw [← hopfS3_hopfParam, ← hopfS3_hopfParam, h]
    have e0 := congrArg (fun n : EuclideanSpace ℝ (Fin 3) => n 0) hc
    have e1 := congrArg (fun n : EuclideanSpace ℝ (Fin 3) => n 1) hc
    have e2 := congrArg (fun n : EuclideanSpace ℝ (Fin 3) => n 2) hc
    simp only [coneAxis, PiLp.smul_apply, smul_eq_mul] at e0 e1 e2
    simp at e0 e1 e2
    have hx := planeDot_self_nonneg x
    have hy := planeDot_self_nonneg y
    have hx' : 1 + planeDot x x ≠ 0 := by linarith
    have hy' : 1 + planeDot y y ≠ 0 := by linarith
    field_simp at e0 e1 e2
    have hP : planeDot x x = planeDot y y := by linarith
    have h0 : x 0 = y 0 := by
      rw [hP] at e0
      apply mul_right_cancel₀ hy'
      linear_combination e0
    have h1 : x 1 = y 1 := by
      rw [hP] at e1
      apply mul_right_cancel₀ hy'
      linear_combination e1
    refine ⟨h0, h1, ?_⟩
    have hy : y = x + fibreShift (y 2 - x 2) := by
      ext i; fin_cases i <;> simp [h0, h1]
    have hq := congrArg (fun u : RoundThree => s3Quat u) h
    change s3Quat (hopfAmbient x) = s3Quat (hopfAmbient y) at hq
    rw [hy, s3Quat_hopfAmbient_add] at hq
    have hu : star (s3Quat (hopfAmbient x)) * s3Quat (hopfAmbient x) = 1 :=
      s3Quat_unit (hopfParam x)
    have he : s3FibreUnit (y 2 - x 2) = 1 := by
      have h' := congrArg (fun w => star (s3Quat (hopfAmbient x)) * w) hq
      change star (s3Quat (hopfAmbient x)) * s3Quat (hopfAmbient x) =
        star (s3Quat (hopfAmbient x)) * (s3Quat (hopfAmbient x) * s3FibreUnit (y 2 - x 2)) at h'
      rw [← mul_assoc, hu, one_mul] at h'
      exact h'.symm
    have hr : Real.cos (y 2 - x 2) = 1 := by
      simpa [s3FibreUnit] using congrArg (fun w : Quaternion ℝ => w.re) he
    obtain ⟨m, hm⟩ := (Real.cos_eq_one_iff _).mp hr
    exact ⟨m, by linarith⟩
  · rintro ⟨h0, h1, m, hm⟩
    have hy : y = x + fibreShift (2 * Real.pi * m) := by
      ext i; fin_cases i <;> simp [h0, h1, hm]
    apply Subtype.ext
    apply s3Quat.injective
    change s3Quat (hopfAmbient x) = s3Quat (hopfAmbient y)
    rw [hy, s3Quat_hopfAmbient_add, s3FibreUnit_two_pi_mul, mul_one]

theorem range_hopfParam :
    Set.range hopfParam = {u : RoundThree | (u : EuclideanSpace ℝ (Fin 4)) 0 ^ 2 +
      (u : EuclideanSpace ℝ (Fin 4)) 1 ^ 2 ≠ 0} := by
  ext u
  constructor
  · rintro ⟨x, rfl⟩
    have hD := Real.sqrt_pos.2 (stereoDenom_pos x)
    change (hopfAmbient x) 0 ^ 2 + (hopfAmbient x) 1 ^ 2 ≠ 0
    have h : (hopfAmbient x) 0 ^ 2 + (hopfAmbient x) 1 ^ 2 = (Real.sqrt (stereoDenom x))⁻¹ ^ 2 := by
      simp [hopfAmbient, hopfFrame]
      linear_combination (Real.sqrt (stereoDenom x))⁻¹ ^ 2 * Real.cos_sq_add_sin_sq (x 2)
    rw [h]
    positivity
  · intro hu
    change (u : EuclideanSpace ℝ (Fin 4)) 0 ^ 2 + (u : EuclideanSpace ℝ (Fin 4)) 1 ^ 2 ≠ 0 at hu
    have key : ∃ a : ℝ, hopfAngleCoord a (u : EuclideanSpace ℝ (Fin 4)) ∈ Complex.slitPlane := by
      by_cases hc : 0 < (u : EuclideanSpace ℝ (Fin 4)) 0 ∨ (u : EuclideanSpace ℝ (Fin 4)) 1 ≠ 0
      · refine ⟨0, Complex.mem_slitPlane_iff.mpr ?_⟩
        simpa using hc
      · push Not at hc
        have h0 : (u : EuclideanSpace ℝ (Fin 4)) 0 ≠ 0 := by
          intro h0
          apply hu
          rw [h0, hc.2]
          ring
        refine ⟨Real.pi, Complex.mem_slitPlane_iff.mpr (Or.inl ?_)⟩
        simpa using lt_of_le_of_ne hc.1 h0
    obtain ⟨a, ha⟩ := key
    exact ⟨_, (hopfChart a).left_inv' ha⟩

theorem screwS3_isometry (v : ModelCoordinates) (θ s : ℝ) :
    Diffeomorph.pullbackMetric sphericalModelMetric (screwS3 v θ s) = sphericalModelMetric :=
  s3Diffeo_isometry _

theorem screwAtS3_isometry (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ : ℝ) :
    Diffeomorph.pullbackMetric sphericalModelMetric (screwAtS3 v p q ℓ) = sphericalModelMetric :=
  s3Diffeo_isometry _

private theorem fibreLiftS3_commute (t : ℝ) (x : S3Lift) : Commute (fibreLiftS3 t) x := by
  apply Prod.ext
  · simp [fibreLiftS3]
  · exact mul_comm _ _

private theorem s3Period_commute (x : S3Lift) : Commute s3Period x := by
  apply Prod.ext
  · simp [s3Period]
  · exact mul_comm _ _

theorem screwAtLiftS3_pow (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ : ℝ) :
    screwAtLiftS3 v p q ℓ ^ (p : ℕ) = s3Period⁻¹ * fibreLiftS3 (-ℓ * q) := by
  have hp : (p : ℝ) ≠ 0 := by positivity
  rw [← zpow_natCast, screwAtLiftS3, screwLiftS3_zpow]
  have hθ : -2 * Real.pi / (p : ℝ) * ((p : ℕ) : ℤ) = 0 + (-1 : ℤ) * (2 * Real.pi) := by
    push_cast
    field_simp
    ring
  have hs : -ℓ * q / (p : ℝ) * ((p : ℕ) : ℤ) = -ℓ * q := by
    push_cast
    field_simp
  rw [hθ, hs, screwLiftS3_add_two_pi, screwLiftS3_zero, zpow_neg_one]
  exact (s3Period_commute _).inv_left.eq.symm

theorem screwAtS3_pow (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ : ℝ) :
    (screwAtS3 v p q ℓ).toEquiv ^ (p : ℕ) = (fibreTranslationS3 (-ℓ * q)).toEquiv := by
  change s3Perm (screwAtLiftS3 v p q ℓ) ^ (p : ℕ) = s3Perm (fibreLiftS3 (-ℓ * q))
  rw [← map_pow, screwAtLiftS3_pow, map_mul, map_inv, s3Perm_s3Period, inv_one, one_mul]

theorem screwAtS3_commute (v : ModelCoordinates) (p : ℕ+) (q : ℤ) (ℓ t : ℝ) :
    Function.Commute (screwAtS3 v p q ℓ) (fibreTranslationS3 t) := by
  have h := ((fibreLiftS3_commute t (screwAtLiftS3 v p q ℓ)).map s3Perm).symm
  intro x
  exact congrArg (fun e : Equiv.Perm RoundThree => e x) h.eq

theorem screwBezoutLiftS3 (v : ModelCoordinates) (p : ℕ+) (q a b : ℤ) (ℓ : ℝ)
    (hpb : (p : ℤ) * b - a * q = 1) :
    screwGeneratorLiftS3 v p a ℓ ^ (p : ℕ) = s3Period ^ (-a) * fibreLiftS3 ℓ ∧
      screwGeneratorLiftS3 v p a ℓ ^ (-q) = s3Period ^ b * screwAtLiftS3 v p q ℓ := by
  have hp : (p : ℝ) ≠ 0 := by positivity
  have hpbR : (p : ℝ) * b - (a : ℝ) * q = 1 := by exact_mod_cast hpb
  constructor
  · rw [← zpow_natCast, screwGeneratorLiftS3, screwLiftS3_zpow]
    have hθ : 2 * Real.pi * (-(a : ℝ)) / (p : ℝ) * ((p : ℕ) : ℤ) =
        0 + ((-a : ℤ) : ℝ) * (2 * Real.pi) := by
      push_cast
      field_simp
      ring
    have hs : ℓ / (p : ℝ) * ((p : ℕ) : ℤ) = ℓ := by
      push_cast
      field_simp
    rw [hθ, hs, screwLiftS3_add_two_pi, screwLiftS3_zero]
    exact ((s3Period_commute _).zpow_left _).eq.symm
  · rw [screwGeneratorLiftS3, screwLiftS3_zpow]
    have hθ : 2 * Real.pi * (-(a : ℝ)) / (p : ℝ) * ((-q : ℤ) : ℝ) =
        -2 * Real.pi / p + b * (2 * Real.pi) := by
      push_cast
      field_simp
      linear_combination -hpbR
    have hs : ℓ / (p : ℝ) * ((-q : ℤ) : ℝ) = -ℓ * q / p := by
      push_cast
      ring
    rw [hθ, hs, screwLiftS3_add_two_pi]
    exact ((s3Period_commute _).zpow_left _).eq.symm

private theorem bezoutAlgebra {G : Type*} [Group G] (u h : G) (p : ℕ+) (q a b : ℤ)
    (hu : u ^ (p : ℕ) = h) (hpb : (p : ℤ) * b - a * q = 1) :
    (u ^ (-q)) ^ (p : ℕ) = h ^ (-q) ∧ (u ^ (-q)) ^ a * h ^ b = u ∧
      Subgroup.closure ({u ^ (-q), h} : Set G) = Subgroup.zpowers u := by
  have huz : u ^ (p : ℤ) = h := by simpa only [zpow_natCast] using hu
  have hpower : (u ^ (-q)) ^ (p : ℕ) = h ^ (-q) := by
    rw [← zpow_natCast, ← huz, ← zpow_mul, ← zpow_mul]
    congr 1
    ring
  have hlongitude : (u ^ (-q)) ^ a * h ^ b = u := by
    rw [← huz, ← zpow_mul, ← zpow_mul, ← zpow_add]
    have he : (-q) * a + (p : ℤ) * b = 1 := by linarith
    rw [he, zpow_one]
  refine ⟨hpower, hlongitude, le_antisymm ?_ ?_⟩
  · apply (Subgroup.closure_le (Subgroup.zpowers u)).mpr
    intro z hz
    rcases Set.mem_insert_iff.mp hz with rfl | hz
    · exact Subgroup.mem_zpowers_iff.mpr ⟨-q, rfl⟩
    · have he : z = h := Set.mem_singleton_iff.mp hz
      subst z
      exact Subgroup.mem_zpowers_iff.mpr ⟨p, huz⟩
  · apply Subgroup.zpowers_le.mpr
    let K := Subgroup.closure ({u ^ (-q), h} : Set G)
    have hc : u ^ (-q) ∈ K := Subgroup.subset_closure (Or.inl rfl)
    have hh : h ∈ K := Subgroup.subset_closure (Or.inr rfl)
    have hmem := K.mul_mem (K.zpow_mem hc a) (K.zpow_mem hh b)
    simpa only [hlongitude] using hmem

theorem screwBezoutS3 (v : ModelCoordinates) (p : ℕ+) (q a b : ℤ) (ℓ : ℝ)
    (hpb : (p : ℤ) * b - a * q = 1) :
    let u := (screwGeneratorS3 v p a ℓ).toEquiv
    let h := (fibreTranslationS3 ℓ).toEquiv
    let c := u ^ (-q)
    u ^ (p : ℕ) = h ∧ c ^ (p : ℕ) = h ^ (-q) ∧ c ^ a * h ^ b = u ∧
      Subgroup.closure ({c, h} : Set (Equiv.Perm RoundThree)) = Subgroup.zpowers u ∧
        (screwAtS3 v p q ℓ).toEquiv = c := by
  dsimp only
  obtain ⟨hlp, hlq⟩ := screwBezoutLiftS3 v p q a b ℓ hpb
  have hu : (screwGeneratorS3 v p a ℓ).toEquiv ^ (p : ℕ) = (fibreTranslationS3 ℓ).toEquiv := by
    change s3Perm (screwGeneratorLiftS3 v p a ℓ) ^ (p : ℕ) = s3Perm (fibreLiftS3 ℓ)
    rw [← map_pow, hlp, map_mul, map_zpow, s3Perm_s3Period, one_zpow, one_mul]
  obtain ⟨hpower, hlongitude, hsubgroup⟩ :=
    bezoutAlgebra (screwGeneratorS3 v p a ℓ).toEquiv (fibreTranslationS3 ℓ).toEquiv p q a b hu hpb
  refine ⟨hu, hpower, hlongitude, hsubgroup, ?_⟩
  change s3Perm (screwAtLiftS3 v p q ℓ) = s3Perm (screwGeneratorLiftS3 v p a ℓ) ^ (-q)
  rw [← map_zpow, hlq, map_mul, map_zpow, s3Perm_s3Period, one_zpow, one_mul]

theorem screwLiftS3_mul (v : ModelCoordinates) (θ s θ' s' : ℝ) :
    screwLiftS3 v θ s * screwLiftS3 v θ' s' = screwLiftS3 v (θ + θ') (s + s') := by
  apply Prod.ext
  · exact (axisQuat_add (coneAxis v) (norm_coneAxis v) θ θ').symm
  · apply Multiplicative.toAdd.injective
    simp only [Prod.snd_mul, toAdd_mul, screwLiftS3, toAdd_ofAdd]
    ring

private theorem s3Period_zpow_eq (v : ModelCoordinates) (m : ℤ) :
    s3Period ^ m = screwLiftS3 v (m * (2 * Real.pi)) 0 := by
  have h := screwLiftS3_add_two_pi v 0 0 m
  rw [zero_add, screwLiftS3_zero] at h
  rw [h]
  simp [fibreLiftS3]

theorem screwMarkLiftS3 (v : ModelCoordinates) (p : ℕ+) (q a b : ℤ) (ℓ : ℝ)
    (hpb : (p : ℤ) * b - a * q = 1) :
    let u := screwGeneratorLiftS3 v p a ℓ
    let h := fibreLiftS3 ℓ
    let c := screwAtLiftS3 v p q ℓ
    c ^ a * h ^ b = u ∧ c ^ (-(p : ℤ)) * h ^ (-q) = s3Period ∧
      Subgroup.closure ({c, h} : Set S3Lift) = Subgroup.closure {u, s3Period} := by
  dsimp only
  have hp : (p : ℝ) ≠ 0 := by positivity
  have hpbR : (p : ℝ) * b - (a : ℝ) * q = 1 := by exact_mod_cast hpb
  have hh : fibreLiftS3 ℓ = screwLiftS3 v 0 ℓ := (screwLiftS3_zero v ℓ).symm
  have hlong : screwAtLiftS3 v p q ℓ ^ a * fibreLiftS3 ℓ ^ b = screwGeneratorLiftS3 v p a ℓ := by
    rw [hh, screwAtLiftS3, screwGeneratorLiftS3, screwLiftS3_zpow, screwLiftS3_zpow,
      screwLiftS3_mul]
    congr 1
    · ring
    · field_simp
      linear_combination ℓ * hpbR
  have hmer : screwAtLiftS3 v p q ℓ ^ (-(p : ℤ)) * fibreLiftS3 ℓ ^ (-q) = s3Period := by
    rw [hh, screwAtLiftS3, screwLiftS3_zpow, screwLiftS3_zpow, screwLiftS3_mul,
      ← zpow_one s3Period, s3Period_zpow_eq v 1]
    congr 1
    · push_cast
      field_simp
      ring
    · push_cast
      field_simp
      ring
  refine ⟨hlong, hmer, le_antisymm ?_ ?_⟩
  · obtain ⟨hu, hc⟩ := screwBezoutLiftS3 v p q a b ℓ hpb
    apply (Subgroup.closure_le _).mpr
    intro z hz
    let K := Subgroup.closure ({screwGeneratorLiftS3 v p a ℓ, s3Period} : Set S3Lift)
    have huK : screwGeneratorLiftS3 v p a ℓ ∈ K := Subgroup.subset_closure (Or.inl rfl)
    have hκK : s3Period ∈ K := Subgroup.subset_closure (Or.inr rfl)
    rcases Set.mem_insert_iff.mp hz with rfl | hz
    · have he : screwAtLiftS3 v p q ℓ =
          s3Period ^ (-b) * screwGeneratorLiftS3 v p a ℓ ^ (-q) := by
        rw [hc, ← mul_assoc, ← zpow_add, neg_add_cancel, zpow_zero, one_mul]
      rw [he]
      exact K.mul_mem (K.zpow_mem hκK _) (K.zpow_mem huK _)
    · have he : z = s3Period ^ a * screwGeneratorLiftS3 v p a ℓ ^ (p : ℕ) := by
        rw [Set.mem_singleton_iff.mp hz, hu, ← mul_assoc, ← zpow_add, add_neg_cancel, zpow_zero,
          one_mul]
      rw [he]
      exact K.mul_mem (K.zpow_mem hκK _) (K.pow_mem huK _)
  · apply (Subgroup.closure_le _).mpr
    intro z hz
    let K := Subgroup.closure ({screwAtLiftS3 v p q ℓ, fibreLiftS3 ℓ} : Set S3Lift)
    have hcK : screwAtLiftS3 v p q ℓ ∈ K := Subgroup.subset_closure (Or.inl rfl)
    have hhK : fibreLiftS3 ℓ ∈ K := Subgroup.subset_closure (Or.inr rfl)
    rcases Set.mem_insert_iff.mp hz with rfl | hz
    · rw [← hlong]
      exact K.mul_mem (K.zpow_mem hcK _) (K.zpow_mem hhK _)
    · rw [Set.mem_singleton_iff.mp hz, ← hmer]
      exact K.mul_mem (K.zpow_mem hcK _) (K.zpow_mem hhK _)

theorem s3Diffeo_mul_apply (x y : S3Lift) (u : RoundThree) :
    s3Diffeo (x * y) u = s3Diffeo x (s3Diffeo y u) :=
  Subtype.ext (s3Act_mul x y u)

theorem s3Diffeo_mul_s3Period (x : S3Lift) (u : RoundThree) :
    s3Diffeo (x * s3Period) u = s3Diffeo x u := by
  rw [s3Diffeo_mul_apply]
  exact congrArg (s3Diffeo x) (Equiv.ext_iff.mp s3Perm_s3Period u)

theorem hopfParam_add_fibreShift (y : ModelCoordinates) (z : ℝ) :
    hopfParam (y + fibreShift z) = fibreTranslationS3 z (hopfParam y) := by
  apply Subtype.ext
  apply s3Quat.injective
  change s3Quat (hopfAmbient (y + fibreShift z)) = s3Quat (s3Act (fibreLiftS3 z) (hopfAmbient y))
  rw [s3Quat_hopfAmbient_add, s3Act_apply]
  simp [fibreLiftS3]

theorem s3Diffeo_hopfParam_add_fibreShift (x : S3Lift) (y y' : ModelCoordinates)
    (h : s3Diffeo x (hopfParam y) = hopfParam y') (z : ℝ) :
    s3Diffeo x (hopfParam (y + fibreShift z)) = hopfParam (y' + fibreShift z) := by
  rw [hopfParam_add_fibreShift, hopfParam_add_fibreShift, ← h]
  have hc := Equiv.ext_iff.mp ((fibreLiftS3_commute z x).map s3Perm).eq (hopfParam y)
  exact hc.symm

def hopfTransition (x : S3Lift) (a : ℝ) (y : ModelCoordinates) : ModelCoordinates :=
  hopfChart a (s3Diffeo x (hopfParam y))

theorem hopfParam_hopfTransition (x : S3Lift) (a : ℝ) (y : ModelCoordinates)
    (h : s3Diffeo x (hopfParam y) ∈ (hopfChart a).source) :
    hopfParam (hopfTransition x a y) = s3Diffeo x (hopfParam y) :=
  (hopfChart a).left_inv' h

theorem isOpen_hopfTransition_domain (x : S3Lift) (a : ℝ) :
    IsOpen {y : ModelCoordinates | s3Diffeo x (hopfParam y) ∈ (hopfChart a).source} :=
  (hopfChart a).open_source.preimage
    ((s3Diffeo x).continuous.comp contMDiff_hopfParam.continuous)

theorem contMDiffOn_hopfTransition (x : S3Lift) (a : ℝ) :
    ContMDiffOn (𝓡 3) (𝓡 3) ∞ (hopfTransition x a)
      {y : ModelCoordinates | s3Diffeo x (hopfParam y) ∈ (hopfChart a).source} :=
  (hopfChart a).contMDiffOn_toFun.comp
    ((s3Diffeo x).contMDiff.comp contMDiff_hopfParam).contMDiffOn fun _ hy => hy

theorem exists_int_phase_of_hopfParam_eq {S : Set ModelCoordinates} (hS : IsPreconnected S)
    (F G : ModelCoordinates → ModelCoordinates) (hF : ContinuousOn F S) (hG : ContinuousOn G S)
    (hFG : ∀ y ∈ S, hopfParam (F y) = hopfParam (G y)) :
    ∃ N : ℤ, ∀ y ∈ S, F y = G y + fibreShift (2 * Real.pi * N) := by
  have hpt : ∀ y ∈ S, ∃ N : ℤ, F y = G y + fibreShift (2 * Real.pi * N) := by
    intro y hy
    obtain ⟨h0, h1, N, hN⟩ := (hopfParam_eq_hopfParam_iff (G y) (F y)).mp (hFG y hy).symm
    refine ⟨N, ?_⟩
    ext i
    fin_cases i <;> simp [h0, h1, hN]
  rcases S.eq_empty_or_nonempty with hE | ⟨y₀, hy₀⟩
  · exact ⟨0, fun y hy => by simp [hE] at hy⟩
  obtain ⟨N₀, hN₀⟩ := hpt y₀ hy₀
  refine ⟨N₀, fun y hy => ?_⟩
  obtain ⟨N, hN⟩ := hpt y hy
  suffices hNN : N = N₀ by rw [hN, hNN]
  let d : ModelCoordinates → ℝ := fun w => (F w 2 - G w 2) / (2 * Real.pi)
  have hd : ContinuousOn d S := by
    have h2 : Continuous fun w : ModelCoordinates => w 2 :=
      (PiLp.proj (𝕜 := ℝ) 2 (fun _ : Fin 3 => ℝ) 2).continuous
    exact ((h2.comp_continuousOn hF).sub (h2.comp_continuousOn hG)).div_const _
  have hval : ∀ w ∈ S, ∃ M : ℤ, d w = M := by
    intro w hw
    obtain ⟨M, hM⟩ := hpt w hw
    refine ⟨M, ?_⟩
    have h2 : F w 2 = G w 2 + 2 * Real.pi * M := by rw [hM]; simp
    simp only [d, h2]
    field_simp
    ring
  have hdy : d y = N := by
    have h2 : F y 2 = G y 2 + 2 * Real.pi * N := by rw [hN]; simp
    simp only [d, h2]
    field_simp
    ring
  have hdy₀ : d y₀ = N₀ := by
    have h2 : F y₀ 2 = G y₀ 2 + 2 * Real.pi * N₀ := by rw [hN₀]; simp
    simp only [d, h2]
    field_simp
    ring
  have himg := hS.image d hd
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hlt
  · have hmem : ((N : ℝ) + 1 / 2) ∈ d '' S := by
      apply himg.Icc_subset ⟨y, hy, hdy⟩ ⟨y₀, hy₀, hdy₀⟩
      have : (N : ℝ) + 1 ≤ N₀ := by exact_mod_cast hlt
      constructor <;> linarith
    obtain ⟨w, hw, hdw⟩ := hmem
    obtain ⟨M, hM⟩ := hval w hw
    rw [hM] at hdw
    have h1 : N < M := by
      have : (N : ℝ) < M := by linarith
      exact_mod_cast this
    have h2 : M < N + 1 := by
      have : (M : ℝ) < N + 1 := by linarith
      exact_mod_cast this
    omega
  · have hmem : ((N₀ : ℝ) + 1 / 2) ∈ d '' S := by
      apply himg.Icc_subset ⟨y₀, hy₀, hdy₀⟩ ⟨y, hy, hdy⟩
      have : (N₀ : ℝ) + 1 ≤ N := by exact_mod_cast hlt
      constructor <;> linarith
    obtain ⟨w, hw, hdw⟩ := hmem
    obtain ⟨M, hM⟩ := hval w hw
    rw [hM] at hdw
    have h1 : N₀ < M := by
      have : (N₀ : ℝ) < M := by linarith
      exact_mod_cast this
    have h2 : M < N₀ + 1 := by
      have : (M : ℝ) < N₀ + 1 := by linarith
      exact_mod_cast this
    omega

theorem hopfTransition_cocycle (x₁ x₂ : S3Lift) (a₁ a₂ a₁₂ : ℝ) {S : Set ModelCoordinates}
    (hS : IsPreconnected S)
    (h₂ : ∀ y ∈ S, s3Diffeo x₂ (hopfParam y) ∈ (hopfChart a₂).source)
    (h₁ : ∀ y ∈ S, s3Diffeo x₁ (hopfParam (hopfTransition x₂ a₂ y)) ∈ (hopfChart a₁).source)
    (h₁₂ : ∀ y ∈ S, s3Diffeo (x₁ * x₂) (hopfParam y) ∈ (hopfChart a₁₂).source) :
    ∃ N : ℤ, ∀ y ∈ S, hopfTransition x₁ a₁ (hopfTransition x₂ a₂ y) =
      hopfTransition (x₁ * x₂) a₁₂ y + fibreShift (2 * Real.pi * N) := by
  apply exists_int_phase_of_hopfParam_eq hS
  · have hc₂ := ((contMDiffOn_hopfTransition x₂ a₂).mono (fun y hy => h₂ y hy)).continuousOn
    have hc₁ := (contMDiffOn_hopfTransition x₁ a₁).continuousOn
    exact hc₁.comp hc₂ fun y hy => h₁ y hy
  · exact ((contMDiffOn_hopfTransition (x₁ * x₂) a₁₂).mono
      (fun y hy => h₁₂ y hy)).continuousOn
  · intro y hy
    rw [hopfParam_hopfTransition _ _ _ (h₁ y hy), hopfParam_hopfTransition _ _ _ (h₂ y hy),
      hopfParam_hopfTransition _ _ _ (h₁₂ y hy), s3Diffeo_mul_apply]

theorem hopfChart_screwS3_zero (θ s a : ℝ) (x : ModelCoordinates)
    (hx : x ∈ (hopfChart a).target) :
    hopfChart (a + s) (screwS3 0 θ s (hopfParam x)) = screwDiffeomorph θ s x := by
  rw [← hopfParam_screwDiffeomorph]
  apply (hopfChart (a + s)).right_inv'
  obtain ⟨h1, h2⟩ := hx
  have hz : screwDiffeomorph θ s x 2 = x 2 + s := by
    rw [screwDiffeomorph_eq]
    simp
  change a + s - Real.pi < screwDiffeomorph θ s x 2 ∧ screwDiffeomorph θ s x 2 < a + s + Real.pi
  rw [hz]
  constructor <;> linarith

end GC.Geometry
