import DifferentialGeometry.Geometry.Thurston.SphericalProductCyclicQuotient

/-!
# Normalizing the dihedral `S² × ℝ` quotient

Chapter 7, packet P8, tier 3. The affine change of the line coordinate
`cylinderAffine c₁ (2 (c₂ - c₁))` conjugates the standard infinite dihedral group generated by
`(-1, s ↦ -s)` and `(-1, s ↦ 1 - s)` onto the group generated by `(-1, s ↦ 2 c₁ - s)` and
`(-1, s ↦ 2 c₂ - s)`, so every dihedral presentation can be renormalized
(`CylinderQuotientPresentation.normalizeDihedral`). Two presentations by the same group give
diffeomorphic quotients, so `DihedralCylinderQuotientIsProjectiveSum` reduces to the single
concrete named input `ProjectiveSumStandardDihedralPresentation`: the model `RP³ # RP³` is the
quotient of `S² × ℝ` by the standard dihedral group.
-/

set_option autoImplicit false

noncomputable section

open DifferentialGeometry DifferentialGeometry.Topology
open DifferentialGeometry.PDE.RicciFlow.Perelman.KappaSolutions
open scoped Manifold ContDiff

namespace GC.Geometry.SphericalProduct

local notation "E3" => EuclideanSpace ℝ (Fin 3)
local notation "CM" => SpatialNeckCylinderModel

universe u

def dihedralGroup (c₁ c₂ : ℝ) : Subgroup CylinderIsometry :=
  Subgroup.closure
    {(LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ c₁),
      (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ c₂)}

def cylinderAffine (a l : ℝ) (p : SpatialNeckCylinder) : SpatialNeckCylinder :=
  (p.1, a + l * p.2)

def cylinderAffineDiffeomorph (a l : ℝ) (hl : l ≠ 0) :
    SpatialNeckCylinder ≃ₘ⟮CM, CM⟯ SpatialNeckCylinder where
  toFun := cylinderAffine a l
  invFun q := (q.1, (q.2 - a) / l)
  left_inv p := by
    refine Prod.ext rfl ?_
    change (a + l * p.2 - a) / l = p.2
    field_simp
    ring
  right_inv q := by
    refine Prod.ext rfl ?_
    change a + l * ((q.2 - a) / l) = q.2
    field_simp
    ring
  contMDiff_toFun :=
    contMDiff_fst.prodMk
      ((contDiff_const.add (contDiff_const.mul contDiff_id)).contMDiff.comp contMDiff_snd)
  contMDiff_invFun :=
    contMDiff_fst.prodMk
      (((contDiff_id.sub contDiff_const).div_const l).contMDiff.comp contMDiff_snd)

def AffineIntertwines (a l : ℝ) (γ γ' : CylinderIsometry) : Prop :=
  ∀ p, cylinderAct γ (cylinderAffine a l p) = cylinderAffine a l (cylinderAct γ' p)

theorem affineIntertwines_one (a l : ℝ) : AffineIntertwines a l 1 1 := by
  intro p
  rw [cylinderAct_one, cylinderAct_one]

theorem AffineIntertwines.mul {a l : ℝ} {γ₁ γ₁' γ₂ γ₂' : CylinderIsometry}
    (h₁ : AffineIntertwines a l γ₁ γ₁') (h₂ : AffineIntertwines a l γ₂ γ₂') :
    AffineIntertwines a l (γ₁ * γ₂) (γ₁' * γ₂') := by
  intro p
  rw [cylinderAct_mul, cylinderAct_mul, h₂, h₁]

theorem AffineIntertwines.inv {a l : ℝ} {γ γ' : CylinderIsometry}
    (h : AffineIntertwines a l γ γ') : AffineIntertwines a l γ⁻¹ γ'⁻¹ := by
  intro p
  have hp := h (cylinderAct γ'⁻¹ p)
  rw [← cylinderAct_mul, mul_inv_cancel, cylinderAct_one] at hp
  rw [← hp, cylinderAct_inv_cylinderAct]

theorem affineIntertwines_reflection (c₀ a l : ℝ) :
    AffineIntertwines a l
      (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ (a + l * c₀))
      (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ c₀) := by
  intro p
  refine Prod.ext (Subtype.ext ?_) ?_
  · simp [cylinderAffine]
  · simp only [cylinderAct_snd, cylinderAffine, AffineIsometryEquiv.pointReflection_apply,
      vsub_eq_sub, vadd_eq_add]
    ring

theorem exists_affineIntertwines_of_mem_closure {a l : ℝ} {g₁ g₂ g₁' g₂' : CylinderIsometry}
    (h₁ : AffineIntertwines a l g₁ g₁') (h₂ : AffineIntertwines a l g₂ g₂')
    {γ : CylinderIsometry} (hγ : γ ∈ Subgroup.closure {g₁, g₂}) :
    ∃ γ' ∈ Subgroup.closure {g₁', g₂'}, AffineIntertwines a l γ γ' := by
  induction hγ using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨g₁', Subgroup.subset_closure (Or.inl rfl), h₁⟩
    · exact ⟨g₂', Subgroup.subset_closure (Or.inr rfl), h₂⟩
  | one => exact ⟨1, Subgroup.one_mem _, affineIntertwines_one a l⟩
  | mul x y _ _ hx hy =>
    obtain ⟨x', hx', hxx⟩ := hx
    obtain ⟨y', hy', hyy⟩ := hy
    exact ⟨x' * y', Subgroup.mul_mem _ hx' hy', hxx.mul hyy⟩
  | inv x _ hx =>
    obtain ⟨x', hx', hxx⟩ := hx
    exact ⟨x'⁻¹, Subgroup.inv_mem _ hx', hxx.inv⟩

theorem exists_affineIntertwines_of_mem_closure' {a l : ℝ} {g₁ g₂ g₁' g₂' : CylinderIsometry}
    (h₁ : AffineIntertwines a l g₁ g₁') (h₂ : AffineIntertwines a l g₂ g₂')
    {γ' : CylinderIsometry} (hγ : γ' ∈ Subgroup.closure {g₁', g₂'}) :
    ∃ γ ∈ Subgroup.closure {g₁, g₂}, AffineIntertwines a l γ γ' := by
  induction hγ using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨g₁, Subgroup.subset_closure (Or.inl rfl), h₁⟩
    · exact ⟨g₂, Subgroup.subset_closure (Or.inr rfl), h₂⟩
  | one => exact ⟨1, Subgroup.one_mem _, affineIntertwines_one a l⟩
  | mul x y _ _ hx hy =>
    obtain ⟨x', hx', hxx⟩ := hx
    obtain ⟨y', hy', hyy⟩ := hy
    exact ⟨x' * y', Subgroup.mul_mem _ hx' hy', hxx.mul hyy⟩
  | inv x _ hx =>
    obtain ⟨x', hx', hxx⟩ := hx
    exact ⟨x'⁻¹, Subgroup.inv_mem _ hx', hxx.inv⟩

def CylinderQuotientPresentation.normalizeDihedral {Z : Type*} [TopologicalSpace Z]
    [ChartedSpace E3 Z] {c₁ c₂ : ℝ} (hne : c₁ ≠ c₂)
    (pr : CylinderQuotientPresentation (dihedralGroup c₁ c₂) Z) :
    CylinderQuotientPresentation (dihedralGroup 0 (1 / 2)) Z where
  proj := pr.proj ∘ cylinderAffine c₁ (2 * (c₂ - c₁))
  isLocalDiffeomorph := DifferentialGeometry.isLocalDiffeomorph_comp pr.isLocalDiffeomorph
    (cylinderAffineDiffeomorph c₁ (2 * (c₂ - c₁))
      (mul_ne_zero two_ne_zero (sub_ne_zero.mpr hne.symm))).isLocalDiffeomorph
  surjective := pr.surjective.comp
    (cylinderAffineDiffeomorph c₁ (2 * (c₂ - c₁))
      (mul_ne_zero two_ne_zero (sub_ne_zero.mpr hne.symm))).surjective
  fibres a b := by
    have hl : 2 * (c₂ - c₁) ≠ 0 := mul_ne_zero two_ne_zero (sub_ne_zero.mpr hne.symm)
    have hinj : Function.Injective (cylinderAffine c₁ (2 * (c₂ - c₁))) :=
      (cylinderAffineDiffeomorph c₁ (2 * (c₂ - c₁)) hl).injective
    have h₁ : AffineIntertwines c₁ (2 * (c₂ - c₁))
        (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ c₁)
        (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ 0) := by
      have h := affineIntertwines_reflection 0 c₁ (2 * (c₂ - c₁))
      rwa [mul_zero, add_zero] at h
    have h₂ : AffineIntertwines c₁ (2 * (c₂ - c₁))
        (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ c₂)
        (LinearIsometryEquiv.neg ℝ, AffineIsometryEquiv.pointReflection ℝ (1 / 2)) := by
      have h := affineIntertwines_reflection (1 / 2) c₁ (2 * (c₂ - c₁))
      rwa [show c₁ + 2 * (c₂ - c₁) * (1 / 2) = c₂ by ring] at h
    change pr.proj (cylinderAffine _ _ a) = pr.proj (cylinderAffine _ _ b) ↔ _
    rw [pr.fibres]
    constructor
    · rintro ⟨γ, hγ, hab⟩
      obtain ⟨γ', hγ', hint⟩ := exists_affineIntertwines_of_mem_closure h₁ h₂ hγ
      exact ⟨γ', hγ', hinj ((hint a).symm.trans hab)⟩
    · rintro ⟨γ', hγ', rfl⟩
      obtain ⟨γ, hγ, hint⟩ := exists_affineIntertwines_of_mem_closure' h₁ h₂ hγ'
      exact ⟨γ, hγ, hint a⟩

def ProjectiveSumStandardDihedralPresentation : Prop :=
  Nonempty (CylinderQuotientPresentation (dihedralGroup 0 (1 / 2))
    (connectedSum projectiveThreeSpaceLift.{u} projectiveThreeSpaceLift.{u}).Carrier)

theorem dihedralCylinderQuotientIsProjectiveSum_of_standard
    (h : ProjectiveSumStandardDihedralPresentation.{u}) :
    DihedralCylinderQuotientIsProjectiveSum.{u} := by
  intro Z _ _ _ c₁ c₂ hne pr
  obtain ⟨pr₀⟩ := h
  let pr' := CylinderQuotientPresentation.normalizeDihedral hne pr
  exact nonempty_diffeomorph_of_same_fibres pr'.proj pr'.isLocalDiffeomorph pr'.surjective
    pr₀.proj pr₀.isLocalDiffeomorph pr₀.surjective
    (fun a b => (pr'.fibres a b).trans (pr₀.fibres a b).symm)

theorem sphericalProductStandardConnectedSum_of_universalCover_of_projectiveSum
    (hU : SphericalProductUniversalCover.{u})
    (hP : ProjectiveSumStandardDihedralPresentation.{u}) :
    GC.Endpoint.SphericalProductStandardConnectedSum.{u} :=
  sphericalProductStandardConnectedSum_of_universalCover_of_dihedral hU
    (dihedralCylinderQuotientIsProjectiveSum_of_standard hP)

theorem geometrizes_of_sphericalProductStructure_of_universalCover_of_projectiveSum
    (hU : SphericalProductUniversalCover.{u})
    (hP : ProjectiveSumStandardDihedralPresentation.{u})
    (P : ConnectedClosedOrientedManifold.{u} 3)
    (g : GeometricStructure (𝓡 3) P.Carrier) (hg : g.model = .sphericalProduct) :
    GC.Endpoint.Geometrizes P :=
  GC.Endpoint.geometrizes_of_sphericalProductStructure
    (sphericalProductStandardConnectedSum_of_universalCover_of_projectiveSum hU hP) P g hg

end GC.Geometry.SphericalProduct
