import DifferentialGeometry.Geometry.Metric.Approximation.EdgePoint
import DifferentialGeometry.Geometry.Metric.Approximation.StripChart
import DifferentialGeometry.Geometry.Metric.Scaling.RescaleComposition
import DifferentialGeometry.Geometry.Metric.Approximation.EdgeHalfPlaneModel
import DifferentialGeometry.Geometry.Metric.Approximation.EdgeBorderLifts
import DifferentialGeometry.Geometry.Metric.Approximation.EdgeHeight
import DifferentialGeometry.Geometry.Metric.Approximation.EdgeCoarseBorder
import DifferentialGeometry.Geometry.Metric.Approximation.StrongEdgePoint
import DifferentialGeometry.Geometry.Metric.Approximation.EndpointProductLifts
import DifferentialGeometry.Geometry.Metric.Approximation.StrongEdgeLifts
import DifferentialGeometry.Geometry.Metric.Approximation.StrongEdgeDensity
import DifferentialGeometry.Geometry.Metric.Approximation.PaddedStripBoundary
import DifferentialGeometry.Geometry.Metric.Approximation.MarkedModelHeight
import DifferentialGeometry.Geometry.Metric.Approximation.WeakEdgeDensity
import DifferentialGeometry.Topology.MetricSpace.LipschitzBallSelection

#print axioms GC.MetricGeometry.isEdgePoint
#print axioms GC.MetricGeometry.isEdgePoint_of_recentered_interval
#print axioms GC.MetricGeometry.isEdgePoint_of_lipschitz_scale
#print axioms GC.MetricGeometry.KleinerLottApprox.stripMap
#print axioms GC.MetricGeometry.KleinerLottApprox.stripMap_basepoint
#print axioms GC.MetricGeometry.KleinerLottApprox.stripMap_height
#print axioms GC.MetricGeometry.KleinerLottApprox.stripMap_estimates
#print axioms MetricSpace.rescale_one
#print axioms MetricSpace.rescale_mul
#print axioms MetricSpace.rescale_inv_ratio
#print axioms GC.MetricGeometry.lipschitzWith_normalized_scale
#print axioms GC.MetricGeometry.isEdgePoint.exists_local_half_plane_model
#print axioms GC.MetricGeometry.isEdgePoint.exists_local_half_plane_model_rescale
#print axioms GC.MetricGeometry.KleinerLottApprox.exists_strip_border_lift
#print axioms GC.MetricGeometry.KleinerLottApprox.exists_weak_edge_strip_border_lift
#print axioms GC.MetricGeometry.KleinerLottApprox.strip_height_lt_of_rescaled_edgePoint
#print axioms GC.MetricGeometry.KleinerLottApprox.strip_height_lt_of_weak_edge
#print axioms GC.MetricGeometry.KleinerLottApprox.coarse_border_of_lipschitz_scale
#print axioms GC.MetricGeometry.isEdgePoint_of_marked_interval_model
#print axioms GC.MetricGeometry.isEdgePoint_of_ray_model
#print axioms GC.MetricGeometry.KleinerLottApprox.coverage_witness_radius
#print axioms GC.MetricGeometry.KleinerLottApprox.exists_product_lift_radius
#print axioms GC.MetricGeometry.KleinerLottApprox.exists_nearby_product_lift
#print axioms GC.MetricGeometry.exists_strong_edge_interval_lift
#print axioms GC.MetricGeometry.exists_strong_edge_ray_lift
#print axioms GC.MetricGeometry.exists_strong_edge_near_interval_model
#print axioms GC.MetricGeometry.exists_strong_edge_near_ray_model
#print axioms GC.MetricGeometry.strip_height_lt_of_local_half_plane_model_of_bounded_mark
#print axioms GC.MetricGeometry.strip_height_lt_of_local_half_plane_model
#print axioms GC.MetricGeometry.padded_strip_height_lt_of_half_plane_model
#print axioms GC.MetricGeometry.KleinerLottApprox.model_height_lt_of_rescaled_edgePoint
#print axioms GC.MetricGeometry.KleinerLottApprox.model_height_lt_of_weak_edge
#print axioms GC.MetricGeometry.exists_strong_edge_near_weak_interval_model
#print axioms GC.MetricGeometry.exists_strong_edge_near_weak_ray_model
#print axioms Metric.estimates_of_intersecting_lipschitz_scale_balls
#print axioms Metric.exists_finite_disjoint_lipschitz_scale_selection
