import DifferentialGeometry.Geometry.Metric.Approximation.PrescribedLowDimensionalModel
import Mathlib.Tactic.Linter

#lint only unusedArguments simpNF synTaut unusedHavesSuffices explicitVarsOfIff in DifferentialGeometry.Geometry.Metric.Approximation.PrescribedLowDimensionalModel
