import Mathlib.Tactic.Linter
import DifferentialGeometry.Geometry.Metric.TruncatedRange
import DifferentialGeometry.Analysis.Calculus.GraphCoverage
import DifferentialGeometry.Geometry.Metric.RetainedMarkerRadii
import DifferentialGeometry.Analysis.ParameterSelection.AdjustmentBudget

#check GC.MetricGeometry.hausdorffDist_truncated_range_le
#print axioms GC.MetricGeometry.hausdorffDist_truncated_range_le

#check GC.MetricGeometry.hausdorffDist_graph_tangent_closedBall_le
#print axioms GC.MetricGeometry.hausdorffDist_graph_tangent_closedBall_le

#check GC.MetricGeometry.graph_coverage_relative_error_le
#print axioms GC.MetricGeometry.graph_coverage_relative_error_le

#check GC.MetricGeometry.scale_comparison_of_retained_marker
#print axioms GC.MetricGeometry.scale_comparison_of_retained_marker

#check GC.MetricGeometry.radius_control_of_retained_markers
#print axioms GC.MetricGeometry.radius_control_of_retained_markers

#check GC.MetricGeometry.scale_bounds_on_closedBall
#print axioms GC.MetricGeometry.scale_bounds_on_closedBall

#check DifferentialGeometry.Analysis.adjustment_errors_le_of_budget
#print axioms DifferentialGeometry.Analysis.adjustment_errors_le_of_budget

#check DifferentialGeometry.Analysis.adjustment_threshold_pos_and_bounds
#print axioms DifferentialGeometry.Analysis.adjustment_threshold_pos_and_bounds

#check DifferentialGeometry.Analysis.adjustment_errors_lt_of_threshold
#print axioms DifferentialGeometry.Analysis.adjustment_errors_lt_of_threshold
