import DifferentialGeometry.Tensor.LinearAlgebra.Eigenspace.FixedSubspace
import DifferentialGeometry.Analysis.InnerProductSpace.NormalSpectralSection
import DifferentialGeometry.Analysis.InnerProductSpace.FiniteNormalReduction
import DifferentialGeometry.Analysis.InnerProductSpace.ProjectionSpectrum
import DifferentialGeometry.Analysis.InnerProductSpace.ProjectionResolvent
import DifferentialGeometry.Analysis.Calculus.Resolvent

#print axioms Submodule.le_iSup_eigenspace_of_fixed
#print axioms Submodule.starProjection_eigenspace_iSup_of_fixed
#print axioms Submodule.eigenspace_iSup_starProjection_comp_of_fixed
#print axioms Submodule.starProjection_weighted_normal_section
#print axioms Submodule.finite_affine_family_normal_reduction
#print axioms ContinuousLinearMap.eigenvector_projection_error_bounds
#print axioms ContinuousLinearMap.min_norm_mul_norm_le_norm_smul_sub_starProjection
#print axioms ContinuousLinearMap.norm_smul_sub_apply_ge_of_norm_sub_starProjection_le
#print axioms ContinuousLinearMap.norm_eigenvalue_or_sub_one_le_of_norm_sub_starProjection_le
#print axioms ContinuousLinearMap.spectrum_subset_closedBall_union_of_norm_sub_starProjection_le
#print axioms ContinuousLinearMap.norm_sub_spectrum_ge_of_norm_sub_starProjection_le
#print axioms ContinuousLinearMap.mem_resolventSet_of_norm_sub_starProjection_lt
#print axioms ContinuousLinearMap.norm_resolvent_le_of_norm_sub_starProjection_le
#print axioms ContDiffWithinAt.resolvent
#print axioms ContDiffAt.resolvent
#print axioms ContDiffOn.resolvent
#print axioms ContDiff.resolvent
#print axioms HasFDerivAt.resolvent
#print axioms DifferentiableAt.norm_fderiv_resolvent_le
