import DifferentialGeometry.Topology.PiecewiseLinear.GeneralPositionInDouble
import DifferentialGeometry.Topology.PiecewiseLinear.TameNestedCells
import DifferentialGeometry.Topology.PiecewiseLinear.LoopTheorem.CoverReductionOrientableProducer
import DifferentialGeometry.Topology.PiecewiseLinear.LoopTheorem.DescentStepOrientable

namespace DifferentialGeometry.Topology.PiecewiseLinear

theorem moise304 : Moise304 :=
  moise304_of_generalPositionBuffered_of_descentStepOrientable generalPositionInDoubleBuffered
    descentStepOrientableStatement

theorem moise305Tame : Moise305Tame :=
  moise305_tame_of_moise304 moise304

end DifferentialGeometry.Topology.PiecewiseLinear
