import DifferentialGeometry.Topology.PiecewiseLinear.CenteredPrismBallPair
import DifferentialGeometry.Topology.PiecewiseLinear.DisjointSupportedPLEmbeddings
import DifferentialGeometry.Topology.PiecewiseLinear.IsAnnulusOnCompact
import DifferentialGeometry.Topology.PiecewiseLinear.LocallyFiniteOpenEnlargements
import DifferentialGeometry.Topology.PiecewiseLinear.LocallyFiniteSeparationScales
import DifferentialGeometry.Topology.PiecewiseLinear.ManifoldPointTransport
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellEnlargement
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellMarkerMove
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnBoundarySphere
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnPolyhedralBall
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnStabilityScales
import DifferentialGeometry.Topology.PiecewiseLinear.PLPieceBallInterior
import DifferentialGeometry.Topology.PiecewiseLinear.PLPieceConjugateEmbedding
import DifferentialGeometry.Topology.PiecewiseLinear.Section34AnnularGenerators
import DifferentialGeometry.Topology.PiecewiseLinear.Section34CellEnlargements
import DifferentialGeometry.Topology.PiecewiseLinear.Section34ChartLocalEnlargements
import DifferentialGeometry.Topology.PiecewiseLinear.Section34EdgeEnds
import DifferentialGeometry.Topology.PiecewiseLinear.Section34EdgeGraphRegions
import DifferentialGeometry.Topology.PiecewiseLinear.Section34GraphCores
import DifferentialGeometry.Topology.PiecewiseLinear.Section34GraphCoveringEdgeCells
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LensImages
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LensIsolation
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LocalMargins
import DifferentialGeometry.Topology.PiecewiseLinear.Section34MarkedPiercedCells
import DifferentialGeometry.Topology.PiecewiseLinear.Section34NestedPiercingRegularNeighborhood
import DifferentialGeometry.Topology.PiecewiseLinear.Section34NestedPiercingSubdivision
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedBallFrontiers
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedBallHeightMove
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedBallModel
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedBallRoof
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedBallTransport
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedEdgeCells
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercedVertexCells
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingCircleNeighborhoods
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingMarkerRoutes
import DifferentialGeometry.Topology.PiecewiseLinear.Section34SeparationMargins
import DifferentialGeometry.Topology.PiecewiseLinear.Section34SplitDiskNeighborhoods
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexCellIntersections
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexEdgePasting
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexPreparationProbe
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexScales
import DifferentialGeometry.Topology.PiecewiseLinear.SupportedPLCellExtension
import DifferentialGeometry.Topology.PiecewiseLinear.SupportedPLPieceConjugate
import DifferentialGeometry.Topology.PiecewiseLinear.SupportedPLPrismShift

open DifferentialGeometry.Topology
open DifferentialGeometry.Topology.PiecewiseLinear

#print axioms exists_centered_prism_piece_of_boundary_disk_pair
#print axioms exists_isPL_embedding_of_finite_disjoint_support
#print axioms IsPLCellOn.exists_image_of_finite_disjoint_support
#print axioms IsAnnulusOn.isCompact
#print axioms IsAnnulusOn.isCompact_first
#print axioms IsAnnulusOn.isCompact_second
#print axioms exists_locallyFinite_open_supersets
#print axioms exists_separation_scales_of_locallyFinite
#print axioms exists_separation_scales_of_locallyFinite_on
#print axioms exists_isPL_homeomorph_map_point_eqOn_compl
#print axioms IsPLCellOn.exists_enlargement
#print axioms exists_locallyFinite_isPLCellOn_enlargements
#print axioms IsPLCellOn.exists_excluding_point_preserving_union
#print axioms exists_marked_cell_pair_of_disjoint_connected_routes
#print axioms IsPLHomeomorphInto.exists_pLPiece_of_isPolyhedron
#print axioms IsPLCellOn.isPolyhedralSphere_boundary
#print axioms IsPLCellOn.isPolyhedralBall
#print axioms IsPolyhedralBall.exists_isPLCellOn
#print axioms IsPolyhedralBall.isPLCellOn
#print axioms exists_core_stability_scales_lt
#print axioms PLPieceIn.frontier_image_of_isPLBall
#print axioms PLPieceIn.image_interior_of_isPLBall
#print axioms PLPieceIn.exists_equiv_conjugate
#print axioms IsLocallyFiniteRegularNeighborhoodOf.carriesFundamentalGroupOnto
#print axioms IsAnnulusOn.boundaries_carry_of_core
#print axioms PLPieceIn.isPLOn_conjugate
#print axioms bicollar_sides_of_regular_closed
#print axioms subset_interior_image_of_bicollar_shift
#print axioms IsPLCellOn.enlargement_of_bicollar_shift
#print axioms exists_section34_chart_local_enlargements
#print axioms exists_section34_edge_ends
#print axioms isCompact_inter_graphSkeletonSpace
#print axioms exists_section34_splitDisk_vertex_neighborhood
#print axioms exists_section34_compact_edge_graph_region
#print axioms isClosed_preimage_graphSkeletonSpace
#print axioms isClosed_graphSkeletonSpace_in_domain
#print axioms exists_section34_graph_cores
#print axioms exists_section34_graph_cores_of_isPLCellOn
#print axioms exists_section34_graph_covering_edge_cells
#print axioms exists_section34_marked_graph_covering_edge_cells
#print axioms locallyFinite_image_of_embedding
#print axioms section34_lens_images
#print axioms exists_section34_overlap_isolation_scales
#print axioms exists_locallyFinite_disjoint_cthickening_intersections
#print axioms exists_section34_vertex_scales_with_isolated_overlaps
#print axioms exists_section34_local_margins
#print axioms exists_pierced_cell_pair_excluding_opposite_markers
#print axioms exists_marked_pierced_cell_pair_covering_compact
#print axioms LocallyFinitePLPieceIn.finiteRestriction
#print axioms LocallyFinitePLPieceIn.exists_derivedNeighborhood_stage
#print axioms LocallyFinitePLPieceIn.isLocallyFiniteRegularNeighborhoodOf_derivedNeighborhood
#print axioms IsPLDerivedNeighborhoodExhaustion.exists_ambient_derivedNeighborhoods
#print axioms exists_isSubdivision_union_of_preserved_intersection
#print axioms exists_isSubdivision_restrict_space_of_finite_patch
#print axioms LocallyFinitePLPieceIn.exists_isSubdivision_restrict_space_finite_change
#print axioms LocallyFinitePLPieceIn.locallyFinite_of_isSubdivision_of_finite_new_faces
#print axioms restrict_faces_finite_of_finite_new_faces
#print axioms LocallyFinitePLPieceIn.isLocallyFiniteRegularNeighborhoodOf_subdivision
#print axioms LocallyFinitePLPieceIn.isPLSphere_preimage_of_isPolyhedralSphere
#print axioms IsPLDerivedNeighborhoodExhaustion.exists_regularNeighborhood_of_isPolyhedralSphere
#print axioms frontier_inter_signed_height_balls
#print axioms piercingHeightMove
#print axioms piercingHeightMove_strictMono
#print axioms piercingHeightMove_injective
#print axioms piercingHeightMove_eq_self
#print axioms piercingHeightMove_image_diff_slab
#print axioms piercingHeightMove_apply_zero
#print axioms isPiecewiseAffineOn_piercingHeightMove
#print axioms piercingHeightMove_image_lower
#print axioms piercingHeightMove_image_upper
#print axioms piercingHeightMove_image_prism
#print axioms isPLHomeomorphOn_piercingHeightMove
#print axioms isPLHomeomorphOn_piercingHeightMove_self
#print axioms exists_pierced_prism_ball_pair
#print axioms exists_pierced_square_ball_pair
#print axioms isPLBall_square_closedBall
#print axioms exists_piercing_square_roof
#print axioms exists_pierced_cell_pair_in_prism
#print axioms exists_pierced_cell_pair_covering_compact
#print axioms exists_section34_pierced_edge_cells
#print axioms exists_section34_pierced_vertex_cells
#print axioms exists_section34_unmarked_vertex_cells
#print axioms exists_section34_piercing_circle_neighborhoods
#print axioms exists_disjoint_piercing_marker_routes
#print axioms exists_section34_separation_margins
#print axioms section34_splitDisks_pairwise_disjoint
#print axioms exists_section34_splitDisk_neighborhoods
#print axioms Section34CutFrame.exists_edge_of_vertex_intersection
#print axioms section34_vertex_cells_intersection_of_ne
#print axioms section34_vertex_cells_disjoint_of_nonadjacent
#print axioms section34_vertex_cells_triple_inter_eq_empty
#print axioms section34_graph_subset_vertex_interiors_union_splitDisks
#print axioms exists_section34_vertex_embeddings
#print axioms exists_section34VertexPreparation
#print axioms exists_section34_vertex_scales_with_sum_margins
#print axioms section34CellThickening_mono
#print axioms Section34VertexPreparation.mono
#print axioms exists_supported_isPL_homeomorph_extension
#print axioms PLPieceIn.exists_supported_conjugate
#print axioms PLPieceIn.exists_supported_prism_shift
