import DifferentialGeometry.Topology.PiecewiseLinear.IsAnnulusOnCompact
import DifferentialGeometry.Topology.PiecewiseLinear.LocallyFiniteSeparationScales
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnStabilityScales
import DifferentialGeometry.Topology.PiecewiseLinear.Section34AnnularGenerators
import DifferentialGeometry.Topology.PiecewiseLinear.Section34EdgeEnds
import DifferentialGeometry.Topology.PiecewiseLinear.Section34GraphCores
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LensImages
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LensIsolation
import DifferentialGeometry.Topology.PiecewiseLinear.Section34LocalMargins
import DifferentialGeometry.Topology.PiecewiseLinear.Section34SeparationMargins
import DifferentialGeometry.Topology.PiecewiseLinear.Section34SplitDiskNeighborhoods
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexPreparationProbe
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexScales

open DifferentialGeometry.Topology.PiecewiseLinear

#print axioms IsAnnulusOn.isCompact
#print axioms IsAnnulusOn.isCompact_first
#print axioms IsAnnulusOn.isCompact_second
#print axioms exists_separation_scales_of_locallyFinite
#print axioms exists_separation_scales_of_locallyFinite_on
#print axioms exists_core_stability_scales_lt
#print axioms IsLocallyFiniteRegularNeighborhoodOf.carriesFundamentalGroupOnto
#print axioms IsAnnulusOn.boundaries_carry_of_core
#print axioms exists_section34_edge_ends
#print axioms isClosed_preimage_graphSkeletonSpace
#print axioms exists_section34_graph_cores
#print axioms exists_section34_graph_cores_of_isPLCellOn
#print axioms locallyFinite_image_of_embedding
#print axioms section34_lens_images
#print axioms exists_section34_overlap_isolation_scales
#print axioms exists_locallyFinite_disjoint_cthickening_intersections
#print axioms exists_section34_vertex_scales_with_isolated_overlaps
#print axioms exists_section34_local_margins
#print axioms exists_section34_separation_margins
#print axioms section34_splitDisks_pairwise_disjoint
#print axioms exists_section34_splitDisk_neighborhoods
#print axioms exists_section34_vertex_scales_with_sum_margins
#print axioms section34CellThickening_mono
#print axioms Section34VertexPreparation.mono
#print axioms exists_section34VertexPreparation
