import DifferentialGeometry.Topology.PiecewiseLinear.ChartRelativeGeneralPosition
import DifferentialGeometry.Topology.PiecewiseLinear.CrossingSurfaceLineChart
import DifferentialGeometry.Topology.PiecewiseLinear.CrossingTracePolyhedron
import DifferentialGeometry.Topology.PiecewiseLinear.DisjointSupportedHomeomorphs
import DifferentialGeometry.Topology.PiecewiseLinear.IsAnnulusOnCompact
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnBoundarySphere
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnInteriorRegionStability
import DifferentialGeometry.Topology.PiecewiseLinear.PLCellOnThickeningStability
import DifferentialGeometry.Topology.PiecewiseLinear.PolyhedralSurfaceCharts
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingAnnularCrossings
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingAuxiliaryScales
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingBufferStability
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingCircles
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingComponentStability
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingConditionsOfCrossings
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingIntersectionConfinement
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingNonempty
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingPackage
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingRegionStability
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingSideStability
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingSourceBicollar
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingSourceBuffers
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingSourceSides
import DifferentialGeometry.Topology.PiecewiseLinear.Section34PiercingSurfacePatches
import DifferentialGeometry.Topology.PiecewiseLinear.Section34RelativeVertexCrossings
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexApproximation
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexChartScales
import DifferentialGeometry.Topology.PiecewiseLinear.Section34VertexSupportedMoves
import DifferentialGeometry.Topology.PiecewiseLinear.SupportedSurfaceGeneralPosition

open DifferentialGeometry.Topology
open DifferentialGeometry.Topology.PiecewiseLinear

#print axioms exists_small_isPL_homeomorph_generalPosition_off_polyhedron_in_chart
#print axioms exists_small_isPL_homeomorph_sphere_crossing_in_chart
#print axioms HasPLCrossingAt.exists_lineChart_of_local_disks
#print axioms HasPLCrossingAt.exists_lineChart_of_surface_charts
#print axioms HasPLCrossingAt.exists_lineChart_of_eventuallyEq_surface_charts
#print axioms HasPLCrossingAt.exists_isPolyhedron_nhdsWithin_inter
#print axioms isLocallyPolyhedral_inter_of_hasPLCrossingAt
#print axioms isPolyhedron_inter_of_isCompact_of_hasPLCrossingAt
#print axioms isPolyhedron_chart_inter_of_isCompact_of_hasPLCrossingAt
#print axioms exists_isPL_homeomorph_of_finite_disjoint_support
#print axioms homeomorph_eqOn_of_disjoint_support
#print axioms homeomorph_image_eq_of_disjoint_support
#print axioms dist_lt_of_disjoint_support
#print axioms IsAnnulusOn.isCompact
#print axioms IsAnnulusOn.isCompact_first
#print axioms IsAnnulusOn.isCompact_second
#print axioms IsPLHomeomorphInto.exists_pLPiece_of_isPolyhedron
#print axioms IsPLCellOn.isPolyhedralSphere_boundary
#print axioms exists_cthickening_subset_image_interior_stable_of_subset_isPLCellOn
#print axioms exists_cthickening_subset_image_interior_stable_of_isPLCellOn
#print axioms IsPolyhedralSphere.exists_isOpen_inter_homeomorph_of_two
#print axioms IsPolyhedralSphere.exists_isOpen_inter_chart_image_homeomorph_of_two
#print axioms IsPLCellOn.exists_isOpen_inter_boundary_homeomorph
#print axioms IsPLCellOn.exists_isOpen_inter_boundary_chart_image_homeomorph
#print axioms section34_piercing_annular_crossings
#print axioms exists_auxiliary_scales_preserving_piercing_sides_of_connected_buffers
#print axioms exists_auxiliary_scales_preserving_piercing_sides
#print axioms exists_section34_component_stability_scales_of_connected_buffers
#print axioms exists_positive_finite_crossing_circle_family
#print axioms exists_positive_finite_piercing_circle_family
#print axioms IsPLCellOn.isConnected_interior
#print axioms IsPLCellOn.frontier_inter_interior_nonempty
#print axioms compact_connected_sides_of_component_pair
#print axioms exists_compact_connected_buffers_of_bicollar
#print axioms piercing_components_of_connected_buffers
#print axioms piercing_conditions_of_crossings_and_margins
#print axioms exists_intersection_confinement_of_compact
#print axioms IsAnnulusOn.isConnected
#print axioms IsAnnulusOn.boundaries_nonempty
#print axioms IsAnnulusOn.image_inter_frontier_nonempty
#print axioms section34_piercing_trace_nonempty
#print axioms exists_section34PiercingPackage
#print axioms exists_section34_region_image_stability_scales
#print axioms exists_section34_outer_annulus_stability_scales
#print axioms exists_section34_inner_end_stability_scales
#print axioms exists_section34_trace_interior_stability_scales
#print axioms exists_section34_second_trace_interior_stability_scales
#print axioms IsAnnulusOn.locallyConnectedSpace
#print axioms IsPolyhedralSphere.isConnected
#print axioms IsPLCellOn.exists_piercing_bicollar
#print axioms exists_section34_connected_buffers_of_source_sides
#print axioms exists_section34_connected_buffers
#print axioms IsPLCellOn.isConnected_boundary
#print axioms section34_piercing_source_sides
#print axioms IsPolyhedralManifoldWithBoundary.exists_patch
#print axioms exists_section34_relative_vertex_crossings
#print axioms Moise341.exists_chart_local_cell_approximations
#print axioms Moise341.exists_section34VertexApproximation
#print axioms exists_chart_stability_scales_of_isCompact
#print axioms exists_section34_vertex_chart_stability_scales
#print axioms exists_section34_vertex_supported_moves
#print axioms IsPolyhedralManifoldWithBoundary.exists_chart_complex
#print axioms eventually_mem_chart_image_iff_of_eventually
#print axioms exists_small_isPL_homeomorph_surface_crossing_in_chart
