import DifferentialGeometry.Topology.Manifold.Quotient
import DifferentialGeometry.Geometry.Metric.Quotient
import DifferentialGeometry.Geometry.Metric.Distance.InducedMetricSpace
import Mathlib.Algebra.Group.MinimalAxioms

/-!
# The flat edge carrier `S¹_a × K_{b,L}` as an orbit quotient (lane O-FIXTURE-CT, K-C, file 1)

Edge fixture (review 75, configuration C-E with the flat Möbius end; lead decision 2026-10-05
23:4x, Option A). The carrier is `ℝ³ / Γ` for the Bieberbach group `Γ` generated by
`(x, y, t) ↦ (x + a, y, t)`, `(x, y, t) ↦ (x, y + b, t)` and the glide reflection
`ι(x, y, t) = (x, -y, t + L/2)`. Collapsing the `t`-circle gives the flat annulus
`S¹_a × [0, b/2]` whose two boundary circles (the reflection lines `y ∈ (b/2)ℤ`) are the edges;
near a reflection line the carrier is `ℝ × Möb_L`, which collapses to the half plane.
The carrier is NOT orientable (it is `S¹ × Klein bottle`); see the lane state file (F2).

* `KleinPeriods_OFT`, `kSign_OFT` (the sign `(-1)^k`), `KleinGroup_OFT` (`ℤ³` with
  `(m, n, k)(m', n', k') = (m + m', n + (-1)^k n', k + k')`), `kleinLin_OFT`, `kleinVec_OFT`;
* the action `g • v = kleinLin_OFT g.k v + kleinVec_OFT P g` (affine Euclidean isometries) and its
  instances: continuous, smooth, free (`IsCancelSMul`), properly discontinuous;
* `Klein_OFT P` (orbit quotient: `ℝ³` charts, smooth, `T₂`, connected, compact),
  `kleinPi_OFT` (local diffeomorphism and covering map), `kleinPi_eq_iff_OFT`.
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric
open scoped Manifold ContDiff Topology

namespace DifferentialGeometry.Geometry.Collapse

local notation "E3" => EuclideanSpace ℝ (Fin 3)

/-- The three periods: `a` (edge direction), `b` (`y`-period; the collapsed strip has width
`b / 2`), `L` (fibre). -/
structure KleinPeriods_OFT where
  a : ℝ
  b : ℝ
  L : ℝ
  a_pos : 0 < a
  b_pos : 0 < b
  L_pos : 0 < L

/-- The sign `(-1)^k ∈ ℤ`. -/
def kSign_OFT (k : ℤ) : ℤ := (k.negOnePow : ℤ)

theorem kSign_add_OFT (k k' : ℤ) : kSign_OFT (k + k') = kSign_OFT k * kSign_OFT k' := by
  simp [kSign_OFT, Int.negOnePow_add]

theorem kSign_zero_OFT : kSign_OFT 0 = 1 := by simp [kSign_OFT]

theorem kSign_neg_OFT (k : ℤ) : kSign_OFT (-k) = kSign_OFT k := by
  simp [kSign_OFT, Int.negOnePow_neg]

theorem kSign_mul_self_OFT (k : ℤ) : kSign_OFT k * kSign_OFT k = 1 := by
  rw [← abs_mul_abs_self, kSign_OFT, Int.abs_negOnePow]
  norm_num

theorem kSign_real_mul_self_OFT (k : ℤ) : (kSign_OFT k : ℝ) * (kSign_OFT k : ℝ) = 1 := by
  exact_mod_cast kSign_mul_self_OFT k

/-- The Bieberbach group as a set: integer triples `(m, n, k)`. -/
@[ext] structure KleinGroup_OFT (_P : KleinPeriods_OFT) where
  m : ℤ
  n : ℤ
  k : ℤ

variable {P : KleinPeriods_OFT}

instance : Mul (KleinGroup_OFT P) :=
  ⟨fun g h => ⟨g.m + h.m, g.n + kSign_OFT g.k * h.n, g.k + h.k⟩⟩

instance : One (KleinGroup_OFT P) := ⟨⟨0, 0, 0⟩⟩

instance : Inv (KleinGroup_OFT P) := ⟨fun g => ⟨-g.m, -(kSign_OFT g.k * g.n), -g.k⟩⟩

@[simp] theorem kleinMul_m_OFT (g h : KleinGroup_OFT P) : (g * h).m = g.m + h.m := rfl
@[simp] theorem kleinMul_n_OFT (g h : KleinGroup_OFT P) :
    (g * h).n = g.n + kSign_OFT g.k * h.n := rfl
@[simp] theorem kleinMul_k_OFT (g h : KleinGroup_OFT P) : (g * h).k = g.k + h.k := rfl
@[simp] theorem kleinOne_m_OFT : (1 : KleinGroup_OFT P).m = 0 := rfl
@[simp] theorem kleinOne_n_OFT : (1 : KleinGroup_OFT P).n = 0 := rfl
@[simp] theorem kleinOne_k_OFT : (1 : KleinGroup_OFT P).k = 0 := rfl
@[simp] theorem kleinInv_m_OFT (g : KleinGroup_OFT P) : g⁻¹.m = -g.m := rfl
@[simp] theorem kleinInv_n_OFT (g : KleinGroup_OFT P) : g⁻¹.n = -(kSign_OFT g.k * g.n) := rfl
@[simp] theorem kleinInv_k_OFT (g : KleinGroup_OFT P) : g⁻¹.k = -g.k := rfl

instance (P : KleinPeriods_OFT) : Group (KleinGroup_OFT P) :=
  Group.ofLeftAxioms
    (fun a b c => by
      ext
      · simp only [kleinMul_m_OFT]; ring
      · simp only [kleinMul_n_OFT, kleinMul_k_OFT, kSign_add_OFT]; ring
      · simp only [kleinMul_k_OFT]; ring)
    (fun a => by
      ext
      · simp
      · simp [kSign_zero_OFT]
      · simp)
    (fun a => by
      ext
      · simp
      · simp only [kleinMul_n_OFT, kleinInv_n_OFT, kleinInv_k_OFT, kSign_neg_OFT,
          kleinOne_n_OFT]
        ring
      · simp)

/-- The linear part `diag(1, (-1)^k, 1)`. -/
def kleinLin_OFT (k : ℤ) : E3 →L[ℝ] E3 :=
  LinearMap.toContinuousLinearMap
    { toFun := fun v => WithLp.toLp 2 ![v 0, (kSign_OFT k : ℝ) * v 1, v 2]
      map_add' := fun v w => by
        ext i
        fin_cases i <;> simp; ring
      map_smul' := fun c v => by
        ext i
        fin_cases i <;> simp; ring }

theorem kleinLin_apply_OFT (k : ℤ) (v : E3) :
    kleinLin_OFT k v = WithLp.toLp 2 ![v 0, (kSign_OFT k : ℝ) * v 1, v 2] := rfl

/-- The translation part `(m a, n b, k L / 2)`. -/
def kleinVec_OFT (P : KleinPeriods_OFT) (g : KleinGroup_OFT P) : E3 :=
  WithLp.toLp 2 ![(g.m : ℝ) * P.a, (g.n : ℝ) * P.b, (g.k : ℝ) * (P.L / 2)]

instance (P : KleinPeriods_OFT) : MulAction (KleinGroup_OFT P) E3 where
  smul g v := kleinLin_OFT g.k v + kleinVec_OFT P g
  one_smul v := by
    change kleinLin_OFT (1 : KleinGroup_OFT P).k v + kleinVec_OFT P 1 = v
    ext i
    fin_cases i <;> simp [kleinLin_apply_OFT, kleinVec_OFT, kSign_zero_OFT]
  mul_smul g h v := by
    change kleinLin_OFT (g * h).k v + kleinVec_OFT P (g * h) =
      kleinLin_OFT g.k (kleinLin_OFT h.k v + kleinVec_OFT P h) + kleinVec_OFT P g
    ext i
    fin_cases i <;> simp [kleinLin_apply_OFT, kleinVec_OFT, kSign_add_OFT] <;> ring

theorem kleinSmul_def_OFT (g : KleinGroup_OFT P) (v : E3) :
    g • v = kleinLin_OFT g.k v + kleinVec_OFT P g := rfl

theorem kleinSmul_zero_OFT (g : KleinGroup_OFT P) (v : E3) :
    (g • v) 0 = v 0 + (g.m : ℝ) * P.a := by
  simp [kleinSmul_def_OFT, kleinLin_apply_OFT, kleinVec_OFT]

theorem kleinSmul_one_OFT (g : KleinGroup_OFT P) (v : E3) :
    (g • v) 1 = (kSign_OFT g.k : ℝ) * v 1 + (g.n : ℝ) * P.b := by
  simp [kleinSmul_def_OFT, kleinLin_apply_OFT, kleinVec_OFT]

theorem kleinSmul_two_OFT (g : KleinGroup_OFT P) (v : E3) :
    (g • v) 2 = v 2 + (g.k : ℝ) * (P.L / 2) := by
  simp [kleinSmul_def_OFT, kleinLin_apply_OFT, kleinVec_OFT]

theorem kleinLin_kleinLin_OFT (k : ℤ) (v : E3) : kleinLin_OFT k (kleinLin_OFT k v) = v := by
  ext i
  fin_cases i <;> simp [kleinLin_apply_OFT, ← mul_assoc, kSign_real_mul_self_OFT]

instance (P : KleinPeriods_OFT) : ContinuousConstSMul (KleinGroup_OFT P) E3 :=
  ⟨fun g => (kleinLin_OFT g.k).continuous.add continuous_const⟩

instance (P : KleinPeriods_OFT) : IsCancelSMul (KleinGroup_OFT P) E3 where
  left_cancel' g x y h := by
    rw [kleinSmul_def_OFT, kleinSmul_def_OFT] at h
    have h' := congrArg (kleinLin_OFT g.k) (add_right_cancel h)
    rwa [kleinLin_kleinLin_OFT, kleinLin_kleinLin_OFT] at h'
  right_cancel' g h x hgh := by
    have h0 := congrArg (fun v : E3 => v 0) hgh
    have h1 := congrArg (fun v : E3 => v 1) hgh
    have h2 := congrArg (fun v : E3 => v 2) hgh
    simp only [kleinSmul_zero_OFT, kleinSmul_one_OFT, kleinSmul_two_OFT] at h0 h1 h2
    have hm : g.m = h.m := by
      have := mul_right_cancel₀ P.a_pos.ne' (add_left_cancel h0)
      exact_mod_cast this
    have hk : g.k = h.k := by
      have := mul_right_cancel₀ (half_pos P.L_pos).ne' (add_left_cancel h2)
      exact_mod_cast this
    rw [hk] at h1
    have hn : g.n = h.n := by
      have := mul_right_cancel₀ P.b_pos.ne' (add_left_cancel h1)
      exact_mod_cast this
    exact KleinGroup_OFT.ext hm hn hk

instance (P : KleinPeriods_OFT) : ContMDiffConstSMul 𝓘(ℝ, E3) ∞ (KleinGroup_OFT P) E3 :=
  ⟨fun g => ((kleinLin_OFT g.k).contDiff.add contDiff_const).contMDiff⟩

/-- The group elements with bounded integer coordinates form a finite set. -/
theorem finite_kleinGroup_bounded_OFT (P : KleinPeriods_OFT) (B : ℝ) :
    {g : KleinGroup_OFT P | |(g.m : ℝ)| * P.a ≤ B ∧ |(g.n : ℝ)| * P.b ≤ B ∧
      |(g.k : ℝ)| * (P.L / 2) ≤ B}.Finite := by
  have hbox : ∀ c : ℝ, 0 < c → ∀ z : ℤ, |(z : ℝ)| * c ≤ B →
      z ∈ Icc (-⌈B / c⌉) ⌈B / c⌉ := by
    intro c hc z hz
    have h2 : |(z : ℝ)| ≤ B / c := by rwa [le_div_iff₀ hc]
    have h3 : (z : ℝ) ≤ ((⌈B / c⌉ : ℤ) : ℝ) := (le_abs_self _).trans (h2.trans (Int.le_ceil _))
    have h4 : -(z : ℝ) ≤ ((⌈B / c⌉ : ℤ) : ℝ) := (neg_le_abs _).trans (h2.trans (Int.le_ceil _))
    exact ⟨by exact_mod_cast (by linarith : -((⌈B / c⌉ : ℤ) : ℝ) ≤ (z : ℝ)),
      by exact_mod_cast h3⟩
  have hfin := ((Set.finite_Icc (-⌈B / P.a⌉) ⌈B / P.a⌉).prod
    ((Set.finite_Icc (-⌈B / P.b⌉) ⌈B / P.b⌉).prod
      (Set.finite_Icc (-⌈B / (P.L / 2)⌉) ⌈B / (P.L / 2)⌉))).image
    (fun z : ℤ × ℤ × ℤ => (⟨z.1, z.2.1, z.2.2⟩ : KleinGroup_OFT P))
  refine hfin.subset fun g hg => ?_
  exact ⟨(g.m, g.n, g.k), ⟨hbox P.a P.a_pos g.m hg.1, hbox P.b P.b_pos g.n hg.2.1,
    hbox (P.L / 2) (half_pos P.L_pos) g.k hg.2.2⟩, rfl⟩

instance (P : KleinPeriods_OFT) : ProperlyDiscontinuousSMul (KleinGroup_OFT P) E3 where
  finite_disjoint_inter_image {K L} hK hL := by
    obtain ⟨r, hr⟩ := (hK.isBounded.union hL.isBounded).subset_closedBall (0 : E3)
    refine (finite_kleinGroup_bounded_OFT P (2 * r)).subset fun g hg => ?_
    obtain ⟨y, ⟨x, hx, rfl⟩, hyL⟩ := hg
    have hx' := hr (Or.inl hx)
    have hy' := hr (Or.inr hyL)
    rw [mem_closedBall, dist_zero_right] at hx' hy'
    have hc : ∀ (v : E3) (i : Fin 3), ‖v‖ ≤ r → |v i| ≤ r := fun v i hv => by
      have := PiLp.norm_apply_le v i
      rw [Real.norm_eq_abs] at this
      linarith
    have hx0 := hc x 0 hx'
    have hx1 := hc x 1 hx'
    have hx2 := hc x 2 hx'
    have hy0 := hc _ 0 hy'
    have hy1 := hc _ 1 hy'
    have hy2 := hc _ 2 hy'
    rw [kleinSmul_zero_OFT] at hy0
    rw [kleinSmul_one_OFT] at hy1
    rw [kleinSmul_two_OFT] at hy2
    have hs : |(kSign_OFT g.k : ℝ) * x 1| ≤ r := by
      rw [abs_mul]
      have : |(kSign_OFT g.k : ℝ)| = 1 := by
        rw [kSign_OFT]
        exact_mod_cast Int.abs_negOnePow g.k
      rw [this, one_mul]
      exact hx1
    refine ⟨?_, ?_, ?_⟩
    · rw [← abs_of_pos P.a_pos, ← abs_mul]
      have := abs_sub (x 0 + (g.m : ℝ) * P.a) (x 0)
      rw [add_sub_cancel_left] at this
      linarith
    · rw [← abs_of_pos P.b_pos, ← abs_mul]
      have := abs_sub ((kSign_OFT g.k : ℝ) * x 1 + (g.n : ℝ) * P.b) ((kSign_OFT g.k : ℝ) * x 1)
      rw [add_sub_cancel_left] at this
      linarith
    · have hL2 := half_pos P.L_pos
      rw [← abs_of_pos hL2, ← abs_mul]
      have := abs_sub (x 2 + (g.k : ℝ) * (P.L / 2)) (x 2)
      rw [add_sub_cancel_left] at this
      linarith


/-! ### The quotient -/

/-- The flat edge carrier `S¹_a × K_{b,L} = ℝ³ / Γ` as the orbit space. -/
abbrev Klein_OFT (P : KleinPeriods_OFT) : Type :=
  MulAction.orbitRel.Quotient (KleinGroup_OFT P) E3

/-- The covering map `ℝ³ → S¹_a × K_{b,L}`. -/
def kleinPi_OFT (P : KleinPeriods_OFT) : E3 → Klein_OFT P := Quotient.mk''

theorem kleinPi_surjective_OFT (P : KleinPeriods_OFT) : Surjective (kleinPi_OFT P) :=
  Quotient.mk''_surjective

theorem kleinPi_eq_iff_OFT {P : KleinPeriods_OFT} {x y : E3} :
    kleinPi_OFT P x = kleinPi_OFT P y ↔ ∃ g : KleinGroup_OFT P, y = g • x := by
  change (Quotient.mk'' x : Klein_OFT P) = Quotient.mk'' y ↔ _
  rw [Quotient.eq'', MulAction.orbitRel_apply, MulAction.mem_orbit_symm,
    MulAction.mem_orbit_iff]
  constructor
  · rintro ⟨g, hg⟩
    exact ⟨g, hg.symm⟩
  · rintro ⟨g, hg⟩
    exact ⟨g, hg.symm⟩

example (P : KleinPeriods_OFT) : ChartedSpace E3 (Klein_OFT P) := inferInstance
example (P : KleinPeriods_OFT) : IsManifold 𝓘(ℝ, E3) ∞ (Klein_OFT P) := inferInstance
example (P : KleinPeriods_OFT) : T2Space (Klein_OFT P) := inferInstance
example (P : KleinPeriods_OFT) : ConnectedSpace (Klein_OFT P) := inferInstance

theorem kleinPi_isLocalDiffeomorph_OFT (P : KleinPeriods_OFT) :
    IsLocalDiffeomorph 𝓘(ℝ, E3) 𝓘(ℝ, E3) ∞ (kleinPi_OFT P) :=
  MulAction.isLocalDiffeomorph_quotientMk_of_properlyDiscontinuousSMul 𝓘(ℝ, E3)

theorem kleinPi_isCoveringMap_OFT (P : KleinPeriods_OFT) : IsCoveringMap (kleinPi_OFT P) :=
  isQuotientCoveringMap_quotientMk_of_properlyDiscontinuousSMul.isCoveringMap

theorem contMDiff_kleinPi_OFT (P : KleinPeriods_OFT) :
    ContMDiff 𝓘(ℝ, E3) 𝓘(ℝ, E3) ∞ (kleinPi_OFT P) :=
  (kleinPi_isLocalDiffeomorph_OFT P).contMDiff

/-- Reduction of one real coordinate modulo a period `c > 0`. -/
theorem exists_int_reduce_OFT (u c : ℝ) (hc : 0 < c) :
    ∃ z : ℤ, 0 ≤ u + (z : ℝ) * c ∧ u + (z : ℝ) * c < c := by
  refine ⟨-⌊u / c⌋, ?_, ?_⟩
  · have h1 := Int.floor_le (u / c)
    rw [le_div_iff₀ hc] at h1
    push_cast
    linarith
  · have h2 := Int.lt_floor_add_one (u / c)
    rw [div_lt_iff₀ hc] at h2
    push_cast
    linarith

/-- Every point of `ℝ³` is equivalent to a point of the box `[0,a) × [0,b) × [0,L/2)`. -/
theorem exists_box_rep_OFT (P : KleinPeriods_OFT) (x : E3) :
    ∃ g : KleinGroup_OFT P, (0 ≤ (g • x) 0 ∧ (g • x) 0 < P.a) ∧
      (0 ≤ (g • x) 1 ∧ (g • x) 1 < P.b) ∧ (0 ≤ (g • x) 2 ∧ (g • x) 2 < P.L / 2) := by
  obtain ⟨k, hk⟩ := exists_int_reduce_OFT (x 2) (P.L / 2) (half_pos P.L_pos)
  obtain ⟨n, hn⟩ := exists_int_reduce_OFT ((kSign_OFT k : ℝ) * x 1) P.b P.b_pos
  obtain ⟨m, hm⟩ := exists_int_reduce_OFT (x 0) P.a P.a_pos
  refine ⟨⟨m, n, k⟩, ?_, ?_, ?_⟩
  · rw [kleinSmul_zero_OFT]; exact hm
  · rw [kleinSmul_one_OFT]; exact hn
  · rw [kleinSmul_two_OFT]; exact hk

theorem exists_mem_closedBall_kleinPi_eq_OFT (P : KleinPeriods_OFT) (x : E3) :
    ∃ y ∈ closedBall (0 : E3) (P.a + P.b + P.L), kleinPi_OFT P y = kleinPi_OFT P x := by
  obtain ⟨g, h0, h1, h2⟩ := exists_box_rep_OFT P x
  refine ⟨g • x, ?_, (kleinPi_eq_iff_OFT.mpr ⟨g, rfl⟩).symm⟩
  rw [mem_closedBall, dist_zero_right, EuclideanSpace.norm_eq]
  have la := P.a_pos
  have lb := P.b_pos
  have lL := P.L_pos
  refine Real.sqrt_le_iff.mpr ⟨by positivity, ?_⟩
  rw [Fin.sum_univ_three]
  simp only [Real.norm_eq_abs, sq_abs]
  have a0 : ((g • x) 0) ^ 2 ≤ P.a ^ 2 := by nlinarith
  have a1 : ((g • x) 1) ^ 2 ≤ P.b ^ 2 := by nlinarith
  have a2 : ((g • x) 2) ^ 2 ≤ P.L ^ 2 := by nlinarith
  nlinarith [mul_pos la lb, mul_pos la lL, mul_pos lb lL]

instance (P : KleinPeriods_OFT) : CompactSpace (Klein_OFT P) := by
  refine ⟨?_⟩
  have h : (univ : Set (Klein_OFT P)) =
      kleinPi_OFT P '' closedBall (0 : E3) (P.a + P.b + P.L) := by
    ext z
    obtain ⟨x, rfl⟩ := kleinPi_surjective_OFT P z
    obtain ⟨y, hy, hyx⟩ := exists_mem_closedBall_kleinPi_eq_OFT P x
    exact ⟨fun _ => ⟨y, hy, hyx⟩, fun _ => mem_univ _⟩
  rw [h]
  exact (isCompact_closedBall _ _).image (contMDiff_kleinPi_OFT P).continuous

example (P : KleinPeriods_OFT) : T3Space (Klein_OFT P) := inferInstance

end DifferentialGeometry.Geometry.Collapse
