import DifferentialGeometry.Analysis.Calculus.IteratedDerivative.ResolventBounds
import DifferentialGeometry.Analysis.Calculus.CircleResolvent
import DifferentialGeometry.Analysis.InnerProductSpace.SpectralProjectionRegularity

#print axioms norm_iteratedFDeriv_succ_resolvent_le
#print axioms resolventDerivativeBound
#print axioms resolventDerivativeBound_mono
#print axioms norm_iteratedFDeriv_resolvent_le_of_small_derivatives
#print axioms isOpen_setOf_circle_subset_resolventSet
#print axioms contDiffOn_circleIntegral_resolvent
#print axioms ContDiffOn.circleIntegral_resolvent
#print axioms DifferentiableAt.norm_fderiv_normalized_circleIntegral_resolvent_le
#print axioms ContDiffOn.norm_iteratedFDeriv_normalized_circleIntegral_resolvent_le
#print axioms ContDiffOn.starProjection_eigenspace_ball
#print axioms DifferentiableAt.norm_fderiv_starProjection_eigenspace_ball_le
#print axioms ContDiffOn.norm_iteratedFDeriv_starProjection_eigenspace_ball_le
