import DifferentialGeometry.Geometry.Collapse.BoundaryPacketsOutBFRSeq

/-!
# T3B-R's per-member conclusion for a GIVEN export packet (lane FC39-BQ2; review 54 §6.4)

External review 54, §6.4: the per-sequence records must keep the SAME packet — the export packet
`P` with `P.cusp = B`, its levels (cusp piece `= {level ≤ 90}`, defining function `= level − 90`)
and the product-or-separation alternative of T3 for THIS packet. `BoundaryPacketsOutBFR_BQ`
(FC39-BQ, verbatim T3B-R) hides `P` behind an existential; this file splits it:

* `BoundaryPacketRestBFR_BQ2 W g K A δn idx … P` — everything after `∃ P, P.cusp = B ∧`
  (verbatim; generated by `build-logs/scratch/FC39-BQ2/gen_rest.py` from the accepted text);
* `boundaryPacketsOutBFR_iff_rest_BQ2` — `BoundaryPacketsOutBFR_BQ … ↔ ∃ P, P.cusp = B ∧ Rest P`
  (definitional).
* Consumers: `BoundaryPacketRestBFR_BQ2.ratio_le_BQ2` (T3B's cusp-tolerance clause),
  `BoundaryPacketRestBFR_BQ2.alternative_BQ2` (T3's labelled whole-product branch OR the separation
  of the enlarged collars and level sets, for the given packet).
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric Bundle Manifold Filter
open scoped ContDiff Manifold Topology ENNReal
open DifferentialGeometry.Topology.Ehresmann DifferentialGeometry.Topology.Manifold
open DifferentialGeometry.Geometry.Riemannian GC.MetricGeometry
open DifferentialGeometry.Geometry.Riemannian.VolumeComparison
open DifferentialGeometry.Geometry.Riemannian.Exponential
open DifferentialGeometry GC.Endpoint DifferentialGeometry.Geometry.Hyperbolic
open DifferentialGeometry.Geometry.Curvature DifferentialGeometry.Analysis.Calculus
open DifferentialGeometry.Geometry.Operator
open DifferentialGeometry.Geometry.Connection DifferentialGeometry.Geometry.Riemannian.Geodesic

namespace DifferentialGeometry.Geometry.Collapse

local notation "E3" => EuclideanSpace ℝ (Fin 3)

attribute [-instance] Tensor0SBundle.tangentSpaceNormedAddCommGroup
  Tensor0SBundle.tangentSpaceNormedSpace

attribute [local instance] nezero_finrank_euclideanThree_LC87

attribute [local instance] interiorCharted_BDRY1 interiorManifold_BDRY1
  connectedSpace_interior_BDRY2

/-- **T3B-R's per-member conclusion after the export packet** (`lc88_boundary_packets_BFR_BCG5`,
verbatim after `∃ P, P.cusp = B ∧`), for a given packet `P`. -/
def BoundaryPacketRestBFR_BQ2 (W : CompactCarrier.{0}) [ConnectedSpace W.Carrier]
    (g : SmoothRiemannianMetric W.model W.Carrier) (K : ℕ) (A : ℝ → ℝ) (δn : ℝ) (idx : ℝ)
    (Λ w : ℝ) (β : ℕ → ℝ)
    (Δ σs σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λ' βd εN : ℝ)
    (P : BoundaryExportPacket W g K A δn (cuspTolerance_BCUSP1 (β 1) βd εN)) : Prop :=
  δn ≤ βd ^ 2 / 1000 ∧
  ∃ ρ : W.Carrier → ℝ, ∃ hρpos : ∀ p, 0 < ρ p,
    ContMDiff W.model 𝓘(ℝ, ℝ) ∞ ρ ∧
    (∀ x y, ENNReal.ofReal |ρ x - ρ y| ≤ ENNReal.ofReal Λ * riemannianEDistOf g x y) ∧
    (∀ p, firstVolumeScale g p w / 2 < ρ p ∧
      ρ p < 2 * firstVolumeScale g p (w / (2 * (1 + 2 * Λ⁻¹) ^ 3))) ∧
    (∀ (i : Fin P.cusp.count) (q : CuspHalfSpace), q.2.val 0 ≤ 96 →
      ρ ((P.cusp.collar i).toFun q) ≤ β 1 ^ 3 / 2000) ∧
    -- BCUSP-1: the late `ρ` certificate and the cusp certificates B3–B5 on the SAME `P`, `ρ`
    (∀ r : ℝ, 0 < r →
      1000 * δn ^ 2 <
        w / (2 * (1 + 2 * Λ⁻¹) ^ 3) * min (1 / 2) (r / 4) ^ 2 →
      ∀ (i : Fin P.cusp.count) (q : CuspHalfSpace), q.2.val 0 ≤ 96 →
        ρ ((P.cusp.collar i).toFun q) < r) ∧
    (∀ L γd : ℝ, 0 ≤ L → βd < γd → γd < 1 →
      1000 * δn ^ 2 <
        w / (2 * (1 + 2 * Λ⁻¹) ^ 3) * min (1 / 2) (βd ^ 3 / (2000 * (1 + L)) / 4) ^ 2 →
      ∀ (i : Fin P.cusp.count) (q₀ : CuspHalfSpace), 2 ≤ q₀.2.val 0 → q₀.2.val 0 ≤ 98 →
        5 ≤ P.height i ((P.cusp.collar i).toFun q₀) →
        P.height i ((P.cusp.collar i).toFun q₀) ≤ 95 →
        letI := (inducedMetricSpace g).rescale (ρ ((P.cusp.collar i).toFun q₀))⁻¹
          (inv_pos.mpr (hρpos _));
        letI := (inducedMetricSpace (P.cusp.collar i).cusp.torusMetric).rescale
          ((ρ ((P.cusp.collar i).toFun q₀))⁻¹ * Real.exp (-(q₀.2.val 0) / 2))
          (mul_pos (inv_pos.mpr (hρpos _)) (Real.exp_pos _));
        ∃ t₀ : Torus, t₀ = q₀.1 ∧ ∃ f : KleinerLottApprox ((P.cusp.collar i).toFun q₀)
            (WithLp.toLp 2 ((0 : ℝ), t₀)) βd,
          (∀ x, (f.toFun x).fst = (P.height i x - P.height i ((P.cusp.collar i).toFun q₀)) /
            ρ ((P.cusp.collar i).toFun q₀)) ∧
          ∀ x, (ρ ((P.cusp.collar i).toFun q₀))⁻¹ *
              (riemannianEDistOf g x ((P.cusp.collar i).toFun q₀)).toReal ≤ βd⁻¹ + βd →
            (f.toFun x).snd = (invFunOn (P.cusp.collar i).toFun cuspDomain x).1) ∧
    (∀ (i : Fin P.cusp.count) (p : CuspHalfSpace), p ∈ cuspDomain → 2 ≤ p.2.val 0 →
      p.2.val 0 ≤ 98 →
      (∀ u : TangentSpace W.model ((P.cusp.collar i).toFun p),
        |mvfderiv W.model (P.height i) ((P.cusp.collar i).toFun p) u| ≤
          (1 + 2 * (εN + βd ^ 2 / 1000)) *
            Real.sqrt (g.inner ((P.cusp.collar i).toFun p) u u)) ∧
      ∀ (R : ℝ), 0 < R → ∀ u w : TangentSpace W.model ((P.cusp.collar i).toFun p),
        R⁻¹ * |(CovariantDerivative.trivial W.model W.Carrier ℝ).hessian
            (LeviCivita g) (P.height i) ((P.cusp.collar i).toFun p) u w| ≤
          2 * R * (R⁻¹ * Real.sqrt (g.inner ((P.cusp.collar i).toFun p) u u)) *
            (R⁻¹ * Real.sqrt (g.inner ((P.cusp.collar i).toFun p) w w))) ∧
    (∀ H : ℝ, 0 < H →
      1000 * δn ^ 2 <
        w / (2 * (1 + 2 * Λ⁻¹) ^ 3) * min (1 / 2) (H⁻¹ / 4) ^ 2 →
    ∀ (i : Fin P.cusp.count) (pa p : CuspHalfSpace), pa.2.val 0 ≤ 96 → 19 ≤ p.2.val 0 →
      p.2.val 0 ≤ 91 →
    ∀ (a : ℝ) (c : ℝ → W.Carrier) (x₀ ℓ : ℝ), 0 < ℓ → ℓ ≤ H →
      (∀ t ∈ Icc x₀ (x₀ + ℓ), ContMDiffAt 𝓘(ℝ, ℝ) W.model 2 c t) →
      (∀ t ∈ Icc x₀ (x₀ + ℓ), HasGeodesicEquationAt g c t) →
      (∀ t ∈ Icc x₀ (x₀ + ℓ), g.inner (c t)
        (mfderiv 𝓘(ℝ, ℝ) W.model c t ((NormedSpace.fromTangentSpace t).symm 1))
        (mfderiv 𝓘(ℝ, ℝ) W.model c t ((NormedSpace.fromTangentSpace t).symm 1)) ≤
          ρ ((P.cusp.collar i).toFun pa) ^ 2) →
      (P.cusp.collar i).toFun p = c x₀ →
      (∀ t ∈ Icc x₀ (x₀ + ℓ), ∃ q ∈ cuspDomain, (P.cusp.collar i).toFun q = c t ∧
        2 ≤ q.2.val 0 ∧ q.2.val 0 ≤ 98) ∧
      |deriv (fun t => (P.height i (c t) - a) / ρ ((P.cusp.collar i).toFun pa)) x₀ -
        ((P.height i (c (x₀ + ℓ)) - a) / ρ ((P.cusp.collar i).toFun pa) -
          (P.height i (c x₀) - a) / ρ ((P.cusp.collar i).toFun pa)) / ℓ| ≤
        ρ ((P.cusp.collar i).toFun pa) * ℓ) ∧
    (∀ L H ϑ c₃ : ℝ, 0 < L → 0 < H → 0 < ϑ → 0 ≤ c₃ →
      1000 * δn ^ 2 <
        w / (2 * (1 + 2 * Λ⁻¹) ^ 3) *
          min (1 / 2) (cuspPhysicalScale_BCUSP1 βd L H ϑ c₃ / 4) ^ 2 →
      (∀ (i : Fin P.cusp.count) (q : CuspHalfSpace), q.2.val 0 ≤ 96 →
        ρ ((P.cusp.collar i).toFun q) < cuspPhysicalScale_BCUSP1 βd L H ϑ c₃ ∧
        ρ ((P.cusp.collar i).toFun q) ≤ βd ^ 3 / (2000 * (1 + H)) ∧
        ρ ((P.cusp.collar i).toFun q) * H < 1 / 100 ∧
        2 * ρ ((P.cusp.collar i).toFun q) * (12 * L + 1000) < ϑ ^ 2 / 10 ^ 8 ∧
        20 * c₃ * ρ ((P.cusp.collar i).toFun q) < 1 / 1000000) ∧
      ∀ (C : ℝ) (p : W.Carrier) (b : Fin P.cusp.count), C ≤ 95 / 100 * L →
        Λ * C ≤ 1 / 2 →
        (∃ x ∈ tsupport (P.toBoundaryCollarPacket.block b),
          riemannianEDistOf g p x < ENNReal.ofReal (C * ρ p)) →
        ρ p < 2 * cuspPhysicalScale_BCUSP1 βd L H ϑ c₃ ∧
        ∀ y, riemannianEDistOf g p y < ENNReal.ofReal (C * ρ p) →
          ∃ q ∈ cuspDomain, (P.cusp.collar b).toFun q = y ∧ 19 < q.2.val 0 ∧
            q.2.val 0 < 91 ∧ 19 < P.height b y ∧ P.height b y < 91) ∧
    (∀ p, 0 < distanceToBoundary W g p →
      idx * (distanceToBoundary W g p).toReal /
          ((distanceToBoundary W g p).toReal + 3) <
        (distanceToBoundary W g p).toReal / ρ p) ∧
    letI := interiorChartedT_BDRY1 W
    haveI := interiorManifoldT_BDRY1 W
    ∃ _ : ConnectedSpace (W.pieceInterior ⊤),
    ∃ ĝ : SmoothRiemannianMetric 𝓘(ℝ, E3) (W.pieceInterior ⊤),
    ∃ O : Set (W.pieceInterior ⊤), IsOpen O ∧
      {x : W.pieceInterior ⊤ | ENNReal.ofReal 4 ≤ distanceToBoundary W g x} ⊆ O ∧
      (∀ x ∈ O, ĝ.inner x = (pieceInteriorMetric W g ⊤).inner x) ∧
      (∀ (x : W.pieceInterior ⊤) (v : TangentSpace 𝓘(ℝ, E3) x),
        (pieceInteriorMetric W g ⊤).inner x v v ≤ ĝ.inner x v v) ∧
      letI := inducedMetricSpace ĝ
      ∃ _ : CompleteSpace (W.pieceInterior ⊤),
      ∃ F : LocalPacketsOnBFR (W.pieceInterior ⊤) ĝ (inducedMetricSpace_hmetric ĝ)
          (fun x => ρ x) (fun x => hρpos x) Λ β Δ σs K σc μ b s b' s' ε γc βc Lmax τ γ δ εr e
          T V vs ζ Λ' {x | ENNReal.ofReal 10 < distanceToBoundary W g x}
          {x | ENNReal.ofReal 20 ≤ distanceToBoundary W g x}
          {x | ENNReal.ofReal 20 < distanceToBoundary W g x}
          {x | ENNReal.ofReal 35 ≤ distanceToBoundary W g x},
        -- ranks on U₀ = {D > 5}
        (∀ x : W.pieceInterior ⊤,
          ENNReal.ofReal 5 < distanceToBoundary W g x →
          scaledSplittingRank.{0, 0} (fun y : W.pieceInterior ⊤ => ρ y)
              (fun y => hρpos y) β x =
            @scaledSplittingRank.{0, 0} W.Carrier (inducedMetricSpace g) ρ hρpos β
              x) ∧
        -- every per-centre consumer domain is an actual g-ball with the distances of W
        (∀ j : W.pieceInterior ⊤,
          ENNReal.ofReal 10 < distanceToBoundary W g j →
          Subtype.val '' Metric.ball j
              (4 * (2010000 + 2000000 * Δ + 400 * V + (β 1)⁻¹ + b⁻¹) * ρ j) =
            riemannianBallOf g j.val
              (4 * (2010000 + 2000000 * Δ + 400 * V + (β 1)⁻¹ + b⁻¹) * ρ j) ∧
          ∀ y ∈ Metric.ball j ((2010000 + 2000000 * Δ + 400 * V + (β 1)⁻¹ + b⁻¹) * ρ j),
            ∀ z ∈ Metric.ball j ((2010000 + 2000000 * Δ + 400 * V + (β 1)⁻¹ + b⁻¹) * ρ j),
              riemannianEDistOf g y.val z.val = edist y z) ∧
        -- the zero balls are actual g-balls of W
        (letI := F.instMetricN
        letI := F.instChartedN
        letI := F.instMetricC
        ∀ z (hz : z ∈ F.zero.centres),
          Subtype.val '' Metric.ball z (F.zero.zero z hz).radius =
            riemannianBallOf g z.val (F.zero.zero z hz).radius) ∧
        -- weak-edge distance locality on the active edge domains
        (∀ j ∈ F.edge.centres, ∀ x ∈ Metric.ball j (200 * Δ * ρ j),
          Metric.infDist x (closure {y : W.pieceInterior ⊤ |
              @isEdgePoint.{0, 0} _ ((inducedMetricSpace ĝ).rescale (ρ y)⁻¹
                (inv_pos.mpr (hρpos y))) y Δ b' s'}) =
            @Metric.infDist W.Carrier (inducedMetricSpace g).toPseudoMetricSpace
              x.val (@closure W.Carrier _ {y : W.Carrier |
                @isEdgePoint.{0, 0} _ ((inducedMetricSpace g).rescale (ρ y)⁻¹
                  (inv_pos.mpr (hρpos y))) y Δ b' s'})) ∧
        -- weak-edge distance locality on the revised (active) edge domains
        (∀ j ∈ F.edgeB.centres, ∀ x ∈ Metric.ball j (200 * Δ * ρ j),
          Metric.infDist x (closure {y : W.pieceInterior ⊤ |
              @isEdgePoint.{0, 0} _ ((inducedMetricSpace ĝ).rescale (ρ y)⁻¹
                (inv_pos.mpr (hρpos y))) y Δ b' s'}) =
            @Metric.infDist W.Carrier (inducedMetricSpace g).toPseudoMetricSpace
              x.val (@closure W.Carrier _ {y : W.Carrier |
                @isEdgePoint.{0, 0} _ ((inducedMetricSpace g).rescale (ρ y)⁻¹
                  (inv_pos.mpr (hρpos y))) y Δ b' s'})) ∧
        -- BZ-1: the original-metric zero certificates of the producer v2 on `F.zero`
        (letI := F.instMetricN
        letI := F.instChartedN
        letI := F.instMetricC
        -- (A6') enlarged zero curvature of the ORIGINAL metric
        (∀ c (hc : c ∈ F.zero.centres),
          ∀ y ∈ riemannianBallOf g c.val (400 * (F.zero.zero c hc).radius),
          SectionalBoundedBelowAt g y
            (-((1 / 60) ^ 2 * ((F.zero.zero c hc).radius)⁻¹ ^ 2))) ∧
        -- (I) `ĝ` is `g` on the enlarged zero balls
        (∀ c (hc : c ∈ F.zero.centres),
          Subtype.val '' Metric.ball c (400 * (F.zero.zero c hc).radius) =
            riemannianBallOf g c.val (400 * (F.zero.zero c hc).radius) ∧
          ∀ y ∈ Metric.ball c (400 * (F.zero.zero c hc).radius),
            ∀ z ∈ Metric.ball c (400 * (F.zero.zero c hc).radius),
              riemannianEDistOf g y.val z.val = edist y z) ∧
        -- (TD) test domains inside `B(c, 11 r_c)`
        (∀ c (hc : c ∈ F.zero.centres), ∀ q, (F.zero.zero c hc).radius / 10 ≤ dist c q →
          dist c q ≤ 10 * (F.zero.zero c hc).radius →
          (∀ x ∈ @Metric.ball _ ((inducedMetricSpace ĝ).rescale (ρ q)⁻¹
              (inv_pos.mpr (hρpos q))).toPseudoMetricSpace q (β 1)⁻¹,
            x ∈ Metric.ball c (11 * (F.zero.zero c hc).radius)) ∧
          ∀ (lam : ℝ) (hlam : 0 < lam), Λ' ≤ lam →
            ∀ x ∈ @Metric.ball _ (((inducedMetricSpace ĝ).rescale
                ((F.zero.zero c hc).radius)⁻¹
                (inv_pos.mpr (F.zero.zero c hc).radius_pos)).rescale lam
                hlam).toPseudoMetricSpace q ζ⁻¹,
              x ∈ Metric.ball c (11 * (F.zero.zero c hc).radius)) ∧
        -- (A3') LC62 for the points of `W`
        ∀ c (hc : c ∈ F.zero.centres), ∀ q : W.Carrier,
          riemannianEDistOf g c.val q ≤
            ENNReal.ofReal (10 * (F.zero.zero c hc).radius) →
          T / 20 ≤ (F.zero.zero c hc).radius / ρ q) ∧
        -- T3: the labelled product alternative OR the separation of zero balls and collars
        (letI := F.instMetricN
        letI := F.instChartedN
        letI := F.instMetricC
        (∃ (i j : Fin P.cusp.count), i ≠ j ∧
          ∃ D : Diffeomorph (torusModel.prod (𝓡∂ 1)) W.model (Torus × Icc (0 : ℝ) 1)
            W.Carrier ∞,
            (∀ p, D p ∈ P.cusp.component i ↔ p.2.1 = 0) ∧
              ∀ p, D p ∈ P.cusp.component j ↔ p.2.1 = 1) ∨
        ((∀ i j : Fin P.cusp.count, i ≠ j →
          Disjoint ((P.cusp.collar i).toFun '' {q : CuspHalfSpace | q.2.val 0 < 92})
            ((P.cusp.collar j).toFun '' {q : CuspHalfSpace | q.2.val 0 < 92}) ∧
          Disjoint {x | P.level i x ≤ 90} {y | P.level j y ≤ 90} ∧
          ∀ x y, P.level i x ≤ 90 → P.level j y ≤ 90 →
            ENNReal.ofReal 1 ≤ riemannianEDistOf g x y) ∧
        (∀ z (hz : z ∈ F.zero.centres) (i : Fin P.cusp.count),
          Disjoint (riemannianBallOf g z.val (F.zero.zero z hz).radius)
            ((P.cusp.collar i).toFun '' {q : CuspHalfSpace | q.2.val 0 < 92})) ∧
        Disjoint (⋃ z, ⋃ hz : z ∈ F.zero.centres,
            riemannianBallOf g z.val (F.zero.zero z hz).radius)
          (⋃ i, tsupport (P.toBoundaryCollarPacket.block i))))

/-- **The split**: T3B-R's per-member conclusion is an export packet with `P.cusp = B` and the
rest for THAT packet. -/
theorem boundaryPacketsOutBFR_iff_rest_BQ2 {W : CompactCarrier.{0}} [ConnectedSpace W.Carrier]
    {g : SmoothRiemannianMetric W.model W.Carrier} {K : ℕ} {A : ℝ → ℝ} {δn : ℝ}
    {B : NearlyCuspidalBoundary W g K δn} {idx : ℝ} {Λ w : ℝ} {β : ℕ → ℝ}
    {Δ σs σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λ' βd εN : ℝ} :
    BoundaryPacketsOutBFR_BQ W g K A δn B idx Λ w β Δ σs σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V
        vs ζ Λ' βd εN ↔
      ∃ P : BoundaryExportPacket W g K A δn (cuspTolerance_BCUSP1 (β 1) βd εN), P.cusp = B ∧
        BoundaryPacketRestBFR_BQ2 W g K A δn idx Λ w β Δ σs σc μ b s b' s' ε γc βc Lmax τ γ δ εr e
          T V vs ζ Λ' βd εN P :=
  Iff.rfl

namespace BoundaryPacketRestBFR_BQ2

variable {W : CompactCarrier.{0}} [ConnectedSpace W.Carrier]
  {g : SmoothRiemannianMetric W.model W.Carrier} {K : ℕ} {A : ℝ → ℝ} {δn idx Λ w : ℝ}
  {β : ℕ → ℝ} {Δ σs σc μ b s b' s' ε γc βc Lmax τ γ δ εr e T V vs ζ Λ' βd εN : ℝ}
  {P : BoundaryExportPacket W g K A δn (cuspTolerance_BCUSP1 (β 1) βd εN)}

/-- **Consumer**: the member's ratio is below T3B's cusp tolerance `βd²/1000`. -/
theorem ratio_le_BQ2 (h : BoundaryPacketRestBFR_BQ2 W g K A δn idx Λ w β Δ σs σc μ b s b' s' ε γc
    βc Lmax τ γ δ εr e T V vs ζ Λ' βd εN P) : δn ≤ βd ^ 2 / 1000 :=
  h.1

/-- **Consumer (product-or-separation for THE packet)**: T3's labelled whole-product branch (two
distinct labels of `P.cusp` at the two ends of `Torus × [0, 1]`) or the separation of the
enlarged collars, of the level sets `{level ≤ 90}`, and their distance `≥ 1`. -/
theorem alternative_BQ2 (h : BoundaryPacketRestBFR_BQ2 W g K A δn idx Λ w β Δ σs σc μ b s b' s' ε
    γc βc Lmax τ γ δ εr e T V vs ζ Λ' βd εN P) :
    (∃ (i j : Fin P.cusp.count), i ≠ j ∧
      ∃ D : Diffeomorph (torusModel.prod (𝓡∂ 1)) W.model (Torus × Icc (0 : ℝ) 1) W.Carrier ∞,
        (∀ p, D p ∈ P.cusp.component i ↔ p.2.1 = 0) ∧
          ∀ p, D p ∈ P.cusp.component j ↔ p.2.1 = 1) ∨
    (∀ i j : Fin P.cusp.count, i ≠ j →
      Disjoint ((P.cusp.collar i).toFun '' {q : CuspHalfSpace | q.2.val 0 < 92})
        ((P.cusp.collar j).toFun '' {q : CuspHalfSpace | q.2.val 0 < 92}) ∧
      Disjoint {x | P.level i x ≤ 90} {y | P.level j y ≤ 90} ∧
      ∀ x y, P.level i x ≤ 90 → P.level j y ≤ 90 →
        ENNReal.ofReal 1 ≤ riemannianEDistOf g x y) := by
  obtain ⟨-, _, _, -, -, -, -, -, -, -, -, -, -, h⟩ := h
  dsimp only at h
  obtain ⟨_, _, _, -, -, -, -, _, _, -, -, -, -, -, -, h⟩ := h
  rcases h with h | ⟨h, -, -⟩
  exacts [Or.inl h, Or.inr h]

end BoundaryPacketRestBFR_BQ2

end DifferentialGeometry.Geometry.Collapse
