import DifferentialGeometry.Geometry.Collapse.StaticRegisterV4Realization
import DifferentialGeometry.Geometry.Collapse.StaticRegisterV2RowsStrategy

/-!
# Threshold strategies on register V4: infimum, "below", and the 11-row strategy (lane FC39-VAL6)

Register-V4 file (lane FC39-VAL6), generated by `build-logs/scratch/FC39-VAL6/gen_v4.py`
from FC39-VAL5's `StaticRegisterV3RowsStrategy.lean` with register V3 → V4 (`βc` chosen right
after `β₂`, `β₂Up` reads the circle prefix `ClosedCirclePrefixV4` without `βc`; see
`StaticRegisterV4.lean`). It imports no register-V3 module.

* `ClosedThresholdsV4.inf U₁ U₂`: the slotwise minimum of the upper slots and maximum of the lower
  slots (`N_b, c_w, I₁, lpa02V, H` from `U₁`); `ClosedStrategyBelowV4 T U`: every upper slot of `T`
  is below `U`'s, every lower slot above it (no equality clauses);
  `ClosedStrategyRefinesV4.below_VAL6`, `ClosedStrategyBelowV4.trans_VAL6`,
  `ClosedThresholdsV4.inf_below_left_VAL6`, `inf_below_right_VAL6`. A strategy refining
  `U₁.inf U₂` is below both, so each row group is proved for its own strategy and the realization
  refines their infimum.
* `partialRowsStrategyV4 D`, `partialRowOuts_of_below_VAL6`: FC39-VAL4's rows strategy and proof
  (`StaticRegisterV2RowsStrategy.lean`, accepted) transcribed onto register V4 (generated by
  `build-logs/scratch/FC39-VAL5/gen_rows11.py`; the row threshold functions `*_VAL4` are reused):
  at every register of a strategy below it, the conclusions of TCP01, TCP02, EGP03, EGP04, EGP06,
  EGP07, SGP01, SGP02, SGP03, SGP04, SGP06 at the register's values.
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric Bundle Manifold Filter
open scoped ContDiff Manifold Topology
open DifferentialGeometry GC.Endpoint GC.MetricGeometry
open DifferentialGeometry.Geometry.Riemannian DifferentialGeometry.Analysis

namespace DifferentialGeometry.Geometry.Collapse

universe u

local notation "E3" => EuclideanSpace ℝ (Fin 3)

attribute [-instance] Tensor0SBundle.tangentSpaceNormedAddCommGroup
  Tensor0SBundle.tangentSpaceNormedSpace

attribute [local instance] nezero_finrank_euclideanThree_LC87

/-! ### Infimum of two threshold records and the relation "below" -/

/-- The infimum of two threshold records of register V4: slotwise minimum of the upper slots,
maximum of the lower slots; `N_b, c_w, I₁`, LPA02's output and the test radius from `U₁`. -/
def ClosedThresholdsV4.inf {D : ClosedEarlyData} (U₁ U₂ : ClosedThresholdsV4 D) :
    ClosedThresholdsV4 D where
  Nb := U₁.Nb
  Nb_nonneg := U₁.Nb_nonneg
  cw := U₁.cw
  cw_nonneg := U₁.cw_nonneg
  lc18 := min U₁.lc18 U₂.lc18
  lc18_pos := lt_min U₁.lc18_pos U₂.lc18_pos
  circleUp := fun st β₃ θs θe θ₂ => min (U₁.circleUp st β₃ θs θe θ₂) (U₂.circleUp st β₃ θs θe θ₂)
  circleUp_pos := fun st β₃ θs θe θ₂ =>
    lt_min (U₁.circleUp_pos st β₃ θs θe θ₂) (U₂.circleUp_pos st β₃ θs θe θ₂)
  β₂Up := fun st ci β₃ => min (U₁.β₂Up st ci β₃) (U₂.β₂Up st ci β₃)
  β₂Up_pos := fun st ci β₃ => lt_min (U₁.β₂Up_pos st ci β₃) (U₂.β₂Up_pos st ci β₃)
  ΔLow := fun st ci β₃ β₂ => max (U₁.ΔLow st ci β₃ β₂) (U₂.ΔLow st ci β₃ β₂)
  errorsUp := fun st ci ex => min (U₁.errorsUp st ci ex) (U₂.errorsUp st ci ex)
  errorsUp_pos := fun st ci ex => lt_min (U₁.errorsUp_pos st ci ex) (U₂.errorsUp_pos st ci ex)
  sectionUp := fun st ci ex co => min (U₁.sectionUp st ci ex co) (U₂.sectionUp st ci ex co)
  sectionUp_pos := fun st ci ex co =>
    lt_min (U₁.sectionUp_pos st ci ex co) (U₂.sectionUp_pos st ci ex co)
  lfr29W := fun st ci ex co bd => min (U₁.lfr29W st ci ex co bd) (U₂.lfr29W st ci ex co bd)
  lfr29W_pos := fun st ci ex co bd =>
    lt_min (U₁.lfr29W_pos st ci ex co bd) (U₂.lfr29W_pos st ci ex co bd)
  endpointUp := fun st ci ex co bd wk =>
    min (U₁.endpointUp st ci ex co bd wk) (U₂.endpointUp st ci ex co bd wk)
  endpointUp_pos := fun st ci ex co bd wk =>
    lt_min (U₁.endpointUp_pos st ci ex co bd wk) (U₂.endpointUp_pos st ci ex co bd wk)
  σcolUp := fun st ci ex co bd wk s =>
    min (U₁.σcolUp st ci ex co bd wk s) (U₂.σcolUp st ci ex co bd wk s)
  σcolUp_pos := fun st ci ex co bd wk s =>
    lt_min (U₁.σcolUp_pos st ci ex co bd wk s) (U₂.σcolUp_pos st ci ex co bd wk s)
  I₁ := U₁.I₁
  I₁_pos := U₁.I₁_pos
  scaleUp := fun st ci ex er => min (U₁.scaleUp st ci ex er) (U₂.scaleUp st ci ex er)
  scaleUp_pos := fun st ci ex er => lt_min (U₁.scaleUp_pos st ci ex er) (U₂.scaleUp_pos st ci ex er)
  wUp := fun st ci ex er Λ => min (U₁.wUp st ci ex er Λ) (U₂.wUp st ci ex er Λ)
  wUp_pos := fun st ci ex er Λ => lt_min (U₁.wUp_pos st ci ex er Λ) (U₂.wUp_pos st ci ex er Λ)
  splitUp := fun st ci ex er sc => min (U₁.splitUp st ci ex er sc) (U₂.splitUp st ci ex er sc)
  splitUp_pos := fun st ci ex er sc =>
    lt_min (U₁.splitUp_pos st ci ex er sc) (U₂.splitUp_pos st ci ex er sc)
  β₁Up := fun st ci ex er sc b => min (U₁.β₁Up st ci ex er sc b) (U₂.β₁Up st ci ex er sc b)
  β₁Up_pos := fun st ci ex er sc b =>
    lt_min (U₁.β₁Up_pos st ci ex er sc b) (U₂.β₁Up_pos st ci ex er sc b)
  T₀Low := fun st ci ex er sc b β₁ =>
    max (U₁.T₀Low st ci ex er sc b β₁) (U₂.T₀Low st ci ex er sc b β₁)
  lpa02V := U₁.lpa02V
  T₀_le_lpa02V := U₁.T₀_le_lpa02V
  LmaxLow := fun st ci ex er sc sp =>
    max (U₁.LmaxLow st ci ex er sc sp) (U₂.LmaxLow st ci ex er sc sp)
  tailLow := fun st ci ex er sc sp Lmax =>
    max (U₁.tailLow st ci ex er sc sp Lmax) (U₂.tailLow st ci ex er sc sp Lmax)
  H := U₁.H
  H_tendsto := U₁.H_tendsto

/-- **`T` is below `U`**: every upper slot of `T` is at most `U`'s and every lower slot at least
`U`'s (so every register at `T` meets each request of `U`). -/
structure ClosedStrategyBelowV4 {D : ClosedEarlyData} (T U : ClosedThresholdsV4 D) : Prop where
  lc18_le : T.lc18 ≤ U.lc18
  circleUp_le : ∀ st β₃ θs θe θ₂, T.circleUp st β₃ θs θe θ₂ ≤ U.circleUp st β₃ θs θe θ₂
  β₂Up_le : ∀ st ci β₃, T.β₂Up st ci β₃ ≤ U.β₂Up st ci β₃
  ΔLow_ge : ∀ st ci β₃ β₂, U.ΔLow st ci β₃ β₂ ≤ T.ΔLow st ci β₃ β₂
  errorsUp_le : ∀ st ci ex, T.errorsUp st ci ex ≤ U.errorsUp st ci ex
  sectionUp_le : ∀ st ci ex co, T.sectionUp st ci ex co ≤ U.sectionUp st ci ex co
  lfr29W_le : ∀ st ci ex co bd, T.lfr29W st ci ex co bd ≤ U.lfr29W st ci ex co bd
  endpointUp_le : ∀ st ci ex co bd wk,
    T.endpointUp st ci ex co bd wk ≤ U.endpointUp st ci ex co bd wk
  σcolUp_le : ∀ st ci ex co bd wk s, T.σcolUp st ci ex co bd wk s ≤ U.σcolUp st ci ex co bd wk s
  scaleUp_le : ∀ st ci ex er, T.scaleUp st ci ex er ≤ U.scaleUp st ci ex er
  wUp_le : ∀ st ci ex er Λ, T.wUp st ci ex er Λ ≤ U.wUp st ci ex er Λ
  splitUp_le : ∀ st ci ex er sc, T.splitUp st ci ex er sc ≤ U.splitUp st ci ex er sc
  β₁Up_le : ∀ st ci ex er sc b, T.β₁Up st ci ex er sc b ≤ U.β₁Up st ci ex er sc b
  T₀Low_ge : ∀ st ci ex er sc b β₁, U.T₀Low st ci ex er sc b β₁ ≤ T.T₀Low st ci ex er sc b β₁
  LmaxLow_ge : ∀ st ci ex er sc sp, U.LmaxLow st ci ex er sc sp ≤ T.LmaxLow st ci ex er sc sp
  tailLow_ge : ∀ st ci ex er sc sp Lmax,
    U.tailLow st ci ex er sc sp Lmax ≤ T.tailLow st ci ex er sc sp Lmax

/-- A refining strategy is below. -/
theorem ClosedStrategyRefinesV4.below_VAL6 {D : ClosedEarlyData} {T U : ClosedThresholdsV4 D}
    (h : ClosedStrategyRefinesV4 T U) : ClosedStrategyBelowV4 T U where
  lc18_le := h.lc18_le
  circleUp_le := h.circleUp_le
  β₂Up_le := h.β₂Up_le
  ΔLow_ge := h.ΔLow_ge
  errorsUp_le := h.errorsUp_le
  sectionUp_le := h.sectionUp_le
  lfr29W_le := h.lfr29W_le
  endpointUp_le := fun _ _ _ _ _ _ => h.endpointUp_eq ▸ le_rfl
  σcolUp_le := h.σcolUp_le
  scaleUp_le := h.scaleUp_le
  wUp_le := h.wUp_le
  splitUp_le := h.splitUp_le
  β₁Up_le := h.β₁Up_le
  T₀Low_ge := h.T₀Low_ge
  LmaxLow_ge := fun _ _ _ _ _ _ => h.LmaxLow_eq ▸ le_rfl
  tailLow_ge := h.tailLow_ge

/-- "Below" is transitive. -/
theorem ClosedStrategyBelowV4.trans_VAL6 {D : ClosedEarlyData} {T U W : ClosedThresholdsV4 D}
    (h₁ : ClosedStrategyBelowV4 T U) (h₂ : ClosedStrategyBelowV4 U W) :
    ClosedStrategyBelowV4 T W where
  lc18_le := h₁.lc18_le.trans h₂.lc18_le
  circleUp_le := fun _ _ _ _ _ => (h₁.circleUp_le _ _ _ _ _).trans (h₂.circleUp_le _ _ _ _ _)
  β₂Up_le := fun _ _ _ => (h₁.β₂Up_le _ _ _).trans (h₂.β₂Up_le _ _ _)
  ΔLow_ge := fun _ _ _ _ => (h₂.ΔLow_ge _ _ _ _).trans (h₁.ΔLow_ge _ _ _ _)
  errorsUp_le := fun _ _ _ => (h₁.errorsUp_le _ _ _).trans (h₂.errorsUp_le _ _ _)
  sectionUp_le := fun _ _ _ _ => (h₁.sectionUp_le _ _ _ _).trans (h₂.sectionUp_le _ _ _ _)
  lfr29W_le := fun _ _ _ _ _ => (h₁.lfr29W_le _ _ _ _ _).trans (h₂.lfr29W_le _ _ _ _ _)
  endpointUp_le := fun _ _ _ _ _ _ =>
    (h₁.endpointUp_le _ _ _ _ _ _).trans (h₂.endpointUp_le _ _ _ _ _ _)
  σcolUp_le := fun _ _ _ _ _ _ _ =>
    (h₁.σcolUp_le _ _ _ _ _ _ _).trans (h₂.σcolUp_le _ _ _ _ _ _ _)
  scaleUp_le := fun _ _ _ _ => (h₁.scaleUp_le _ _ _ _).trans (h₂.scaleUp_le _ _ _ _)
  wUp_le := fun _ _ _ _ _ => (h₁.wUp_le _ _ _ _ _).trans (h₂.wUp_le _ _ _ _ _)
  splitUp_le := fun _ _ _ _ _ => (h₁.splitUp_le _ _ _ _ _).trans (h₂.splitUp_le _ _ _ _ _)
  β₁Up_le := fun _ _ _ _ _ _ => (h₁.β₁Up_le _ _ _ _ _ _).trans (h₂.β₁Up_le _ _ _ _ _ _)
  T₀Low_ge := fun _ _ _ _ _ _ _ => (h₂.T₀Low_ge _ _ _ _ _ _ _).trans (h₁.T₀Low_ge _ _ _ _ _ _ _)
  LmaxLow_ge := fun _ _ _ _ _ _ => (h₂.LmaxLow_ge _ _ _ _ _ _).trans (h₁.LmaxLow_ge _ _ _ _ _ _)
  tailLow_ge := fun _ _ _ _ _ _ _ =>
    (h₂.tailLow_ge _ _ _ _ _ _ _).trans (h₁.tailLow_ge _ _ _ _ _ _ _)

/-- The infimum is below its first argument. -/
theorem ClosedThresholdsV4.inf_below_left_VAL6 {D : ClosedEarlyData}
    (U₁ U₂ : ClosedThresholdsV4 D) : ClosedStrategyBelowV4 (U₁.inf U₂) U₁ where
  lc18_le := min_le_left _ _
  circleUp_le := fun _ _ _ _ _ => min_le_left _ _
  β₂Up_le := fun _ _ _ => min_le_left _ _
  ΔLow_ge := fun _ _ _ _ => le_max_left _ _
  errorsUp_le := fun _ _ _ => min_le_left _ _
  sectionUp_le := fun _ _ _ _ => min_le_left _ _
  lfr29W_le := fun _ _ _ _ _ => min_le_left _ _
  endpointUp_le := fun _ _ _ _ _ _ => min_le_left _ _
  σcolUp_le := fun _ _ _ _ _ _ _ => min_le_left _ _
  scaleUp_le := fun _ _ _ _ => min_le_left _ _
  wUp_le := fun _ _ _ _ _ => min_le_left _ _
  splitUp_le := fun _ _ _ _ _ => min_le_left _ _
  β₁Up_le := fun _ _ _ _ _ _ => min_le_left _ _
  T₀Low_ge := fun _ _ _ _ _ _ _ => le_max_left _ _
  LmaxLow_ge := fun _ _ _ _ _ _ => le_max_left _ _
  tailLow_ge := fun _ _ _ _ _ _ _ => le_max_left _ _

/-- The infimum is below its second argument. -/
theorem ClosedThresholdsV4.inf_below_right_VAL6 {D : ClosedEarlyData}
    (U₁ U₂ : ClosedThresholdsV4 D) : ClosedStrategyBelowV4 (U₁.inf U₂) U₂ where
  lc18_le := min_le_right _ _
  circleUp_le := fun _ _ _ _ _ => min_le_right _ _
  β₂Up_le := fun _ _ _ => min_le_right _ _
  ΔLow_ge := fun _ _ _ _ => le_max_right _ _
  errorsUp_le := fun _ _ _ => min_le_right _ _
  sectionUp_le := fun _ _ _ _ => min_le_right _ _
  lfr29W_le := fun _ _ _ _ _ => min_le_right _ _
  endpointUp_le := fun _ _ _ _ _ _ => min_le_right _ _
  σcolUp_le := fun _ _ _ _ _ _ _ => min_le_right _ _
  scaleUp_le := fun _ _ _ _ => min_le_right _ _
  wUp_le := fun _ _ _ _ _ => min_le_right _ _
  splitUp_le := fun _ _ _ _ _ => min_le_right _ _
  β₁Up_le := fun _ _ _ _ _ _ => min_le_right _ _
  T₀Low_ge := fun _ _ _ _ _ _ _ => le_max_right _ _
  LmaxLow_ge := fun _ _ _ _ _ _ => le_max_right _ _
  tailLow_ge := fun _ _ _ _ _ _ _ => le_max_right _ _

/-! ### FC39-VAL4's rows strategy on register V4 -/

/-- **FC39-VAL4's rows strategy on register V4** (the requests of TCP01, TCP02, EGP03, EGP04,
EGP06, EGP07, SGP01, SGP02, SGP03, SGP04, SGP06; TCP02 at `ν = β₃/3`). Each upper slot is the
minimum of the requests read from the values before it (wrapped in `posOr_VAL3`), `L_max`'s lower
request is the maximum of the rows' `L_c`, `σ⁻¹` and `4(10 + 4·10⁶Δ + Δ/3)`; the slots the 11 rows
do not read are `1` (upper), `0` (lower) or trivial. -/
def partialRowsStrategyV4 (D : ClosedEarlyData) : ClosedThresholdsV4 D where
  Nb := fun _ => 0
  Nb_nonneg := fun _ => le_rfl
  cw := fun _ => 0
  cw_nonneg := fun _ => le_rfl
  lc18 := 1 / 2
  lc18_pos := by norm_num
  circleUp := fun _ _ _ _ _ => 1
  circleUp_pos := fun _ _ _ _ _ => one_pos
  β₂Up := fun _ ci β₃ => min (1 / 10000000) (min (posOr_VAL3 (tcp02σ_VAL4 ci.E (β₃ / 3)) / 3)
    (posOr_VAL3 (tcp02η₂_VAL4 ci.E (β₃ / 3))))
  β₂Up_pos := fun _ _ _ =>
    lt_min (by norm_num) (lt_min (div_pos (posOr_pos_VAL3 _) (by norm_num)) (posOr_pos_VAL3 _))
  ΔLow := fun _ _ _ _ => 0
  errorsUp := fun st ci ex => min (posOr_VAL3 (ci.θe ^ 2 / 10 ^ 8))
    (min (posOr_VAL3 (1 / (1000 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 (1 / (100 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 (ci.θe / (100 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 (ci.θs ^ 2 / 10 ^ 6))
    (min (posOr_VAL3 (ci.θs / 100))
    (min (posOr_VAL3 (ci.θs / (100 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 (sgp04θ_VAL4 ex.Δ ex.β₂ (st.e 2) ^ 2 / 10 ^ 6))
    (min (posOr_VAL3 (sgp04θ_VAL4 ex.Δ ex.β₂ (st.e 2) / 100))
    (min (posOr_VAL3 (sgp04θ_VAL4 ex.Δ ex.β₂ (st.e 2) / (100 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 (sgp06θ_VAL4 ex.Δ ex.β₂ (st.Γ 2) (st.Sig 2) (st.e 2) ^ 2 / 10 ^ 6))
    (min (posOr_VAL3 (sgp06θ_VAL4 ex.Δ ex.β₂ (st.Γ 2) (st.Sig 2) (st.e 2) / 100))
    (min (posOr_VAL3 (sgp06θ_VAL4 ex.Δ ex.β₂ (st.Γ 2) (st.Sig 2) (st.e 2) /
      (100 * (1000000 * ex.Δ))))
    (min (posOr_VAL3 ((st.e 1 / (20 * egpGraphConst)) ^ 2 / 10 ^ 8))
    (min (posOr_VAL3 (st.e 1 / (20 * egpGraphConst) / 100))
      (posOr_VAL3 (st.e 1 / (20 * egpGraphConst) / (100 * (1000000 * ex.Δ))))))))))))))))))
  errorsUp_pos := fun _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  sectionUp := fun st ci ex _ => min (posOr_VAL3 (ci.θe / 100 / ex.Δ))
    (posOr_VAL3 (st.e 1 / (20 * egpGraphConst) / 100 / ex.Δ))
  sectionUp_pos := fun _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  lfr29W := fun _ _ _ _ _ => 1
  lfr29W_pos := fun _ _ _ _ _ => one_pos
  endpointUp := fun _ _ _ _ _ _ => 1
  endpointUp_pos := fun _ _ _ _ _ _ => one_pos
  σcolUp := fun _ _ _ _ _ _ _ => 1
  σcolUp_pos := fun _ _ _ _ _ _ _ => one_pos
  I₁ := 1
  I₁_pos := one_pos
  scaleUp := fun _ _ _ _ => 1
  scaleUp_pos := fun _ _ _ _ => one_pos
  wUp := fun _ _ _ _ _ => 1
  wUp_pos := fun _ _ _ _ _ => one_pos
  splitUp := fun st ci ex _ _ => min (posOr_VAL3 (tcp02η₁_VAL4 ci.E (ex.β₃ / 3) ex.Δ))
    (min (posOr_VAL3 (egp03η_VAL4 ex.Δ ex.β₂ ci.E))
    (min (posOr_VAL3 (egp04η_VAL4 ex.Δ ex.β₂ ci.θe))
    (min (posOr_VAL3 (egp06η_VAL4 ex.Δ ex.β₂ (st.e 1)))
      (posOr_VAL3 (egp07η_VAL4 ex.Δ ex.β₂ (st.Γ 1) (st.Sig 1) (st.e 1))))))
  splitUp_pos := fun _ _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  β₁Up := fun st ci ex _ _ _ => min (posOr_VAL3 (tcp02η₁_VAL4 ci.E (ex.β₃ / 3) ex.Δ))
    (min (posOr_VAL3 (egp03η_VAL4 ex.Δ ex.β₂ ci.E))
    (min (posOr_VAL3 (egp04η_VAL4 ex.Δ ex.β₂ ci.θe))
    (min (posOr_VAL3 (egp06η_VAL4 ex.Δ ex.β₂ (st.e 1)))
    (min (posOr_VAL3 (egp07η_VAL4 ex.Δ ex.β₂ (st.Γ 1) (st.Sig 1) (st.e 1)))
    (min (posOr_VAL3 (sgp02η_VAL4 ex.Δ ex.β₂ ci.E))
    (min (posOr_VAL3 (sgp03η_VAL4 ex.Δ ex.β₂ ci.θs (ci.θs ^ 2 / (2 * 10 ^ 6))))
    (min (posOr_VAL3 (sgp04η_VAL4 ex.Δ ex.β₂ (st.e 2)))
      (posOr_VAL3 (sgp06η_VAL4 ex.Δ ex.β₂ (st.Γ 2) (st.Sig 2) (st.e 2))))))))))
  β₁Up_pos := fun _ _ _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  T₀Low := fun _ _ _ _ _ _ _ => 0
  lpa02V := fun _ _ _ _ _ _ _ T₀ => T₀
  T₀_le_lpa02V := fun _ _ _ _ _ _ _ _ => le_rfl
  LmaxLow := fun st ci ex _ _ _ => max (4 * (10 + 2 * (2000000 * ex.Δ) + ex.Δ / 3))
    (max (tcp02σ_VAL4 ci.E (ex.β₃ / 3))⁻¹
    (max (egp03Lc_VAL4 ex.Δ ex.β₂ ci.E)
    (max (egp04Lc_VAL4 ex.Δ ex.β₂ ci.θe)
    (max (egp06Lc_VAL4 ex.Δ ex.β₂ (st.e 1))
    (max (egp07Lc_VAL4 ex.Δ ex.β₂ (st.Γ 1) (st.Sig 1) (st.e 1))
    (max (sgp02Lc_VAL4 ex.Δ ex.β₂ ci.E)
    (max (sgp03Lc_VAL4 ex.Δ ex.β₂ ci.θs (ci.θs ^ 2 / (2 * 10 ^ 6)))
    (max (sgp04Lc_VAL4 ex.Δ ex.β₂ (st.e 2))
      (sgp06Lc_VAL4 ex.Δ ex.β₂ (st.Γ 2) (st.Sig 2) (st.e 2))))))))))
  tailLow := fun _ _ _ _ _ _ _ => 0
  H := fun m => (m : ℝ)
  H_tendsto := tendsto_natCast_atTop_atTop

/-- **The 11 rows at every register of a strategy below the 11-row strategy** (FC39-VAL4's proof on
register V4): with `C_ge`, for every register `R` at `T`, every `εr < ε₀`, `20Λz ≤ T₀` and every
final family at `R`'s values, the
conclusions of TCP01, TCP02, EGP03, EGP04, EGP06, EGP07, SGP01, SGP02, SGP03, SGP04, SGP06 hold at
the register's tolerances. -/
theorem partialRowOuts_of_below_VAL6 {D : ClosedEarlyData} (hC : ∀ j, gafGraphConst j ≤ D.C j)
    {T : ClosedThresholdsV4 D} (hTU : ClosedStrategyBelowV4 T (partialRowsStrategyV4 D))
    (R : ClosedRegisterV4 D T) {K : ℕ} {X : Type} [MetricSpace X] [ChartedSpace E3 X]
    [IsManifold 𝓘(ℝ, E3) ∞ X] [CompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
    {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
    {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {δ εr Λz : ℝ} (hεr : εr < R.later.err.co.ε₀)
    (hΛz : 20 * Λz ≤ R.later.split.T₀)
    (P : LocalChartPacketsC14 X g hmetric ρ hρ R.later.scale.Λ R.β R.later.excl.Δ
      R.later.err.co.qs K R.later.err.co.qe R.later.err.bd.μ R.later.split.b R.later.err.s
      R.later.err.wk.b' R.later.err.wk.s' R.later.err.co.ε R.later.circle.γc R.later.circle.βc
      R.later.Lmax R.later.err.bd.τ R.later.circle.γ δ εr R.later.err.co.e₀ R.later.split.T₀
      R.later.split.V R.later.err.co.ve R.later.err.co.ζ Λz) :
    Tcp01GramOutV2 P.toLocalChartPackets ∧
    Tcp02OutV2 P.toLocalChartPackets R.later.circle.E ∧
    Egp03OutV2 P.toLocalChartFamilyE R.later.circle.E ∧
    Egp04OutV2 P.toLocalChartPacketsRVZ R.later.circle.θe ∧
    Egp06OutV2 P.toLocalChartPacketsRVZ (R.stage.e 1) ∧
    Egp07OutV2 P (R.stage.Γ 1) (R.stage.Sig 1) (R.stage.e 1) ∧
    Sgp01OutV2 P.toLocalChartPacketsR ∧
    Sgp02OutV2 P.toLocalChartFamilyQ R.later.circle.E ∧
    Sgp03ZeroOutV2 P.toLocalChartPacketsRVZ R.later.circle.θs
      (R.later.circle.θs ^ 2 / (2 * 10 ^ 6)) ∧
    Sgp04OutV2 P.toLocalChartPacketsRVZ (R.stage.e 2) ∧
    Sgp06OutV2 P (R.stage.Γ 2) (R.stage.Sig 2) (R.stage.e 2)
    := by
  -- the register's ranges
  have hΔ0 : 0 < R.later.excl.Δ := R.later.Δ_pos_VAL6
  have hΔ1 : 1 ≤ R.later.excl.Δ :=
    ((by norm_num : (1 : ℝ) < 100).trans R.later.hundred_lt_Δ_VAL6).le
  have hβ₂0 := R.later.β₂_pos
  have hβ₂6 : R.later.excl.β₂ < 1 / 1000000 := R.later.β₂_lt_audit_VAL6.trans_eq (by norm_num)
  have hβ₂1 : R.later.excl.β₂ < 1 := hβ₂6.trans (by norm_num)
  have hβ₃0 := R.later.β₃_pos
  have hβ₃ : R.later.excl.β₃ < 1 / 2 := R.later.β₃_lt.trans_le hTU.lc18_le
  have hΛ0 : 0 ≤ R.later.scale.Λ := R.later.Λ_pos.le
  have hLΛ : 1000000 * R.later.excl.Δ * R.later.scale.Λ < 1 / 100000 := by
    have h := R.later.regScale_L
    unfold closedLongLength at h
    linarith
  have hT1600 : 1600 * (1000000 * R.later.excl.Δ) ≤ R.later.split.T₀ := by
    have h := (le_max_left _ _).trans R.later.T₀_ge
    unfold closedLongLength at h
    linarith
  have he40 : R.later.err.co.e₀ < 1 / 40 := R.later.e₀_lt_VAL6
  have hμ : R.later.err.bd.μ ≤ 1 / 100 := (R.later.μ_lt_VAL6.trans (by norm_num)).le
  have hτ : R.later.err.bd.τ ≤ 1 / 100 := (R.later.τ_lt_VAL6.trans (by norm_num)).le
  have hs6 : R.later.err.s < 1 / 1000000 := R.later.s_lt_audit_VAL6.trans_eq (by norm_num)
  have hσs0 := R.later.qs_pos
  have hζ0 := R.later.ζ_pos
  have hE0 := R.later.E_pos
  have hθe0 := R.later.θe_pos
  have hθe1 : R.later.circle.θe < 1 := R.later.θe_lt_hundredth_VAL6.trans (by norm_num)
  have hθs0 := R.later.θs_pos
  have hrange2 := R.stage.stage_range_VAL3 hC 2
  have hrange1 := R.stage.stage_range_VAL3 hC 1
  have hθs1 : R.later.circle.θs < 1 := by
    have h := R.later.θs_lt
    have hC2 : sgpGraphBound ≤ D.C 2 := hC 2
    have h4 := four_le_sgpGraphBound_SGP4
    have he2 := hrange2.2.2.2.2.2.2.1
    have hD : 0 < 10 * D.C 2 := by linarith
    calc R.later.circle.θs < R.stage.e 2 / (10 * D.C 2) := h
      _ < 1 := by rw [div_lt_one hD]; linarith
  have hκ : 0 < R.stage.e 1 / (20 * egpGraphConst) :=
    div_pos hrange1.2.2.2.2.2.1 (mul_pos (by norm_num) egpGraphConst_pos_KC4)
  -- the strategy's slots at the register
  have hβ₂U : R.later.excl.β₂ < (partialRowsStrategyV4 D).β₂Up R.stage R.later.circle.toPrefixV4
      R.later.excl.β₃ := (R.later.β₂_lt.trans_le (min_le_left _ _)).trans_le (hTU.β₂Up_le _ _ _)
  simp only [partialRowsStrategyV4, ClosedCircleRequestsV2.toPrefixV4, lt_min_iff] at hβ₂U
  obtain ⟨hβ₂7, hβ₂σ, hβ₂η⟩ := hβ₂U
  have hζU := R.later.ζ_lt.trans_le (hTU.errorsUp_le _ _ _)
  have hqsU := (R.later.qs_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hqeU := (R.later.qe_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hveU := (R.later.ve_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hε₀U := (R.later.ε₀_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hve := R.later.ve_lt.trans_le (min_le_left _ _)
  simp only [partialRowsStrategyV4, lt_min_iff] at hζU hqsU hqeU hveU hε₀U
  obtain ⟨hζA1, hζA2, hζA2b, -, hζB1, -, -, hζC1, -, -, hζD1, -, -, hζK1, -, -⟩ := hζU
  obtain ⟨hqsA1, -, -, -, hqsB1, -, -, hqsC1, -, -, hqsD1, -, -, hqsK1, -, -⟩ := hqsU
  obtain ⟨hqeA1, -, -, -, -, -, -, -, -, -, -, -, -, hqeK1, -, -⟩ := hqeU
  obtain ⟨-, -, -, -, -, hveB2, -, -, hveC2, -, -, hveD2, -, -, hveK2, -⟩ := hveU
  obtain ⟨-, -, -, hε₀A3, -, -, hε₀B3, -, -, hε₀C3, -, -, hε₀D3, -, -, hε₀K3⟩ := hε₀U
  have hμU := (R.later.μ_lt.trans_le (min_le_right _ _)).trans_le (hTU.sectionUp_le _ _ _ _)
  simp only [partialRowsStrategyV4, lt_min_iff] at hμU
  obtain ⟨hμA, hμK⟩ := hμU
  have hbU := (R.later.b_lt.trans_le (min_le_left _ _)).trans_le (hTU.splitUp_le _ _ _ _ _)
  simp only [partialRowsStrategyV4, lt_min_iff] at hbU
  obtain ⟨hbT2, hbE3, hbE4, hbE6, hbE7⟩ := hbU
  have hβ₁U := (R.later.β₁_lt.trans_le (min_le_left _ _)).trans_le (hTU.β₁Up_le _ _ _ _ _ _)
  simp only [partialRowsStrategyV4, lt_min_iff] at hβ₁U
  obtain ⟨h1T2, h1E3, h1E4, h1E6, h1E7, h1S2, h1S3, h1S4, h1S6⟩ := hβ₁U
  have hLU := (hTU.LmaxLow_ge _ _ _ _ _ _).trans_lt ((le_max_right _ _).trans_lt R.later.Lmax_gt)
  simp only [partialRowsStrategyV4, max_lt_iff] at hLU
  obtain ⟨hL4, hLσ, hLE3, hLE4, hLE6, hLE7, hLS2, hLS3, hLS4, hLS6⟩ := hLU
  -- stripping `posOr` at the explicit tolerances
  have hp : ∀ {x y : ℝ}, 0 < y → x < posOr_VAL3 y → x < y := fun hy h =>
    h.trans_eq (posOr_eq_VAL3 hy)
  have hΔL : 0 < 1000000 * R.later.excl.Δ := by positivity
  refine ⟨tcp01_gram_out_VAL3 P.toLocalChartPackets R.later.γ_pos.le
    (R.β_two_VAL6.trans_le hβ₂7.le), ?_, ?_, ?_, ?_, ?_,
    sgp01_row_out_VAL3 P.toLocalChartPacketsR hΛ0 hΔ1 hLΛ he40 hT1600 hσs0.le
      R.later.qs_le_hundredth_VAL6, ?_, ?_, ?_, ?_⟩
  · -- TCP02 at `E₀ = E`, `ν = β₃ / 3`
    have hc : 0 < R.later.circle.E ∧ 0 < R.later.excl.β₃ / 3 ∧ R.later.excl.β₃ / 3 < 1 :=
      ⟨hE0, by positivity, by linarith only [hβ₃]⟩
    obtain ⟨sσ, -, s2⟩ := Classical.choose_spec (tcp02_row_out_VAL3 hc.1 hc.2.1 hc.2.2)
    have s2' := Classical.choose_spec s2
    have s3 := Classical.choose_spec (s2'.2 _ hΔ1)
    have hc1 : 0 < R.later.circle.E ∧ 0 < R.later.excl.β₃ / 3 ∧ R.later.excl.β₃ / 3 < 1 ∧
        1 ≤ R.later.excl.Δ := ⟨hc.1, hc.2.1, hc.2.2, hΔ1⟩
    have hν3 : 3 * (R.later.excl.β₃ / 3) ≤ R.β 3 := by
      rw [R.β_three_VAL6]
      linarith only []
    have hβ3 : R.β 3 < 1 := by
      rw [R.β_three_VAL6]
      linarith only [hβ₃]
    have h3σ : 3 * R.later.excl.β₂ < posOr_VAL3 (tcp02σ_VAL4 R.later.circle.E
        (R.later.excl.β₃ / 3)) := (lt_div_iff₀' three_pos).mp hβ₂σ
    have hσ : 3 * R.later.excl.β₂ <
        Classical.choose (tcp02_row_out_VAL3 hc.1 hc.2.1 hc.2.2) :=
      lt_of_lt_posOr_dite_VAL4 hc sσ h3σ
    have hη : R.later.excl.β₂ < Classical.choose s2 := lt_of_lt_posOr_dite_VAL4 hc s2'.1 hβ₂η
    have hη1 : R.later.split.β₁ < Classical.choose (s2'.2 _ hΔ1) :=
      lt_of_lt_posOr_dite_VAL4 hc1 s3.1 h1T2
    have hb1 : R.later.split.b < Classical.choose (s2'.2 _ hΔ1) :=
      lt_of_lt_posOr_dite_VAL4 hc1 s3.1 hbT2
    have hσL : (Classical.choose (tcp02_row_out_VAL3 hc.1 hc.2.1 hc.2.2))⁻¹ ≤ R.later.Lmax :=
      inv_le_of_dite_le_VAL4 hc hLσ.le
    exact s3.2 P.toLocalChartPackets hΛ0 hμ hτ hLΛ hL4.le he40 hT1600 hν3 hβ3
      (R.β_two_VAL6 ▸ hσ.le) (R.β_two_VAL6 ▸ hη.le) (R.β_one_VAL6.trans_le hη1.le) hb1.le hσL
  · -- EGP03 at `E`
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 / 1000000 ∧
        0 < R.later.circle.E := ⟨hΔ1, hβ₂0, hβ₂6, hE0⟩
    have s := choose₂_spec_VAL4 (egp03_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2)
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartFamilyE (lt_of_lt_posOr_dite_VAL4 hc s.2.1 hbE3).le hs6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1E3).le)
      (le_of_dite_le_VAL4 hc hLE3.le) hΛ0 hLΛ hμ hτ
  · -- EGP04 at `θ_e`
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 / 1000000 ∧
        0 < R.later.circle.θe ∧ R.later.circle.θe < 1 := ⟨hΔ1, hβ₂0, hβ₂6, hθe0, hθe1⟩
    have s := choose₂_spec_VAL4 (egp04_row_RVZ_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2)
    have hA1 : 0 < R.later.circle.θe ^ 2 / 10 ^ 8 := by positivity
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartPacketsRVZ (lt_of_lt_posOr_dite_VAL4 hc s.2.1 hbE4).le hs6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1E4).le)
      (le_of_dite_le_VAL4 hc hLE4.le) hΛ0 hLΛ hμ hτ (hp hA1 hqeA1).le
      ((lt_div_iff₀ hΔ0).mp (hp (by positivity) hμA)) hσs0 (hp hA1 hqsA1).le hve he40 hT1600
      hΛz hζ0 (hp hA1 hζA1).le (hp (by positivity) hζA2).le
      (hεr.trans (hp (by positivity) hε₀A3))
  · -- EGP06 at `e₁`
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 / 1000000 ∧
        0 < R.stage.e 1 ∧ R.stage.e 1 < 1 / 100 :=
      ⟨hΔ1, hβ₂0, hβ₂6, hrange1.2.2.2.2.2.1, hrange1.2.2.2.2.2.2.1⟩
    have s := choose₂_spec_VAL4 (egp06_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1 hc.2.2.2.2)
    have hK1 : 0 < (R.stage.e 1 / (20 * egpGraphConst)) ^ 2 / 10 ^ 8 := by positivity
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartPacketsRVZ (lt_of_lt_posOr_dite_VAL4 hc s.2.1 hbE6).le hs6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1E6).le)
      (le_of_dite_le_VAL4 hc hLE6.le) hΛ0 hLΛ hμ hτ (hp hK1 hqeK1).le
      ((lt_div_iff₀ hΔ0).mp (hp (by positivity) hμK)) hσs0 (hp hK1 hqsK1).le
      (hp (by positivity) hveK2) he40 hT1600 hΛz hζ0 (hp hK1 hζK1).le
      (hp (by positivity) hζA2).le (hεr.trans (hp (by positivity) hε₀K3))
  · -- EGP07 at the edge stage values
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 / 1000000 ∧
        R.stage.Γ 1 ∈ Ioo (0 : ℝ) 1 ∧ 0 < R.stage.Sig 1 ∧
        R.stage.Sig 1 < min (R.stage.Γ 1 / 200) (R.stage.Γ 1 ^ 3 / (100 * egpGraphConst)) ∧
        0 < R.stage.e 1 ∧
        R.stage.e 1 < min (1 / 100) (min (R.stage.Γ 1 * R.stage.Sig 1 / 100)
          (R.stage.Sig 1 / 1000)) := ⟨hΔ1, hβ₂0, hβ₂6, R.stage.egp07_range_VAL3 hC⟩
    have s := choose₂_spec_VAL4 (egp07_row_C14_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2)
    have hK1 : 0 < (R.stage.e 1 / (20 * egpGraphConst)) ^ 2 / 10 ^ 8 := by positivity
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P (lt_of_lt_posOr_dite_VAL4 hc s.2.1 hbE7).le hs6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1E7).le)
      (le_of_dite_le_VAL4 hc hLE7.le) hΛ0 hLΛ hμ hτ (hp hK1 hqeK1).le
      ((lt_div_iff₀ hΔ0).mp (hp (by positivity) hμK)) hσs0 (hp hK1 hqsK1).le
      (hp (by positivity) hveK2) he40 hT1600 hΛz hζ0 (hp hK1 hζK1).le
      (hp (by positivity) hζA2).le (hεr.trans (hp (by positivity) hε₀K3))
  · -- SGP02 at `E`
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 ∧
        0 < R.later.circle.E := ⟨hΔ1, hβ₂0, hβ₂1, hE0⟩
    have s := choose₂_spec_VAL4 (sgp02_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2)
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartFamilyQ R.β_two_VAL6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1S2).le)
      (le_of_dite_le_VAL4 hc hLS2.le) hΛ0 hLΛ
  · -- SGP03 at `θ_s` with accuracy `θ_s² / (2·10⁶)`
    have hθ2 : 0 < R.later.circle.θs ^ 2 := by positivity
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 ∧
        0 < R.later.circle.θs ∧ R.later.circle.θs < 1 ∧
        0 < R.later.circle.θs ^ 2 / (2 * 10 ^ 6) ∧
        R.later.circle.θs ^ 2 / (2 * 10 ^ 6) < R.later.circle.θs ^ 2 / 10 ^ 6 :=
      ⟨hΔ1, hβ₂0, hβ₂1, hθs0, hθs1, by positivity, by linarith only [hθ2]⟩
    have s := choose₂_spec_VAL4 (sgp03_zero_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2)
    have hB1 : 0 < R.later.circle.θs ^ 2 / 10 ^ 6 := by positivity
    exact s.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartPacketsRVZ R.β_two_VAL6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s.2.1 h1S3).le)
      (le_of_dite_le_VAL4 hc hLS3.le) hΛ0 hLΛ he40 hT1600 hΛz hσs0 (hp hB1 hqsB1)
      (hp (by positivity) hveB2) hζ0 (hp hB1 hζB1) (hp (by positivity) hζA2b)
      (hεr.trans (hp (by positivity) hε₀B3))
  · -- SGP04 at `e₂`
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 ∧
        0 < R.stage.e 2 ∧ R.stage.e 2 < 1 / 100 :=
      ⟨hΔ1, hβ₂0, hβ₂1, hrange2.2.2.2.2.2.1, hrange2.2.2.2.2.2.2.1⟩
    have s := Classical.choose_spec (sgp04_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2)
    have s' := choose₂_spec_VAL4 s.2.2
    have e : sgp04θ_VAL4 R.later.excl.Δ R.later.excl.β₂ (R.stage.e 2) =
        Classical.choose (sgp04_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1 hc.2.2.2.2) :=
      dite_eq_left hc
    rw [e] at hqsC1 hveC2 hζC1 hε₀C3
    have hC1 : 0 < Classical.choose (sgp04_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
        hc.2.2.2.2) ^ 2 / 10 ^ 6 := by have := s.1; positivity
    exact s'.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P.toLocalChartPacketsRVZ R.β_two_VAL6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s'.2.1 h1S4).le)
      (le_of_dite_le_VAL4 hc hLS4.le) hΛ0 hLΛ he40 hT1600 hΛz hσs0 (hp hC1 hqsC1)
      (hp (by have := s.1; positivity) hveC2) hζ0 (hp hC1 hζC1) (hp (by positivity) hζA2b)
      (hεr.trans (hp (by have := s.1; positivity) hε₀C3))
  · -- SGP06 at the slim stage values
    have hc : 1 ≤ R.later.excl.Δ ∧ 0 < R.later.excl.β₂ ∧ R.later.excl.β₂ < 1 ∧
        0 < R.stage.Γ 2 ∧ R.stage.Γ 2 < 1 ∧ 0 < R.stage.Sig 2 ∧
        R.stage.Sig 2 < R.stage.Γ 2 / 200 ∧
        R.stage.Sig 2 < R.stage.Γ 2 ^ 3 / (100 * sgpGraphBound) ∧ 0 < R.stage.e 2 ∧
        R.stage.e 2 < 1 / 100 ∧ R.stage.e 2 < R.stage.Γ 2 * R.stage.Sig 2 / 100 :=
      ⟨hΔ1, hβ₂0, hβ₂1, R.stage.sgp06_range_VAL3 hC⟩
    have s := Classical.choose_spec (sgp06_row_C14_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.1
      hc.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2)
    have s' := choose₂_spec_VAL4 s.2.2
    have e : sgp06θ_VAL4 R.later.excl.Δ R.later.excl.β₂ (R.stage.Γ 2) (R.stage.Sig 2)
        (R.stage.e 2) = Classical.choose (sgp06_row_C14_out_VAL3 hc.1 hc.2.1 hc.2.2.1
          hc.2.2.2.1 hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.1
          hc.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2) :=
      dite_eq_left hc
    rw [e] at hqsD1 hveD2 hζD1 hε₀D3
    have hD1 := s.1
    exact s'.2.2 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
      P R.β_two_VAL6
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s'.2.1 h1S6).le)
      (le_of_dite_le_VAL4 hc hLS6.le) hΛ0 hLΛ he40 hT1600 hΛz hσs0 (hp (by positivity) hqsD1)
      (hp (by positivity) hveD2) hζ0 (hp (by positivity) hζD1) (hp (by positivity) hζA2b)
      (hεr.trans (hp (by positivity) hε₀D3))

end DifferentialGeometry.Geometry.Collapse
