import DifferentialGeometry.Geometry.Collapse.StaticRegisterV4RowsStrategy
import DifferentialGeometry.Geometry.Collapse.StaticRegisterV4ValidityRows

/-!
# TCP03–TCP06 at every register V4 (lane FC39-VAL6)

Register-V4 file (lane FC39-VAL6), generated by `build-logs/scratch/FC39-VAL6/gen_v4.py`
from FC39-VAL5's `StaticRegisterV3RowsCircle.lean` with register V3 → V4 (`βc` chosen right
after `β₂`, `β₂Up` reads the circle prefix `ClosedCirclePrefixV4` without `βc`; see
`StaticRegisterV4.lean`). It imports no register-V3 module.

The obstruction of lane FC39-VAL4 (register V2 chose `γ, γc, βc` before `β₃`, while TCP03–TCP06
request `γ, γc ≤ γ₀(ν)` and `βc ≤ η_c(ν)` with `3ν ≤ β₃`) disappears on register V4, where `β₃` is
fixed before PR11 and the circle slot reads it. With `ν = β₃/3`:

* total threshold functions (the accepted rows' Skolem witnesses, `1` outside a row's range):
  TCP03 (`tcp03σ_VAL6`, `tcp03η₂_VAL6`, `tcp03γ₀_VAL6`, `tcp03η₁_VAL6` at `(θ, ν)`), TCP04
  (`tcp04σ/η₂/γ₀/ηc_VAL6` at `(θ, ν)`), TCP05 (`tcp05σ/η₂/γ₀/ηc/θ_VAL6` at `(e, ν)`,
  `tcp05η₁_VAL6` at `(e, ν, Δ)`), TCP06 (the same at `(Γ, Σ, e, ν)`);
* `circleRowsStrategyV4 D`: the circle slot (`γ, γc ≤ γ₀`, `βc ≤ η_c` of TCP03–TCP06 at
  `ν = β₃/3`), `β₂Up` (`3β₂ ≤ σ`, `β₂ ≤ η₂`), `errorsUp` (`ζ, σc, σs ≤ θ²/1000`, `v_s, ε_r ≤ θ/100`,
  `ε ≤ 1`), `sectionUp` (`μΔ ≤ θ/100`), `splitUp`/`β₁Up` (`b, β₁ ≤ η₁`) and `L_max`'s lower request
  (`σ⁻¹`, `4(10 + 4·10⁶Δ + Δ/3)`), `lc18 = 1/2` (so `ν < 1`, `β 3 < 1`);
* `tcp03_out_of_below_VAL6`, `tcp04_out_of_below_VAL6`, `tcp05_out_of_below_VAL6`,
  `tcp06_out_of_below_VAL6`: at every register of a strategy below it (with `C_ge`), the row
  conclusions on every final family at the register's values (TCP03 and TCP04 at `θ₂`, TCP05 at
  `e₀`, TCP06 at `(Γ₀, Σ₀, e₀)`, as in `ClosedRowOutsV4`).
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric Bundle Manifold Filter
open scoped ContDiff Manifold Topology
open DifferentialGeometry GC.Endpoint GC.MetricGeometry
open DifferentialGeometry.Geometry.Riemannian DifferentialGeometry.Analysis

namespace DifferentialGeometry.Geometry.Collapse

local notation "E3" => EuclideanSpace ℝ (Fin 3)

attribute [-instance] Tensor0SBundle.tangentSpaceNormedAddCommGroup
  Tensor0SBundle.tangentSpaceNormedSpace

attribute [local instance] nezero_finrank_euclideanThree_LC87

/-! ### Total threshold functions -/

/-- TCP03's `σ` at `(θ, ν)`. -/
def tcp03σ_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (tcp03_zero_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)
  else 1

/-- TCP03's `η₂` at `(θ, ν)`. -/
def tcp03η₂_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (tcp03_zero_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2
  else 1

/-- TCP03's `γ₀` at `(θ, ν)`. -/
def tcp03γ₀_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec
      (tcp03_zero_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2).2
  else 1

/-- TCP03's `η₁` at `(θ, ν)`. -/
def tcp03η₁_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (tcp03_zero_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2).2).2
  else 1

/-- TCP04's `σ` at `(θ, ν)`. -/
def tcp04σ_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (tcp04_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)
  else 1

/-- TCP04's `η₂` at `(θ, ν)`. -/
def tcp04η₂_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (tcp04_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2
  else 1

/-- TCP04's `γ₀` at `(θ, ν)`. -/
def tcp04γ₀_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec
      (tcp04_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2).2
  else 1

/-- TCP04's `η_c` at `(θ, ν)`. -/
def tcp04ηc_VAL6 (θ ν : ℝ) : ℝ :=
  if h : 0 < θ ∧ θ < 1 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (tcp04_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2).2).2
  else 1

/-- TCP05's `σ` at `(e, ν)`. -/
def tcp05σ_VAL6 (eg ν : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)
  else 1

/-- TCP05's `η₂` at `(e, ν)`. -/
def tcp05η₂_VAL6 (eg ν : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2
  else 1

/-- TCP05's `γ₀` at `(e, ν)`. -/
def tcp05γ₀_VAL6 (eg ν : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec
      (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2)
  else 1

/-- TCP05's `η_c` at `(e, ν)`. -/
def tcp05ηc_VAL6 (eg ν : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2))
  else 1

/-- TCP05's tolerance `θ` at `(e, ν)`. -/
def tcp05θ_VAL6 (eg ν : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2)).2.2)))
  else 1

/-- TCP05's `η₁` at `(e, ν, Δ)`. -/
def tcp05η₁_VAL6 (eg ν Δ : ℝ) : ℝ :=
  if h : 0 < eg ∧ eg < 1 / 100 ∧ 0 < ν ∧ ν < 1 ∧ 1200 ≤ Δ then
    Classical.choose ((Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec (Classical.choose_spec
        (tcp05_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1)).2.2)))).2.2.2.2.2 Δ h.2.2.2.2)
  else 1

/-- TCP06's `σ` at `(Γ, Σ, e, ν)`. -/
def tcp06σ_VAL6 (Γ sg eg ν : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (tcp06_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1 h.2.2.2.2.1 h.2.2.2.2.2.1
      h.2.2.2.2.2.2.1
        h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2)
  else 1

/-- TCP06's `η₂` at `(Γ, Σ, e, ν)`. -/
def tcp06η₂_VAL6 (Γ sg eg ν : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (tcp06_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1
      h.2.2.2.2.1 h.2.2.2.2.2.1 h.2.2.2.2.2.2.1
        h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2)).2.2
  else 1

/-- TCP06's `γ₀` at `(Γ, Σ, e, ν)`. -/
def tcp06γ₀_VAL6 (Γ sg eg ν : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (tcp06_row_out_VAL3 h.1 h.2.1
      h.2.2.1 h.2.2.2.1 h.2.2.2.2.1 h.2.2.2.2.2.1 h.2.2.2.2.2.2.1
        h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2)).2.2)
  else 1

/-- TCP06's `η_c` at `(Γ, Σ, e, ν)`. -/
def tcp06ηc_VAL6 (Γ sg eg ν : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (tcp06_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1 h.2.2.2.2.1 h.2.2.2.2.2.1 h.2.2.2.2.2.2.1
        h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2)).2.2))
  else 1

/-- TCP06's tolerance `θ` at `(Γ, Σ, e, ν)`. -/
def tcp06θ_VAL6 (Γ sg eg ν : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 then
    Classical.choose (Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec (tcp06_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1 h.2.2.2.2.1
        h.2.2.2.2.2.1 h.2.2.2.2.2.2.1
        h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2)).2.2)))
  else 1

/-- TCP06's `η₁` at `(Γ, Σ, e, ν, Δ)`. -/
def tcp06η₁_VAL6 (Γ sg eg ν Δ : ℝ) : ℝ :=
  if h : 0 < Γ ∧ Γ < 1 ∧ 0 < sg ∧ sg < Γ / 200 ∧ sg < Γ ^ 3 / (100 * tcpGraphConst) ∧
      0 < eg ∧ eg < 1 / 100 ∧ eg < Γ * sg / 100 ∧ 0 < ν ∧ ν < 1 ∧ 1200 ≤ Δ then
    Classical.choose ((Classical.choose_spec (Classical.choose_spec (Classical.choose_spec
      (Classical.choose_spec (Classical.choose_spec
      (tcp06_row_out_VAL3 h.1 h.2.1 h.2.2.1 h.2.2.2.1 h.2.2.2.2.1 h.2.2.2.2.2.1 h.2.2.2.2.2.2.1
          h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2.1)).2.2)))).2.2.2.2.2 Δ
            h.2.2.2.2.2.2.2.2.2.2)
  else 1

/-! ### The circle rows strategy -/

/-- **The circle rows strategy on register V4** (TCP03–TCP06 at `ν = β₃/3`): the circle slot reads
`β₃` (TCP03/TCP04 at `θ₂`, TCP05 at `e₀`, TCP06 at `(Γ₀, Σ₀, e₀)`); every other request reads only
values chosen before its slot; the slots these rows do not read are `1` (upper), `0` (lower) or
trivial. -/
def circleRowsStrategyV4 (D : ClosedEarlyData) : ClosedThresholdsV4 D where
  Nb := fun _ => 0
  Nb_nonneg := fun _ => le_rfl
  cw := fun _ => 0
  cw_nonneg := fun _ => le_rfl
  lc18 := 1 / 2
  lc18_pos := by norm_num
  circleUp := fun st β₃ _ _ θ₂ => min (posOr_VAL3 (tcp03γ₀_VAL6 θ₂ (β₃ / 3)))
    (min (posOr_VAL3 (tcp04γ₀_VAL6 θ₂ (β₃ / 3)))
    (min (posOr_VAL3 (tcp04ηc_VAL6 θ₂ (β₃ / 3)))
    (min (posOr_VAL3 (tcp05γ₀_VAL6 (st.e 0) (β₃ / 3)))
    (min (posOr_VAL3 (tcp05ηc_VAL6 (st.e 0) (β₃ / 3)))
    (min (posOr_VAL3 (tcp06γ₀_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (β₃ / 3)))
      (posOr_VAL3 (tcp06ηc_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (β₃ / 3))))))))
  circleUp_pos := fun _ _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  β₂Up := fun st ci β₃ => min (posOr_VAL3 (tcp03σ_VAL6 ci.θ₂ (β₃ / 3)) / 3)
    (min (posOr_VAL3 (tcp03η₂_VAL6 ci.θ₂ (β₃ / 3)))
    (min (posOr_VAL3 (tcp04σ_VAL6 ci.θ₂ (β₃ / 3)) / 3)
    (min (posOr_VAL3 (tcp04η₂_VAL6 ci.θ₂ (β₃ / 3)))
    (min (posOr_VAL3 (tcp05σ_VAL6 (st.e 0) (β₃ / 3)) / 3)
    (min (posOr_VAL3 (tcp05η₂_VAL6 (st.e 0) (β₃ / 3)))
    (min (posOr_VAL3 (tcp06σ_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (β₃ / 3)) / 3)
      (posOr_VAL3 (tcp06η₂_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (β₃ / 3)))))))))
  β₂Up_pos := fun _ _ _ => by
    simp only [lt_min_iff, posOr_pos_VAL3, and_self, div_pos (posOr_pos_VAL3 _) three_pos]
  ΔLow := fun _ _ _ _ => 0
  errorsUp := fun st ci ex => min (posOr_VAL3 (ci.θ₂ ^ 2 / 1000))
    (min (posOr_VAL3 (ci.θ₂ / 100))
    (min (posOr_VAL3 (tcp05θ_VAL6 (st.e 0) (ex.β₃ / 3) ^ 2 / 1000))
    (min (posOr_VAL3 (tcp05θ_VAL6 (st.e 0) (ex.β₃ / 3) / 100))
    (min (posOr_VAL3 (tcp06θ_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3) ^ 2 / 1000))
    (min (posOr_VAL3 (tcp06θ_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3) / 100)) 1)))))
  errorsUp_pos := fun _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self, zero_lt_one]
  sectionUp := fun st _ ex _ => min (posOr_VAL3 (tcp05θ_VAL6 (st.e 0) (ex.β₃ / 3) / 100 / ex.Δ))
    (posOr_VAL3 (tcp06θ_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3) / 100 / ex.Δ))
  sectionUp_pos := fun _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  lfr29W := fun _ _ _ _ _ => 1
  lfr29W_pos := fun _ _ _ _ _ => one_pos
  endpointUp := fun _ _ _ _ _ _ => 1
  endpointUp_pos := fun _ _ _ _ _ _ => one_pos
  σcolUp := fun _ _ _ _ _ _ _ => 1
  σcolUp_pos := fun _ _ _ _ _ _ _ => one_pos
  I₁ := 1
  I₁_pos := one_pos
  scaleUp := fun _ _ _ _ => 1
  scaleUp_pos := fun _ _ _ _ => one_pos
  wUp := fun _ _ _ _ _ => 1
  wUp_pos := fun _ _ _ _ _ => one_pos
  splitUp := fun st _ ex _ _ => min (posOr_VAL3 (tcp05η₁_VAL6 (st.e 0) (ex.β₃ / 3) ex.Δ))
    (posOr_VAL3 (tcp06η₁_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3) ex.Δ))
  splitUp_pos := fun _ _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  β₁Up := fun st ci ex _ _ _ => min (posOr_VAL3 (tcp03η₁_VAL6 ci.θ₂ (ex.β₃ / 3)))
    (min (posOr_VAL3 (tcp05η₁_VAL6 (st.e 0) (ex.β₃ / 3) ex.Δ))
      (posOr_VAL3 (tcp06η₁_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3) ex.Δ)))
  β₁Up_pos := fun _ _ _ _ _ _ => by simp only [lt_min_iff, posOr_pos_VAL3, and_self]
  T₀Low := fun _ _ _ _ _ _ _ => 0
  lpa02V := fun _ _ _ _ _ _ _ T₀ => T₀
  T₀_le_lpa02V := fun _ _ _ _ _ _ _ _ => le_rfl
  LmaxLow := fun st ci ex _ _ _ => max (4 * (10 + 2 * (2000000 * ex.Δ) + ex.Δ / 3))
    (max (tcp03σ_VAL6 ci.θ₂ (ex.β₃ / 3))⁻¹
    (max (tcp04σ_VAL6 ci.θ₂ (ex.β₃ / 3))⁻¹
    (max (tcp05σ_VAL6 (st.e 0) (ex.β₃ / 3))⁻¹
      (tcp06σ_VAL6 (st.Γ 0) (st.Sig 0) (st.e 0) (ex.β₃ / 3))⁻¹)))
  tailLow := fun _ _ _ _ _ _ _ => 0
  H := fun m => (m : ℝ)
  H_tendsto := tendsto_natCast_atTop_atTop

/-! ### TCP03–TCP06 at every register below the circle rows strategy -/

/-- **TCP03–TCP06 at every register V4 of a strategy below the circle rows strategy** (the
obstruction of register V2 removed): with `C_ge`, for every register `R` at `T`, every
`εr < ε₀`, `20Λz ≤ T₀` and every final family at `R`'s values, the conclusions of TCP03 (zero
block) and TCP04 at `θ₂`, TCP05 at `e₀` and TCP06 at `(Γ₀, Σ₀, e₀)`, all at the exclusion quality
`ν = β₃/3`. -/
theorem circleRowOuts_of_below_VAL6 {D : ClosedEarlyData} (hC : ∀ j, gafGraphConst j ≤ D.C j)
    {T : ClosedThresholdsV4 D} (hTU : ClosedStrategyBelowV4 T (circleRowsStrategyV4 D))
    (R : ClosedRegisterV4 D T) {K : ℕ} {X : Type} [MetricSpace X] [ChartedSpace E3 X]
    [IsManifold 𝓘(ℝ, E3) ∞ X] [CompactSpace X] {g : SmoothRiemannianMetric 𝓘(ℝ, E3) X}
    {hmetric : ∀ a b : X, riemannianEDistOf g a b = ENNReal.ofReal (dist a b)}
    {ρ : X → ℝ} {hρ : ∀ p, 0 < ρ p} {δ εr Λz : ℝ} (hεr : εr < R.later.err.co.ε₀)
    (hΛz : 20 * Λz ≤ R.later.split.T₀)
    (P : LocalChartPacketsC14 X g hmetric ρ hρ R.later.scale.Λ R.β R.later.excl.Δ
      R.later.err.co.qs K R.later.err.co.qe R.later.err.bd.μ R.later.split.b R.later.err.s
      R.later.err.wk.b' R.later.err.wk.s' R.later.err.co.ε R.later.circle.γc R.later.circle.βc
      R.later.Lmax R.later.err.bd.τ R.later.circle.γ δ εr R.later.err.co.e₀ R.later.split.T₀
      R.later.split.V R.later.err.co.ve R.later.err.co.ζ Λz) :
    Tcp03ZeroOutV2 P.toLocalChartPacketsZ R.later.circle.θ₂ ∧
    Tcp04OutV2 P.toLocalChartPackets R.later.circle.θ₂ ∧
    Tcp05OutV2 P (R.stage.e 0) ∧
    Tcp06OutV2 P (R.stage.Γ 0) (R.stage.Sig 0) (R.stage.e 0) := by
  -- the register's ranges
  have hΔ0 : 0 < R.later.excl.Δ := R.later.Δ_pos_VAL6
  have hΔ1 : 1 ≤ R.later.excl.Δ :=
    ((by norm_num : (1 : ℝ) < 100).trans R.later.hundred_lt_Δ_VAL6).le
  have hΔ12 : 1200 ≤ R.later.excl.Δ := R.later.twelve_hundred_le_Δ_VAL6
  have hβ₃0 := R.later.β₃_pos
  have hβ₃ : R.later.excl.β₃ < 1 / 2 := R.later.β₃_lt.trans_le hTU.lc18_le
  have hΛ0 : 0 ≤ R.later.scale.Λ := R.later.Λ_pos.le
  have hLΛ : 1000000 * R.later.excl.Δ * R.later.scale.Λ < 1 / 100000 := by
    have h := R.later.regScale_L
    unfold closedLongLength at h
    linarith
  have hT1600 : 1600 * (1000000 * R.later.excl.Δ) ≤ R.later.split.T₀ := by
    have h := (le_max_left _ _).trans R.later.T₀_ge
    unfold closedLongLength at h
    linarith
  have he40 : R.later.err.co.e₀ < 1 / 40 := R.later.e₀_lt_VAL6
  have hμ : R.later.err.bd.μ ≤ 1 / 100 := (R.later.μ_lt_VAL6.trans (by norm_num)).le
  have hτ : R.later.err.bd.τ ≤ 1 / 100 := (R.later.τ_lt_VAL6.trans (by norm_num)).le
  have hσs0 := R.later.qs_pos
  have hζ0 := R.later.ζ_pos
  have hqe0 := R.later.qe_pos
  have hε0 := R.later.ε_pos
  have hγc0 := R.later.γc_pos
  have hrange0 := R.stage.tcp06_range_VAL3 hC
  have hθ₂0 := R.later.θ₂_pos
  have hθ₂1 : R.later.circle.θ₂ < 1 := by
    have h := R.later.θ₂_lt
    have hC0 : 1 ≤ D.C 0 := one_le_tcpGraphConst.trans (hC 0)
    have he0 : R.stage.e 0 < 1 / 100 := hrange0.2.2.2.2.2.2.1
    have hD : 100 ≤ 100 * D.C 0 ^ 2 := by nlinarith
    calc R.later.circle.θ₂ < R.stage.e 0 / (100 * D.C 0 ^ 2) := h
      _ < 1 := by rw [div_lt_one (by linarith)]; linarith
  have hν0 : 0 < R.later.excl.β₃ / 3 := by positivity
  have hν1 : R.later.excl.β₃ / 3 < 1 := by linarith only [hβ₃]
  have hν3 : 3 * (R.later.excl.β₃ / 3) ≤ R.β 3 := by
    rw [R.β_three_VAL6]
    linarith only []
  have hβ3 : R.β 3 < 1 := by
    rw [R.β_three_VAL6]
    linarith only [hβ₃]
  have hscale := R.tcp_scale_budget_VAL6 hC
  -- the strategy's slots at the register
  have hγU := (R.later.γ_lt.trans_le (min_le_right _ _)).trans_le (hTU.circleUp_le _ _ _ _ _)
  have hγcU := R.later.γc_lt.trans_le (hTU.circleUp_le _ _ _ _ _)
  have hβcU := R.later.βc_lt_circleUp_VAL6.trans_le (hTU.circleUp_le _ _ _ _ _)
  simp only [circleRowsStrategyV4, lt_min_iff] at hγU hγcU hβcU
  obtain ⟨hγ3, hγ4, -, hγ5, -, hγ6, -⟩ := hγU
  obtain ⟨-, hγc4, -, hγc5, -, hγc6, -⟩ := hγcU
  obtain ⟨-, -, hβc4, -, hβc5, -, hβc6⟩ := hβcU
  have hβ₂U := (R.later.β₂_lt.trans_le (min_le_left _ _)).trans_le (hTU.β₂Up_le _ _ _)
  simp only [circleRowsStrategyV4, ClosedCircleRequestsV2.toPrefixV4, lt_min_iff] at hβ₂U
  obtain ⟨hσ3, hη3, hσ4, hη4, hσ5, hη5, hσ6, hη6⟩ := hβ₂U
  have hζU := R.later.ζ_lt.trans_le (hTU.errorsUp_le _ _ _)
  have hqsU := (R.later.qs_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hqeU := (R.later.qe_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hveU := (R.later.ve_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hε₀U := (R.later.ε₀_lt.trans_le (min_le_right _ _)).trans_le (hTU.errorsUp_le _ _ _)
  have hεU := R.later.ε_lt.trans_le (hTU.errorsUp_le _ _ _)
  simp only [circleRowsStrategyV4, lt_min_iff] at hζU hqsU hqeU hveU hε₀U hεU
  obtain ⟨hζ3, -, hζ5, -, hζ6, -, -⟩ := hζU
  obtain ⟨-, -, hqs5, -, hqs6, -, -⟩ := hqsU
  obtain ⟨-, -, hqe5, -, hqe6, -, -⟩ := hqeU
  obtain ⟨-, -, -, hve5, -, hve6, -⟩ := hveU
  obtain ⟨-, hε₀3, -, hε₀5, -, hε₀6, -⟩ := hε₀U
  obtain ⟨-, -, -, -, -, -, hε1⟩ := hεU
  have hμU := (R.later.μ_lt.trans_le (min_le_right _ _)).trans_le (hTU.sectionUp_le _ _ _ _)
  simp only [circleRowsStrategyV4, lt_min_iff] at hμU
  obtain ⟨hμ5, hμ6⟩ := hμU
  have hbU := (R.later.b_lt.trans_le (min_le_left _ _)).trans_le (hTU.splitUp_le _ _ _ _ _)
  simp only [circleRowsStrategyV4, lt_min_iff] at hbU
  obtain ⟨hb5, hb6⟩ := hbU
  have hβ₁U := (R.later.β₁_lt.trans_le (min_le_left _ _)).trans_le (hTU.β₁Up_le _ _ _ _ _ _)
  simp only [circleRowsStrategyV4, lt_min_iff] at hβ₁U
  obtain ⟨h1η3, h1η5, h1η6⟩ := hβ₁U
  have hLU := (hTU.LmaxLow_ge _ _ _ _ _ _).trans_lt ((le_max_right _ _).trans_lt R.later.Lmax_gt)
  simp only [circleRowsStrategyV4, max_lt_iff] at hLU
  obtain ⟨hL4, hLσ3, hLσ4, hLσ5, hLσ6⟩ := hLU
  have hp : ∀ {x y : ℝ}, 0 < y → x < posOr_VAL3 y → x < y := fun hy h =>
    h.trans_eq (posOr_eq_VAL3 hy)
  refine ⟨?_, ?_, ?_, ?_⟩
  · -- TCP03 (zero block) at `θ₂`, `ν = β₃/3`
    have hc : 0 < R.later.circle.θ₂ ∧ R.later.circle.θ₂ < 1 ∧ 0 < R.later.excl.β₃ / 3 ∧
        R.later.excl.β₃ / 3 < 1 := ⟨hθ₂0, hθ₂1, hν0, hν1⟩
    obtain ⟨sσ, -, s2⟩ :=
      Classical.choose_spec (tcp03_zero_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2)
    have s3 := Classical.choose_spec s2
    have s4 := Classical.choose_spec s3.2
    have s5 := Classical.choose_spec s4.2
    have hσ : 3 * R.later.excl.β₂ <
        Classical.choose (tcp03_zero_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2) :=
      lt_of_lt_posOr_dite_VAL4 hc sσ ((lt_div_iff₀' three_pos).mp hσ3)
    have hθ2 : 0 < R.later.circle.θ₂ ^ 2 / 1000 := by positivity
    exact s5.2 P.toLocalChartPacketsZ hΛ0 hΔ1 hLΛ he40 hT1600 hν3 hβ3 (R.β_two_VAL6 ▸ hσ.le)
      (R.β_two_VAL6 ▸ (lt_of_lt_posOr_dite_VAL4 hc s3.1 hη3).le)
      (lt_of_lt_posOr_dite_VAL4 hc s4.1 hγ3).le
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc s5.1 h1η3).le) hζ0
      (hp hθ2 hζ3).le (hεr.trans (hp (by positivity) hε₀3)).le hΛz
      (inv_le_of_dite_le_VAL4 hc hLσ3.le)
  · -- TCP04 at `θ₂`, `ν = β₃/3`
    have hc : 0 < R.later.circle.θ₂ ∧ R.later.circle.θ₂ < 1 ∧ 0 < R.later.excl.β₃ / 3 ∧
        R.later.excl.β₃ / 3 < 1 := ⟨hθ₂0, hθ₂1, hν0, hν1⟩
    obtain ⟨sσ, -, s2⟩ := Classical.choose_spec (tcp04_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2)
    have s3 := Classical.choose_spec s2
    have s4 := Classical.choose_spec s3.2
    have s5 := Classical.choose_spec s4.2
    have hσ : 3 * R.later.excl.β₂ <
        Classical.choose (tcp04_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2) :=
      lt_of_lt_posOr_dite_VAL4 hc sσ ((lt_div_iff₀' three_pos).mp hσ4)
    exact s5.2 P.toLocalChartPackets hΛ0 hΔ12 hμ hτ hLΛ hL4.le he40 hT1600 hε0.le hε1.le hqe0.le
      R.later.qe_lt_one_VAL6.le hν3 hβ3 (R.β_two_VAL6 ▸ hσ.le)
      (R.β_two_VAL6 ▸ (lt_of_lt_posOr_dite_VAL4 hc s3.1 hη4).le)
      (lt_of_lt_posOr_dite_VAL4 hc s4.1 hγ4).le hγc0 (lt_of_lt_posOr_dite_VAL4 hc s4.1 hγc4).le
      (lt_of_lt_posOr_dite_VAL4 hc s5.1 hβc4).le (inv_le_of_dite_le_VAL4 hc hLσ4.le)
  · -- TCP05 at `e₀`, `ν = β₃/3`
    have hc : 0 < R.stage.e 0 ∧ R.stage.e 0 < 1 / 100 ∧ 0 < R.later.excl.β₃ / 3 ∧
        R.later.excl.β₃ / 3 < 1 := ⟨hrange0.2.2.2.2.2.1, hrange0.2.2.2.2.2.2.1, hν0, hν1⟩
    have A := Classical.choose_spec (tcp05_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2)
    have B := Classical.choose_spec A.2.2
    have C := Classical.choose_spec B
    have E4 := Classical.choose_spec C
    obtain ⟨sη, sγ, sηc, sθ, -, s7⟩ := Classical.choose_spec E4
    have hc1 : 0 < R.stage.e 0 ∧ R.stage.e 0 < 1 / 100 ∧ 0 < R.later.excl.β₃ / 3 ∧
        R.later.excl.β₃ / 3 < 1 ∧ 1200 ≤ R.later.excl.Δ := ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2, hΔ12⟩
    have F := Classical.choose_spec (s7 _ hΔ12)
    have e : tcp05θ_VAL6 (R.stage.e 0) (R.later.excl.β₃ / 3) = Classical.choose E4 :=
      dite_eq_left hc
    rw [e] at hζ5 hqs5 hqe5 hve5 hε₀5 hμ5
    have hσ : 3 * R.later.excl.β₂ <
        Classical.choose (tcp05_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2) :=
      lt_of_lt_posOr_dite_VAL4 hc A.1 ((lt_div_iff₀' three_pos).mp hσ5)
    have hθ2 : 0 < Classical.choose E4 ^ 2 / 1000 := by positivity
    have hθ1 : 0 < Classical.choose E4 / 100 := by positivity
    exact F.2 P hΛ0 hμ hτ hLΛ hL4.le he40 hT1600 hε0.le hε1.le hqe0.le (hp hθ2 hqe5).le
      ((lt_div_iff₀ hΔ0).mp (hp (by positivity) hμ5)).le hν3 hβ3 (R.β_two_VAL6 ▸ hσ.le)
      (R.β_two_VAL6 ▸ (lt_of_lt_posOr_dite_VAL4 hc sη hη5).le)
      (lt_of_lt_posOr_dite_VAL4 hc sγ hγ5).le hγc0 (lt_of_lt_posOr_dite_VAL4 hc sγ hγc5).le
      (lt_of_lt_posOr_dite_VAL4 hc sηc hβc5).le (lt_of_lt_posOr_dite_VAL4 hc1 F.1 hb5).le
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc1 F.1 h1η5).le) hσs0 (hp hθ2 hqs5).le
      (hp hθ1 hve5).le hζ0 (hp hθ2 hζ5).le (hεr.trans (hp hθ1 hε₀5)).le hΛz
      (inv_le_of_dite_le_VAL4 hc hLσ5.le) hscale
  · -- TCP06 at `(Γ₀, Σ₀, e₀)`, `ν = β₃/3`
    obtain ⟨r1, r2, r3, r4, r5, r6, r7, r8⟩ := hrange0
    have hc : 0 < R.stage.Γ 0 ∧ R.stage.Γ 0 < 1 ∧ 0 < R.stage.Sig 0 ∧
        R.stage.Sig 0 < R.stage.Γ 0 / 200 ∧
        R.stage.Sig 0 < R.stage.Γ 0 ^ 3 / (100 * tcpGraphConst) ∧ 0 < R.stage.e 0 ∧
        R.stage.e 0 < 1 / 100 ∧ R.stage.e 0 < R.stage.Γ 0 * R.stage.Sig 0 / 100 ∧
        0 < R.later.excl.β₃ / 3 ∧ R.later.excl.β₃ / 3 < 1 :=
      ⟨r1, r2, r3, r4, r5, r6, r7, r8, hν0, hν1⟩
    have A := Classical.choose_spec (tcp06_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1
      hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.1
      hc.2.2.2.2.2.2.2.2.2)
    have B := Classical.choose_spec A.2.2
    have C := Classical.choose_spec B
    have E4 := Classical.choose_spec C
    obtain ⟨sη, sγ, sηc, sθ, -, s7⟩ := Classical.choose_spec E4
    have hc1 : 0 < R.stage.Γ 0 ∧ R.stage.Γ 0 < 1 ∧ 0 < R.stage.Sig 0 ∧
        R.stage.Sig 0 < R.stage.Γ 0 / 200 ∧
        R.stage.Sig 0 < R.stage.Γ 0 ^ 3 / (100 * tcpGraphConst) ∧ 0 < R.stage.e 0 ∧
        R.stage.e 0 < 1 / 100 ∧ R.stage.e 0 < R.stage.Γ 0 * R.stage.Sig 0 / 100 ∧
        0 < R.later.excl.β₃ / 3 ∧ R.later.excl.β₃ / 3 < 1 ∧ 1200 ≤ R.later.excl.Δ :=
      ⟨r1, r2, r3, r4, r5, r6, r7, r8, hν0, hν1, hΔ12⟩
    have F := Classical.choose_spec (s7 _ hΔ12)
    have e : tcp06θ_VAL6 (R.stage.Γ 0) (R.stage.Sig 0) (R.stage.e 0) (R.later.excl.β₃ / 3) =
        Classical.choose E4 := dite_eq_left hc
    rw [e] at hζ6 hqs6 hqe6 hve6 hε₀6 hμ6
    have hσ : 3 * R.later.excl.β₂ < Classical.choose (tcp06_row_out_VAL3 hc.1 hc.2.1 hc.2.2.1
        hc.2.2.2.1 hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.1
        hc.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2) :=
      lt_of_lt_posOr_dite_VAL4 hc A.1 ((lt_div_iff₀' three_pos).mp hσ6)
    have hθ2 : 0 < Classical.choose E4 ^ 2 / 1000 := by positivity
    have hθ1 : 0 < Classical.choose E4 / 100 := by positivity
    exact F.2 P hΛ0 hμ hτ hLΛ hL4.le he40 hT1600 hε0.le hε1.le hqe0.le (hp hθ2 hqe6).le
      ((lt_div_iff₀ hΔ0).mp (hp (by positivity) hμ6)).le hν3 hβ3 (R.β_two_VAL6 ▸ hσ.le)
      (R.β_two_VAL6 ▸ (lt_of_lt_posOr_dite_VAL4 hc sη hη6).le)
      (lt_of_lt_posOr_dite_VAL4 hc sγ hγ6).le hγc0 (lt_of_lt_posOr_dite_VAL4 hc sγ hγc6).le
      (lt_of_lt_posOr_dite_VAL4 hc sηc hβc6).le (lt_of_lt_posOr_dite_VAL4 hc1 F.1 hb6).le
      (R.β_one_VAL6.trans_le (lt_of_lt_posOr_dite_VAL4 hc1 F.1 h1η6).le) hσs0 (hp hθ2 hqs6).le
      (hp hθ1 hve6).le hζ0 (hp hθ2 hζ6).le (hεr.trans (hp hθ1 hε₀6)).le hΛz
      (inv_le_of_dite_le_VAL4 hc hLσ6.le) hscale

end DifferentialGeometry.Geometry.Collapse
