import DifferentialGeometry.Geometry.Collapse.StaticRegisterV4Applications
import DifferentialGeometry.Geometry.Collapse.StaticRegisterV2Provenance
import DifferentialGeometry.Geometry.Fibration.ActualStageMeanShared
import DifferentialGeometry.Geometry.Fibration.ActualStageCloudBudgetInterior

/-!
# Early data of register V4 on the ONE shared stage modulus; `N_b`, `c_w` (lane FC39-VAL6)

Register-V4 file (lane FC39-VAL6), generated by `build-logs/scratch/FC39-VAL6/gen_v4.py`
from FC39-VAL5's `StaticRegisterV3Provenance.lean` with register V3 → V4 (`βc` chosen right
after `β₂`, `β₂Up` reads the circle prefix `ClosedCirclePrefixV4` without `βc`; see
`StaticRegisterV4.lean`). It imports no register-V3 module.

PR01–PR03 and PR10 (B:10094–10121) for register V4 (`StaticRegisterV4.lean`). The early constants
are those of `closedEarlyDataV3` (constant provenance, lane FC39-VAL3: `N = gafMultiplicity`,
`P = max{1, P_cgp, P_sgp, P_zero}`, `C = gafGraphConst`, `L₀ = max{1, L_gaf}`); the stage moduli
`Ξ_j` are now bound to the ONE modulus shared with GAF02, `cfs15_shared_modulus_GAFS4 (k_j) K`
(lane C14-GAFS4: CFS15's jet-order-`K` conclusion, CFS12's interior condition, EDP01's mean clause
for the same `Ξ`), below its threshold and `1` above it.

* `earlyDataSharedV4 K`; `earlyDataSharedV4_fields_VAL6`: the early fields of the validity
  record (`N_ge`, `P_ge`, `P_ge_sgp`, `P_ge_zero`, `L₀_ge`, `Ξ_cfs15`, `Ξ_range`, `C_ge`).
* `earlyDataSharedV4_stage_mean_VAL6`: at every stage value `Γ_j`, the interior condition at the
  buffer `Ξ_j(Γ_j)⁻¹` and the mean clause, verbatim, at `ε = Ξ_j(Γ_j)`.
* PR10 at the first stage (B:10108–10113, B:10397 "derive `N_b, c_w, C_ρ` as in PR10 from this first
  …"): the buffer `b_st = Ξ_0(Γ_0)⁻¹ ≥ 1`, `N_b = ⌈(1 + 2·(5/3)·165·b_st)^{k_0}⌉` and
  `c_w = c_w(0, b_st)` with `c_w` the weight function of `nb_cw_stage_selection_GAFS3`.
* Inhabitant: a threshold record of register V4 on `earlyDataSharedV4 K` with these `N_b, c_w`
  slots, and one register at it.
-/

set_option autoImplicit false

noncomputable section

open Set Function Metric Filter
open scoped ContDiff Manifold Topology
open GC.MetricGeometry DifferentialGeometry.Analysis

namespace DifferentialGeometry.Geometry.Collapse

/-! ### The shared modulus as a function -/

/-- The threshold `θ₁` of the shared stage modulus at `(k, K)`. -/
def sharedRange_VAL6 (k K : ℕ) : ℝ := Classical.choose (cfs15_shared_modulus_GAFS4 k K)

/-- The shared stage modulus `Ξ` at `(k, K)` (lane C14-GAFS4). -/
def sharedModulus_VAL6 (k K : ℕ) : ℝ → ℝ :=
  Classical.choose (Classical.choose_spec (cfs15_shared_modulus_GAFS4 k K)).2

theorem sharedRange_pos_VAL6 (k K : ℕ) : 0 < sharedRange_VAL6 k K :=
  (Classical.choose_spec (cfs15_shared_modulus_GAFS4 k K)).1

theorem sharedModulus_tendsto_VAL6 (k K : ℕ) :
    Tendsto (sharedModulus_VAL6 k K) (𝓝[>] 0) (𝓝 0) :=
  (Classical.choose_spec (Classical.choose_spec (cfs15_shared_modulus_GAFS4 k K)).2).1

/-- On its range the shared modulus is dyadic, carries CFS15's jet-order-`K` conclusion and CFS12's
interior condition. -/
theorem sharedModulus_on_range_VAL6 (k K : ℕ) {Γ : ℝ} (hΓ : 0 < Γ)
    (hΓ1 : Γ < sharedRange_VAL6 k K) :
    (∃ m : ℕ, sharedModulus_VAL6 k K Γ = (1 / 2 : ℝ) ^ (m + 4)) ∧
      Cfs15ModulusAtV2 k K (5 / 3) (sharedModulus_VAL6 k K) Γ ∧
      Γ * ((80 * (5 / 3) + 31) * (sharedModulus_VAL6 k K Γ)⁻¹ + 2) < 1 :=
  let h := (Classical.choose_spec (Classical.choose_spec
    (cfs15_shared_modulus_GAFS4 k K)).2).2 Γ hΓ hΓ1
  ⟨h.1, h.2.1, h.2.2.1⟩

/-! ### The early data -/

/-- The register's modulus `Ξ_j`: the shared modulus below its threshold, `1` above it. -/
def modulusSharedV4 (K : ℕ) (j : Fin 3) (Γ : ℝ) : ℝ :=
  if Γ < sharedRange_VAL6 (gafStageDim j) K then sharedModulus_VAL6 (gafStageDim j) K Γ else 1

theorem modulusSharedV4_atV2_VAL6 (K : ℕ) (j : Fin 3) {Γ : ℝ} (hΓ : 0 < Γ)
    (hΓ1 : Γ < sharedRange_VAL6 (gafStageDim j) K) :
    Cfs15ModulusAtV2 (gafStageDim j) K (5 / 3) (modulusSharedV4 K j) Γ :=
  cfs15ModulusAtV2_congr_VAL3 (by simp only [modulusSharedV4, hΓ1, ↓reduceIte])
    (sharedModulus_on_range_VAL6 _ K hΓ hΓ1).2.1

theorem modulusSharedV4_pos_VAL6 (K : ℕ) (j : Fin 3) {Γ : ℝ} (hΓ : 0 < Γ) :
    0 < modulusSharedV4 K j Γ := by
  by_cases h : Γ < sharedRange_VAL6 (gafStageDim j) K
  · obtain ⟨m, hm⟩ := (sharedModulus_on_range_VAL6 _ K hΓ h).1
    simp only [modulusSharedV4, h, ↓reduceIte, hm]
    positivity
  · simp only [modulusSharedV4, h, ↓reduceIte]
    exact one_pos

theorem modulusSharedV4_tendsto_VAL6 (K : ℕ) (j : Fin 3) :
    Tendsto (modulusSharedV4 K j) (𝓝[>] 0) (𝓝 0) := by
  refine (sharedModulus_tendsto_VAL6 (gafStageDim j) K).congr' ?_
  filter_upwards [nhdsWithin_le_nhds (Iio_mem_nhds (sharedRange_pos_VAL6 (gafStageDim j) K))]
    with Γ hΓ
  have hΓ' : Γ < sharedRange_VAL6 (gafStageDim j) K := hΓ
  simp only [modulusSharedV4, hΓ', ↓reduceIte]

/-- **The early data of register V4** (PR01–PR03): the constants of the native rows and the stage
moduli of the ONE shared modulus. -/
def earlyDataSharedV4 (K : ℕ) : ClosedEarlyData where
  N := gafMultiplicity
  P := max 1 (max cgpProfileBound (max sgpProfileBound zeroProfileBound))
  one_le_P := le_max_left _ _
  C := gafGraphConst
  C_pos := gafGraphConst_pos_VAL3
  L₀ := max 1 gafDerivativeBound
  one_le_L₀ := le_max_left _ _
  Ξ := modulusSharedV4 K
  Ξ_pos := fun j _ hΓ => modulusSharedV4_pos_VAL6 K j hΓ
  Ξ_tendsto := modulusSharedV4_tendsto_VAL6 K

/-- Every admissible stage value `Γ_j` of `earlyDataSharedV4 K` lies below the shared
modulus's threshold. -/
theorem ClosedStage.Γ_lt_sharedRange_VAL6 {K : ℕ} (st : ClosedStage (earlyDataSharedV4 K))
    (j : Fin 3) : st.Γ j < sharedRange_VAL6 (gafStageDim j) K := by
  by_contra h
  have hlt := st.Ξ_lt j
  have hb : closedAccuracyBound (earlyDataSharedV4 K) (st.c j) ≤ 1 / 10 := min_le_left _ _
  have h1 : (earlyDataSharedV4 K).Ξ j (st.Γ j) = 1 := by
    change modulusSharedV4 K j (st.Γ j) = 1
    simp only [modulusSharedV4, h, ↓reduceIte]
  rw [h1] at hlt
  linarith

/-- At every stage value the register's `Ξ_j` IS the shared modulus. -/
theorem earlyDataSharedV4_Ξ_eq_VAL6 {K : ℕ} (st : ClosedStage (earlyDataSharedV4 K))
    (j : Fin 3) :
    (earlyDataSharedV4 K).Ξ j (st.Γ j) = sharedModulus_VAL6 (gafStageDim j) K (st.Γ j) := by
  change modulusSharedV4 K j (st.Γ j) = _
  simp only [modulusSharedV4, st.Γ_lt_sharedRange_VAL6 j, ↓reduceIte]

/-- **The early fields hold for the shared data**: `N_ge`, `P_ge`, `P_ge_sgp`, `P_ge_zero`,
`L₀_ge`, `Ξ_cfs15`, `Ξ_range` (every actual `Γ_j` in the shared modulus's range) and `C_ge`. -/
theorem earlyDataSharedV4_fields_VAL6 (K : ℕ) :
    gafMultiplicity ≤ (earlyDataSharedV4 K).N ∧ cgpProfileBound ≤ (earlyDataSharedV4 K).P ∧
      sgpProfileBound ≤ (earlyDataSharedV4 K).P ∧
      zeroProfileBound ≤ (earlyDataSharedV4 K).P ∧
      gafDerivativeBound ≤ (earlyDataSharedV4 K).L₀ ∧
      (∀ j, Cfs15ModulusOut (gafStageDim j) K (5 / 3) ((earlyDataSharedV4 K).Ξ j)) ∧
      (∀ (st : ClosedStage (earlyDataSharedV4 K)) j,
        Cfs15ModulusAtV2 (gafStageDim j) K (5 / 3) ((earlyDataSharedV4 K).Ξ j) (st.Γ j)) ∧
      ∀ j, gafGraphConst j ≤ (earlyDataSharedV4 K).C j := by
  refine ⟨le_rfl, (le_max_left _ _).trans (le_max_right _ _),
    ((le_max_left _ _).trans (le_max_right _ _)).trans (le_max_right _ _),
    ((le_max_right _ _).trans (le_max_right _ _)).trans (le_max_right _ _), le_max_right _ _,
    fun j => ?_, fun st j => modulusSharedV4_atV2_VAL6 K j (st.Γ_pos j)
      (st.Γ_lt_sharedRange_VAL6 j), fun j => le_rfl⟩
  exact ⟨_, sharedRange_pos_VAL6 (gafStageDim j) K, modulusSharedV4_tendsto_VAL6 K j,
    fun Γ hΓ hΓ1 => modulusSharedV4_atV2_VAL6 K j hΓ hΓ1⟩

/-- **The stage accuracies of `earlyDataSharedV4 K` carry the shared modulus's conclusions**:
at every stage and every index `j`, CFS12's interior condition at the buffer `Ξ_j(Γ_j)⁻¹` and
    EDP01's
mean clause of `cfs15_shared_modulus_GAFS4` (verbatim, at `ε = Ξ_j(Γ_j)`, `Γ = Γ_j`, `k = k_j`): the
SAME modulus that fills `Ξ_cfs15`/`Ξ_range` drives GAF02's stage maps. -/
theorem earlyDataSharedV4_stage_mean_VAL6 {K : ℕ} (st : ClosedStage (earlyDataSharedV4 K))
    (j : Fin 3) :
    st.Γ j * ((80 * (5 / 3) + 31) * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ + 2) < 1 ∧
    ∃ cw : ℝ, 0 ≤ cw ∧
    ∀ (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [FiniteDimensional ℝ H]
      (S T : Set H), S ⊆ T → TotallyBounded S →
      ∀ (r : H → ℝ) (P : H → Submodule ℝ H),
      (∀ x ∈ S, Module.finrank ℝ (P x) = gafStageDim j) →
      ∀ rmin R : ℝ, 0 < rmin → (∀ x ∈ S, rmin ≤ r x) → (∀ x ∈ S, r x ≤ R) →
      (∀ x ∈ T, ∀ y ∈ T, dist y x ≤ 128 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * max (r y)
          (r x) →
        r x / (5 / 3) ≤ r y ∧ r y ≤ (5 / 3) * r x) →
      (∀ x ∈ S, hausdorffEDist (T ∩ ball x (r x / st.Γ j))
        ((AffineSubspace.mk' x (P x) : Set H) ∩ ball x (r x / st.Γ j)) ≤
          ENNReal.ofReal (st.Γ j * r x)) →
      ∃ a : H → H, ContDiffOn ℝ ∞ a (⋃ x ∈ S, ball x (r x)) ∧
        ∀ x ∈ S, ∀ z ∈ ball x (r x),
          ‖a z - (x + (P x).starProjection (z - x))‖ ≤ ((earlyDataSharedV4 K).Ξ j (st.Γ j)) *
              r x ∧
          DifferentiableAt ℝ a z ∧
          ‖fderiv ℝ a z - (P x).starProjection‖ ≤ ((earlyDataSharedV4 K).Ξ j (st.Γ j)) ∧
          (∀ (Kk : Submodule ℝ H) (c : H),
            (∀ i ∈ S, (closedBall i (80 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r i) ∩
                ball x (8 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r x)).Nonempty →
              Kk.starProjection i = c ∧ P i ≤ Kkᗮ) →
            Kk.starProjection (a z) = c) ∧
          ∀ ℓ : H →L[ℝ] ℝ,
            (∀ i ∈ S, (closedBall i (80 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r i) ∩
                ball x (8 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r x)).Nonempty →
              P i ≤ LinearMap.ker (ℓ : H →ₗ[ℝ] ℝ)) →
            ∀ R₀ β : ℝ,
            (∀ i ∈ S, (closedBall i (80 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r i) ∩
                ball x (8 * ((earlyDataSharedV4 K).Ξ j (st.Γ j))⁻¹ * r x)).Nonempty → |ℓ i -
                    R₀| ≤ β) →
            |ℓ (a z) - R₀| ≤ β ∧ ‖ℓ.comp (fderiv ℝ a z)‖ ≤ 2 * cw * β / r x := by
  have h := (Classical.choose_spec (Classical.choose_spec
    (cfs15_shared_modulus_GAFS4 (gafStageDim j) K)).2).2 (st.Γ j) (st.Γ_pos j)
    (st.Γ_lt_sharedRange_VAL6 j)
  rw [earlyDataSharedV4_Ξ_eq_VAL6 st j]
  exact h.2.2

/-! ### PR10 at the first stage: the buffer, `N_b`, `c_w` -/

/-- The first stage's buffer `b_st = Ξ_0(Γ_0)⁻¹` (B:10108–10113). -/
def stageBuffer_VAL6 {D : ClosedEarlyData} (st : ClosedStage D) : ℝ := (D.Ξ 0 (st.Γ 0))⁻¹

theorem ClosedStage.one_le_stageBuffer_VAL6 {D : ClosedEarlyData} (st : ClosedStage D) :
    1 ≤ stageBuffer_VAL6 st := by
  have hpos := D.Ξ_pos 0 (st.Γ 0) (st.Γ_pos 0)
  have hlt : D.Ξ 0 (st.Γ 0) < 1 / 10 := (st.Ξ_lt 0).trans_le (min_le_left _ _)
  exact one_le_inv₀ hpos |>.mpr (by linarith)

/-- PR10's `N_b` at the first stage: `⌈(1 + 2·(5/3)·165·b_st)^{k_0}⌉` (CFS11's multiplicity on the
stage cloud, `nb_cw_stage_selection_GAFS3`). -/
def sharedNb_VAL6 {D : ClosedEarlyData} (st : ClosedStage D) : ℝ :=
  (⌈(1 + 2 * (5 / 3) * 165 * stageBuffer_VAL6 st) ^ gafStageDim 0⌉₊ : ℝ)

/-- PR10's `c_w` at the first stage: the weight function of `nb_cw_stage_selection_GAFS3` at
`(0, b_st)`. -/
def sharedCw_VAL6 {D : ClosedEarlyData} (st : ClosedStage D) : ℝ :=
  Classical.choose nb_cw_stage_selection_GAFS3 0 (stageBuffer_VAL6 st)

theorem sharedCw_nonneg_VAL6 {D : ClosedEarlyData} (st : ClosedStage D) :
    0 ≤ sharedCw_VAL6 st :=
  (Classical.choose_spec nb_cw_stage_selection_GAFS3 0 (stageBuffer_VAL6 st)
    st.one_le_stageBuffer_VAL6).1

/-- On `earlyDataSharedV4 K` the first stage meets CFS12's interior condition at its buffer
(the hypothesis of `nb_cw_stage_selection_GAFS3` at `Γ = Γ_0`, `bb = b_st`). -/
theorem ClosedStage.interior_stageBuffer_VAL6 {K : ℕ} (st : ClosedStage (earlyDataSharedV4 K)) :
    st.Γ 0 * ((80 * (5 / 3) + 31) * stageBuffer_VAL6 st + 2) < 1 :=
  (earlyDataSharedV4_stage_mean_VAL6 st 0).1

/-! ### Inhabitant of register V4 at the shared early data -/

/-- A threshold record of register V4 on `earlyDataSharedV4 K`: PR10's `N_b, c_w` at the first
stage, every other upper slot `1`, LPA02 output `V = T₀`, every lower slot `0`, `H_α = α`. -/
def sharedClosedThresholdsV4 (K : ℕ) : ClosedThresholdsV4 (earlyDataSharedV4 K) where
  Nb := sharedNb_VAL6
  Nb_nonneg := fun _ => Nat.cast_nonneg _
  cw := sharedCw_VAL6
  cw_nonneg := sharedCw_nonneg_VAL6
  lc18 := 1
  lc18_pos := one_pos
  circleUp := fun _ _ _ _ _ => 1
  circleUp_pos := fun _ _ _ _ _ => one_pos
  β₂Up := fun _ _ _ => 1
  β₂Up_pos := fun _ _ _ => one_pos
  ΔLow := fun _ _ _ _ => 0
  errorsUp := fun _ _ _ => 1
  errorsUp_pos := fun _ _ _ => one_pos
  sectionUp := fun _ _ _ _ => 1
  sectionUp_pos := fun _ _ _ _ => one_pos
  lfr29W := fun _ _ _ _ _ => 1
  lfr29W_pos := fun _ _ _ _ _ => one_pos
  endpointUp := fun _ _ _ _ _ _ => 1
  endpointUp_pos := fun _ _ _ _ _ _ => one_pos
  σcolUp := fun _ _ _ _ _ _ _ => 1
  σcolUp_pos := fun _ _ _ _ _ _ _ => one_pos
  I₁ := 1
  I₁_pos := one_pos
  scaleUp := fun _ _ _ _ => 1
  scaleUp_pos := fun _ _ _ _ => one_pos
  wUp := fun _ _ _ _ _ => 1
  wUp_pos := fun _ _ _ _ _ => one_pos
  splitUp := fun _ _ _ _ _ => 1
  splitUp_pos := fun _ _ _ _ _ => one_pos
  β₁Up := fun _ _ _ _ _ _ => 1
  β₁Up_pos := fun _ _ _ _ _ _ => one_pos
  T₀Low := fun _ _ _ _ _ _ _ => 0
  lpa02V := fun _ _ _ _ _ _ _ T₀ => T₀
  T₀_le_lpa02V := fun _ _ _ _ _ _ _ _ => le_rfl
  LmaxLow := fun _ _ _ _ _ _ => 0
  tailLow := fun _ _ _ _ _ _ _ => 0
  H := fun α => (α : ℝ)
  H_tendsto := tendsto_natCast_atTop_atTop

/-- **Consumer (inhabitant at the shared data)**: a register V4 exists on `earlyDataSharedV4 K`;
at it the first stage's `Γ_0` lies in the shared modulus's range with CFS15's jet-order-`K`
conclusion, its buffer `b ≥ 1` meets CFS12's interior condition, and the `N_b`, `c_w` slots are
PR10's values at `b`. -/
theorem shared_closedRegisterV4_facts_VAL6 (K : ℕ) :
    ∃ R : ClosedRegisterV4 (earlyDataSharedV4 K) (sharedClosedThresholdsV4 K),
      Cfs15ModulusAtV2 (gafStageDim 0) K (5 / 3) ((earlyDataSharedV4 K).Ξ 0) (R.stage.Γ 0) ∧
      1 ≤ stageBuffer_VAL6 R.stage ∧
      R.stage.Γ 0 * ((80 * (5 / 3) + 31) * stageBuffer_VAL6 R.stage + 2) < 1 ∧
      (sharedClosedThresholdsV4 K).Nb R.stage =
        (⌈(1 + 2 * (5 / 3) * 165 * stageBuffer_VAL6 R.stage) ^ gafStageDim 0⌉₊ : ℝ) ∧
      0 ≤ (sharedClosedThresholdsV4 K).cw R.stage := by
  obtain ⟨R⟩ := exists_closedRegisterV4 (earlyDataSharedV4 K) (sharedClosedThresholdsV4 K)
  exact ⟨R, (earlyDataSharedV4_fields_VAL6 K).2.2.2.2.2.2.1 R.stage 0,
    R.stage.one_le_stageBuffer_VAL6, R.stage.interior_stageBuffer_VAL6, rfl,
    sharedCw_nonneg_VAL6 R.stage⟩

end DifferentialGeometry.Geometry.Collapse
