import DifferentialGeometry.Geometry.Collapse.StaticRegisterV4
import DifferentialGeometry.Geometry.Collapse.StaticRegisterV2Validity

/-!
# The closed threshold validity on register V4: the core record (lane FC39-VAL6)

Register-V4 file (lane FC39-VAL6), generated by `build-logs/scratch/FC39-VAL6/gen_v4.py`
from FC39-VAL5's `StaticRegisterV3Validity.lean` with register V3 → V4 (`βc` chosen right
after `β₂`, `β₂Up` reads the circle prefix `ClosedCirclePrefixV4` without `βc`; see
`StaticRegisterV4.lean`). It imports no register-V3 module.

`StaticRegisterV2Validity.lean` (lane FC39-VAL2; kept unchanged as history) on register V4
(`StaticRegisterV4.lean`: `β₃` fixed before PR11, the lead's decision of 2026-10-05). The
register-independent objects are reused from it unchanged: `Cfs15ModulusAtV2`, `Lpa02WitnessAtV2`,
`Lpa02WitnessV2` and the zero-model instances `inst*_VAL2`. Renamed onto register V4, with the same
bodies:

* `Lc18ExclusionOutV4 R M`, `lc18ExclusionOutV4_of_lc09Out_VAL6`;
* `ClosedFamilyInstanceV4 K R M δ εr Λz`: the scale in LPA01's window, the final family
  `LocalChartPacketsC14` with EXACTLY the register's values, LPA02's joint witness, the zero-ball
  selection;
* `ClosedFamilyOnTailV4`, `ClosedFamilyAtV4`: prefix witness functions `εr, δ', Λz` of the values
  read before `T₀`, with `20 Λz ≤ T₀Low`, one `δ < δ'`, on every member of the tail one instance,
  LC09 at `σ_col` and LC18's exclusion;
* `PartialClosedThresholdValidityV4` (PARTIAL, as V2's core record) and its consumers.
-/

set_option autoImplicit false

noncomputable section

open Set Metric Filter Bundle Function
open DifferentialGeometry DifferentialGeometry.Analysis GC.Endpoint
open DifferentialGeometry.Geometry.Riemannian DifferentialGeometry.Geometry.Curvature
open DifferentialGeometry.Geometry.Comparison.Toponogov
open DifferentialGeometry.CheegerGromovCompactness DifferentialGeometry.Geometry.Operator
open DifferentialGeometry.Integral.Measure DifferentialGeometry.Analysis.Calculus
open scoped BigOperators NNReal ContDiff Manifold Topology ENNReal

local notation "E3" => EuclideanSpace ℝ (Fin 3)
local notation "I3" => 𝓘(ℝ, EuclideanSpace ℝ (Fin 3))

attribute [-instance] Tensor0SBundle.tangentSpaceNormedAddCommGroup
  Tensor0SBundle.tangentSpaceNormedSpace


namespace DifferentialGeometry.Geometry.Collapse

open GC.MetricGeometry

universe u

/-- LC18's exclusion on the normalized member (PR12, B:10136): at every scale `ρ` of LPA01's window
at `(w, Λ)` of the register, the rescaled member has no three-splitting of quality `β₃`. -/
def Lc18ExclusionOutV4 {D : ClosedEarlyData} {T : ClosedThresholdsV4 D} (R : ClosedRegisterV4 D T)
    {W : CompactCarrier.{u}} {g : SmoothRiemannianMetric W.model W.Carrier}
    (M : ClosedModel W g) : Prop :=
  ∀ (p : M.X) (ρ : ℝ) (hρ : 0 < ρ), firstVolumeScale M.gX p R.later.scale.w / 2 ≤ ρ →
    ρ ≤ 2 * firstVolumeScale M.gX p (closedWPrime R.later.scale) →
    ¬ @HasEuclideanSplitting.{0, 0} M.X (M.mX.rescale ρ⁻¹ (inv_pos.mpr hρ)) p 3
      R.later.excl.β₃

/-- **LC18's exclusion from LC09's model** (bindable now): on a normalized model carrying LC09's
conclusion at `σ_col`, with `σ_col` and `β₃` in LC18's range, `Lc18ExclusionOutV4` holds. -/
theorem lc18ExclusionOutV4_of_lc09Out_VAL6 {D : ClosedEarlyData} {T : ClosedThresholdsV4 D}
    (R : ClosedRegisterV4 D T) {W : CompactCarrier.{u}}
    {g : SmoothRiemannianMetric W.model W.Carrier} (M : ClosedModel W g)
    (hσ : R.later.err.σcol ≤ threeSplittingExclusionThreshold.{0, 0})
    (hβ : R.later.excl.β₃ ≤ threeSplittingExclusionThreshold.{0, 0})
    (h : Lc09Out R.later.err.σcol R.later.scale.Λ R.later.scale.w M) :
    Lc18ExclusionOutV4 R M := by
  intro p ρ hρ h1 h2
  obtain ⟨Y, mY, q, hc, -, hdim, hcomp, hseg, ⟨f⟩⟩ := h p ρ hρ h1 h2
  let := M.mX.rescale ρ⁻¹ (inv_pos.mpr hρ)
  exact threeSplittingExclusionThreshold_excludes q hseg hdim hcomp hσ hβ f

/-- **One instance of the final family at the staged register `R`** on a normalized member model:
the scale `ρ` in LPA01's window at `w, Λ`, the family `LocalChartPacketsC14` with EXACTLY the
register's values (no substitution), LPA02's joint witness on the member at the family's `εr`,
`e = e₀`, `[T₀, V]` and cone error `δ`, and every zero ball selected from that witness. -/
structure ClosedFamilyInstanceV4 (K : ℕ) {D : ClosedEarlyData} {T : ClosedThresholdsV4 D}
    (R : ClosedRegisterV4 D T) {W : CompactCarrier.{u}}
    {g : SmoothRiemannianMetric W.model W.Carrier} (M : ClosedModel W g) (δ εr Λz : ℝ) where
  /-- The scale. -/
  ρ : M.X → ℝ
  ρ_pos : ∀ p, 0 < ρ p
  /-- LPA01's window (C14P:259–260). -/
  ρ_bounds : ∀ p, firstVolumeScale M.gX p R.later.scale.w / 2 < ρ p ∧
    ρ p < 2 * firstVolumeScale M.gX p (closedWPrime R.later.scale)
  /-- The final family at the register's values. -/
  family : LocalChartPacketsC14 M.X M.gX M.hmetric ρ ρ_pos R.later.scale.Λ R.β R.later.excl.Δ
    R.later.err.co.qs K R.later.err.co.qe R.later.err.bd.μ R.later.split.b R.later.err.s
    R.later.err.wk.b' R.later.err.wk.s' R.later.err.co.ε R.later.circle.γc R.later.circle.βc
    R.later.Lmax R.later.err.bd.τ R.later.circle.γ δ εr R.later.err.co.e₀ R.later.split.T₀
    R.later.split.V R.later.err.co.ve R.later.err.co.ζ Λz
  /-- PR23 / LPA02: the full joint witness on this member, in the same chain. -/
  witness : Lpa02WitnessV2 M.gX K R.later.scale.Λ R.later.scale.w εr R.later.err.co.e₀
    R.later.split.T₀ R.later.split.V δ
  /-- The finite zero family is selected from that witness: every zero ball at `c` has radius
  `s ρ(c)` for a scale `s ∈ [T₀, V]` at which the joint witness at `(c, ρ(c))` holds. -/
  selected : ∀ c (hc : c ∈ family.zero.centres), ∃ s ∈ Icc R.later.split.T₀ R.later.split.V,
    ∃ hs : 0 < s, (family.zero.zero c hc).radius = s * ρ c ∧
      Lpa02WitnessAtV2 M.gX K εr R.later.err.co.e₀ δ c (ρ c) s (ρ_pos c) hs

/-- The single-certificate chain at `R` for given prefix witnesses `εr, δ', Λz` (review 52): the
witnesses' ranges, `20 Λz ≤ T₀Low` (the SAME `Λz`), then ONE `δ < δ'` and, on EVERY member of the
register's tail, a normalized model with one family instance, LC09 at `σ_col` and LC18's
exclusion. -/
def ClosedFamilyOnTailV4 (K : ℕ) (Wseq : ℕ → CompactCarrier.{u})
    (gseq : ∀ m, SmoothRiemannianMetric (Wseq m).model (Wseq m).Carrier) {D : ClosedEarlyData}
    {T : ClosedThresholdsV4 D} (R : ClosedRegisterV4 D T) (εr δ' Λz : ℝ) : Prop :=
  0 < εr ∧ εr < 1 / 4 ∧ εr < R.later.err.co.ε₀ ∧ 0 < δ' ∧ 0 < Λz ∧
    20 * Λz ≤ T.T₀Low R.stage R.later.circle R.later.excl R.later.err R.later.scale
      R.later.split.b R.later.split.β₁ ∧
    ∃ δ : ℝ, 0 < δ ∧ δ < δ' ∧ ∀ m, R.later.tail ≤ m → ∃ M : ClosedModel (Wseq m) (gseq m),
      Nonempty (ClosedFamilyInstanceV4 K R M δ εr Λz) ∧
        Lc09Out R.later.err.σcol R.later.scale.Λ R.later.scale.w M ∧ Lc18ExclusionOutV4 R M

/-- **The joint `Out` of the producer-bound closed slots** (review 52, single-certificate row):
prefix witness FUNCTIONS `εr, δ', Λz` of the values a threshold reads before `T₀`
(`st, ci, ex, er, sc, b, β₁`), and at EVERY staged register the chain `ClosedFamilyOnTailV4`
with these witnesses. -/
def ClosedFamilyAtV4 (K : ℕ) (Wseq : ℕ → CompactCarrier.{u})
    (gseq : ∀ m, SmoothRiemannianMetric (Wseq m).model (Wseq m).Carrier) {D : ClosedEarlyData}
    (T : ClosedThresholdsV4 D) : Prop :=
  ∃ εrF δ'F ΛzF : ClosedStage D → ClosedCircleRequestsV2 → ClosedExclusions → ClosedErrorsV2 →
      ClosedScales → ℝ → ℝ → ℝ,
    ∀ R : ClosedRegisterV4 D T,
      ClosedFamilyOnTailV4 K Wseq gseq R
        (εrF R.stage R.later.circle R.later.excl R.later.err R.later.scale R.later.split.b
          R.later.split.β₁)
        (δ'F R.stage R.later.circle R.later.excl R.later.err R.later.scale R.later.split.b
          R.later.split.β₁)
        (ΛzF R.stage R.later.circle R.later.excl R.later.err R.later.scale R.later.split.b
          R.later.split.β₁)

/-- **The core of the closed threshold validity on the staged register** (review 52; PARTIAL: the
per-instance chapter-14 row fields are added by the complete record). Every slot is bound to the
analytic conclusion of its native declaration at the chosen value, on the given standing sequence.
-/
structure PartialClosedThresholdValidityV4 (K : ℕ) (A : ℝ → ℝ) (Wseq : ℕ → CompactCarrier.{u})
    (gseq : ∀ m, SmoothRiemannianMetric (Wseq m).model (Wseq m).Carrier)
    (D : ClosedEarlyData) (T : ClosedThresholdsV4 D) : Prop where
  /-- PR01 `N`: GAF01's multiplicity `⌊fc07ActiveBound⌋₊` (every active-tag count of `𝓔⁰`). -/
  N_ge : gafMultiplicity ≤ D.N
  /-- PR01 `P`: CGP02's profile bound. -/
  P_ge : cgpProfileBound ≤ D.P
  /-- PR01 `P`: the slim/edge/circle graph-model profile bound (SGP04, EGP06, TCP05). -/
  P_ge_sgp : sgpProfileBound ≤ D.P
  /-- PR01 `P`: the zero graph-model profile bound. -/
  P_ge_zero : zeroProfileBound ≤ D.P
  /-- PR02 `L₀`: CGP02's global derivative bound of the initial map. -/
  L₀_ge : gafDerivativeBound ≤ D.L₀
  /-- PR03 `Ξ_j`: CFS15's full conclusion for the chosen modulus at the stage dimension `k_j`, jet
  order `K`, ratio `B = 5/3` (GAF01, `ActualAdjustmentChoice.lean:96`). -/
  Ξ_cfs15 : ∀ j, Cfs15ModulusOut (gafStageDim j) K (5 / 3) (D.Ξ j)
  /-- PR03: every actual `Γ_j` of every stage choice lies in CFS15's native range. -/
  Ξ_range : ∀ (st : ClosedStage D) j, Cfs15ModulusAtV2 (gafStageDim j) K (5 / 3) (D.Ξ j) (st.Γ j)
  /-- PR12 `lc18`: LC18's obstruction (the producer's `β 3 ≤ thr`, C14P:240). -/
  lc18_le : T.lc18 ≤ threeSplittingExclusionThreshold.{0, 0}
  /-- PR20 `I₁`: the comparison constant of `v_* = w'/(24 I(1))` (LPA02's volume constant). -/
  I₁_eq : T.I₁ = ∫ t in (0 : ℝ)..1, Real.sinh t ^ 2
  /-- PR24 `H`: LPA01's standing clauses at `α = T.H` (the producer's `hstand`, `hder`,
  C14P:249–255, with `A' = boundaryDerivativeConstant A K`) on every member. -/
  standing : ∀ m (p : (Wseq m).Carrier),
    ENNReal.ofReal (T.H m * firstVolumeScale (gseq m) p (T.H m)⁻¹) ≤ curvatureRadius (gseq m) p ∧
    ∀ v, 0 < v → v < 4 * Real.pi / 3 → (T.H m)⁻¹ ≤ v → ∀ C, 0 < C → C < T.H m → ∀ k ≤ K,
      ∀ y ∈ riemannianBallOf (gseq m) p (C * firstVolumeScale (gseq m) p v),
        curvatureDerivativeNorm (gseq m) k y ≤
          boundaryDerivativeConstant A K C v * (firstVolumeScale (gseq m) p v ^ (k + 2))⁻¹
  /-- PR11–PR25: the joint package of the producer-bound slots (closed members). -/
  family : (∀ m, ClosedMemberFacts (Wseq m)) → ClosedFamilyAtV4 K Wseq gseq T

namespace PartialClosedThresholdValidityV4

variable {K : ℕ} {A : ℝ → ℝ} {Wseq : ℕ → CompactCarrier.{u}}
  {gseq : ∀ m, SmoothRiemannianMetric (Wseq m).model (Wseq m).Carrier}
  {D : ClosedEarlyData} {T : ClosedThresholdsV4 D}

/-- **Consumer (wrapper (1) shape, family level)**: at every staged register, one tail
`N ≥ R.later.tail` on which every member carries the final family at `R`, with `20 Λz ≤ T₀`. -/
theorem exists_family_on_tail_VAL6 (hv : PartialClosedThresholdValidityV4 K A Wseq gseq D T)
    (hf : ∀ m, ClosedMemberFacts (Wseq m)) (R : ClosedRegisterV4 D T) :
    ∃ N : ℕ, R.later.tail ≤ N ∧ ∃ δ εr Λz : ℝ, 20 * Λz ≤ R.later.split.T₀ ∧ ∀ m, N ≤ m →
      ∃ M : ClosedModel (Wseq m) (gseq m), Nonempty (ClosedFamilyInstanceV4 K R M δ εr Λz) := by
  obtain ⟨εrF, δ'F, ΛzF, h⟩ := hv.family hf
  obtain ⟨-, -, -, -, -, hT, δ, -, -, ht⟩ := h R
  refine ⟨R.later.tail, le_rfl, δ, _, _, hT.trans ((le_max_right _ _).trans R.later.T₀_ge),
    fun m hm => (ht m hm).imp fun _ hM => hM.1⟩

/-- **Consumer (H transport)**: the standing clauses transported to ANY normalized model of a
member — exactly the producer's `hstand` and `hder` on the model sequence. -/
theorem standing_on_model_VAL6 (hv : PartialClosedThresholdValidityV4 K A Wseq gseq D T)
    (m : ℕ) (M : ClosedModel (Wseq m) (gseq m)) (p : M.X) :
    ENNReal.ofReal (T.H m * firstVolumeScale M.gX p (T.H m)⁻¹) ≤ curvatureRadius M.gX p ∧
    ∀ v, 0 < v → v < 4 * Real.pi / 3 → (T.H m)⁻¹ ≤ v → ∀ C, 0 < C → C < T.H m → ∀ k ≤ K,
      ∀ y ∈ riemannianBallOf M.gX p (C * firstVolumeScale M.gX p v),
        curvatureDerivativeNorm M.gX k y ≤
          boundaryDerivativeConstant A K C v * (firstVolumeScale M.gX p v ^ (k + 2))⁻¹ := by
  obtain ⟨h1, h2⟩ := hv.standing m (M.ψ p)
  refine ⟨by rw [M.firstVolumeScale_eq, M.curvatureRadius_eq]; exact h1, ?_⟩
  intro v hv0 hvc hvH C hC hCH k hk y hy
  rw [M.ball_eq_preimage, M.firstVolumeScale_eq] at hy
  rw [M.curvatureDerivativeNorm_eq, M.firstVolumeScale_eq]
  exact h2 v hv0 hvc hvH C hC hCH k hk (M.ψ y) hy

/-- **Consumer (LC18)**: the splitting coordinate `β 3 = β₃` of the family at `R` is below LC18's
obstruction. -/
theorem β_three_le_VAL6 (hv : PartialClosedThresholdValidityV4 K A Wseq gseq D T)
    (R : ClosedRegisterV4 D T) : R.β 3 ≤ threeSplittingExclusionThreshold.{0, 0} := by
  rw [ClosedRegisterV4.β_three_VAL6]
  exact (R.later.β₃_lt.trans_le hv.lc18_le).le

/-- **Consumer (PR03)**: the accuracy `ε_j = Ξ_j(Γ_j)` of the actual stage choice is a value of
CFS15's dyadic modulus. -/
theorem Ξ_dyadic_VAL6 (hv : PartialClosedThresholdValidityV4 K A Wseq gseq D T)
    (st : ClosedStage D) (j : Fin 3) : ∃ n : ℕ, D.Ξ j (st.Γ j) = (1 / 2 : ℝ) ^ (n + 4) :=
  (hv.Ξ_range st j).1

/-- **Consumer (I₁)**: the register's `v_*` is LPA02's volume constant
`w' / (24 ∫₀¹ sinh²)`. -/
theorem vStar_eq_VAL6 (hv : PartialClosedThresholdValidityV4 K A Wseq gseq D T)
    (R : ClosedRegisterV4 D T) :
    closedVStarV4 T R.later.scale = R.later.scale.w / (2 * (1 + 2 * R.later.scale.Λ⁻¹) ^ 3) /
      (24 * ∫ t in (0 : ℝ)..1, Real.sinh t ^ 2) := by
  rw [closedVStarV4, hv.I₁_eq, closedWPrime]

end PartialClosedThresholdValidityV4

end DifferentialGeometry.Geometry.Collapse
